# FastConformer CTC Vietnamese Fine-Tune Main Notebook

<style>
.jp-RenderedMarkdown, .jp-MarkdownOutput, .rendered_html, .text_cell_render, .markdown-cell {
  font-family: "Noto Sans", "Segoe UI", "Arial", "DejaVu Sans", sans-serif !important;
}
.jp-RenderedMarkdown code, .jp-MarkdownOutput code, .rendered_html code, .text_cell_render code {
  font-family: "JetBrains Mono", "Consolas", "DejaVu Sans Mono", monospace !important;
}
</style>

Notebook chính đã được tách cell để dễ chạy/debug trên Kaggle.

Run order: chạy lần lượt từ trên xuống. Các phase được chạy ở từng cell riêng: Phase 1, Phase 2, Phase 3, rồi Finalize.

In [16]:
# Kaggle setup: run once if dependencies are missing.
!pip install -q "nemo_toolkit[asr]" huggingface_hub jiwer sentencepiece soundfile pandas

## 1. Imports and Configuration

In [17]:
"""
Kaggle-ready controlled fine-tuning pipeline for
`nvidia/stt_en_fastconformer_ctc_large` on Vietnamese VIVOS.

Run on Kaggle after installing dependencies, for example:

    pip install -q "nemo_toolkit[asr]" huggingface_hub jiwer sentencepiece soundfile pandas
    python finetune_fastconformer_vi_best_checkpoint.py

The pipeline follows three phases:
1. Decoder warmup with frozen encoder.
2. Partial encoder adaptation with the last encoder blocks unfrozen.
3. Full fine-tune with a low learning rate.

Each phase keeps only the best checkpoint by `val_wer`, keeps `last.ckpt`
for resume, and exports the best `.nemo` model for the next phase.
"""

from __future__ import annotations

import gc
import gzip
import json
import math
import os
import random
import re
import shutil
import tarfile
import time
import unicodedata
from collections import Counter
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import pandas as pd
import sentencepiece as spm
import soundfile as sf
import torch
from huggingface_hub import snapshot_download
from jiwer import cer, wer
from omegaconf import OmegaConf

import nemo.collections.asr as nemo_asr

try:
    import lightning.pytorch as pl
    from lightning.pytorch.callbacks import Callback, EarlyStopping, ModelCheckpoint
except ImportError:
    import pytorch_lightning as pl
    from pytorch_lightning.callbacks import Callback, EarlyStopping, ModelCheckpoint


SEED = 42
random.seed(SEED)
os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")
os.environ.setdefault("NEMO_LOG_LEVEL", "INFO")

ROOT = Path("/kaggle/working/vivos")
EXTRACT_DIR = ROOT / "data" / "extracted"
MANIFEST_DIR = Path("/kaggle/working/vivos_manifest_phase_best")
TOKENIZER_ROOT = Path("/kaggle/working/tokenizers")
TOKENIZER_DIR = TOKENIZER_ROOT / "tokenizer_spe_unigram_v1024_vi"
CORPUS_PATH = TOKENIZER_ROOT / "vivos_train_only_corpus_vi.txt"

MODEL_NAME = "nvidia/stt_en_fastconformer_ctc_large"
DATASET_ID = "AILAB-VNUHCM/vivos"

EXP_DIR = Path("/kaggle/working/nemo_experiments")
EXP_NAME = "fastconformer_vi"
PHASE_ROOT = EXP_DIR / EXP_NAME
ARTIFACT_DIR = Path("/kaggle/working/fastconformer_vi_artifacts")

PHASE1_BEST_NEMO = Path("/kaggle/working/phase1_best_decoder_only.nemo")
PHASE2_BEST_NEMO = Path("/kaggle/working/phase2_best_partial_encoder.nemo")
PHASE3_BEST_NEMO = Path("/kaggle/working/phase3_best_full_finetune.nemo")
OVERALL_BEST_NEMO = Path("/kaggle/working/fastconformer_vi_best_model.nemo")

TRAIN_MANIFEST = MANIFEST_DIR / "train_manifest.json"
VAL_MANIFEST = MANIFEST_DIR / "val_manifest.json"
TEST_MANIFEST = MANIFEST_DIR / "test_manifest.json"

EVAL_CSV = ARTIFACT_DIR / "phase_eval_summary.csv"
TRAINING_CSV = ARTIFACT_DIR / "phase_training_summary.csv"
SAMPLE_PREDICTIONS_CSV = ARTIFACT_DIR / "sample_predictions.csv"

TOKENIZER_VOCAB_SIZE = 1024
TOKENIZER_MODEL_TYPE = "unigram"
RETRAIN_TOKENIZER = True

MIN_DURATION = 0.1
MAX_DURATION = 8.0
EVAL_BATCH_SIZE = 8
NUM_SAMPLE_PREDICTIONS_PER_EPOCH = 10

PRECISION = "16-mixed"
GRADIENT_CLIP_VAL = 1.0
WEIGHT_DECAY = 0.001
WARMUP_STEPS = 500
EARLY_STOPPING_PATIENCE = 5
EARLY_STOPPING_MIN_DELTA = 0.0

# Set to True and point the phase entry at its `last.ckpt` to resume after a
# Kaggle interruption. Resume is exact only within the same phase.
RESUME_FROM_LAST = False
RESUME_CKPT_BY_PHASE = {
    "phase1_decoder_warmup": "",
    "phase2_partial_encoder": "",
    "phase3_full_finetune": "",
}


@dataclass(frozen=True)
class PhaseConfig:
    name: str
    output_nemo: Path
    init_nemo: Path | None
    trainable_mode: str
    max_epochs: int
    lr: float
    batch_size: int
    accumulate_grad_batches: int
    unfrozen_encoder_blocks: int = 0
    max_duration: float = MAX_DURATION


PHASES = [
    PhaseConfig(
        name="phase1_decoder_warmup",
        output_nemo=PHASE1_BEST_NEMO,
        init_nemo=None,
        trainable_mode="decoder_only",
        max_epochs=3,
        lr=5e-4,
        batch_size=4,
        accumulate_grad_batches=8,
    ),
    PhaseConfig(
        name="phase2_partial_encoder",
        output_nemo=PHASE2_BEST_NEMO,
        init_nemo=PHASE1_BEST_NEMO,
        trainable_mode="partial_encoder_last",
        max_epochs=10,
        lr=3e-5,
        batch_size=2,
        accumulate_grad_batches=16,
        unfrozen_encoder_blocks=6,
    ),
    PhaseConfig(
        name="phase3_full_finetune",
        output_nemo=PHASE3_BEST_NEMO,
        init_nemo=PHASE2_BEST_NEMO,
        trainable_mode="full_encoder_decoder",
        max_epochs=25,
        lr=3e-5,
        batch_size=2,
        accumulate_grad_batches=16,
    ),
]


VIETNAMESE_LETTER_RE = re.compile(
    r"[^0-9a-z"
    r"àáảãạăằắẳẵặâầấẩẫậ"
    r"èéẻẽẹêềếểễệ"
    r"ìíỉĩị"
    r"òóỏõọôồốổỗộơờớởỡợ"
    r"ùúủũụưừứửữự"
    r"ỳýỷỹỵđ"
    r"\s]"
)

## 2. Text Normalization

In [18]:
def normalize_transcript(text: str) -> str:
    text = unicodedata.normalize("NFC", str(text)).lower()
    text = VIETNAMESE_LETTER_RE.sub(" ", text)
    return re.sub(r"\s+", " ", text).strip()


def normalize_for_metric(text: str) -> str:
    return normalize_transcript(text)

## 3. Dataset and Manifest Preparation

In [19]:
def download_and_extract_vivos() -> None:
    archive_path = ROOT / "data" / "vivos.tar.gz"
    ROOT.mkdir(parents=True, exist_ok=True)
    if not archive_path.exists():
        snapshot_download(
            repo_id=DATASET_ID,
            repo_type="dataset",
            local_dir=str(ROOT),
            local_dir_use_symlinks=False,
        )

    EXTRACT_DIR.mkdir(parents=True, exist_ok=True)
    if not list(EXTRACT_DIR.rglob("*.wav")):
        with tarfile.open(archive_path, "r:gz") as tar:
            tar.extractall(EXTRACT_DIR)


def read_prompts(path: Path, wav_index: dict[str, str]) -> list[dict[str, Any]]:
    rows = []
    with gzip.open(path, "rt", encoding="utf-8") as f:
        for line in f:
            parts = line.strip().split(" ", 1)
            if len(parts) != 2:
                continue
            utt_id, text = parts
            audio_path = wav_index.get(utt_id)
            if audio_path is None:
                continue
            info = sf.info(audio_path)
            rows.append(
                {
                    "utt_id": utt_id,
                    "audio_filepath": audio_path,
                    "duration": info.frames / info.samplerate,
                    "sample_rate": info.samplerate,
                    "text": normalize_transcript(text),
                }
            )
    return rows


def write_manifest(rows: list[dict[str, Any]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        for row in rows:
            f.write(
                json.dumps(
                    {
                        "audio_filepath": row["audio_filepath"],
                        "duration": float(row["duration"]),
                        "text": row["text"],
                    },
                    ensure_ascii=False,
                )
                + "\n"
            )


def prepare_manifests() -> None:
    download_and_extract_vivos()
    wav_index = {path.stem: str(path) for path in EXTRACT_DIR.rglob("*.wav")}
    train_all = read_prompts(ROOT / "data" / "prompts-train.txt.gz", wav_index)
    test_rows = read_prompts(ROOT / "data" / "prompts-test.txt.gz", wav_index)

    random.Random(SEED).shuffle(train_all)
    val_size = max(1, int(len(train_all) * 0.05))
    val_rows = train_all[:val_size]
    train_rows = train_all[val_size:]

    write_manifest(train_rows, TRAIN_MANIFEST)
    write_manifest(val_rows, VAL_MANIFEST)
    write_manifest(test_rows, TEST_MANIFEST)

    audit_rows = []
    for split, rows in [("train", train_rows), ("val", val_rows), ("test", test_rows)]:
        durations = [row["duration"] for row in rows]
        sample_rates = Counter(row["sample_rate"] for row in rows)
        audit_rows.append(
            {
                "split": split,
                "rows": len(rows),
                "sample_rates": dict(sample_rates),
                "min_duration": min(durations),
                "max_duration": max(durations),
                "mean_duration": sum(durations) / len(durations),
                "filtered_by_max_duration_8s": sum(d > MAX_DURATION for d in durations),
            }
        )
    print(pd.DataFrame(audit_rows))

## 4. SentencePiece Tokenizer

In [20]:
def train_sentencepiece_tokenizer() -> None:
    if RETRAIN_TOKENIZER and TOKENIZER_DIR.exists():
        shutil.rmtree(TOKENIZER_DIR)

    TOKENIZER_DIR.mkdir(parents=True, exist_ok=True)
    TOKENIZER_ROOT.mkdir(parents=True, exist_ok=True)

    with open(CORPUS_PATH, "w", encoding="utf-8") as out:
        with open(TRAIN_MANIFEST, encoding="utf-8") as f:
            for line in f:
                out.write(json.loads(line)["text"] + "\n")

    model_file = TOKENIZER_DIR / "tokenizer.model"
    if not model_file.exists():
        spm.SentencePieceTrainer.Train(
            input=str(CORPUS_PATH),
            model_prefix=str(TOKENIZER_DIR / "tokenizer"),
            vocab_size=TOKENIZER_VOCAB_SIZE,
            model_type=TOKENIZER_MODEL_TYPE,
            character_coverage=1.0,
            unk_id=0,
            bos_id=-1,
            eos_id=-1,
            pad_id=-1,
            hard_vocab_limit=False,
            shuffle_input_sentence=True,
            input_sentence_size=1_000_000,
        )

    sp = spm.SentencePieceProcessor(model_file=str(model_file))
    vocab_txt = TOKENIZER_DIR / "vocab.txt"
    with open(vocab_txt, "w", encoding="utf-8") as f:
        for piece_id in range(sp.get_piece_size()):
            f.write(sp.id_to_piece(piece_id) + "\n")

    samples = [
        "tôi đang học tiếng việt",
        "vườn thuốc nam của trường có đủ các loại cây trồng trên luống",
        "đây là một câu kiểm tra đầy đủ dấu tiếng việt",
    ]
    print("Tokenizer dir:", TOKENIZER_DIR)
    print("Tokenizer vocab size:", sp.get_piece_size())
    print("Tokenizer vocab.txt:", vocab_txt)
    for text in samples:
        ids = sp.encode(text)
        decoded = sp.decode(ids)
        print("TOKENIZER CHECK:", text, "=>", decoded)
        assert normalize_for_metric(decoded) == normalize_for_metric(text)

## 5. NeMo Data and Model Setup Helpers

In [21]:
def dataloader_cfg(manifest_path: Path, batch_size: int, shuffle: bool, max_duration: float | None = None):
    cfg = {
        "manifest_filepath": str(manifest_path),
        "sample_rate": 16000,
        "batch_size": batch_size,
        "shuffle": shuffle,
        "num_workers": 2,
        "pin_memory": True,
        "min_duration": MIN_DURATION,
        "is_tarred": False,
        "tarred_audio_filepaths": None,
    }
    if max_duration is not None:
        cfg["max_duration"] = max_duration
    return OmegaConf.create(cfg)


def setup_validation_data(model, cfg) -> None:
    try:
        model.setup_multiple_validation_data(cfg)
    except Exception:
        model.setup_validation_data(cfg)


def load_phase_model(init_nemo: Path | None):
    if init_nemo is None:
        print("Loading pretrained English checkpoint:", MODEL_NAME)
        model = nemo_asr.models.EncDecCTCModelBPE.from_pretrained(model_name=MODEL_NAME)
        model.change_vocabulary(new_tokenizer_dir=str(TOKENIZER_DIR), new_tokenizer_type="bpe")
        return model

    if not init_nemo.exists():
        raise FileNotFoundError(f"Missing phase init model: {init_nemo}")
    print("Restoring phase init model:", init_nemo)
    return nemo_asr.models.ASRModel.restore_from(str(init_nemo))


def encoder_blocks(model):
    blocks = getattr(model.encoder, "layers", None)
    if blocks is not None and len(blocks) > 0:
        return blocks, "encoder.layers"

    candidates = []
    for name, module in model.encoder.named_modules():
        if hasattr(module, "__len__") and hasattr(module, "__iter__"):
            try:
                length = len(module)
            except Exception:
                continue
            if length >= 2 and ("layer" in name.lower() or "block" in name.lower()):
                candidates.append((length, name, module))
    if not candidates:
        raise RuntimeError("Could not find encoder layers for partial unfreeze.")
    candidates.sort(reverse=True, key=lambda item: item[0])
    _, name, module = candidates[0]
    return module, name


def set_trainable_mode(model, mode: str, unfrozen_encoder_blocks: int = 0) -> dict[str, Any]:
    for parameter in model.parameters():
        parameter.requires_grad = False

    for parameter in model.decoder.parameters():
        parameter.requires_grad = True

    info: dict[str, Any] = {
        "trainable_mode": mode,
        "encoder_block_path": None,
        "unfrozen_encoder_blocks": 0,
    }

    if mode == "decoder_only":
        model.encoder.eval()
    elif mode == "partial_encoder_last":
        blocks, block_path = encoder_blocks(model)
        n_blocks = unfrozen_encoder_blocks or 6
        if len(blocks) < n_blocks:
            raise ValueError(f"Requested {n_blocks} blocks but encoder only has {len(blocks)}.")
        for block in list(blocks)[-n_blocks:]:
            for parameter in block.parameters():
                parameter.requires_grad = True
        model.encoder.train()
        info["encoder_block_path"] = block_path
        info["unfrozen_encoder_blocks"] = n_blocks
    elif mode == "full_encoder_decoder":
        for parameter in model.encoder.parameters():
            parameter.requires_grad = True
        model.encoder.train()
        info["encoder_block_path"] = "encoder"
        info["unfrozen_encoder_blocks"] = "all"
    else:
        raise ValueError(f"Unknown trainable mode: {mode}")

    encoder_trainable = sum(p.numel() for p in model.encoder.parameters() if p.requires_grad)
    decoder_trainable = sum(p.numel() for p in model.decoder.parameters() if p.requires_grad)
    total_trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total_params = sum(p.numel() for p in model.parameters())
    trainable_names = [name for name, p in model.named_parameters() if p.requires_grad]

    info.update(
        {
            "encoder_trainable_params": encoder_trainable,
            "decoder_trainable_params": decoder_trainable,
            "total_trainable_params": total_trainable,
            "total_params": total_params,
            "trainable_fraction": total_trainable / max(total_params, 1),
        }
    )

    print("Trainable mode:", mode)
    print("Encoder trainable params:", f"{encoder_trainable:,}")
    print("Decoder trainable params:", f"{decoder_trainable:,}")
    print("Total trainable params:", f"{total_trainable:,}/{total_params:,}")
    print("First trainable parameter names:", trainable_names[:20])

    if mode == "decoder_only":
        assert encoder_trainable == 0, "Encoder should be frozen in decoder-only mode."
    else:
        assert encoder_trainable > 0, "Encoder should be trainable in this phase."
    assert decoder_trainable > 0, "Decoder should always be trainable."
    return info

## 6. Training Callbacks

In [22]:
class EncoderModeCallback(Callback):
    def __init__(self, mode: str):
        self.mode = mode

    def _apply(self, pl_module):
        if self.mode == "decoder_only":
            pl_module.encoder.eval()
        else:
            pl_module.encoder.train()

    def on_train_start(self, trainer, pl_module):
        self._apply(pl_module)

    def on_train_epoch_start(self, trainer, pl_module):
        self._apply(pl_module)

    def on_train_batch_start(self, trainer, pl_module, batch, batch_idx):
        self._apply(pl_module)


def metric_to_float(value):
    if value is None:
        return None
    if hasattr(value, "detach"):
        value = value.detach().cpu()
    try:
        return float(value)
    except Exception:
        return None


def metric_lookup(metrics: dict, *names: str):
    for name in names:
        if name in metrics:
            return metric_to_float(metrics[name])
    for key, value in metrics.items():
        key_str = str(key)
        if any(key_str == name or key_str.endswith(name) for name in names):
            return metric_to_float(value)
    return None


class BestNemoExporter(Callback):
    def __init__(self, output_path: Path, monitor: str = "val_wer", mode: str = "min"):
        self.output_path = Path(output_path)
        self.monitor = monitor
        self.mode = mode
        self.best_score = math.inf if mode == "min" else -math.inf
        self.best_epoch = None

    def _is_better(self, score: float) -> bool:
        return score < self.best_score if self.mode == "min" else score > self.best_score

    def on_validation_epoch_end(self, trainer, pl_module):
        if getattr(trainer, "sanity_checking", False):
            return
        score = metric_lookup(getattr(trainer, "callback_metrics", {}) or {}, self.monitor)
        if score is None or not self._is_better(score):
            return
        self.best_score = score
        self.best_epoch = trainer.current_epoch
        self.output_path.parent.mkdir(parents=True, exist_ok=True)
        pl_module.save_to(str(self.output_path))
        print(
            f"[best {self.monitor}] epoch={trainer.current_epoch + 1} "
            f"{self.monitor}={score:.6f} exported={self.output_path}"
        )


class EpochPredictionLogger(Callback):
    def __init__(self, manifest_path: Path, output_csv: Path, num_samples: int = 10, batch_size: int = 4):
        self.output_csv = Path(output_csv)
        self.batch_size = batch_size
        self.rows = []
        self.samples = []
        with open(manifest_path, encoding="utf-8") as f:
            for idx, line in enumerate(f):
                if idx >= num_samples:
                    break
                row = json.loads(line)
                self.samples.append(row)

    def on_validation_epoch_end(self, trainer, pl_module):
        if getattr(trainer, "sanity_checking", False) or not self.samples:
            return

        audio_paths = [row["audio_filepath"] for row in self.samples]
        refs = [row["text"] for row in self.samples]
        try:
            predictions = pl_module.transcribe(audio_paths, batch_size=self.batch_size, verbose=False)
        except TypeError:
            predictions = pl_module.transcribe(audio_paths, batch_size=self.batch_size)
        except Exception as error:
            print("Sample prediction logging failed:", repr(error))
            return

        clean_predictions = []
        for pred in predictions:
            clean_predictions.append(getattr(pred, "text", pred))

        print(f"\nSample predictions after epoch {trainer.current_epoch + 1}:")
        for idx, (audio_path, ref, hyp) in enumerate(zip(audio_paths, refs, clean_predictions)):
            hyp = normalize_for_metric(str(hyp))
            ref_norm = normalize_for_metric(ref)
            print(f"  [{idx}] REF: {ref_norm}")
            print(f"      HYP: {hyp}")
            self.rows.append(
                {
                    "epoch": trainer.current_epoch,
                    "global_step": trainer.global_step,
                    "idx": idx,
                    "audio_filepath": audio_path,
                    "ref": ref_norm,
                    "hyp": hyp,
                }
            )

        self.output_csv.parent.mkdir(parents=True, exist_ok=True)
        pd.DataFrame(self.rows).to_csv(self.output_csv, index=False, encoding="utf-8-sig")


class EpochMetricsLogger(Callback):
    def __init__(self):
        self.rows = []

    def on_validation_epoch_end(self, trainer, pl_module):
        if getattr(trainer, "sanity_checking", False):
            return
        metrics = getattr(trainer, "callback_metrics", {}) or {}
        row = {
            "epoch": trainer.current_epoch,
            "global_step": trainer.global_step,
            "val_loss": metric_lookup(metrics, "val_loss"),
            "val_wer": metric_lookup(metrics, "val_wer"),
        }
        if torch.cuda.is_available():
            row.update(
                {
                    "gpu_allocated_mb": torch.cuda.memory_allocated() / (1024 ** 2),
                    "gpu_reserved_mb": torch.cuda.memory_reserved() / (1024 ** 2),
                    "gpu_peak_allocated_mb": torch.cuda.max_memory_allocated() / (1024 ** 2),
                }
            )
        self.rows.append(row)
        print(
            "[epoch]"
            f" epoch={trainer.current_epoch + 1}/{trainer.max_epochs}"
            f" step={trainer.global_step}"
            f" val_loss={row['val_loss']}"
            f" val_wer={row['val_wer']}"
        )

## 7. Checkpointing, Optimizer, and Phase Runner

In [23]:
def create_checkpoint_callback(phase: PhaseConfig) -> ModelCheckpoint:
    checkpoint_dir = PHASE_ROOT / phase.name / "checkpoints"
    checkpoint_dir.mkdir(parents=True, exist_ok=True)
    kwargs = {
        "dirpath": str(checkpoint_dir),
        "filename": "best-{epoch:02d}-{val_wer:.4f}",
        "monitor": "val_wer",
        "mode": "min",
        "save_top_k": 1,
        "save_last": True,
        "auto_insert_metric_name": False,
    }
    try:
        return ModelCheckpoint(every_n_epochs=1, **kwargs)
    except TypeError:
        return ModelCheckpoint(**kwargs)


def optimizer_cfg(lr: float):
    return OmegaConf.create(
        {
            "name": "adamw",
            "lr": lr,
            "betas": [0.9, 0.98],
            "weight_decay": WEIGHT_DECAY,
            "sched": {
                "name": "CosineAnnealing",
                "warmup_steps": WARMUP_STEPS,
                "min_lr": lr / 10,
            },
        }
    )


def count_manifest_rows(manifest_path: Path, max_duration: float | None = None) -> int:
    count = 0
    with open(manifest_path, encoding="utf-8") as f:
        for line in f:
            row = json.loads(line)
            duration = float(row.get("duration", 0.0))
            if duration < MIN_DURATION:
                continue
            if max_duration is not None and duration > max_duration:
                continue
            count += 1
    return count


def run_phase(phase: PhaseConfig) -> dict[str, Any]:
    print("\n" + "=" * 80)
    print("Starting", phase.name)
    print(asdict(phase))
    print("=" * 80)

    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()

    phase_dir = PHASE_ROOT / phase.name
    phase_dir.mkdir(parents=True, exist_ok=True)

    checkpoint_callback = create_checkpoint_callback(phase)
    best_exporter = BestNemoExporter(phase.output_nemo, monitor="val_wer", mode="min")
    sample_logger = EpochPredictionLogger(
        VAL_MANIFEST,
        ARTIFACT_DIR / f"{phase.name}_sample_predictions.csv",
        num_samples=NUM_SAMPLE_PREDICTIONS_PER_EPOCH,
    )
    metric_logger = EpochMetricsLogger()
    early_stopping = EarlyStopping(
        monitor="val_wer",
        mode="min",
        patience=EARLY_STOPPING_PATIENCE,
        min_delta=EARLY_STOPPING_MIN_DELTA,
    )

    trainer = pl.Trainer(
        devices=1,
        accelerator="gpu" if torch.cuda.is_available() else "cpu",
        strategy="auto",
        precision=PRECISION,
        max_epochs=phase.max_epochs,
        accumulate_grad_batches=phase.accumulate_grad_batches,
        gradient_clip_val=GRADIENT_CLIP_VAL,
        log_every_n_steps=50,
        enable_checkpointing=True,
        enable_progress_bar=True,
        enable_model_summary=False,
        logger=False,
        callbacks=[
            checkpoint_callback,
            best_exporter,
            sample_logger,
            metric_logger,
            early_stopping,
            EncoderModeCallback(phase.trainable_mode),
        ],
        num_sanity_val_steps=2,
        default_root_dir=str(phase_dir),
    )

    model = load_phase_model(phase.init_nemo)
    model.set_trainer(trainer)
    model.setup_training_data(
        dataloader_cfg(TRAIN_MANIFEST, phase.batch_size, shuffle=True, max_duration=phase.max_duration)
    )
    setup_validation_data(model, dataloader_cfg(VAL_MANIFEST, phase.batch_size, shuffle=False))
    trainable_info = set_trainable_mode(
        model,
        phase.trainable_mode,
        unfrozen_encoder_blocks=phase.unfrozen_encoder_blocks,
    )
    model.setup_optimization(optimizer_cfg(phase.lr))

    train_samples = count_manifest_rows(TRAIN_MANIFEST, max_duration=phase.max_duration)
    steps_per_epoch = math.ceil(train_samples / (phase.batch_size * phase.accumulate_grad_batches))
    print("effective_batch_size:", phase.batch_size * phase.accumulate_grad_batches)
    print("steps_per_epoch:", steps_per_epoch)
    print("estimated_total_steps:", steps_per_epoch * phase.max_epochs)
    print("checkpoint_dir:", checkpoint_callback.dirpath)
    print("best_nemo_target:", phase.output_nemo)

    ckpt_path = None
    configured_resume = RESUME_CKPT_BY_PHASE.get(phase.name, "")
    if RESUME_FROM_LAST and configured_resume:
        ckpt_path = str(Path(configured_resume))
        print("Resuming trainer state from:", ckpt_path)

    start_time = time.perf_counter()
    trainer.fit(model, ckpt_path=ckpt_path)
    elapsed_minutes = (time.perf_counter() - start_time) / 60

    if not phase.output_nemo.exists():
        print("No best .nemo was exported; saving current model as fallback:", phase.output_nemo)
        model.save_to(str(phase.output_nemo))

    phase_metrics_csv = ARTIFACT_DIR / f"{phase.name}_epoch_metrics.csv"
    if metric_logger.rows:
        df = pd.DataFrame(metric_logger.rows)
        df.insert(0, "phase", phase.name)
        df.to_csv(phase_metrics_csv, index=False, encoding="utf-8-sig")

    summary = {
        **asdict(phase),
        **trainable_info,
        "best_val_wer": best_exporter.best_score if math.isfinite(best_exporter.best_score) else None,
        "best_epoch": best_exporter.best_epoch,
        "best_nemo_path": str(phase.output_nemo),
        "best_checkpoint_path": checkpoint_callback.best_model_path,
        "last_checkpoint_path": str(Path(checkpoint_callback.dirpath) / "last.ckpt"),
        "elapsed_minutes": elapsed_minutes,
        "steps_per_epoch": steps_per_epoch,
        "estimated_total_steps": steps_per_epoch * phase.max_epochs,
        "precision": PRECISION,
        "warmup_steps": WARMUP_STEPS,
        "weight_decay": WEIGHT_DECAY,
    }

    del model
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    return summary

## 8. Evaluation and Artifact Helpers

In [24]:
def read_manifest_for_eval(manifest_path: Path) -> tuple[list[str], list[str]]:
    audio_paths = []
    refs = []
    with open(manifest_path, encoding="utf-8") as f:
        for line in f:
            row = json.loads(line)
            audio_paths.append(row["audio_filepath"])
            refs.append(row["text"])
    return audio_paths, refs


def transcribe_model(model, audio_paths: list[str], batch_size: int) -> list[str]:
    predictions = []
    for start in range(0, len(audio_paths), batch_size):
        batch = audio_paths[start : start + batch_size]
        try:
            batch_preds = model.transcribe(batch, batch_size=batch_size, verbose=False)
        except TypeError:
            batch_preds = model.transcribe(batch, batch_size=batch_size)
        predictions.extend(getattr(pred, "text", pred) for pred in batch_preds)
    return [normalize_for_metric(str(pred)) for pred in predictions]


def evaluate_nemo(nemo_path: Path, manifest_path: Path, split: str, phase_name: str) -> dict[str, Any]:
    print(f"Evaluating {phase_name} on {split}: {nemo_path}")
    audio_paths, refs = read_manifest_for_eval(manifest_path)
    refs_norm = [normalize_for_metric(ref) for ref in refs]

    model = nemo_asr.models.ASRModel.restore_from(str(nemo_path))
    if torch.cuda.is_available():
        model = model.cuda()
    model.eval()

    start_time = time.perf_counter()
    preds_norm = transcribe_model(model, audio_paths, batch_size=EVAL_BATCH_SIZE)
    inference_seconds = time.perf_counter() - start_time

    row = {
        "phase": phase_name,
        "split": split,
        "model_path": str(nemo_path),
        "samples": len(refs_norm),
        "wer": wer(refs_norm, preds_norm),
        "cer": cer(refs_norm, preds_norm),
        "empty_pred_rate": sum(1 for pred in preds_norm if not pred) / max(len(preds_norm), 1),
        "ref_word_count": sum(len(ref.split()) for ref in refs_norm),
        "pred_word_count": sum(len(pred.split()) for pred in preds_norm),
        "inference_seconds": inference_seconds,
    }
    row["pred_ref_word_ratio"] = row["pred_word_count"] / max(row["ref_word_count"], 1)

    del model
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    print(row)
    return row


def select_overall_best(eval_rows: list[dict[str, Any]]) -> None:
    val_rows = [row for row in eval_rows if row["split"] == "val"]
    if not val_rows:
        print("No validation eval rows; skipping overall best selection.")
        return
    best_row = sorted(val_rows, key=lambda row: row["wer"])[0]
    source = Path(best_row["model_path"])
    shutil.copy2(source, OVERALL_BEST_NEMO)
    print("Overall best by val WER:", best_row)
    print("Copied overall best to:", OVERALL_BEST_NEMO)


def combine_sample_predictions() -> None:
    frames = []
    for phase in PHASES:
        path = ARTIFACT_DIR / f"{phase.name}_sample_predictions.csv"
        if path.exists():
            frame = pd.read_csv(path)
            frame.insert(0, "phase", phase.name)
            frames.append(frame)
    if frames:
        pd.concat(frames, ignore_index=True).to_csv(SAMPLE_PREDICTIONS_CSV, index=False, encoding="utf-8-sig")


def csv_safe_summary(summary: dict[str, Any]) -> dict[str, Any]:
    safe = {}
    for key, value in summary.items():
        if isinstance(value, Path):
            safe[key] = str(value)
        else:
            safe[key] = value
    return safe


def run_phase_and_eval(
    phase: PhaseConfig,
    training_rows: list[dict[str, Any]],
    eval_rows: list[dict[str, Any]],
) -> dict[str, Any]:
    summary = run_phase(phase)
    training_rows.append(csv_safe_summary(summary))
    pd.DataFrame(training_rows).to_csv(TRAINING_CSV, index=False, encoding="utf-8-sig")

    eval_rows.append(evaluate_nemo(phase.output_nemo, VAL_MANIFEST, "val", phase.name))
    eval_rows.append(evaluate_nemo(phase.output_nemo, TEST_MANIFEST, "test", phase.name))
    pd.DataFrame(eval_rows).to_csv(EVAL_CSV, index=False, encoding="utf-8-sig")
    combine_sample_predictions()
    return summary

## 9. Optional Full Pipeline Function

Hàm `main()` vẫn được giữ để chạy tự động toàn bộ nếu muốn, nhưng workflow chính bên dưới chạy từng phase riêng.

In [25]:
def main() -> None:
    for directory in [MANIFEST_DIR, TOKENIZER_ROOT, EXP_DIR, ARTIFACT_DIR]:
        directory.mkdir(parents=True, exist_ok=True)

    print("torch:", torch.__version__)
    print("cuda available:", torch.cuda.is_available())
    if torch.cuda.is_available():
        print("gpu:", torch.cuda.get_device_name(0))

    prepare_manifests()
    train_sentencepiece_tokenizer()

    training_rows = []
    eval_rows = []
    for phase in PHASES:
        run_phase_and_eval(phase, training_rows, eval_rows)

    select_overall_best(eval_rows)

    print("\nArtifacts:")
    for path in [
        PHASE1_BEST_NEMO,
        PHASE2_BEST_NEMO,
        PHASE3_BEST_NEMO,
        OVERALL_BEST_NEMO,
        TRAINING_CSV,
        EVAL_CSV,
        SAMPLE_PREDICTIONS_CSV,
    ]:
        if path.exists():
            print(path, f"{path.stat().st_size / (1024 ** 2):.2f} MB")
        else:
            print("Missing:", path)
    print("\nCheckpoint folders:")
    for phase in PHASES:
        print(phase.name, PHASE_ROOT / phase.name / "checkpoints")

## 10. Prepare Data and Tokenizer

Chạy cell này trước các phase. Cell này tạo manifest, train tokenizer, và sinh `vocab.txt` để NeMo `change_vocabulary()` không lỗi.

In [26]:
for directory in [MANIFEST_DIR, TOKENIZER_ROOT, EXP_DIR, ARTIFACT_DIR]:
    directory.mkdir(parents=True, exist_ok=True)

print("torch:", torch.__version__)
print("cuda available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("gpu:", torch.cuda.get_device_name(0))

prepare_manifests()
train_sentencepiece_tokenizer()

training_rows = []
eval_rows = []
print("Ready for Phase 1")

torch: 2.10.0+cu128
cuda available: True
gpu: Tesla T4
   split   rows    sample_rates  min_duration  max_duration  mean_duration  \
0  train  11077  {16000: 11077}      0.811875     17.125000       4.599300
1    val    583    {16000: 583}      1.187500     17.000000       4.750377
2   test    760    {16000: 760}      1.375000      7.843125       3.533611

   filtered_by_max_duration_8s
0                         1030
1                           70
2                            0
Tokenizer dir: /kaggle/working/tokenizers/tokenizer_spe_unigram_v1024_vi
Tokenizer vocab size: 1024
Tokenizer vocab.txt: /kaggle/working/tokenizers/tokenizer_spe_unigram_v1024_vi/vocab.txt
TOKENIZER CHECK: tôi đang học tiếng việt => tôi đang học tiếng việt
TOKENIZER CHECK: vườn thuốc nam của trường có đủ các loại cây trồng trên luống => vườn thuốc nam của trường có đủ các loại cây trồng trên luống
TOKENIZER CHECK: đây là một câu kiểm tra đầy đủ dấu tiếng việt => đây là một câu kiểm tra đầy đủ dấu tiếng việt
Ready for Phase 1

sentencepiece_trainer.cc(78) LOG(INFO) Starts training with :
trainer_spec {
  input: /kaggle/working/tokenizers/vivos_train_only_corpus_vi.txt
  input_format:
  model_prefix: /kaggle/working/tokenizers/tokenizer_spe_unigram_v1024_vi/tokenizer
  model_type: UNIGRAM
  vocab_size: 1024
  self_test_sample_size: 0
  character_coverage: 1
  input_sentence_size: 1000000
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  pretokenization_delimiter:
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  required_chars:
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  seed_sentencepieces_file:
  hard_vocab_limit: 0
  use_all_vocab: 0
  unk_id: 0
  bos_id: -1
  eos_id: -1
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇
  enable_differential_privacy: 0
  differential_privacy_noise_level: 0
  differential_privacy_clipping_threshold: 0
}
normalizer_spec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv:
}
denormalizer_spec {}
trainer_interface.cc(355) LOG(INFO) SentenceIterator is not specified. Using MultiFileSentenceIterator.
trainer_interface.cc(186) LOG(INFO) Loading corpus: /kaggle/working/tokenizers/vivos_train_only_corpus_vi.txt
trainer_interface.cc(411) LOG(INFO) Loaded all 11077 sentences
trainer_interface.cc(427) LOG(INFO) Adding meta_piece: <unk>
trainer_interface.cc(432) LOG(INFO) Normalizing sentences...
trainer_interface.cc(541) LOG(INFO) all chars count=635591
trainer_interface.cc(562) LOG(INFO) Alphabet size=91
trainer_interface.cc(563) LOG(INFO) Final character coverage=1
trainer_interface.cc(594) LOG(INFO) Done! preprocessed 11077 sentences.
unigram_model_trainer.cc(265) LOG(INFO) Making suffix array...
unigram_model_trainer.cc(269) LOG(INFO) Extracting frequent sub strings... node_num=302503
unigram_model_trainer.cc(312) LOG(INFO) Initialized 6984 seed sentencepieces
trainer_interface.cc(600) LOG(INFO) Tokenizing input sentences with whitespace: 11077
trainer_interface.cc(611) LOG(INFO) Done! 4792
unigram_model_trainer.cc(602) LOG(INFO) Using 4792 sentences for EM training
unigram_model_trainer.cc(618) LOG(INFO) EM sub_iter=0 size=4769 obj=8.69424 num_tokens=7275 num_tokens/piece=1.52548
unigram_model_trainer.cc(618) LOG(INFO) EM sub_iter=1 size=3319 obj=7.51016 num_tokens=7218 num_tokens/piece=2.17475
unigram_model_trainer.cc(618) LOG(INFO) EM sub_iter=0 size=2489 obj=7.46618 num_tokens=7755 num_tokens/piece=3.11571
unigram_model_trainer.cc(618) LOG(INFO) EM sub_iter=1 size=2489 obj=7.44384 num_tokens=7755 num_tokens/piece=3.11571
unigram_model_trainer.cc(618) LOG(INFO) EM sub_iter=0 size=1866 obj=7.61935 num_tokens=8756 num_tokens/piece=4.69239
unigram_model_trainer.cc(618) LOG(INFO) EM sub_iter=1 size=1866 obj=7.58461 num_tokens=8756 num_tokens/piece=4.69239
unigram_model_trainer.cc(618) LOG(INFO) EM sub_iter=0 size=1399 obj=7.9713 num_tokens=9702 num_tokens/piece=6.93495
unigram_model_trainer.cc(618) LOG(INFO) EM sub_iter=1 size=1399 obj=7.91754 num_tokens=9702 num_tokens/piece=6.93495
unigram_model_trainer.cc(618) LOG(INFO) EM sub_iter=0 size=1126 obj=8.47033 num_tokens=10492 num_tokens/piece=9.31794
unigram_model_trainer.cc(618) LOG(INFO) EM sub_iter=1 size=1126 obj=8.42093 num_tokens=10494 num_tokens/piece=9.31972
trainer_interface.cc(689) LOG(INFO) Saving model: /kaggle/working/tokenizers/tokenizer_spe_unigram_v1024_vi/tokenizer.model
trainer_interface.cc(701) LOG(INFO) Saving vocabs: /kaggle/working/tokenizers/tokenizer_spe_unigram_v1024_vi/tokenizer.vocab

## 11. Phase 1 - Decoder Warmup

Freeze encoder, train Vietnamese CTC decoder only, export `/kaggle/working/phase1_best_decoder_only.nemo`.

In [27]:
# phase1_summary = run_phase_and_eval(PHASES[0], training_rows, eval_rows)
# phase1_summary

## 12. Phase 2 - Partial Encoder Fine-Tune

Load Phase 1 best model, unfreeze the last 6 encoder blocks plus decoder, export `/kaggle/working/phase2_best_partial_encoder.nemo`.

In [28]:
# phase2_summary = run_phase_and_eval(PHASES[1], training_rows, eval_rows)
# phase2_summary

## 13. Phase 3 - Full Fine-Tune

Load Phase 2 best model, unfreeze the full encoder plus decoder, export `/kaggle/working/phase3_best_full_finetune.nemo`.

In [29]:
PHASE3_RESUME_NEMO = Path("/kaggle/input/models/trnmnhtn/finetune-fastconformer/other/default/1/phase3_best_full_finetune.nemo")

phase3_continue = PhaseConfig(
    name="phase3_continue_from_epoch11",
    output_nemo=Path("/kaggle/working/phase3_continue_best.nemo"),
    init_nemo=PHASE3_RESUME_NEMO,
    trainable_mode="full_encoder_decoder",
    max_epochs=12,
    lr=2e-5,
    batch_size=2,
    accumulate_grad_batches=16,
)

In [31]:
phase3_summary = run_phase_and_eval(phase3_continue, training_rows, eval_rows)
phase3_summary

Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

================================================================================
Starting phase3_continue_from_epoch11
{'name': 'phase3_continue_from_epoch11', 'output_nemo': PosixPath('/kaggle/working/phase3_continue_best.nemo'), 'init_nemo': PosixPath('/kaggle/input/models/trnmnhtn/finetune-fastconformer/other/default/1/phase3_best_full_finetune.nemo'), 'trainable_mode': 'full_encoder_decoder', 'max_epochs': 12, 'lr': 2e-05, 'batch_size': 2, 'accumulate_grad_batches': 16, 'unfrozen_encoder_blocks': 0, 'max_duration': 8.0}
================================================================================
Restoring phase init model: /kaggle/input/models/trnmnhtn/finetune-fastconformer/other/default/1/phase3_best_full_finetune.nemo
[NeMo I 2026-07-01 10:43:14 mixins:184] Tokenizer SentencePieceTokenizer initialized with 1024 tokens

[NeMo W 2026-07-01 10:43:14 modelPT:188] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config :
    manifest_filepath: /kaggle/working/vivos_manifest_phase_best/train_manifest.json
    sample_rate: 16000
    batch_size: 2
    shuffle: true
    num_workers: 2
    pin_memory: true
    min_duration: 0.1
    is_tarred: false
    tarred_audio_filepaths: null
    max_duration: 8.0

[NeMo W 2026-07-01 10:43:14 modelPT:195] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
    Validation config :
    manifest_filepath: /kaggle/working/vivos_manifest_phase_best/val_manifest.json
    sample_rate: 16000
    batch_size: 2
    shuffle: false
    num_workers: 2
    pin_memory: true
    min_duration: 0.1
    is_tarred: false
    tarred_audio_filepaths: null

[NeMo W 2026-07-01 10:43:14 modelPT:202] Please call the ModelPT.setup_test_data() or ModelPT.setup_multiple_test_data() method and provide a valid configuration file to setup the test data loader(s).
    Test config :
    manifest_filepath: null
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    num_workers: 8
    pin_memory: true
    use_start_end_token: false

[NeMo I 2026-07-01 10:43:17 save_restore_connector:285] Model EncDecCTCModelBPE was successfully restored from /kaggle/input/models/trnmnhtn/finetune-fastconformer/other/default/1/phase3_best_full_finetune.nemo.
[NeMo I 2026-07-01 10:43:17 collections:201] Dataset loaded with 10047 files totalling 11.29 hours
[NeMo I 2026-07-01 10:43:17 collections:202] 1030 files were filtered totalling 2.86 hours
[NeMo I 2026-07-01 10:43:17 collections:201] Dataset loaded with 583 files totalling 0.77 hours
[NeMo I 2026-07-01 10:43:17 collections:202] 0 files were filtered totalling 0.00 hours
Trainable mode: full_encoder_decoder
Encoder trainable params: 115,074,560
Decoder trainable params: 525,825
Total trainable params: 115,600,385/115,600,385
First trainable parameter names: ['encoder.pre_encode.out.weight', 'encoder.pre_encode.out.bias', 'encoder.pre_encode.conv.0.weight', 'encoder.pre_encode.conv.0.bias', 'encoder.pre_encode.conv.2.weight', 'encoder.pre_encode.conv.2.bias', 'encoder.pre_encode.conv.3.weight', 'encoder.pre_encode.conv.3.bias', 'encoder.pre_encode.conv.5.weight', 'encoder.pre_encode.conv.5.bias', 'encoder.pre_encode.conv.6.weight', 'encoder.pre_encode.conv.6.bias', 'encoder.layers.0.norm_feed_forward1.weight', 'encoder.layers.0.norm_feed_forward1.bias', 'encoder.layers.0.feed_forward1.linear1.weight', 'encoder.layers.0.feed_forward1.linear1.bias', 'encoder.layers.0.feed_forward1.linear2.weight', 'encoder.layers.0.feed_forward1.linear2.bias', 'encoder.layers.0.norm_conv.weight', 'encoder.layers.0.norm_conv.bias']
[NeMo I 2026-07-01 10:43:17 modelPT:830] Optimizer config = AdamW (
    Parameter Group 0
        amsgrad: False
        betas: (0.9, 0.98)
        capturable: False
        decoupled_weight_decay: True
        differentiable: False
        eps: 1e-08
        foreach: None
        fused: None
        lr: 2e-05
        maximize: False
        weight_decay: 0.001
    )
[NeMo I 2026-07-01 10:43:17 lr_scheduler:995] Scheduler "<nemo.core.optim.lr_scheduler.CosineAnnealing object at 0x7a2064a45070>"
    will be used during training (effective maximum steps = 3768) -
    Parameters :
    (warmup_steps: 500
    min_lr: 2.0000000000000003e-06
    max_steps: 3768
    )
effective_batch_size: 32
steps_per_epoch: 314
estimated_total_steps: 3768
checkpoint_dir: /kaggle/working/nemo_experiments/fastconformer_vi/phase3_continue_from_epoch11/checkpoints
best_nemo_target: /kaggle/working/phase3_continue_best.nemo

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1]

[NeMo I 2026-07-01 10:43:17 modelPT:830] Optimizer config = AdamW (
    Parameter Group 0
        amsgrad: False
        betas: (0.9, 0.98)
        capturable: False
        decoupled_weight_decay: True
        differentiable: False
        eps: 1e-08
        foreach: None
        fused: None
        lr: 2e-05
        maximize: False
        weight_decay: 0.001
    )
[NeMo I 2026-07-01 10:43:17 lr_scheduler:995] Scheduler "<nemo.core.optim.lr_scheduler.CosineAnnealing object at 0x7a20650140b0>"
    will be used during training (effective maximum steps = 3768) -
    Parameters :
    (warmup_steps: 500
    min_lr: 2.0000000000000003e-06
    max_steps: 3768
    )

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

[NeMo W 2026-07-01 10:43:19 ctc_greedy_decoding:277] CTC decoding strategy 'greedy' is slower than 'greedy_batch', which implements the same exact interface. Consider changing your strategy to 'greedy_batch' for a free performance improvement.

[NeMo I 2026-07-01 10:43:19 wer:336]

[NeMo I 2026-07-01 10:43:19 wer:337] WER reference:những con vật này đã bị giết và đốt
[NeMo I 2026-07-01 10:43:19 wer:338] WER predicted:nh con vật này đã bị gì và tốt
[NeMo I 2026-07-01 10:43:19 wer:336]

[NeMo I 2026-07-01 10:43:19 wer:337] WER reference:do vậy có máy cũng không thường dùng
[NeMo I 2026-07-01 10:43:19 wer:338] WER predicted:do vậy có mấy cũng không thường dụng

Training: |          | 0/? [00:00<?, ?it/s]

[NeMo I 2026-07-01 10:44:02 wer:336]

[NeMo I 2026-07-01 10:44:02 wer:337] WER reference:kinh tế suy thoái khiến các nhà đầu tư la làng
[NeMo I 2026-07-01 10:44:02 wer:338] WER predicted:ki tế sĩ thôi khiặt nhà được từ là là
[NeMo I 2026-07-01 10:44:27 wer:336]

[NeMo I 2026-07-01 10:44:27 wer:337] WER reference:chúc anh sống vui vẻ và đạt được những điều tốt đẹp như mong ước
[NeMo I 2026-07-01 10:44:27 wer:338] WER predicted:trước anh sống phụ về và đ được nh điều tốt đẹp như m muốn
[NeMo I 2026-07-01 10:44:50 wer:336]

[NeMo I 2026-07-01 10:44:50 wer:337] WER reference:để tránh tích tụ chất béo bạn nên ăn thịt nạc
[NeMo I 2026-07-01 10:44:50 wer:338] WER predicted:để sản thức tôi chất theo bạn nên năng thạ
[NeMo I 2026-07-01 10:45:05 wer:336]

[NeMo I 2026-07-01 10:45:05 wer:337] WER reference:ông thường la rầy mỗi khi chúng tôi tiến đến gần khu vườn nhà ông
[NeMo I 2026-07-01 10:45:05 wer:338] WER predicted:ông từ ra ra một khi chúng tôi tiền đến g gần cứu phương nhau
[NeMo I 2026-07-01 10:45:19 wer:336]

[NeMo I 2026-07-01 10:45:19 wer:337] WER reference:rất nhiều trường hợp phụ huynh đau đầu vì con một đã tìm đến chuyên viên tư vấn tâm lý
[NeMo I 2026-07-01 10:45:19 wer:338] WER predicted:rất nhiều trường học ph quan đầu đầuì có một đã tìm đến trên viên tư vẫn tâm lý
[NeMo I 2026-07-01 10:45:33 wer:336]

[NeMo I 2026-07-01 10:45:33 wer:337] WER reference:vệ sinh an toàn thực phẩm ngày tết đỡ hơn nhưng chưa yên tâm
[NeMo I 2026-07-01 10:45:33 wer:338] WER predicted:về sinh ăn tạo thực phòng này tế đầu hơn nh chuyện làm
[NeMo I 2026-07-01 10:45:47 wer:336]

[NeMo I 2026-07-01 10:45:47 wer:337] WER reference:nhưng bất chấp những khó khăn anh đã tập luyện miệt mài
[NeMo I 2026-07-01 10:45:47 wer:338] WER predicted:nhưng b choững kh hàng anh đã tập liên m máy
[NeMo I 2026-07-01 10:45:58 wer:336]

[NeMo I 2026-07-01 10:45:58 wer:337] WER reference:lúc nhỏ thấy đứa bạn nào bị đánh là tôi đứng ra bảo vệ
[NeMo I 2026-07-01 10:45:58 wer:338] WER predicted:lúc nhỏ thấy tư bạn nào bị đã là tôi chúng ra b để
[NeMo I 2026-07-01 10:46:08 wer:336]

[NeMo I 2026-07-01 10:46:08 wer:337] WER reference:cũng phải thán phục
[NeMo I 2026-07-01 10:46:08 wer:338] WER predicted:cũng phải tăng phố
[NeMo I 2026-07-01 10:46:17 wer:336]

[NeMo I 2026-07-01 10:46:17 wer:337] WER reference:do đang trong thời gian nghỉ sau giải hạng nhất nên chí công chưa đủ thể lực để theo kịp giáo án tập
[NeMo I 2026-07-01 10:46:17 wer:338] WER predicted:do đang trong thời chỉ sau dài hàng nhất nên chi trong chưa đủ thể lúc để theo kịp cho anh tập
[NeMo I 2026-07-01 10:46:28 wer:336]

[NeMo I 2026-07-01 10:46:28 wer:337] WER reference:nếu con không đáp ứng được yêu cầu thì chính tôi sẽ đuổi con ngay
[NeMo I 2026-07-01 10:46:28 wer:338] WER predicted:ếu con không đọc ứng được yêu cầu thì chúng tôi sẽ vẫn con ngày
[NeMo I 2026-07-01 10:46:37 wer:336]

[NeMo I 2026-07-01 10:46:37 wer:337] WER reference:theo tôi đất đai là sở hữu toàn dân thì phải sử dụng đất một cách hiệu quả nhất cho xã hội
[NeMo I 2026-07-01 10:46:37 wer:338] WER predicted:theo người đ cái là sựư toàn dân thì phải sự dụng đ đất một gặp thì quá nhất cho s hội
[NeMo I 2026-07-01 10:46:46 wer:336]

[NeMo I 2026-07-01 10:46:46 wer:337] WER reference:các hoạt động tham quan nơi này
[NeMo I 2026-07-01 10:46:46 wer:338] WER predicted:các khó đồng th quan nơi này
[NeMo I 2026-07-01 10:46:55 wer:336]

[NeMo I 2026-07-01 10:46:55 wer:337] WER reference:những năm gần đây lượng khách về thăm khu chứng tích sơn mỹ tăng vọt
[NeMo I 2026-07-01 10:46:55 wer:338] WER predicted:những năm g đây lời khách và thông của trường thích s mỹ tăng bỏ
[NeMo I 2026-07-01 10:47:03 wer:336]

[NeMo I 2026-07-01 10:47:03 wer:337] WER reference:công trình chỉ được thi công lại
[NeMo I 2026-07-01 10:47:03 wer:338] WER predicted:công trên chỉ được thế công lại
[NeMo I 2026-07-01 10:47:12 wer:336]

[NeMo I 2026-07-01 10:47:12 wer:337] WER reference:cách lý sơn chừng dăm chục hải lý về phương bắc
[NeMo I 2026-07-01 10:47:12 wer:338] WER predicted:cách đi s chúng gi chúng hai lý về phương b
[NeMo I 2026-07-01 10:47:20 wer:336]

[NeMo I 2026-07-01 10:47:20 wer:337] WER reference:các nhà cung cấp thuốc nói anh không kê đơn thì những người khác vẫn làm giá thuốc cũng vẫn thế rồi
[NeMo I 2026-07-01 10:47:20 wer:338] WER predicted:các nhà cũng cấp thuốc nói anh không đi đến thìững được khi vẫn làm giá thuốc bốn vẫn tôi rồi
[NeMo I 2026-07-01 10:47:28 wer:336]

[NeMo I 2026-07-01 10:47:28 wer:337] WER reference:với câu trả lời xuất sắc và gương mặt khả ái
[NeMo I 2026-07-01 10:47:28 wer:338] WER predicted:với câu đã ở sức s và nguyên mà khá
[NeMo I 2026-07-01 10:47:36 wer:336]

[NeMo I 2026-07-01 10:47:36 wer:337] WER reference:hả họng gào liên hồi kỳ trận
[NeMo I 2026-07-01 10:47:36 wer:338] WER predicted:hà ông g liên họ chỉ trong
[NeMo I 2026-07-01 10:47:45 wer:336]

[NeMo I 2026-07-01 10:47:45 wer:337] WER reference:dân tài xế ngang tàng đến thế
[NeMo I 2026-07-01 10:47:45 wer:338] WER predicted:nhưng tại sĩ năng bạn đến thế
[NeMo I 2026-07-01 10:47:53 wer:336]

[NeMo I 2026-07-01 10:47:53 wer:337] WER reference:tổ chức hoạt động này nhằm có kế hoạch dài hạn
[NeMo I 2026-07-01 10:47:53 wer:338] WER predicted:vụ trước mà động này nhà có cứ mặt này học
[NeMo I 2026-07-01 10:48:01 wer:336]

[NeMo I 2026-07-01 10:48:01 wer:337] WER reference:cháu thật sự rất nghi vấn về tư cách của anh ấy và thấy lo lắm
[NeMo I 2026-07-01 10:48:01 wer:338] WER predicted:cho th sự rất gì đến về các trước các của ăn ngày và thế lo năm
[NeMo I 2026-07-01 10:48:09 wer:336]

[NeMo I 2026-07-01 10:48:09 wer:337] WER reference:nghĩa là người nào không có được tín nhiệm của dân thì sẽ không được bầu thì sẽ mất chức
[NeMo I 2026-07-01 10:48:09 wer:338] WER predicted:nghe là người nào không có được tính nghiệp của dân thì sẽ không được vào thì gì được ch
[NeMo I 2026-07-01 10:48:17 wer:336]

[NeMo I 2026-07-01 10:48:17 wer:337] WER reference:nhưng cảm giác lúc đó không ghê sợ như những ngày này
[NeMo I 2026-07-01 10:48:17 wer:338] WER predicted:nhưng các để lúc đó không cứ số như những này này
[NeMo I 2026-07-01 10:48:26 wer:336]

[NeMo I 2026-07-01 10:48:26 wer:337] WER reference:nhằm mục đích là gây quỹ học bỗng
[NeMo I 2026-07-01 10:48:26 wer:338] WER predicted:nhưng mộtạ là gái của th học b
[NeMo I 2026-07-01 10:48:33 wer:336]

[NeMo I 2026-07-01 10:48:33 wer:337] WER reference:đạo quân tả dực
[NeMo I 2026-07-01 10:48:33 wer:338] WER predicted:đầu qu ta dịch
[NeMo I 2026-07-01 10:48:41 wer:336]

[NeMo I 2026-07-01 10:48:41 wer:337] WER reference:nhiều lần như vậy nàng chợt nghĩ sao mình không chọn món mình thích và bảo chồng ăn chung với mình
[NeMo I 2026-07-01 10:48:41 wer:338] WER predicted:nhiều lần m vậy đang cho ngày sau mình em cho có mình hết và bảo trong ăn chúng với mốt
[NeMo I 2026-07-01 10:48:50 wer:336]

[NeMo I 2026-07-01 10:48:50 wer:337] WER reference:tôi đặt khẩu súng lục bên đầu nằm phòng khi nửa đêm nó viếng thăm bất ngờ
[NeMo I 2026-07-01 10:48:50 wer:338] WER predicted:tôi đã kh xuống lúc bên đầu năm phần khi được đêm nó nh trong b có
[NeMo I 2026-07-01 10:48:58 wer:336]

[NeMo I 2026-07-01 10:48:58 wer:337] WER reference:con gái gầy quá cố gắng ăn uống cho khỏe mà học tốt nghe con
[NeMo I 2026-07-01 10:48:58 wer:338] WER predicted:còn gái lại qua cô gáiắ u cho khỏe mà học tốt nghe con
[NeMo I 2026-07-01 10:49:05 wer:336]

[NeMo I 2026-07-01 10:49:05 wer:337] WER reference:doanh nghiệp nước ngoài được đầu tư chống thất thoát nước
[NeMo I 2026-07-01 10:49:05 wer:338] WER predicted:cho nghiệp mới đ được từ trong th th nước
[NeMo I 2026-07-01 10:49:14 wer:336]

[NeMo I 2026-07-01 10:49:14 wer:337] WER reference:tôi luôn vượt qua các đợt sát hạch của ban huấn luyện
[NeMo I 2026-07-01 10:49:14 wer:338] WER predicted:tôi luôn được qua các đất sách học của bạn h với
[NeMo I 2026-07-01 10:49:22 wer:336]

[NeMo I 2026-07-01 10:49:22 wer:337] WER reference:sẽ làm được tốt hơn những người không có đức tin
[NeMo I 2026-07-01 10:49:22 wer:338] WER predicted:sẽ làm được tốt hơn nh người không và được tính
[NeMo I 2026-07-01 10:49:31 wer:336]

[NeMo I 2026-07-01 10:49:31 wer:337] WER reference:như hạt bụi giữa ba nghìn thế giới
[NeMo I 2026-07-01 10:49:31 wer:338] WER predicted:như khác bộa bạn nhìn hơn giới
[NeMo I 2026-07-01 10:49:40 wer:336]

[NeMo I 2026-07-01 10:49:40 wer:337] WER reference:năm mươi năm mươi mốt
[NeMo I 2026-07-01 10:49:40 wer:338] WER predicted:năm mươi năm mươi mốt
[NeMo I 2026-07-01 10:49:48 wer:336]

[NeMo I 2026-07-01 10:49:48 wer:337] WER reference:lính bắn tỉa nả đạn
[NeMo I 2026-07-01 10:49:48 wer:338] WER predicted:lênnh bằng để nào đang
[NeMo I 2026-07-01 10:49:55 wer:336]

[NeMo I 2026-07-01 10:49:55 wer:337] WER reference:vì công việc nhiều và không phải lúc nào
[NeMo I 2026-07-01 10:49:55 wer:338] WER predicted:ì công việc nhiều và không phải l lúc nào
[NeMo I 2026-07-01 10:50:03 wer:336]

[NeMo I 2026-07-01 10:50:03 wer:337] WER reference:liên kết đào tạo huấn luyện cho tuyến dưới để giảm tải ở tuyến trên
[NeMo I 2026-07-01 10:50:03 wer:338] WER predicted:liên kết bà tạo h liên cho tin dưới để gi tại ở biến trên
[NeMo I 2026-07-01 10:50:12 wer:336]

[NeMo I 2026-07-01 10:50:12 wer:337] WER reference:đây sẽ là một trận đấu cởi mở đức sẽ giải quyết trận đấu ngay trong hiệp một
[NeMo I 2026-07-01 10:50:12 wer:338] WER predicted:đây gia là mộtẳng đầu cái mà kết x giá quyết ch đầu ngày trong hiệnp một
[NeMo I 2026-07-01 10:50:20 wer:336]

[NeMo I 2026-07-01 10:50:20 wer:337] WER reference:tôi biết có những bậc cha mẹ luôn bảo bọc con cái
[NeMo I 2026-07-01 10:50:20 wer:338] WER predicted:tôi biết có nhữngọ cho mẹ luôn bảo b con cái
[NeMo I 2026-07-01 10:50:29 wer:336]

[NeMo I 2026-07-01 10:50:29 wer:337] WER reference:lãi từ tiền mua bán xăng tôi sử dụng vào việc mở các trạm xăng dầu rồi thành lập luôn một công ty mua bán xăng dầu
[NeMo I 2026-07-01 10:50:29 wer:338] WER predicted:lại từ việc mua bạn sáng với sự dụng và việc và cácạ sáng d rồi th lập luôn công tới mua bạn sản d
[NeMo I 2026-07-01 10:50:36 wer:336]

[NeMo I 2026-07-01 10:50:36 wer:337] WER reference:người đẹp không thiếu chỉ sợ ông anh không có tiền
[NeMo I 2026-07-01 10:50:36 wer:338] WER predicted:người đẹp không thiếu chỉ s ở mình không đó tiền
[NeMo I 2026-07-01 10:50:44 wer:336]

[NeMo I 2026-07-01 10:50:44 wer:337] WER reference:theo phó chủ tịch ủy ban an toàn giao thông quốc gia
[NeMo I 2026-07-01 10:50:44 wer:338] WER predicted:theo ph chưa thích người bạn ăn tôi giáo thông quốc gia
[NeMo I 2026-07-01 10:50:52 wer:336]

[NeMo I 2026-07-01 10:50:52 wer:337] WER reference:mà biết có làm ăn gì được hay không
[NeMo I 2026-07-01 10:50:52 wer:338] WER predicted:mà biết có làm ăn gì được hai không
[NeMo I 2026-07-01 10:51:00 wer:336]

[NeMo I 2026-07-01 10:51:00 wer:337] WER reference:nước triều đang lên
[NeMo I 2026-07-01 10:51:00 wer:338] WER predicted:nước chưa đang lên
[NeMo I 2026-07-01 10:51:09 wer:336]

[NeMo I 2026-07-01 10:51:09 wer:337] WER reference:cua gái cũng là một nghệ thuật
[NeMo I 2026-07-01 10:51:09 wer:338] WER predicted:khu gái cũng là một cái xuất
[NeMo I 2026-07-01 10:51:17 wer:336]

[NeMo I 2026-07-01 10:51:17 wer:337] WER reference:xe tải của tôi không thắng tay ba nhịp chồng thành tám nhịp
[NeMo I 2026-07-01 10:51:17 wer:338] WER predicted:sẽ tại của tôi không thân tay ba nghiệp trong thành cảm nghiệp
[NeMo I 2026-07-01 10:51:25 wer:336]

[NeMo I 2026-07-01 10:51:25 wer:337] WER reference:tiêu dùng có trách nhiệm là một phần không thể tách rời của kinh doanh có trách nhiệm
[NeMo I 2026-07-01 10:51:25 wer:338] WER predicted:từ dụng có cách nhiệm là một ph không thể các rồi của chínhnh cóích nhiệm
[NeMo I 2026-07-01 10:51:33 wer:336]

[NeMo I 2026-07-01 10:51:33 wer:337] WER reference:khi ấy tôi đã biết ơn cái điểm số của mình biết chừng nào
[NeMo I 2026-07-01 10:51:33 wer:338] WER predicted:thì ấy tôi đã biết ăn đến điểm số của mình biết trường nào
[NeMo I 2026-07-01 10:51:41 wer:336]

[NeMo I 2026-07-01 10:51:41 wer:337] WER reference:một hai ba bốn năm
[NeMo I 2026-07-01 10:51:41 wer:338] WER predicted:một hai ba bốn năm
[NeMo I 2026-07-01 10:51:48 wer:336]

[NeMo I 2026-07-01 10:51:48 wer:337] WER reference:ngoài việc học lý thuyết tại trung tâm các học viên sẽ thực hành tại bệnh viện điều dưỡng và phục hồi chức năng thành phố
[NeMo I 2026-07-01 10:51:48 wer:338] WER predicted:ngoài vì kh lý việc tại chúng tâm các học viên sẽ từ hành tại bệnh viên điều d và hội ch năng thành ph
[NeMo I 2026-07-01 10:51:56 wer:336]

[NeMo I 2026-07-01 10:51:56 wer:337] WER reference:người trai ấy nhấp một ngụm rượu lớn và phun lên cây khèn
[NeMo I 2026-07-01 10:51:56 wer:338] WER predicted:nhưng bị tra đây các một nămmưa lớn và ph đang cái kh
[NeMo I 2026-07-01 10:52:05 wer:336]

[NeMo I 2026-07-01 10:52:05 wer:337] WER reference:họ đã chứng kiến quê cha đất tổ của mình bị người bồ đào nha xâm lược
[NeMo I 2026-07-01 10:52:05 wer:338] WER predicted:họ đã ch kiến qu cho đ tốt của mình tiền người bộ đồng nhà sống lực
[NeMo I 2026-07-01 10:52:13 wer:336]

[NeMo I 2026-07-01 10:52:13 wer:337] WER reference:cũng đã giải thích với giới truyền thông
[NeMo I 2026-07-01 10:52:13 wer:338] WER predicted:cũng đã dài thích với giới truyền thông
[NeMo I 2026-07-01 10:52:20 wer:336]

[NeMo I 2026-07-01 10:52:20 wer:337] WER reference:nhưng nếu muốn được đăng cai trước tiên bạn phải tham gia cái đã
[NeMo I 2026-07-01 10:52:20 wer:338] WER predicted:nhưng người muốn được đang cả ch tiền b thm giá cả đã
[NeMo I 2026-07-01 10:52:28 wer:336]

[NeMo I 2026-07-01 10:52:28 wer:337] WER reference:như vung tay mạnh
[NeMo I 2026-07-01 10:52:28 wer:338] WER predicted:như bốn tay m mình
[NeMo I 2026-07-01 10:52:36 wer:336]

[NeMo I 2026-07-01 10:52:36 wer:337] WER reference:bảy mươi hai bảy mươi ba
[NeMo I 2026-07-01 10:52:36 wer:338] WER predicted:bảy mươi hai bảy mươi ba
[NeMo I 2026-07-01 10:52:44 wer:336]

[NeMo I 2026-07-01 10:52:44 wer:337] WER reference:các máy để bàn cồng kềnh sẽ ngày càng ít đi trong mọi văn phòng
[NeMo I 2026-07-01 10:52:44 wer:338] WER predicted:các bảy thì bạn phòng cơ sẽ ngày cả ch đi trong mỗi văn phòng
[NeMo I 2026-07-01 10:52:52 wer:336]

[NeMo I 2026-07-01 10:52:52 wer:337] WER reference:gió mang hơi ấm pha chút lành lạnh của tiết xuân
[NeMo I 2026-07-01 10:52:52 wer:338] WER predicted:do mang thời ông phải trước lại làm được đi sinh
[NeMo I 2026-07-01 10:52:59 wer:336]

[NeMo I 2026-07-01 10:52:59 wer:337] WER reference:hao tổn thiệt hại từ việc di dời sẽ do chủ đầu tư gánh
[NeMo I 2026-07-01 10:52:59 wer:338] WER predicted:học trong thị hai từ việc chỉ giờ sẽ do tr đầu từ
[NeMo I 2026-07-01 10:53:07 wer:336]

[NeMo I 2026-07-01 10:53:07 wer:337] WER reference:đúng vậy và từ xuất phát điểm này ông đi tiếp
[NeMo I 2026-07-01 10:53:07 wer:338] WER predicted:đúng vậy và từ xuất phát điểm này ông đi thị
[NeMo I 2026-07-01 10:53:15 wer:336]

[NeMo I 2026-07-01 10:53:15 wer:337] WER reference:trong khi đó một giao dịch mua bán nhà nếu làm nhanh cũng mất khoảng một tháng
[NeMo I 2026-07-01 10:53:15 wer:338] WER predicted:trong khi đó một cái vụ bán nhàếu ăn thanh cũngân ngoài một tháng
[NeMo I 2026-07-01 10:53:22 wer:336]

[NeMo I 2026-07-01 10:53:22 wer:337] WER reference:thanh niên bắc giang cũng đã giao lưu với thanh niên tại các trại giam
[NeMo I 2026-07-01 10:53:22 wer:338] WER predicted:anh n b gian cũng ta giáo l với định liên tại các trả giá
[NeMo I 2026-07-01 10:53:30 wer:336]

[NeMo I 2026-07-01 10:53:30 wer:337] WER reference:nhiều viên gạch trên nền sân dẫn vào đền cũng chênh vênh
[NeMo I 2026-07-01 10:53:30 wer:338] WER predicted:nhiều viên các trên nên sống nh vào đến cũng trên đến
[NeMo I 2026-07-01 10:53:38 wer:336]

[NeMo I 2026-07-01 10:53:38 wer:337] WER reference:nên các trường chỉ nhắm vào số lượng là chính
[NeMo I 2026-07-01 10:53:38 wer:338] WER predicted:nên các trường chỉ nhận vào số luôn là chín
[NeMo I 2026-07-01 10:53:46 wer:336]

[NeMo I 2026-07-01 10:53:46 wer:337] WER reference:nhưng điều này thật ra rất có ích
[NeMo I 2026-07-01 10:53:46 wer:338] WER predicted:nhưng đều này tập ra rất ít
[NeMo I 2026-07-01 10:53:53 wer:336]

[NeMo I 2026-07-01 10:53:53 wer:337] WER reference:hồng hay nghỉ học để đi mua sắm và đi chơi cả tuần
[NeMo I 2026-07-01 10:53:53 wer:338] WER predicted:không hai ý học để đi mua sống và đi chưa cả tôi
[NeMo I 2026-07-01 10:54:01 wer:336]

[NeMo I 2026-07-01 10:54:01 wer:337] WER reference:khi chúng tôi rời quán người chủ kịp ném theo sau lưng lời gay gắt chiều nó làm gì con bé ấy gặp ai chẳng vòi vĩnh
[NeMo I 2026-07-01 10:54:01 wer:338] WER predicted:khi tôi r quá người chỉ nghiệp nam theo số lớn là g gây đã chưa đó làm gì công ấy cho ai trong cũng
[NeMo I 2026-07-01 10:54:09 wer:336]

[NeMo I 2026-07-01 10:54:09 wer:337] WER reference:lồng ghép mục tiêu giảm nghèo bền vững
[NeMo I 2026-07-01 10:54:09 wer:338] WER predicted:làm nghiệp một tiêuạ nhà mình với
[NeMo I 2026-07-01 10:54:16 wer:336]

[NeMo I 2026-07-01 10:54:16 wer:337] WER reference:ca pin tàu xị xé rách nát toàn hoàn toàn
[NeMo I 2026-07-01 10:54:16 wer:338] WER predicted:có biến tạo sĩ sẽ rấtắc còn hoàn toàn
[NeMo I 2026-07-01 10:54:24 wer:336]

[NeMo I 2026-07-01 10:54:24 wer:337] WER reference:và các thiết bị chuyên dùng
[NeMo I 2026-07-01 10:54:24 wer:338] WER predicted:và các thị bị chuyện dụng
[NeMo I 2026-07-01 10:54:32 wer:336]

[NeMo I 2026-07-01 10:54:32 wer:337] WER reference:bên cạnh những đồ chơi kinh dị đồ chơi phát điện cũng rất được giới học sinh ưa chuộng
[NeMo I 2026-07-01 10:54:32 wer:338] WER predicted:bên cả những đầu cho kinh gì đầu chơi phát điện cũng rất được giới học x nuôi chủ
[NeMo I 2026-07-01 10:54:40 wer:336]

[NeMo I 2026-07-01 10:54:40 wer:337] WER reference:thường xảy ra khi gập cổ hay xoay đầu
[NeMo I 2026-07-01 10:54:40 wer:338] WER predicted:từ sẽ g khi gặp có hay sĩ đầu
[NeMo I 2026-07-01 10:54:47 wer:336]

[NeMo I 2026-07-01 10:54:47 wer:337] WER reference:đồng thời cũng áp dụng chính sách phát thẻ học nghề đối với những khu vực mới nhập về hà nội
[NeMo I 2026-07-01 10:54:47 wer:338] WER predicted:đồng thời nhậnạ dụng chính sách phát thể học nhà đã với những khu vực mấy nhất về hà nó
[NeMo I 2026-07-01 10:54:55 wer:336]

[NeMo I 2026-07-01 10:54:55 wer:337] WER reference:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 10:54:55 wer:338] WER predicted:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 10:55:03 wer:336]

[NeMo I 2026-07-01 10:55:03 wer:337] WER reference:sau khi diễn ra rầm rộ trong gần một năm
[NeMo I 2026-07-01 10:55:03 wer:338] WER predicted:sau khi gian làm r rồi không đường một năm
[NeMo I 2026-07-01 10:55:11 wer:336]

[NeMo I 2026-07-01 10:55:11 wer:337] WER reference:hôm qua anh vừa sắm một con ngựa sắt đẹp lắm
[NeMo I 2026-07-01 10:55:11 wer:338] WER predicted:hô quanhừa sống một con người sách để lắm
[NeMo I 2026-07-01 10:55:19 wer:336]

[NeMo I 2026-07-01 10:55:19 wer:337] WER reference:xúc tôm tép bằng cái giủi
[NeMo I 2026-07-01 10:55:19 wer:338] WER predicted:xuất trong tế bằng cái dù
[NeMo I 2026-07-01 10:55:26 wer:336]

[NeMo I 2026-07-01 10:55:26 wer:337] WER reference:rồi sau đó nữa là một cuộc hẹn hò
[NeMo I 2026-07-01 10:55:26 wer:338] WER predicted:rồi s đó người làm một cuộc hàng họ
[NeMo I 2026-07-01 10:55:34 wer:336]

[NeMo I 2026-07-01 10:55:34 wer:337] WER reference:bà con còn tự bỏ tiền túi ra mua cừ
[NeMo I 2026-07-01 10:55:34 wer:338] WER predicted:ba con công tự và tiền tôi ra mua cơ
[NeMo I 2026-07-01 10:55:42 wer:336]

[NeMo I 2026-07-01 10:55:42 wer:337] WER reference:theo hàng xóm gia đình sống trong ngôi nhà trên rất hòa thuận và những đứa trẻ trong nhà rất dễ thương
[NeMo I 2026-07-01 10:55:42 wer:338] WER predicted:cho sống gia được trong trong người nhà trên được họ thu và những nước trẻ trong nhà được chỉ thứ
[NeMo I 2026-07-01 10:55:50 wer:336]

[NeMo I 2026-07-01 10:55:50 wer:337] WER reference:bình dương thêm một nhà máy sản xuất cần cẩu cần trục
[NeMo I 2026-07-01 10:55:50 wer:338] WER predicted:mình dự thêm một nhà máy sản xuất cần cầu cònục
[NeMo I 2026-07-01 10:55:58 wer:336]


Validation: |          | 0/? [00:00<?, ?it/s]

[NeMo I 2026-07-01 10:58:25 wer:336]

[NeMo I 2026-07-01 10:58:25 wer:337] WER reference:những con vật này đã bị giết và đốt
[NeMo I 2026-07-01 10:58:25 wer:338] WER predicted:nh con vật này đã bị gì và được
[NeMo I 2026-07-01 10:58:25 wer:336]

[NeMo I 2026-07-01 10:58:25 wer:337] WER reference:do vậy có máy cũng không thường dùng
[NeMo I 2026-07-01 10:58:25 wer:338] WER predicted:do vậy có mấy cũng không thường dụng
[NeMo I 2026-07-01 10:58:25 wer:336]

[NeMo I 2026-07-01 10:58:25 wer:337] WER reference:đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
[NeMo I 2026-07-01 10:58:25 wer:338] WER predicted:đây sẽ là của gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
[NeMo I 2026-07-01 10:58:25 wer:336]

[NeMo I 2026-07-01 10:58:25 wer:337] WER reference:sau đó một vật lạ bay xợt ngang nóc nhà ông
[NeMo I 2026-07-01 10:58:25 wer:338] WER predicted:sau đó một và là bảy sự năng n nước nhau
[NeMo I 2026-07-01 10:58:25 wer:336]

[NeMo I 2026-07-01 10:58:25 wer:337] WER reference:hiện ra tận phía xa
[NeMo I 2026-07-01 10:58:25 wer:338] WER predicted:hiện ra tình phía xa
[NeMo I 2026-07-01 10:58:25 wer:336]

[NeMo I 2026-07-01 10:58:25 wer:337] WER reference:nên với thông tin này
[NeMo I 2026-07-01 10:58:25 wer:338] WER predicted:nên với thông tiền này
[NeMo I 2026-07-01 10:58:25 wer:336]

[NeMo I 2026-07-01 10:58:25 wer:337] WER reference:và dân dã như chính cái tên của nó
[NeMo I 2026-07-01 10:58:25 wer:338] WER predicted:và dân gia như chính cái tình của nó
[NeMo I 2026-07-01 10:58:26 wer:336]

[NeMo I 2026-07-01 10:58:26 wer:337] WER reference:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 10:58:26 wer:338] WER predicted:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 10:58:26 wer:336]

[NeMo I 2026-07-01 10:58:26 wer:337] WER reference:sau nhiều pha hảm thành liên tục
[NeMo I 2026-07-01 10:58:26 wer:338] WER predicted:sau nhiều phá h thành liên tục
[NeMo I 2026-07-01 10:58:26 wer:336]

[NeMo I 2026-07-01 10:58:26 wer:337] WER reference:anh vẫn nhớ kỷ niệm cầu đầu lâu
[NeMo I 2026-07-01 10:58:26 wer:338] WER predicted:anh vẫn như kỳ nhiệm cầu đầu lâu
[NeMo I 2026-07-01 10:58:26 wer:336]

[NeMo I 2026-07-01 10:58:26 wer:337] WER reference:gay go lắm nhưng hoàng anh gia lai sẽ làm được
[NeMo I 2026-07-01 10:58:26 wer:338] WER predicted:g g có làm nhưng hơn anh gia là sẽ làm được
[NeMo I 2026-07-01 10:58:26 wer:336]

[NeMo I 2026-07-01 10:58:26 wer:337] WER reference:do đó khi chơi chung với bạn bè cùng lứa chúng thường tỏ ra thiếu tự tin
[NeMo I 2026-07-01 10:58:26 wer:338] WER predicted:do đó khi chơi chúng với bạn bé cũng lư chúng ta thường tôi cả thiếu từ tình
[NeMo I 2026-07-01 10:58:26 wer:336]

[NeMo I 2026-07-01 10:58:26 wer:337] WER reference:mối đục luỗng cả tấm gỗ
[NeMo I 2026-07-01 10:58:26 wer:338] WER predicted:mọ được luôn các t tâm g
[NeMo I 2026-07-01 10:58:26 wer:336]

[NeMo I 2026-07-01 10:58:26 wer:337] WER reference:người ta cho rằng trung tâm này có khả năng ảnh hưởng đến quá trình lão hóa
[NeMo I 2026-07-01 10:58:26 wer:338] WER predicted:người ta cho rằng trung tâm này có khá năng anh hướng đến quá trên lao hoa
[NeMo I 2026-07-01 10:58:26 wer:336]

[NeMo I 2026-07-01 10:58:26 wer:337] WER reference:các giò phong lan tháng ba cũng không chịu yên mình
[NeMo I 2026-07-01 10:58:26 wer:338] WER predicted:các cho phòng là tha bà cũng công chịu ý mình
[NeMo I 2026-07-01 10:58:26 wer:336]

[NeMo I 2026-07-01 10:58:26 wer:337] WER reference:hãy cho tôi quyền năng vô tận để bảo vệ loài vật
[NeMo I 2026-07-01 10:58:26 wer:338] WER predicted:hay cho tôi viên năng v vụ tăng để bảo về đối rất
[NeMo I 2026-07-01 10:58:27 wer:336]

[NeMo I 2026-07-01 10:58:27 wer:337] WER reference:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 10:58:27 wer:338] WER predicted:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 10:58:27 wer:336]

[NeMo I 2026-07-01 10:58:27 wer:337] WER reference:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 10:58:27 wer:338] WER predicted:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 10:58:27 wer:336]

[NeMo I 2026-07-01 10:58:27 wer:337] WER reference:sáng chiều hội diễn tiếng hát bảo minh do công ty bảo hiểm bảo minh tổ chức
[NeMo I 2026-07-01 10:58:27 wer:338] WER predicted:sáng chịu họ gian tiếng khác đầu mình do công ty báo em bảo mình tôi chức
[NeMo I 2026-07-01 10:58:27 wer:336]

[NeMo I 2026-07-01 10:58:27 wer:337] WER reference:cô nằm thiếp đi lúc nào không biết
[NeMo I 2026-07-01 10:58:27 wer:338] WER predicted:cô năm tiếp đi lúc nó không biết
[NeMo I 2026-07-01 10:58:27 wer:336]

[NeMo I 2026-07-01 10:58:27 wer:337] WER reference:mười bảy mười tám mười chín
[NeMo I 2026-07-01 10:58:27 wer:338] WER predicted:mươi bảy mươi tám mươi chín
[NeMo I 2026-07-01 10:58:27 wer:336]

[NeMo I 2026-07-01 10:58:27 wer:337] WER reference:tích cóp đủ thứ đồ lạc xon những ngọn đèn
[NeMo I 2026-07-01 10:58:27 wer:338] WER predicted:tiếp cấpưa thứ đồ đã số nhữngọ đến
[NeMo I 2026-07-01 10:58:28 wer:336]

[NeMo I 2026-07-01 10:58:28 wer:337] WER reference:nhưng đất nước đã chọn một nhà lãnh đạo khác
[NeMo I 2026-07-01 10:58:28 wer:338] WER predicted:nhưng nước nước đã cho một nhà là đầu khác
[NeMo I 2026-07-01 10:58:28 wer:336]

[NeMo I 2026-07-01 10:58:28 wer:337] WER reference:ưu thế này có được là nhờ quá trình cơ giới hóa nhanh sử dụng phân bón cho dù hậu quả có là
[NeMo I 2026-07-01 10:58:28 wer:338] WER predicted:uống thế này có được là nhà quá trình cơ giới hoa nh sự dụng phần bốn cho dụnghầu quá có lại
[NeMo I 2026-07-01 10:58:28 wer:336]

[NeMo I 2026-07-01 10:58:28 wer:337] WER reference:thường xuyên xảy ra hiện tượng đạo văn quỵt nhuận bút
[NeMo I 2026-07-01 10:58:28 wer:338] WER predicted:thường xuyên x ra hiện thường đầu văn quyết nh quốc
[NeMo I 2026-07-01 10:58:28 wer:336]

[NeMo I 2026-07-01 10:58:28 wer:337] WER reference:chỉ cho chúng tôi xem hàng đống gạch đá cát sỏi
[NeMo I 2026-07-01 10:58:28 wer:338] WER predicted:chỉ cho chúng tôi xem hàng đồng g đã các s
[NeMo I 2026-07-01 10:58:28 wer:336]

[NeMo I 2026-07-01 10:58:28 wer:337] WER reference:đối với cảng hàng không quốc tế đà nẵng sử dụng nhà ga hành khách hiện hữu làm nhà ga nội địa
[NeMo I 2026-07-01 10:58:28 wer:338] WER predicted:đối với càng hàng không quốc tới đã năng sự dụng nhà cả hành khách hiện hồ làm nhà cả nói để
[NeMo I 2026-07-01 10:58:28 wer:336]

[NeMo I 2026-07-01 10:58:28 wer:337] WER reference:người giàu thì vác nặng những xâu tiền kẽm trên vai
[NeMo I 2026-07-01 10:58:28 wer:338] WER predicted:ngườiào thì vật mặt những sau tiềnk trên phải
[NeMo I 2026-07-01 10:58:29 wer:336]

[NeMo I 2026-07-01 10:58:29 wer:337] WER reference:các nữ công nhân làm ca đêm
[NeMo I 2026-07-01 10:58:29 wer:338] WER predicted:các nữa công nhân làm cả điểm
[NeMo I 2026-07-01 10:58:29 wer:336]

[NeMo I 2026-07-01 10:58:29 wer:337] WER reference:tui biết bà giỏi rồi
[NeMo I 2026-07-01 10:58:29 wer:338] WER predicted:tôi biết ba d rồi
[NeMo I 2026-07-01 10:58:29 wer:336]

[NeMo I 2026-07-01 10:58:29 wer:337] WER reference:đưa một chú bồ câu bay đi bay về
[NeMo I 2026-07-01 10:58:29 wer:338] WER predicted:đường một chú bộ cầu bảy đi bị về
[NeMo I 2026-07-01 10:58:30 wer:336]

[NeMo I 2026-07-01 10:58:30 wer:337] WER reference:tôi đến kiểm tra và phát hiện thấy ông và cô gái nằm kia thám tử ra hiệu cho ngài triệu phú nhìn vào phòng tắm cô ta đã chết
[NeMo I 2026-07-01 10:58:30 wer:338] WER predicted:tôi đến kiếmm ra và phát hiện thấy ông và cô gái nămk tha từ ra hiểu cho ngày chịu phương nhìn vào phòng tâm cô đ đã chết
[NeMo I 2026-07-01 10:58:30 wer:336]

[NeMo I 2026-07-01 10:58:30 wer:337] WER reference:để thực hiện thắng lợi kế hoạch năm năm
[NeMo I 2026-07-01 10:58:30 wer:338] WER predicted:để thực hiện thân lại cái hết năm năm
[NeMo I 2026-07-01 10:58:30 wer:336]

[NeMo I 2026-07-01 10:58:30 wer:337] WER reference:trước khi hóa thân thành cộng hòa sét để đến bồ đào nha
[NeMo I 2026-07-01 10:58:30 wer:338] WER predicted:trước khi hoa thân thành có hoa sức để đến bộ động nhà
[NeMo I 2026-07-01 10:58:31 wer:336]

[NeMo I 2026-07-01 10:58:31 wer:337] WER reference:tuy nhiên tôi không chắc những người chưa từng đọc cuốn nhật ký có thể hiểu hết được ý nghĩa bộ phim
[NeMo I 2026-07-01 10:58:31 wer:338] WER predicted:tuy nhiên tôi không chắc những người chưa từ đọc cũng nhất kỳ có thể hiểu hết được ý nghĩ bộ phim
[NeMo I 2026-07-01 10:58:31 wer:336]

[NeMo I 2026-07-01 10:58:31 wer:337] WER reference:chi đầu tư từ khu vực nhà nước còn lớn và hiệu quả thấp
[NeMo I 2026-07-01 10:58:31 wer:338] WER predicted:chỉ đầu tư từ khu vực nhà n nước còn lớn và hiệu quá th hợp
[NeMo I 2026-07-01 10:58:31 wer:336]

[NeMo I 2026-07-01 10:58:31 wer:337] WER reference:cái nền xưa của nó bây giờ là một cái hố nông choèn
[NeMo I 2026-07-01 10:58:31 wer:338] WER predicted:cái nên sự của nó bị giờ là một cái hồ năm tr
[NeMo I 2026-07-01 10:58:32 wer:336]

[NeMo I 2026-07-01 10:58:32 wer:337] WER reference:giải truyền thông điện ảnh trung quốc là giải thưởng điện ảnh duy nhất xét trao cho tất cả các bộ phim hoa ngữ
[NeMo I 2026-07-01 10:58:32 wer:338] WER predicted:dài trên thường đến anh chúng quốc là dài thường đến anh gì sẽ cho cho tất cả các bộ hiện hoàn người
[NeMo I 2026-07-01 10:58:32 wer:336]

[NeMo I 2026-07-01 10:58:32 wer:337] WER reference:dự đoán ba tháng nữa giá cà phê sẽ tăng gấp đôi hiện nay
[NeMo I 2026-07-01 10:58:32 wer:338] WER predicted:điều rằng bà tháng nữa giá cả về sự tăng gặp đổi hiện này
[NeMo I 2026-07-01 10:58:32 wer:336]

[NeMo I 2026-07-01 10:58:32 wer:337] WER reference:họ đến đây vì nhiều mục đích
[NeMo I 2026-07-01 10:58:32 wer:338] WER predicted:họ đến đâyì nhiều mộtích
[NeMo I 2026-07-01 10:58:32 wer:336]

[NeMo I 2026-07-01 10:58:32 wer:337] WER reference:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 10:58:32 wer:338] WER predicted:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 10:58:32 wer:336]

[NeMo I 2026-07-01 10:58:32 wer:337] WER reference:vậy trước đây nông dân đối phó với hiện tượng này như thế nào thưa ông
[NeMo I 2026-07-01 10:58:32 wer:338] WER predicted:vậy trước này n năm nhân đối phố với hiện từ này như đến nào thu  ông
[NeMo I 2026-07-01 10:58:32 wer:336]

[NeMo I 2026-07-01 10:58:32 wer:337] WER reference:làm sao để có tiền nhanh nhất
[NeMo I 2026-07-01 10:58:32 wer:338] WER predicted:làm sao để có tiền nhân nhất
[NeMo I 2026-07-01 10:58:32 wer:336]

[NeMo I 2026-07-01 10:58:32 wer:337] WER reference:đùi dang ra ngoài
[NeMo I 2026-07-01 10:58:32 wer:338] WER predicted:được gian ra ngoài
[NeMo I 2026-07-01 10:58:32 wer:336]

[NeMo I 2026-07-01 10:58:32 wer:337] WER reference:đã hai lần cô gác lại ước mơ vào đời và cũng đã ít nhiều trải qua những thăng trầm xô bồ của cuộc sống
[NeMo I 2026-07-01 10:58:32 wer:338] WER predicted:đã hai lần cô gái lại  mới vào đời và cũng đã ít nhiều trái quá những thành trong số bộ của của sống
[NeMo I 2026-07-01 10:58:33 wer:336]

[NeMo I 2026-07-01 10:58:33 wer:337] WER reference:trong bối cảnh như vậy một phản ứng chính sách đối với vấn đề thất nghiệp đang là đòi hỏi cấp bách hiện nay
[NeMo I 2026-07-01 10:58:33 wer:338] WER predicted:trong bộ cảnh như vậy một phầnững chính sách đối với vẫn để nghiệp đang là để họ các cách hiện này
[NeMo I 2026-07-01 10:58:33 wer:336]

[NeMo I 2026-07-01 10:58:33 wer:337] WER reference:ở xứ sở chuột túi
[NeMo I 2026-07-01 10:58:33 wer:338] WER predicted:ở s sự chủ tôi
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:do vậy dựa trên cơ sở nào mà ông khoa phát biểu như vậy
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:do vậy dự trên cơ s nào ông khoa phát biểu như vậy
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:tá tàng
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:ta tăng
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:cách đây tám năm nhưng trước đó khoảng hai năm đã được mời đóng phim và có nhiều vai chính trong các phim điện ảnh truyền hình
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:cách đây tám năm những trước đó hoàn hai năm đã được mới động phim và có nhiều và chính trong các phim điện anh truyền hình
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:đã thăm hỏi thì thế nào cũng phải có quà cáp
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:đã thông họ thì thế nào cũng phải có quá các
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:có mặt tay xã điện phòng
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:em lơ đễnh lật xem vài tờ báo
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:em là điện l xem vậy từ báo
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:và không ít người cứ tì tì uống từ sáng đến tối suốt mấy ngày hội nghị
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:và không ít người cứ ty từ uống từ sáng đến tôi xuất máy ngày hội này
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:minh châu vào miền nam công tác tại nhà hát trần hữu trang
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:mình cao vào m năm công tất tại nhà hết rằng h rằng
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:hết chiến tranh quê hương im tiếng súng anh lính cụ hồ lại trở về với đời thường tham gia sản xuất xây dựng và bảo vệ đất nước
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:hết chín cho với hơn ý tiếng xuống anh lên của hồ lại cho về với đời thường tha giá sản xuất sẽ dựngững và b với đất nước
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:chuyến đi đó đến giờ vẫn là một ám ảnh trong ký ức tôi
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:chỉ đi đó đến giờ vẫn là một ông anh trong chỉ
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:ây da ây da
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:d gia
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:có rất nhiều vệ tinh bị rơi khỏi quỹ đạo
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:nhiều về tính bị rồi khó cuối nào
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:nhuốm đầy máu của thổ dân châu mỹ
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:dụng đây màu của thu dân cho mỹ
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:cụ thể về đất đai xây dựng văn hóa thuộc về từng ngành riêng biệt
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:cô thể về đất đây văn sẽ những bằng hoa thuốc về từ anh riêng biết
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:tôi muốn hỏi liệu có mùi hương sen nhân tạo là một loại hóa chất không
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:tôi muốn hỏi liệu có người hướng s nhân tạo là một loạii họ chắc cao
[NeMo I 2026-07-01 10:58:34 wer:336]

[NeMo I 2026-07-01 10:58:34 wer:337] WER reference:cả nhà bà ngoại cười nắc nẻ vì câu nói ngây ngô của con
[NeMo I 2026-07-01 10:58:34 wer:338] WER predicted:các nhà bao ngoài người nước ngheì cô nói ngày người của con
[NeMo I 2026-07-01 10:58:35 wer:336]

[NeMo I 2026-07-01 10:58:35 wer:337] WER reference:xin được chân khuân vác
[NeMo I 2026-07-01 10:58:35 wer:338] WER predicted:xin được trên khu phát
[NeMo I 2026-07-01 10:58:35 wer:336]

[NeMo I 2026-07-01 10:58:35 wer:337] WER reference:nằm khuất dưới tàn tre sát bờ sông châu
[NeMo I 2026-07-01 10:58:35 wer:338] WER predicted:quá giới đang trẻ sẽ bà sống ch
[NeMo I 2026-07-01 10:58:35 wer:336]

[NeMo I 2026-07-01 10:58:35 wer:337] WER reference:nếu kiên cố hóa thì vốn được đưa thẳng cho dân sẽ không thất thoát
[NeMo I 2026-07-01 10:58:35 wer:338] WER predicted:nếu ki cô hoa thì bốn đượcưa tăng cho dân sẽ không thật
[NeMo I 2026-07-01 10:58:35 wer:336]

[NeMo I 2026-07-01 10:58:35 wer:337] WER reference:nói chung cô hồng nào cũng có một số phận hoàn cảnh và cuộc đời riêng
[NeMo I 2026-07-01 10:58:35 wer:338] WER predicted:nói chúng cô học nào cũng có một số phần quan cảnh với của đời chuyện
[NeMo I 2026-07-01 10:58:35 wer:336]

[NeMo I 2026-07-01 10:58:35 wer:337] WER reference:nhưng tất cả những điều ấy chẳng mấy khi đi liền với nhau
[NeMo I 2026-07-01 10:58:35 wer:338] WER predicted:những tất cả những điều ấy ch mấy khi đi liên với nhau
[NeMo I 2026-07-01 10:58:36 wer:336]

[NeMo I 2026-07-01 10:58:36 wer:337] WER reference:như vậy là bạn có thể sử dụng được nhiều số điện thoại của nhiều nhà cung cấp dịch vụ chỉ trên một sim
[NeMo I 2026-07-01 10:58:36 wer:338] WER predicted:như vậy bạn có thể sự dụng được nhiều số đến thấy của như nhà cũng cấp dịch vụ chỉ trên một xem
[NeMo I 2026-07-01 10:58:36 wer:336]

[NeMo I 2026-07-01 10:58:36 wer:337] WER reference:trong trường hợp hai bên có thỏa thuận lại không yêu cầu trọng tài giải quyết nữa thì có quyền kiện ra tòa án
[NeMo I 2026-07-01 10:58:36 wer:338] WER predicted:trong trường hợp hai bên có thể thường lại không yêu cầu trong ta giải quyết nữa thì có viên kiến ra toàn ăn
[NeMo I 2026-07-01 10:58:36 wer:336]

[NeMo I 2026-07-01 10:58:36 wer:337] WER reference:kiểu này chắc phải cắt giảm biên chế
[NeMo I 2026-07-01 10:58:36 wer:338] WER predicted:chịu này chắc phải các giá biến chị
[NeMo I 2026-07-01 10:58:37 wer:336]

[NeMo I 2026-07-01 10:58:37 wer:337] WER reference:nhưng tôi không yêu cô cô biết rõ điều đó mà
[NeMo I 2026-07-01 10:58:37 wer:338] WER predicted:nhưng tôi không yêu cô cô biết rồi điều đó mà
[NeMo I 2026-07-01 10:58:37 wer:336]

[NeMo I 2026-07-01 10:58:37 wer:337] WER reference:khó mà đoán trước chính xác kết quả khi quả bóng còn lăn
[NeMo I 2026-07-01 10:58:37 wer:338] WER predicted:không mà đó trước chính sẽ cách qua khi qua b con
[NeMo I 2026-07-01 10:58:37 wer:336]

[NeMo I 2026-07-01 10:58:37 wer:337] WER reference:vừa nhìn thấy sự xuất hiện của bố tất cả mấy thằng khác vùng bỏ chạy sạch
[NeMo I 2026-07-01 10:58:37 wer:338] WER predicted:với nh thấy sự khi của bố tất cả máy th thành khác vùng bỏi trẻ sách
[NeMo I 2026-07-01 10:58:37 wer:336]

[NeMo I 2026-07-01 10:58:37 wer:337] WER reference:phải nâng cao khả năng cạnh tranh của nền kinh tế
[NeMo I 2026-07-01 10:58:37 wer:338] WER predicted:phải n cao kh năng cảnh trên của nên kinh tình
[NeMo I 2026-07-01 10:58:37 wer:336]

[NeMo I 2026-07-01 10:58:37 wer:337] WER reference:bà thường lấy ý tưởng cho các tác phẩm từ đâu
[NeMo I 2026-07-01 10:58:37 wer:338] WER predicted:bà thườngấy ý từ cho các tác phẩm từ đầu
[NeMo I 2026-07-01 10:58:37 wer:336]

[NeMo I 2026-07-01 10:58:37 wer:337] WER reference:khi chứng kiến người vợ lăng loàn
[NeMo I 2026-07-01 10:58:37 wer:338] WER predicted:khi chính kiến người vào lần lòng
[NeMo I 2026-07-01 10:58:38 wer:336]

[NeMo I 2026-07-01 10:58:38 wer:337] WER reference:tác phẩm to lớn bằng đồng như tượng phật quỳnh lâm chuông quy điền tháp báo thiên vạc phổ minh an nam tứ đại khí
[NeMo I 2026-07-01 10:58:38 wer:338] WER predicted:đã phẩm ta luôn bạn đồng như thường phát quan làm chúng quy điện th bảo tìm và phố mình ăn năm từ đây khi
[NeMo I 2026-07-01 10:58:38 wer:336]

[NeMo I 2026-07-01 10:58:38 wer:337] WER reference:ngoài ra họ vẫn còn muốn giữ chân cầu thủ xuất sắc nhất của mình
[NeMo I 2026-07-01 10:58:38 wer:338] WER predicted:họ vẫn cầu muốnư chân cầu thủ s s
[NeMo I 2026-07-01 10:58:38 wer:336]

[NeMo I 2026-07-01 10:58:38 wer:337] WER reference:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 10:58:38 wer:338] WER predicted:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 10:58:38 wer:336]

[NeMo I 2026-07-01 10:58:38 wer:337] WER reference:và gã thệ bị điều về làm trưởng phòng xã hội huyện
[NeMo I 2026-07-01 10:58:38 wer:338] WER predicted:và cả thể biết điều về làm trường phần x hội h
[NeMo I 2026-07-01 10:58:38 wer:336]

[NeMo I 2026-07-01 10:58:38 wer:337] WER reference:là rút rỉa tiền của bạn càng nhiều càng tốt

[NeMo W 2026-07-01 10:59:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 10:59:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

Sample predictions after epoch 1:
  [0] REF: những con vật này đã bị giết và đốt
      HYP: nh con vật này đã bị gì và được
  [1] REF: phòng chống tham nhũng không được chủ quan cần làm liên tục đồng bộ và có các giải pháp
      HYP: phòng trong tha dụng không được chủ quan cần làm liên tục động bộ và có các lại pháp
  [2] REF: do vậy có máy cũng không thường dùng
      HYP: do vậy có mấy cũng không thường dụng
  [3] REF: mới khệnh khạng đứng lên đi ra
      HYP: mới kh hàng đến lên đi ra
  [4] REF: đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
      HYP: đây sẽ là của gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
  [5] REF: sau một năm eo sèo
      HYP: sáu một năm yêu sẽ
  [6] REF: sau đó một vật lạ bay xợt ngang nóc nhà ông
      HYP: sau đó một và là bảy sự năng n nước nhau
  [7] REF: chín mươi hai chín mươi ba
      HYP: chín mươi hai chín mươi ba
  [8] REF: hiện ra tận phía xa
      HYP: hiện ra tình phía xa
  [9] REF: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã qua của thị trường
      HYP: những gì chúng ta đã làm chỉ thứ hợp với những thời điểm đã quá của thì trường
[epoch] epoch=1/12 step=314 val_loss=None val_wer=None
[NeMo I 2026-07-01 11:00:01 wer:336]

[NeMo I 2026-07-01 11:00:01 wer:337] WER reference:rất nhiều trường hợp phụ huynh đau đầu vì con một đã tìm đến chuyên viên tư vấn tâm lý
[NeMo I 2026-07-01 11:00:01 wer:338] WER predicted:rất người trường học phụ kh đầu đầuì anh một đã tìm đến trên viên tư anh tâm lý
[NeMo I 2026-07-01 11:00:09 wer:336]

[NeMo I 2026-07-01 11:00:09 wer:337] WER reference:trước tình thế đó tôi buộc phải tìm cho mình một bến đỗ mới và tôi đã quyết định ra đi
[NeMo I 2026-07-01 11:00:09 wer:338] WER predicted:lúc tình thế đó tôi bộ phải tiền cho mình một bình đầu mới và tôi đã quyết định ra
[NeMo I 2026-07-01 11:00:18 wer:336]

[NeMo I 2026-07-01 11:00:18 wer:337] WER reference:tuy nhiên tình hình đó không diễn ra ở tất cả trường
[NeMo I 2026-07-01 11:00:18 wer:338] WER predicted:tuy nhiên tình hình đó không nh khác ở tất các trường
[NeMo I 2026-07-01 11:00:26 wer:336]

[NeMo I 2026-07-01 11:00:26 wer:337] WER reference:nếu xét trên qui mô toàn tỉnh con số ấy vẫn còn khiêm tốn lắm
[NeMo I 2026-07-01 11:00:26 wer:338] WER predicted:để x chỉ viên mua toàn tình còn số ấy vẫn còn khiù làm
[NeMo I 2026-07-01 11:00:35 wer:336]

[NeMo I 2026-07-01 11:00:35 wer:337] WER reference:các vùng sâu vùng xa khó mà phát triển
[NeMo I 2026-07-01 11:00:35 wer:338] WER predicted:các vùng sau vùng sẽ khó mà khác đi
[NeMo I 2026-07-01 11:00:43 wer:336]

[NeMo I 2026-07-01 11:00:43 wer:337] WER reference:thì không hiểu sao ở phần thơ cổ đại
[NeMo I 2026-07-01 11:00:43 wer:338] WER predicted:thì không hiểu s ở phần hết của đây
[NeMo I 2026-07-01 11:00:52 wer:336]

[NeMo I 2026-07-01 11:00:52 wer:337] WER reference:anh muốn thùy có thể tự do tìm cho mình một hạnh phúc khác tràn đầy
[NeMo I 2026-07-01 11:00:52 wer:338] WER predicted:anh muốn thời có thể từ do tìm cho mình một thành ph khác ngày lại
[NeMo I 2026-07-01 11:01:01 wer:336]

[NeMo I 2026-07-01 11:01:01 wer:337] WER reference:áo thun trắng sát nách
[NeMo I 2026-07-01 11:01:01 wer:338] WER predicted:ở thu trang sát nhất
[NeMo I 2026-07-01 11:01:09 wer:336]

[NeMo I 2026-07-01 11:01:09 wer:337] WER reference:đây cũng là giai đoạn thị trường nhiều biến cố nhất
[NeMo I 2026-07-01 11:01:09 wer:338] WER predicted:đây cũng là chế đồng thì trường nhiều biến cô nhất
[NeMo I 2026-07-01 11:01:18 wer:336]

[NeMo I 2026-07-01 11:01:18 wer:337] WER reference:mới thành món ngon và độc đáo
[NeMo I 2026-07-01 11:01:18 wer:338] WER predicted:mới thành m ng và được đầu
[NeMo I 2026-07-01 11:01:26 wer:336]

[NeMo I 2026-07-01 11:01:26 wer:337] WER reference:người đẹp không thiếu chỉ sợ ông anh không có tiền
[NeMo I 2026-07-01 11:01:26 wer:338] WER predicted:người để không hiểu chỉ s ông anh không có trình
[NeMo I 2026-07-01 11:01:35 wer:336]

[NeMo I 2026-07-01 11:01:35 wer:337] WER reference:ngày thường chù ụ thì được
[NeMo I 2026-07-01 11:01:35 wer:338] WER predicted:ngày thường chủ ông gì được
[NeMo I 2026-07-01 11:01:44 wer:336]

[NeMo I 2026-07-01 11:01:44 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 11:01:44 wer:338] WER predicted:có mặt tại sẽ điện phương
[NeMo I 2026-07-01 11:01:52 wer:336]

[NeMo I 2026-07-01 11:01:52 wer:337] WER reference:tôi cũng biết có những tiêu cực trong giáo dục và nhà trường cũng như những lĩnh vực khác của xã hội
[NeMo I 2026-07-01 11:01:52 wer:338] WER predicted:tôi cũng biết có những tiêu thực trong giá được và nhà trường của như những lên với h của xã hội
[NeMo I 2026-07-01 11:02:01 wer:336]

[NeMo I 2026-07-01 11:02:01 wer:337] WER reference:xắn quần vượt qua là bước vào thế giới
[NeMo I 2026-07-01 11:02:01 wer:338] WER predicted:sống qu v qua là bước vào thời giới
[NeMo I 2026-07-01 11:02:09 wer:336]

[NeMo I 2026-07-01 11:02:09 wer:337] WER reference:mới và cải tiến
[NeMo I 2026-07-01 11:02:09 wer:338] WER predicted:mới và cái tiền
[NeMo I 2026-07-01 11:02:18 wer:336]

[NeMo I 2026-07-01 11:02:18 wer:337] WER reference:hai vợ chồng thị tớn và văn đục
[NeMo I 2026-07-01 11:02:18 wer:338] WER predicted:hai vợ trong thì từ và văn được
[NeMo I 2026-07-01 11:02:27 wer:336]

[NeMo I 2026-07-01 11:02:27 wer:337] WER reference:chợ đêm ca ba dành cho những người đang vào mùa tăng ca cuối năm
[NeMo I 2026-07-01 11:02:27 wer:338] WER predicted:ở đến và và danh cho nh người đang vào một thành cả cứ năm
[NeMo I 2026-07-01 11:02:35 wer:336]

[NeMo I 2026-07-01 11:02:35 wer:337] WER reference:hai mươi hai mươi mốt
[NeMo I 2026-07-01 11:02:35 wer:338] WER predicted:hai mươi hai mươi mốt
[NeMo I 2026-07-01 11:02:43 wer:336]

[NeMo I 2026-07-01 11:02:43 wer:337] WER reference:anh không thể quên được những giây phút ngọt ngào ấy
[NeMo I 2026-07-01 11:02:44 wer:338] WER predicted:anh tôi được quan được nh ph nhiên ngọ nào ấy
[NeMo I 2026-07-01 11:02:52 wer:336]

[NeMo I 2026-07-01 11:02:52 wer:337] WER reference:đưa tới tình trạng phá sản
[NeMo I 2026-07-01 11:02:52 wer:338] WER predicted:người tư tiền rất phá sản
[NeMo I 2026-07-01 11:03:01 wer:336]

[NeMo I 2026-07-01 11:03:01 wer:337] WER reference:phụ huynh và học sinh đang phải è cổ vì sách giá cao
[NeMo I 2026-07-01 11:03:01 wer:338] WER predicted:vụ qu và học sinh đang phải em cô vì sách gia cao
[NeMo I 2026-07-01 11:03:09 wer:336]

[NeMo I 2026-07-01 11:03:09 wer:337] WER reference:thỉnh thoảng lại có người ghép thận trước đó trở qua xin xét nghiệm vì có trục trặc
[NeMo I 2026-07-01 11:03:09 wer:338] WER predicted:tình toàn lại có người g thân tư tập tôi qua sinh sẽ nghe về có tr đọc
[NeMo I 2026-07-01 11:03:18 wer:336]

[NeMo I 2026-07-01 11:03:18 wer:337] WER reference:cuộc thi nhằm trau dồi niềm đam mê
[NeMo I 2026-07-01 11:03:18 wer:338] WER predicted:cuộc thế nh cho d nhiệm đã mẹ
[NeMo I 2026-07-01 11:03:26 wer:336]

[NeMo I 2026-07-01 11:03:26 wer:337] WER reference:đề thi môn vẽ thông thường là về vẽ trang trí sản phẩm vật thể
[NeMo I 2026-07-01 11:03:26 wer:338] WER predicted:để thi muốn v vẻ hô thường là về việc sáng chỉ sáng phẩm một thể
[NeMo I 2026-07-01 11:03:35 wer:336]

[NeMo I 2026-07-01 11:03:35 wer:337] WER reference:bước vào một mối tình
[NeMo I 2026-07-01 11:03:35 wer:338] WER predicted:bước vào một mua tình
[NeMo I 2026-07-01 11:03:44 wer:336]

[NeMo I 2026-07-01 11:03:44 wer:337] WER reference:lão nạp chỉ có nhiêu đây thôi
[NeMo I 2026-07-01 11:03:44 wer:338] WER predicted:là ôngạ chỉ có như lại tôi
[NeMo I 2026-07-01 11:03:52 wer:336]

[NeMo I 2026-07-01 11:03:52 wer:337] WER reference:hai tuần sau
[NeMo I 2026-07-01 11:03:52 wer:338] WER predicted:hai cũng sáu
[NeMo I 2026-07-01 11:04:01 wer:336]

[NeMo I 2026-07-01 11:04:01 wer:337] WER reference:những ngày cuối cùng trên dương thế
[NeMo I 2026-07-01 11:04:01 wer:338] WER predicted:những này của công trên nhưng thế
[NeMo I 2026-07-01 11:04:09 wer:336]

[NeMo I 2026-07-01 11:04:09 wer:337] WER reference:trên nhiều tuyến phố công nhân đang hối hả dọn dẹp
[NeMo I 2026-07-01 11:04:09 wer:338] WER predicted:trên nhiều tiếng ph công nh đang hội hay động nghiệpp
[NeMo I 2026-07-01 11:04:17 wer:336]

[NeMo I 2026-07-01 11:04:17 wer:337] WER reference:có trường hợp bất hợp pháp như trần thị thu h
[NeMo I 2026-07-01 11:04:17 wer:338] WER predicted:có chuyện học b học pháp như trong thì thu
[NeMo I 2026-07-01 11:04:26 wer:336]

[NeMo I 2026-07-01 11:04:26 wer:337] WER reference:nhưng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được các khó khăn đó
[NeMo I 2026-07-01 11:04:26 wer:338] WER predicted:chúng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được cả kh không đó
[NeMo I 2026-07-01 11:04:34 wer:336]

[NeMo I 2026-07-01 11:04:34 wer:337] WER reference:lúc đó em không thể tiếp tục công việc đánh cá của cha một mình vì còn quá nhỏ
[NeMo I 2026-07-01 11:04:34 wer:338] WER predicted:lúc đó em không phải tiếp cơ không việc đến các của ch một mình việc còn qua nhỏ
[NeMo I 2026-07-01 11:04:43 wer:336]

[NeMo I 2026-07-01 11:04:43 wer:337] WER reference:cuốn sách nói về sự lầm lẫn giữa luật kinh tế ở châu âu và châu mỹ kim vẫn chưa đọc tới vì cô không quan tâm đến luật
[NeMo I 2026-07-01 11:04:43 wer:338] WER predicted:cũng sẽ nói về làm lần d được ki thế ở trong ông và trong muốn cho vẫn chưa đọc tôi việc của không quan tăng đến luật
[NeMo I 2026-07-01 11:04:51 wer:336]

[NeMo I 2026-07-01 11:04:51 wer:337] WER reference:khi tên lửa bay lên
[NeMo I 2026-07-01 11:04:51 wer:338] WER predicted:khi đến lực vậy lên
[NeMo I 2026-07-01 11:05:00 wer:336]

[NeMo I 2026-07-01 11:05:00 wer:337] WER reference:mà theo thời gian sẽ tiệm cận với trí khôn của con người
[NeMo I 2026-07-01 11:05:00 wer:338] WER predicted:mà theo thời dân sẽ tìm cần với trí cũng quốc con người
[NeMo I 2026-07-01 11:05:08 wer:336]

[NeMo I 2026-07-01 11:05:08 wer:337] WER reference:bên kia láng giềng của tôi hôm nay không thấy thăm hoa
[NeMo I 2026-07-01 11:05:08 wer:338] WER predicted:đến chỉ là diễn của tôi hô này không thấy th h
[NeMo I 2026-07-01 11:05:17 wer:336]

[NeMo I 2026-07-01 11:05:17 wer:337] WER reference:anh yêu cầu các cầu thủ phải đeo bám ngay khi đối phương có bóng
[NeMo I 2026-07-01 11:05:17 wer:338] WER predicted:anh nhiều cầu các cầu số phảieo bạn ngày khi đối phương có
[NeMo I 2026-07-01 11:05:25 wer:336]

[NeMo I 2026-07-01 11:05:25 wer:337] WER reference:ngay cả công an đi lẻ loi cũng bị tấn công vì trong khu vực này có một thứ luật riêng cấm người lạ vào
[NeMo I 2026-07-01 11:05:25 wer:338] WER predicted:nghe và không đi lẽ cũng bị không con việc trong có việc mẹ một thứ lực viên công như l
[NeMo I 2026-07-01 11:05:34 wer:336]

[NeMo I 2026-07-01 11:05:34 wer:337] WER reference:thì chúng sẽ nằm trong tầm kiểm soát của bạn
[NeMo I 2026-07-01 11:05:34 wer:338] WER predicted:thì chúng sẽ năm trong làmm kiể sau của bạn
[NeMo I 2026-07-01 11:05:42 wer:336]

[NeMo I 2026-07-01 11:05:42 wer:337] WER reference:đó là hai con sói hoàn toàn trái ngược nhau về hình thức
[NeMo I 2026-07-01 11:05:42 wer:338] WER predicted:đó là hay con s hộ còn chính được nhau về hình thức
[NeMo I 2026-07-01 11:05:51 wer:336]

[NeMo I 2026-07-01 11:05:51 wer:337] WER reference:trại đồng xã yên sở giữa một biển nước mênh mông ảnh nguyễn quân
[NeMo I 2026-07-01 11:05:51 wer:338] WER predicted:tr đồng x em s giờ một bịương mình m anh nguyên quan
[NeMo I 2026-07-01 11:05:59 wer:336]

[NeMo I 2026-07-01 11:05:59 wer:337] WER reference:không sao rồi em mừng lắm
[NeMo I 2026-07-01 11:05:59 wer:338] WER predicted:không sao rồi em mình làm
[NeMo I 2026-07-01 11:06:08 wer:336]

[NeMo I 2026-07-01 11:06:08 wer:337] WER reference:việc tòa án của pháp truy tố công dân một nước độc lập trên lãnh thổ quê hương của người ấy là một điều vô giá trị
[NeMo I 2026-07-01 11:06:08 wer:338] WER predicted:việc tôi ăn cuộc phát tr tốt không một được được l trên l lên tôi cuối hơn ng ở ấy là một bị chú giá chỉ
[NeMo I 2026-07-01 11:06:16 wer:336]

[NeMo I 2026-07-01 11:06:16 wer:337] WER reference:bà mẹ nghèo đông con
[NeMo I 2026-07-01 11:06:16 wer:338] WER predicted:và mẹ nghe vẫn con
[NeMo I 2026-07-01 11:06:25 wer:336]

[NeMo I 2026-07-01 11:06:25 wer:337] WER reference:lấy tĩnh chế động
[NeMo I 2026-07-01 11:06:25 wer:338] WER predicted:l liệu tình cho đồng
[NeMo I 2026-07-01 11:06:33 wer:336]

[NeMo I 2026-07-01 11:06:33 wer:337] WER reference:mình mẩy tôi tuy đau đớn
[NeMo I 2026-07-01 11:06:33 wer:338] WER predicted:mình bảy tôi tuy đau đường
[NeMo I 2026-07-01 11:06:42 wer:336]

[NeMo I 2026-07-01 11:06:42 wer:337] WER reference:luôn ngẩng cao đầu sự khác biệt lớn nhất giữa người tự tin và người nhút nhát là gì
[NeMo I 2026-07-01 11:06:42 wer:338] WER predicted:luôn ngn cao đầu x khách người lớn nhỏ d người từ tiền biết và người nhất nhạc là gì
[NeMo I 2026-07-01 11:06:50 wer:336]

[NeMo I 2026-07-01 11:06:50 wer:337] WER reference:với các bạn trẻ trên đây có vẻ tình yêu không phải là tất cả
[NeMo I 2026-07-01 11:06:50 wer:338] WER predicted:với các bạn trẻ chính đây có tình yêu kh và là tục cả
[NeMo I 2026-07-01 11:06:59 wer:336]

[NeMo I 2026-07-01 11:06:59 wer:337] WER reference:nếu trẻ bú không đủ có thể vắt sữa và cho trẻ uống bằng muỗng
[NeMo I 2026-07-01 11:06:59 wer:338] WER predicted:như trẻú không đủ có thể biết sự và tr trẻ  uống bằngôn
[NeMo I 2026-07-01 11:07:07 wer:336]

[NeMo I 2026-07-01 11:07:07 wer:337] WER reference:hãy để thời gian tìm hiểu thêm và thuyết phục gia đình
[NeMo I 2026-07-01 11:07:07 wer:338] WER predicted:hay để thời gian để mỹ thêm phải thu phục gia đình
[NeMo I 2026-07-01 11:07:15 wer:336]

[NeMo I 2026-07-01 11:07:15 wer:337] WER reference:vân vân và vân vân
[NeMo I 2026-07-01 11:07:15 wer:338] WER predicted:vẫn bốn và vẫn bốn
[NeMo I 2026-07-01 11:07:24 wer:336]

[NeMo I 2026-07-01 11:07:24 wer:337] WER reference:mà phụ nữ trong khu vực công đang gặp phải
[NeMo I 2026-07-01 11:07:24 wer:338] WER predicted:mà phụ nơi trong khu vực công đang g gặp phải
[NeMo I 2026-07-01 11:07:32 wer:336]

[NeMo I 2026-07-01 11:07:32 wer:337] WER reference:những năm trước phần lớn sếu ở kiên lương kiên giang
[NeMo I 2026-07-01 11:07:32 wer:338] WER predicted:những năm ch phần lên sẽ ở khi lớn ki gia
[NeMo I 2026-07-01 11:07:41 wer:336]

[NeMo I 2026-07-01 11:07:41 wer:337] WER reference:theo nguyên đào kinh tế đô thị
[NeMo I 2026-07-01 11:07:41 wer:338] WER predicted:theo nguyên đào ki tìnhưa thời
[NeMo I 2026-07-01 11:07:50 wer:336]

[NeMo I 2026-07-01 11:07:50 wer:337] WER reference:nhưng ngủ quá nhiều sẽ khiến bạn trở nên bơ phờ
[NeMo I 2026-07-01 11:07:50 wer:338] WER predicted:nhưng người quá nhiều sẽ khiến đangở đến b ph
[NeMo I 2026-07-01 11:07:58 wer:336]

[NeMo I 2026-07-01 11:07:58 wer:337] WER reference:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 11:07:58 wer:338] WER predicted:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 11:08:06 wer:336]

[NeMo I 2026-07-01 11:08:06 wer:337] WER reference:thường xuyên đối mặt với nạn khan hiếm lương thực
[NeMo I 2026-07-01 11:08:06 wer:338] WER predicted:thường x đối m với ăn khá hếm luôn thực
[NeMo I 2026-07-01 11:08:15 wer:336]

[NeMo I 2026-07-01 11:08:15 wer:337] WER reference:tôi có cảm tình với cô ấy nhưng tôi không muốn xen vào giữa họ
[NeMo I 2026-07-01 11:08:15 wer:338] WER predicted:tôi có cảm tình về cơiững tôi không muốn xe vào d họ
[NeMo I 2026-07-01 11:08:23 wer:336]

[NeMo I 2026-07-01 11:08:23 wer:337] WER reference:với tôi chết là một sự ích kỷ còn bản chất sự sống đã là một bao dung ít nhất với chính mình
[NeMo I 2026-07-01 11:08:23 wer:338] WER predicted:với tôi ch là sự đi công bạn ch sĩ sống đã một bao người biết nhất với chính mới
[NeMo I 2026-07-01 11:08:32 wer:336]

[NeMo I 2026-07-01 11:08:32 wer:337] WER reference:cậu không biết làm gì thì suốt đời cậu đúng là một kẻ hèn nhát
[NeMo I 2026-07-01 11:08:32 wer:338] WER predicted:cầu không biết làm chỉ thì xuất đời cầu đường là một các hiện nhà
[NeMo I 2026-07-01 11:08:41 wer:336]

[NeMo I 2026-07-01 11:08:41 wer:337] WER reference:màu đen của những tấm cha
[NeMo I 2026-07-01 11:08:41 wer:338] WER predicted:màu để của những tâm xe
[NeMo I 2026-07-01 11:08:50 wer:336]

[NeMo I 2026-07-01 11:08:50 wer:337] WER reference:tôi chỉ thấy người ta nhắc đến phượng vĩ tháng sáu hay cùng lắm là tháng năm
[NeMo I 2026-07-01 11:08:50 wer:338] WER predicted:tôi chỉ thấy người taạ để phương với th sau hai cũng tám là thành là
[NeMo I 2026-07-01 11:08:58 wer:336]

[NeMo I 2026-07-01 11:08:58 wer:337] WER reference:với câu trả lời xuất sắc và gương mặt khả ái
[NeMo I 2026-07-01 11:08:58 wer:338] WER predicted:với cô cho lời sức s vàương một khá ai
[NeMo I 2026-07-01 11:09:07 wer:336]

[NeMo I 2026-07-01 11:09:07 wer:337] WER reference:nhưng em có biết rằng anh yêu em cũng bởi những lý do đó
[NeMo I 2026-07-01 11:09:07 wer:338] WER predicted:thì có biết tr anh như em cũng người nh lý do
[NeMo I 2026-07-01 11:09:15 wer:336]

[NeMo I 2026-07-01 11:09:15 wer:337] WER reference:để nhìn thấy sự khôi hài
[NeMo I 2026-07-01 11:09:15 wer:338] WER predicted:để nhìn thấy sự khu hai
[NeMo I 2026-07-01 11:09:23 wer:336]

[NeMo I 2026-07-01 11:09:23 wer:337] WER reference:rèm cửa phòng khách của bạn giống như cung điện
[NeMo I 2026-07-01 11:09:23 wer:338] WER predicted:ra của phòng khách của bạn gi như cũng điện
[NeMo I 2026-07-01 11:09:32 wer:336]

[NeMo I 2026-07-01 11:09:32 wer:337] WER reference:và những khuyết điểm nhỏ của họ
[NeMo I 2026-07-01 11:09:32 wer:338] WER predicted:và những quyết điểm nhà của họ
[NeMo I 2026-07-01 11:09:40 wer:336]

[NeMo I 2026-07-01 11:09:40 wer:337] WER reference:tôi biết đây là quy tắc đòi hỏi
[NeMo I 2026-07-01 11:09:40 wer:338] WER predicted:tôi biết đây là quyết tác đòi hỏi
[NeMo I 2026-07-01 11:09:49 wer:336]

[NeMo I 2026-07-01 11:09:49 wer:337] WER reference:cũng trong ngày đó bài xã luận gằn giọng
[NeMo I 2026-07-01 11:09:49 wer:338] WER predicted:cũng trong ngày đó và sến rằng gi
[NeMo I 2026-07-01 11:09:57 wer:336]

[NeMo I 2026-07-01 11:09:57 wer:337] WER reference:bạn có thể ghé thăm nó
[NeMo I 2026-07-01 11:09:57 wer:338] WER predicted:bạn có thể g nghĩa tha nó
[NeMo I 2026-07-01 11:10:06 wer:336]

[NeMo I 2026-07-01 11:10:06 wer:337] WER reference:các anh sẽ mãi là những người con ưu tú của tổ quốc của nhân dân việt nam
[NeMo I 2026-07-01 11:10:06 wer:338] WER predicted:các anh xem hay là những người con của thu tổ quốc của nhân dân việc nam
[NeMo I 2026-07-01 11:10:14 wer:336]

[NeMo I 2026-07-01 11:10:14 wer:337] WER reference:để luôn có một bình hoa tươi mới
[NeMo I 2026-07-01 11:10:14 wer:338] WER predicted:để luôn có một bên hoa tôi mới
[NeMo I 2026-07-01 11:10:23 wer:336]

[NeMo I 2026-07-01 11:10:23 wer:337] WER reference:chúc bạn đọc có thật nhiều thời gian thư giãn thoải mái
[NeMo I 2026-07-01 11:10:23 wer:338] WER predicted:trước bạn đó có thực nhiều thời gian thứ d ở tôii mà
[NeMo I 2026-07-01 11:10:31 wer:336]

[NeMo I 2026-07-01 11:10:31 wer:337] WER reference:bất chấp sự ngăn cản của cơ quan chức năng
[NeMo I 2026-07-01 11:10:31 wer:338] WER predicted:bập sự năng đang của cơ quan nước năng
[NeMo I 2026-07-01 11:10:40 wer:336]

[NeMo I 2026-07-01 11:10:40 wer:337] WER reference:chỉ có điều cô ta mang giày chiếc váy len dài bằng lông cừu
[NeMo I 2026-07-01 11:10:40 wer:338] WER predicted:chỉ có điều cuộc ta mang giảiiếc với l lên dài bằng luôn cứ
[NeMo I 2026-07-01 11:10:48 wer:336]

[NeMo I 2026-07-01 11:10:48 wer:337] WER reference:thánh nhân đãi khù khờ chính là chỗ này
[NeMo I 2026-07-01 11:10:48 wer:338] WER predicted:thành nhân ra khu thời chỉ thể chủ này
[NeMo I 2026-07-01 11:10:56 wer:336]

[NeMo I 2026-07-01 11:10:56 wer:337] WER reference:cô bé rất lấy làm vui mừng và làm quen với những nốt nhạc đầu tiên bằng chính chiếc đàn đồ chơi ấy
[NeMo I 2026-07-01 11:10:56 wer:338] WER predicted:có bé làm vui và làm quan với những nàyạ đầu tiền trên bạn chính ch đang được s ấy
[NeMo I 2026-07-01 11:11:05 wer:336]

[NeMo I 2026-07-01 11:11:05 wer:337] WER reference:với mức khởi điểm tính thuế như trong dự thảo là cao
[NeMo I 2026-07-01 11:11:05 wer:338] WER predicted:với mất thời điểm sinh thế như trong nhiều tạo là

Validation: |          | 0/? [00:00<?, ?it/s]

[NeMo I 2026-07-01 11:14:09 wer:336]

[NeMo I 2026-07-01 11:14:09 wer:337] WER reference:những con vật này đã bị giết và đốt
[NeMo I 2026-07-01 11:14:09 wer:338] WER predicted:nh con vật này đã bị gì và tốt
[NeMo I 2026-07-01 11:14:09 wer:336]

[NeMo I 2026-07-01 11:14:09 wer:337] WER reference:do vậy có máy cũng không thường dùng
[NeMo I 2026-07-01 11:14:09 wer:338] WER predicted:do vậy có mấy cũng không thường dụng
[NeMo I 2026-07-01 11:14:09 wer:336]

[NeMo I 2026-07-01 11:14:09 wer:337] WER reference:đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
[NeMo I 2026-07-01 11:14:09 wer:338] WER predicted:đây sẽ là của gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
[NeMo I 2026-07-01 11:14:09 wer:336]

[NeMo I 2026-07-01 11:14:09 wer:337] WER reference:sau đó một vật lạ bay xợt ngang nóc nhà ông
[NeMo I 2026-07-01 11:14:09 wer:338] WER predicted:sau đó một và là bảy sự năng n nước nhau
[NeMo I 2026-07-01 11:14:09 wer:336]

[NeMo I 2026-07-01 11:14:09 wer:337] WER reference:hiện ra tận phía xa
[NeMo I 2026-07-01 11:14:09 wer:338] WER predicted:hiện ra tình phía xa
[NeMo I 2026-07-01 11:14:09 wer:336]

[NeMo I 2026-07-01 11:14:09 wer:337] WER reference:nên với thông tin này
[NeMo I 2026-07-01 11:14:09 wer:338] WER predicted:nên với thông tiền này
[NeMo I 2026-07-01 11:14:09 wer:336]

[NeMo I 2026-07-01 11:14:09 wer:337] WER reference:và dân dã như chính cái tên của nó
[NeMo I 2026-07-01 11:14:09 wer:338] WER predicted:và dân gia như chín cái tình của nó
[NeMo I 2026-07-01 11:14:09 wer:336]

[NeMo I 2026-07-01 11:14:09 wer:337] WER reference:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 11:14:09 wer:338] WER predicted:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 11:14:09 wer:336]

[NeMo I 2026-07-01 11:14:09 wer:337] WER reference:sau nhiều pha hảm thành liên tục
[NeMo I 2026-07-01 11:14:09 wer:338] WER predicted:sau nhiều phá h thành liên tốt
[NeMo I 2026-07-01 11:14:09 wer:336]

[NeMo I 2026-07-01 11:14:09 wer:337] WER reference:anh vẫn nhớ kỷ niệm cầu đầu lâu
[NeMo I 2026-07-01 11:14:09 wer:338] WER predicted:anh vẫn như kỳ nhiệm cầu đầu lâu
[NeMo I 2026-07-01 11:14:09 wer:336]

[NeMo I 2026-07-01 11:14:09 wer:337] WER reference:gay go lắm nhưng hoàng anh gia lai sẽ làm được
[NeMo I 2026-07-01 11:14:09 wer:338] WER predicted:g g có làm nhưng hơn anh gia là sẽ làm được
[NeMo I 2026-07-01 11:14:09 wer:336]

[NeMo I 2026-07-01 11:14:09 wer:337] WER reference:do đó khi chơi chung với bạn bè cùng lứa chúng thường tỏ ra thiếu tự tin
[NeMo I 2026-07-01 11:14:09 wer:338] WER predicted:do đó khi tr chơi chúng với bạn bé cũng l lời chúng ta thường tôi cả thiếu từ tình
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:mối đục luỗng cả tấm gỗ
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:mới được luôn các t tâm g
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:người ta cho rằng trung tâm này có khả năng ảnh hưởng đến quá trình lão hóa
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:người ta cho rằng trong tâm này có khá năng anh hướng đến quá trên lâu hoa
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:các giò phong lan tháng ba cũng không chịu yên mình
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:các cho phòng lên tha bà cũng công chịu ý mình
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:hãy cho tôi quyền năng vô tận để bảo vệ loài vật
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:hay cho tôi viên năng v vụ tăng để bảo vềỗ vật
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:sáng chiều hội diễn tiếng hát bảo minh do công ty bảo hiểm bảo minh tổ chức
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:sáng chịu họ diễn tiếng khác đầu mình do công ty bảo em bảo mình tôi chức
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:cô nằm thiếp đi lúc nào không biết
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:cô năm tiếp đi lúc nào không biết
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:mười bảy mười tám mười chín
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:mươi bảy mươi tám mươi chín
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:tích cóp đủ thứ đồ lạc xon những ngọn đèn
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:tiếpốcưa thứ đồ đ số nhữngọ đến
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:nhưng đất nước đã chọn một nhà lãnh đạo khác
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:nhưng được nước đã cho một nhà là đầu khác
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:ưu thế này có được là nhờ quá trình cơ giới hóa nhanh sử dụng phân bón cho dù hậu quả có là
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:uống thế này có được là nhớ quá trình cơ giới hoa nh sự dụng phần bốn cho dụnghầu quá có là
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:thường xuyên xảy ra hiện tượng đạo văn quỵt nhuận bút
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:thường xuyên x ra hiện thường đầu văn quyết nh quốc
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:chỉ cho chúng tôi xem hàng đống gạch đá cát sỏi
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:chỉ cho chúng tôi xem hàng đồng g đã các số
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:đối với cảng hàng không quốc tế đà nẵng sử dụng nhà ga hành khách hiện hữu làm nhà ga nội địa
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:đối với càng hàng không quốc tế đã năng sự dụng nhà cả hành khách hiện hồ làm nhà cả nói để
[NeMo I 2026-07-01 11:14:10 wer:336]

[NeMo I 2026-07-01 11:14:10 wer:337] WER reference:người giàu thì vác nặng những xâu tiền kẽm trên vai
[NeMo I 2026-07-01 11:14:10 wer:338] WER predicted:ngườiào thì phátạ những sau tiềnk trên phải
[NeMo I 2026-07-01 11:14:11 wer:336]

[NeMo I 2026-07-01 11:14:11 wer:337] WER reference:các nữ công nhân làm ca đêm
[NeMo I 2026-07-01 11:14:11 wer:338] WER predicted:các nữa công nhân làm cả điểm
[NeMo I 2026-07-01 11:14:11 wer:336]

[NeMo I 2026-07-01 11:14:11 wer:337] WER reference:tui biết bà giỏi rồi
[NeMo I 2026-07-01 11:14:11 wer:338] WER predicted:tôi biết ba d rồi
[NeMo I 2026-07-01 11:14:11 wer:336]

[NeMo I 2026-07-01 11:14:11 wer:337] WER reference:đưa một chú bồ câu bay đi bay về
[NeMo I 2026-07-01 11:14:11 wer:338] WER predicted:đường một chú bộ cầu bảy đi bị về
[NeMo I 2026-07-01 11:14:11 wer:336]

[NeMo I 2026-07-01 11:14:11 wer:337] WER reference:tôi đến kiểm tra và phát hiện thấy ông và cô gái nằm kia thám tử ra hiệu cho ngài triệu phú nhìn vào phòng tắm cô ta đã chết
[NeMo I 2026-07-01 11:14:11 wer:338] WER predicted:tôi đến kiểm ra và phát hiện thấy ông và cô gái nămk tâm từ ra hiểu cho ngày chịu phương nh vào phòng tâm cô đã chết
[NeMo I 2026-07-01 11:14:11 wer:336]

[NeMo I 2026-07-01 11:14:11 wer:337] WER reference:để thực hiện thắng lợi kế hoạch năm năm
[NeMo I 2026-07-01 11:14:11 wer:338] WER predicted:để thực hiện thân lại cái hết năm năm
[NeMo I 2026-07-01 11:14:11 wer:336]

[NeMo I 2026-07-01 11:14:11 wer:337] WER reference:trước khi hóa thân thành cộng hòa sét để đến bồ đào nha
[NeMo I 2026-07-01 11:14:11 wer:338] WER predicted:trước khi hoa thân thành có hoa sức để đến bộ động nhà
[NeMo I 2026-07-01 11:14:11 wer:336]

[NeMo I 2026-07-01 11:14:11 wer:337] WER reference:tuy nhiên tôi không chắc những người chưa từng đọc cuốn nhật ký có thể hiểu hết được ý nghĩa bộ phim
[NeMo I 2026-07-01 11:14:11 wer:338] WER predicted:tuy nhiên tôi không chắc những người chưa từ đọc cũng nhất kỳ có thể hiểu hết được ý nghĩ bộ phim
[NeMo I 2026-07-01 11:14:11 wer:336]

[NeMo I 2026-07-01 11:14:11 wer:337] WER reference:chi đầu tư từ khu vực nhà nước còn lớn và hiệu quả thấp
[NeMo I 2026-07-01 11:14:11 wer:338] WER predicted:chỉ đầu tư từ khu vực nhà n nước còn lớn và hiệu quá hợp
[NeMo I 2026-07-01 11:14:11 wer:336]

[NeMo I 2026-07-01 11:14:11 wer:337] WER reference:cái nền xưa của nó bây giờ là một cái hố nông choèn
[NeMo I 2026-07-01 11:14:11 wer:338] WER predicted:cái nên sự của nó bị giờ là một cái hồ năm tr
[NeMo I 2026-07-01 11:14:11 wer:336]

[NeMo I 2026-07-01 11:14:11 wer:337] WER reference:giải truyền thông điện ảnh trung quốc là giải thưởng điện ảnh duy nhất xét trao cho tất cả các bộ phim hoa ngữ
[NeMo I 2026-07-01 11:14:11 wer:338] WER predicted:dài trên thường đến anh chúng quốc là dài thường đến anh gì sẽ cho cho tất cả các bộ hiện hoàn người
[NeMo I 2026-07-01 11:14:11 wer:336]

[NeMo I 2026-07-01 11:14:11 wer:337] WER reference:dự đoán ba tháng nữa giá cà phê sẽ tăng gấp đôi hiện nay
[NeMo I 2026-07-01 11:14:11 wer:338] WER predicted:điều rằng bà tháng nữa giá và về sự tăng gặp đổi hiện này
[NeMo I 2026-07-01 11:14:11 wer:336]

[NeMo I 2026-07-01 11:14:11 wer:337] WER reference:họ đến đây vì nhiều mục đích
[NeMo I 2026-07-01 11:14:11 wer:338] WER predicted:họ đến đâyì nhiều mộtích
[NeMo I 2026-07-01 11:14:11 wer:336]

[NeMo I 2026-07-01 11:14:11 wer:337] WER reference:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 11:14:11 wer:338] WER predicted:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 11:14:11 wer:336]

[NeMo I 2026-07-01 11:14:11 wer:337] WER reference:vậy trước đây nông dân đối phó với hiện tượng này như thế nào thưa ông
[NeMo I 2026-07-01 11:14:11 wer:338] WER predicted:và trước này n năm nhân đối phố với hiện từ này như đến nào thu  ông
[NeMo I 2026-07-01 11:14:11 wer:336]

[NeMo I 2026-07-01 11:14:11 wer:337] WER reference:làm sao để có tiền nhanh nhất
[NeMo I 2026-07-01 11:14:11 wer:338] WER predicted:làm sao để có tiền nhân nhất
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:đùi dang ra ngoài
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:được gian ra ngoài
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:đã hai lần cô gác lại ước mơ vào đời và cũng đã ít nhiều trải qua những thăng trầm xô bồ của cuộc sống
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:đã hai l lần cô gái lạiút mới vào đời và cũng đã ít nhiều trái quá những thành trong số bộ của cuộc sống
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:trong bối cảnh như vậy một phản ứng chính sách đối với vấn đề thất nghiệp đang là đòi hỏi cấp bách hiện nay
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:trong bộ cảnh như vậy một phầnững chính sách đối với vẫn để nghiệpp đang là để họ các cách hiện này
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:ở xứ sở chuột túi
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:ở s sự tr chủ tôi
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:do vậy dựa trên cơ sở nào mà ông khoa phát biểu như vậy
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:do vậy dự trên cơ s nào ông khoa phát biểu như vậy
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:tá tàng
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:ta tăng
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:cách đây tám năm nhưng trước đó khoảng hai năm đã được mời đóng phim và có nhiều vai chính trong các phim điện ảnh truyền hình
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:cách đây tâm năm những trước đó hoàn hai năm đã được mới động phim và có nhiều và chính trong các phim điện anh truyền hình
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:đã thăm hỏi thì thế nào cũng phải có quà cáp
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:đã tâm họ thì thế nào cũng phải có quả các
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:có mặt tạià điện phòng
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:em lơ đễnh lật xem vài tờ báo
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:em là điện l xem vậy tế báo
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:và không ít người cứ tì tì uống từ sáng đến tối suốt mấy ngày hội nghị
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:và không ít người cứ ty từ uống từ sáng đến tôi xuất máy ngày hội này
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:minh châu vào miền nam công tác tại nhà hát trần hữu trang
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:mình cao vào m nam công tất tại nhà ho rằng h rằng
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:hết chiến tranh quê hương im tiếng súng anh lính cụ hồ lại trở về với đời thường tham gia sản xuất xây dựng và bảo vệ đất nước
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:hết tiếng cho với hơn ý tiếng xuống anh lên của hồ lại cho về với đời thường tha giá sản xuất sẽ dững và b với đất nước
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:chuyến đi đó đến giờ vẫn là một ám ảnh trong ký ức tôi
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:chỉ đi đó đến giờ vẫn là một ông anh trong chỉ
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:ây da ây da
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:giá gia
[NeMo I 2026-07-01 11:14:12 wer:336]

[NeMo I 2026-07-01 11:14:12 wer:337] WER reference:có rất nhiều vệ tinh bị rơi khỏi quỹ đạo
[NeMo I 2026-07-01 11:14:12 wer:338] WER predicted:rất nhiều về tính bị rồi khó qu nào
[NeMo I 2026-07-01 11:14:13 wer:336]

[NeMo I 2026-07-01 11:14:13 wer:337] WER reference:nhuốm đầy máu của thổ dân châu mỹ
[NeMo I 2026-07-01 11:14:13 wer:338] WER predicted:dụng đây màu của thu dân cho mỹ
[NeMo I 2026-07-01 11:14:13 wer:336]

[NeMo I 2026-07-01 11:14:13 wer:337] WER reference:cụ thể về đất đai xây dựng văn hóa thuộc về từng ngành riêng biệt
[NeMo I 2026-07-01 11:14:13 wer:338] WER predicted:cô thể về đất đây văn sẽ những văn hoa thuốc về từ ngành riêng biết
[NeMo I 2026-07-01 11:14:13 wer:336]

[NeMo I 2026-07-01 11:14:13 wer:337] WER reference:tôi muốn hỏi liệu có mùi hương sen nhân tạo là một loại hóa chất không
[NeMo I 2026-07-01 11:14:13 wer:338] WER predicted:tôi muốn hỏi liệu có người hướng s nhân tạo là một loại họ chắc cao
[NeMo I 2026-07-01 11:14:13 wer:336]

[NeMo I 2026-07-01 11:14:13 wer:337] WER reference:cả nhà bà ngoại cười nắc nẻ vì câu nói ngây ngô của con
[NeMo I 2026-07-01 11:14:13 wer:338] WER predicted:các nhà bao ngoài người nước nghe v của nói ngày ngồi của con
[NeMo I 2026-07-01 11:14:13 wer:336]

[NeMo I 2026-07-01 11:14:13 wer:337] WER reference:xin được chân khuân vác
[NeMo I 2026-07-01 11:14:13 wer:338] WER predicted:xin được trên không phát
[NeMo I 2026-07-01 11:14:13 wer:336]

[NeMo I 2026-07-01 11:14:13 wer:337] WER reference:nằm khuất dưới tàn tre sát bờ sông châu
[NeMo I 2026-07-01 11:14:13 wer:338] WER predicted:ho giới đang trẻ sẽ bà sống ch
[NeMo I 2026-07-01 11:14:13 wer:336]

[NeMo I 2026-07-01 11:14:13 wer:337] WER reference:nếu kiên cố hóa thì vốn được đưa thẳng cho dân sẽ không thất thoát
[NeMo I 2026-07-01 11:14:13 wer:338] WER predicted:nếu ki cô hoa thì bốn đượcưa tăng cho dân sẽ không thật
[NeMo I 2026-07-01 11:14:13 wer:336]

[NeMo I 2026-07-01 11:14:13 wer:337] WER reference:nói chung cô hồng nào cũng có một số phận hoàn cảnh và cuộc đời riêng
[NeMo I 2026-07-01 11:14:13 wer:338] WER predicted:nói chúng cô học nào cũng có một số phần quan cảnh với cuộc đời riêng
[NeMo I 2026-07-01 11:14:13 wer:336]

[NeMo I 2026-07-01 11:14:13 wer:337] WER reference:nhưng tất cả những điều ấy chẳng mấy khi đi liền với nhau
[NeMo I 2026-07-01 11:14:13 wer:338] WER predicted:những tất cả những điều ấy ch mấy khi đi liên với nhau
[NeMo I 2026-07-01 11:14:13 wer:336]

[NeMo I 2026-07-01 11:14:13 wer:337] WER reference:như vậy là bạn có thể sử dụng được nhiều số điện thoại của nhiều nhà cung cấp dịch vụ chỉ trên một sim
[NeMo I 2026-07-01 11:14:13 wer:338] WER predicted:như vậy bạn có thể sự dụng được nhiều số đến th của như nhà cũng cấp dịch vụ chỉ trên một xem
[NeMo I 2026-07-01 11:14:13 wer:336]

[NeMo I 2026-07-01 11:14:13 wer:337] WER reference:trong trường hợp hai bên có thỏa thuận lại không yêu cầu trọng tài giải quyết nữa thì có quyền kiện ra tòa án
[NeMo I 2026-07-01 11:14:13 wer:338] WER predicted:trong trường hợp hai bên có thể thường lại không yêu cầu trong ta d quyết nữa thì có viên kiến ra toàn ăn
[NeMo I 2026-07-01 11:14:13 wer:336]

[NeMo I 2026-07-01 11:14:13 wer:337] WER reference:kiểu này chắc phải cắt giảm biên chế
[NeMo I 2026-07-01 11:14:13 wer:338] WER predicted:chưa này chắc phải các giá biến chế
[NeMo I 2026-07-01 11:14:13 wer:336]

[NeMo I 2026-07-01 11:14:13 wer:337] WER reference:nhưng tôi không yêu cô cô biết rõ điều đó mà
[NeMo I 2026-07-01 11:14:13 wer:338] WER predicted:nhưng tôi không yêu cô cô biết rồi điều đó mà
[NeMo I 2026-07-01 11:14:13 wer:336]

[NeMo I 2026-07-01 11:14:13 wer:337] WER reference:khó mà đoán trước chính xác kết quả khi quả bóng còn lăn
[NeMo I 2026-07-01 11:14:13 wer:338] WER predicted:không mà đó trước chính sẽích qua khi qua b con
[NeMo I 2026-07-01 11:14:13 wer:336]

[NeMo I 2026-07-01 11:14:13 wer:337] WER reference:vừa nhìn thấy sự xuất hiện của bố tất cả mấy thằng khác vùng bỏ chạy sạch
[NeMo I 2026-07-01 11:14:13 wer:338] WER predicted:với nh thấy sự sự hiện của bố tất cả máy thành khác vùng bội trẻ sách
[NeMo I 2026-07-01 11:14:14 wer:336]

[NeMo I 2026-07-01 11:14:14 wer:337] WER reference:phải nâng cao khả năng cạnh tranh của nền kinh tế
[NeMo I 2026-07-01 11:14:14 wer:338] WER predicted:phải năng cao hình năng cảnh trên của nên kinh tình
[NeMo I 2026-07-01 11:14:14 wer:336]

[NeMo I 2026-07-01 11:14:14 wer:337] WER reference:bà thường lấy ý tưởng cho các tác phẩm từ đâu
[NeMo I 2026-07-01 11:14:14 wer:338] WER predicted:bà thườngấy ý từ cho các tác phẩm từ đồng
[NeMo I 2026-07-01 11:14:14 wer:336]

[NeMo I 2026-07-01 11:14:14 wer:337] WER reference:khi chứng kiến người vợ lăng loàn
[NeMo I 2026-07-01 11:14:14 wer:338] WER predicted:khi chính kiến người vào l lần lòng
[NeMo I 2026-07-01 11:14:14 wer:336]

[NeMo I 2026-07-01 11:14:14 wer:337] WER reference:tác phẩm to lớn bằng đồng như tượng phật quỳnh lâm chuông quy điền tháp báo thiên vạc phổ minh an nam tứ đại khí
[NeMo I 2026-07-01 11:14:14 wer:338] WER predicted:ta phẩm ta lớn bạn đồng như thường phát quan làm chúng quy điện th bảo tìm và phố mình ăn năm từ đây khi
[NeMo I 2026-07-01 11:14:14 wer:336]

[NeMo I 2026-07-01 11:14:14 wer:337] WER reference:ngoài ra họ vẫn còn muốn giữ chân cầu thủ xuất sắc nhất của mình
[NeMo I 2026-07-01 11:14:14 wer:338] WER predicted:họ vẫn cầu muốnư chân cầu thủ xuất s
[NeMo I 2026-07-01 11:14:14 wer:336]

[NeMo I 2026-07-01 11:14:14 wer:337] WER reference:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 11:14:14 wer:338] WER predicted:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 11:14:14 wer:336]

[NeMo I 2026-07-01 11:14:14 wer:337] WER reference:và gã thệ bị điều về làm trưởng phòng xã hội huyện
[NeMo I 2026-07-01 11:14:14 wer:338] WER predicted:và cả thể biết điều về làm trường phần x hội h
[NeMo I 2026-07-01 11:14:14 wer:336]

[NeMo I 2026-07-01 11:14:14 wer:337] WER reference:là rút rỉa tiền của bạn càng nhiều càng tốt

[NeMo W 2026-07-01 11:14:29 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 11:14:29 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

[best val_wer] epoch=2 val_wer=0.479520 exported=/kaggle/working/phase3_continue_best.nemo

Sample predictions after epoch 2:
  [0] REF: những con vật này đã bị giết và đốt
      HYP: nh con vật này đã bị gì và tốt
  [1] REF: phòng chống tham nhũng không được chủ quan cần làm liên tục đồng bộ và có các giải pháp
      HYP: phòng trong tham dụng không được chủ quan cần làm liên tục động bộ và có các lại pháp
  [2] REF: do vậy có máy cũng không thường dùng
      HYP: do vậy có mấy cũng không thường dụng
  [3] REF: mới khệnh khạng đứng lên đi ra
      HYP: mới kh khá đến lên đi ra
  [4] REF: đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
      HYP: đây sẽ là của gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
  [5] REF: sau một năm eo sèo
      HYP: sáu một năm em sẽ
  [6] REF: sau đó một vật lạ bay xợt ngang nóc nhà ông
      HYP: sau đó một và là bảy sự năng n nước nhau
  [7] REF: chín mươi hai chín mươi ba
      HYP: chín mươi hai chín mươi ba
  [8] REF: hiện ra tận phía xa
      HYP: hiện ra tình phía xa
  [9] REF: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã qua của thị trường
      HYP: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã quá của thì trường
[epoch] epoch=2/12 step=628 val_loss=2.329350471496582 val_wer=0.4795202314853668
[NeMo I 2026-07-01 11:14:57 wer:336]

[NeMo I 2026-07-01 11:14:57 wer:337] WER reference:rất nhiều trường hợp phụ huynh đau đầu vì con một đã tìm đến chuyên viên tư vấn tâm lý
[NeMo I 2026-07-01 11:14:57 wer:338] WER predicted:rất người trường học phụ kh đầu đầuì anh một đã tìm đến trên viên tư anh tâm lý
[NeMo I 2026-07-01 11:15:06 wer:336]

[NeMo I 2026-07-01 11:15:06 wer:337] WER reference:trước tình thế đó tôi buộc phải tìm cho mình một bến đỗ mới và tôi đã quyết định ra đi
[NeMo I 2026-07-01 11:15:06 wer:338] WER predicted:lúc tình thế đó tôi bộ phải tìm cho mình một b đầu mới và tôi đã quyết bệnh ra
[NeMo I 2026-07-01 11:15:15 wer:336]

[NeMo I 2026-07-01 11:15:15 wer:337] WER reference:tuy nhiên tình hình đó không diễn ra ở tất cả trường
[NeMo I 2026-07-01 11:15:15 wer:338] WER predicted:tuy nhiên tình hình đó không nhá ở tất các trường
[NeMo I 2026-07-01 11:15:23 wer:336]

[NeMo I 2026-07-01 11:15:23 wer:337] WER reference:nếu xét trên qui mô toàn tỉnh con số ấy vẫn còn khiêm tốn lắm
[NeMo I 2026-07-01 11:15:23 wer:338] WER predicted:để x chỉ ph mua toàn tình còn số ấy vẫn còn khiù làm
[NeMo I 2026-07-01 11:15:32 wer:336]

[NeMo I 2026-07-01 11:15:32 wer:337] WER reference:các vùng sâu vùng xa khó mà phát triển
[NeMo I 2026-07-01 11:15:32 wer:338] WER predicted:các vùng sau vùng sẽ khó mà phát chỉ
[NeMo I 2026-07-01 11:15:40 wer:336]

[NeMo I 2026-07-01 11:15:40 wer:337] WER reference:thì không hiểu sao ở phần thơ cổ đại
[NeMo I 2026-07-01 11:15:40 wer:338] WER predicted:thì không hiểu sao ở phần hết của đây
[NeMo I 2026-07-01 11:15:48 wer:336]

[NeMo I 2026-07-01 11:15:48 wer:337] WER reference:anh muốn thùy có thể tự do tìm cho mình một hạnh phúc khác tràn đầy
[NeMo I 2026-07-01 11:15:48 wer:338] WER predicted:anh muốn thời có thể từ do tìm cho mình một thành ph khác cho lại
[NeMo I 2026-07-01 11:15:57 wer:336]

[NeMo I 2026-07-01 11:15:57 wer:337] WER reference:áo thun trắng sát nách
[NeMo I 2026-07-01 11:15:57 wer:338] WER predicted:ở thu trang sát nhất
[NeMo I 2026-07-01 11:16:05 wer:336]

[NeMo I 2026-07-01 11:16:05 wer:337] WER reference:đây cũng là giai đoạn thị trường nhiều biến cố nhất
[NeMo I 2026-07-01 11:16:05 wer:338] WER predicted:đây cũng là chế đồng thì trường nhiều biến cô nhất
[NeMo I 2026-07-01 11:16:14 wer:336]

[NeMo I 2026-07-01 11:16:14 wer:337] WER reference:mới thành món ngon và độc đáo
[NeMo I 2026-07-01 11:16:14 wer:338] WER predicted:mới thành món ngon và được đâu
[NeMo I 2026-07-01 11:16:22 wer:336]

[NeMo I 2026-07-01 11:16:22 wer:337] WER reference:người đẹp không thiếu chỉ sợ ông anh không có tiền
[NeMo I 2026-07-01 11:16:22 wer:338] WER predicted:người để không thiếu chỉ s ông anh không có tình
[NeMo I 2026-07-01 11:16:31 wer:336]

[NeMo I 2026-07-01 11:16:31 wer:337] WER reference:ngày thường chù ụ thì được
[NeMo I 2026-07-01 11:16:31 wer:338] WER predicted:ngày thường chủ ông gì được
[NeMo I 2026-07-01 11:16:40 wer:336]

[NeMo I 2026-07-01 11:16:40 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 11:16:40 wer:338] WER predicted:có mặt tại sẽ điện phương
[NeMo I 2026-07-01 11:16:48 wer:336]

[NeMo I 2026-07-01 11:16:48 wer:337] WER reference:tôi cũng biết có những tiêu cực trong giáo dục và nhà trường cũng như những lĩnh vực khác của xã hội
[NeMo I 2026-07-01 11:16:48 wer:338] WER predicted:tôi cũng biết có những tiêu thực trong giá được và nhà trường của như những lên với h của xã hội
[NeMo I 2026-07-01 11:16:57 wer:336]

[NeMo I 2026-07-01 11:16:57 wer:337] WER reference:xắn quần vượt qua là bước vào thế giới
[NeMo I 2026-07-01 11:16:57 wer:338] WER predicted:sống qu v qua là bước vào thời giới
[NeMo I 2026-07-01 11:17:05 wer:336]

[NeMo I 2026-07-01 11:17:05 wer:337] WER reference:mới và cải tiến
[NeMo I 2026-07-01 11:17:05 wer:338] WER predicted:mới và cái tiền
[NeMo I 2026-07-01 11:17:14 wer:336]

[NeMo I 2026-07-01 11:17:14 wer:337] WER reference:hai vợ chồng thị tớn và văn đục
[NeMo I 2026-07-01 11:17:14 wer:338] WER predicted:hai vợ trong thì từ và văn được
[NeMo I 2026-07-01 11:17:22 wer:336]

[NeMo I 2026-07-01 11:17:22 wer:337] WER reference:chợ đêm ca ba dành cho những người đang vào mùa tăng ca cuối năm
[NeMo I 2026-07-01 11:17:22 wer:338] WER predicted:ở đến và ba danh cho nh người đang vào một ta cả cứ năm
[NeMo I 2026-07-01 11:17:31 wer:336]

[NeMo I 2026-07-01 11:17:31 wer:337] WER reference:hai mươi hai mươi mốt
[NeMo I 2026-07-01 11:17:31 wer:338] WER predicted:hai mươi hai mươi mốt
[NeMo I 2026-07-01 11:17:39 wer:336]

[NeMo I 2026-07-01 11:17:39 wer:337] WER reference:anh không thể quên được những giây phút ngọt ngào ấy
[NeMo I 2026-07-01 11:17:39 wer:338] WER predicted:anh không được qu được nh ph gian ngọ nào ấy
[NeMo I 2026-07-01 11:17:48 wer:336]

[NeMo I 2026-07-01 11:17:48 wer:337] WER reference:đưa tới tình trạng phá sản
[NeMo I 2026-07-01 11:17:48 wer:338] WER predicted:ưa tư tiền r phá sản
[NeMo I 2026-07-01 11:17:57 wer:336]

[NeMo I 2026-07-01 11:17:57 wer:337] WER reference:phụ huynh và học sinh đang phải è cổ vì sách giá cao
[NeMo I 2026-07-01 11:17:57 wer:338] WER predicted:vụ qunh và học sinh đang phải em cô vì sách gia cao
[NeMo I 2026-07-01 11:18:05 wer:336]

[NeMo I 2026-07-01 11:18:05 wer:337] WER reference:thỉnh thoảng lại có người ghép thận trước đó trở qua xin xét nghiệm vì có trục trặc
[NeMo I 2026-07-01 11:18:05 wer:338] WER predicted:tình toàn lại có người g thân tư gặp tôi qua sinh sẽ nghe về có tr đọc
[NeMo I 2026-07-01 11:18:14 wer:336]

[NeMo I 2026-07-01 11:18:14 wer:337] WER reference:cuộc thi nhằm trau dồi niềm đam mê
[NeMo I 2026-07-01 11:18:14 wer:338] WER predicted:cuộc thế nh cho d nhiệm đã mẹ
[NeMo I 2026-07-01 11:18:22 wer:336]

[NeMo I 2026-07-01 11:18:22 wer:337] WER reference:đề thi môn vẽ thông thường là về vẽ trang trí sản phẩm vật thể
[NeMo I 2026-07-01 11:18:22 wer:338] WER predicted:để thi muốn v vẻ hô thường là về về sáng chỉ sáng ph một thể
[NeMo I 2026-07-01 11:18:31 wer:336]

[NeMo I 2026-07-01 11:18:31 wer:337] WER reference:bước vào một mối tình
[NeMo I 2026-07-01 11:18:31 wer:338] WER predicted:bước vào một mua tình
[NeMo I 2026-07-01 11:18:39 wer:336]

[NeMo I 2026-07-01 11:18:39 wer:337] WER reference:lão nạp chỉ có nhiêu đây thôi
[NeMo I 2026-07-01 11:18:39 wer:338] WER predicted:làạ chỉ có như lại tôi
[NeMo I 2026-07-01 11:18:48 wer:336]

[NeMo I 2026-07-01 11:18:48 wer:337] WER reference:hai tuần sau
[NeMo I 2026-07-01 11:18:48 wer:338] WER predicted:hai cũng sáu
[NeMo I 2026-07-01 11:18:56 wer:336]

[NeMo I 2026-07-01 11:18:56 wer:337] WER reference:những ngày cuối cùng trên dương thế
[NeMo I 2026-07-01 11:18:56 wer:338] WER predicted:những này của cùng trên dân thế
[NeMo I 2026-07-01 11:19:05 wer:336]

[NeMo I 2026-07-01 11:19:05 wer:337] WER reference:trên nhiều tuyến phố công nhân đang hối hả dọn dẹp
[NeMo I 2026-07-01 11:19:05 wer:338] WER predicted:trên nhiều tuy ph công nh đang hội hay động nghiệpp
[NeMo I 2026-07-01 11:19:13 wer:336]

[NeMo I 2026-07-01 11:19:13 wer:337] WER reference:có trường hợp bất hợp pháp như trần thị thu h
[NeMo I 2026-07-01 11:19:13 wer:338] WER predicted:có chuyện học b học pháp như trong thì thu
[NeMo I 2026-07-01 11:19:22 wer:336]

[NeMo I 2026-07-01 11:19:22 wer:337] WER reference:nhưng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được các khó khăn đó
[NeMo I 2026-07-01 11:19:22 wer:338] WER predicted:chúng tôi nghĩ r nếu có quyết tâm cao thì sẽ giải quyết được cả kh không đó
[NeMo I 2026-07-01 11:19:30 wer:336]

[NeMo I 2026-07-01 11:19:30 wer:337] WER reference:lúc đó em không thể tiếp tục công việc đánh cá của cha một mình vì còn quá nhỏ
[NeMo I 2026-07-01 11:19:30 wer:338] WER predicted:lúc đó em không phải tiếp cơ không việc đến các của cho một mình việc còn qua nhỏ
[NeMo I 2026-07-01 11:19:39 wer:336]

[NeMo I 2026-07-01 11:19:39 wer:337] WER reference:cuốn sách nói về sự lầm lẫn giữa luật kinh tế ở châu âu và châu mỹ kim vẫn chưa đọc tới vì cô không quan tâm đến luật
[NeMo I 2026-07-01 11:19:39 wer:338] WER predicted:cũng sẽ nói về làm lần d được ki thế ở trong ông và trong muốn cho vẫn chưa đọc tôi việc của không quan tăng đến luật
[NeMo I 2026-07-01 11:19:47 wer:336]

[NeMo I 2026-07-01 11:19:47 wer:337] WER reference:khi tên lửa bay lên
[NeMo I 2026-07-01 11:19:47 wer:338] WER predicted:khi tên lời vậy lên
[NeMo I 2026-07-01 11:19:55 wer:336]

[NeMo I 2026-07-01 11:19:55 wer:337] WER reference:mà theo thời gian sẽ tiệm cận với trí khôn của con người
[NeMo I 2026-07-01 11:19:55 wer:338] WER predicted:mà theo thời dân sẽ tìm cần với trí không quốc con người
[NeMo I 2026-07-01 11:20:04 wer:336]

[NeMo I 2026-07-01 11:20:04 wer:337] WER reference:bên kia láng giềng của tôi hôm nay không thấy thăm hoa
[NeMo I 2026-07-01 11:20:04 wer:338] WER predicted:đến chỉ là diễn của tôi hô này không thấy th h
[NeMo I 2026-07-01 11:20:13 wer:336]

[NeMo I 2026-07-01 11:20:13 wer:337] WER reference:anh yêu cầu các cầu thủ phải đeo bám ngay khi đối phương có bóng
[NeMo I 2026-07-01 11:20:13 wer:338] WER predicted:anh nhiều cầu các cầu số phảieo bạn ngày khi đối phương có
[NeMo I 2026-07-01 11:20:21 wer:336]

[NeMo I 2026-07-01 11:20:21 wer:337] WER reference:ngay cả công an đi lẻ loi cũng bị tấn công vì trong khu vực này có một thứ luật riêng cấm người lạ vào
[NeMo I 2026-07-01 11:20:21 wer:338] WER predicted:nghe và không đi lẽ cũng bị không con việc trong có việc mẹ một thứ lực viên công như l
[NeMo I 2026-07-01 11:20:29 wer:336]

[NeMo I 2026-07-01 11:20:29 wer:337] WER reference:thì chúng sẽ nằm trong tầm kiểm soát của bạn
[NeMo I 2026-07-01 11:20:29 wer:338] WER predicted:thì chúng sẽ năm trong làmm kiể sau của bạn
[NeMo I 2026-07-01 11:20:38 wer:336]

[NeMo I 2026-07-01 11:20:38 wer:337] WER reference:đó là hai con sói hoàn toàn trái ngược nhau về hình thức
[NeMo I 2026-07-01 11:20:38 wer:338] WER predicted:đó là hay con s hộ còn chính được nhau về hiện thức
[NeMo I 2026-07-01 11:20:46 wer:336]

[NeMo I 2026-07-01 11:20:46 wer:337] WER reference:trại đồng xã yên sở giữa một biển nước mênh mông ảnh nguyễn quân
[NeMo I 2026-07-01 11:20:46 wer:338] WER predicted:tr đồng x em s giờ một bịương mình m  anh quyền quan
[NeMo I 2026-07-01 11:20:55 wer:336]

[NeMo I 2026-07-01 11:20:55 wer:337] WER reference:không sao rồi em mừng lắm
[NeMo I 2026-07-01 11:20:55 wer:338] WER predicted:không sao rồi em mình làm
[NeMo I 2026-07-01 11:21:03 wer:336]

[NeMo I 2026-07-01 11:21:03 wer:337] WER reference:việc tòa án của pháp truy tố công dân một nước độc lập trên lãnh thổ quê hương của người ấy là một điều vô giá trị
[NeMo I 2026-07-01 11:21:03 wer:338] WER predicted:việc tôi ăn cuộc phát tr tốt người không một được được l trên l lên tôi cuối hơn ng ở ấy là một bị chú giá chỉ
[NeMo I 2026-07-01 11:21:12 wer:336]

[NeMo I 2026-07-01 11:21:12 wer:337] WER reference:bà mẹ nghèo đông con
[NeMo I 2026-07-01 11:21:12 wer:338] WER predicted:và mẹ nghe vẫn con
[NeMo I 2026-07-01 11:21:20 wer:336]

[NeMo I 2026-07-01 11:21:20 wer:337] WER reference:lấy tĩnh chế động
[NeMo I 2026-07-01 11:21:20 wer:338] WER predicted:l liệu tình cho đồng
[NeMo I 2026-07-01 11:21:29 wer:336]

[NeMo I 2026-07-01 11:21:29 wer:337] WER reference:mình mẩy tôi tuy đau đớn
[NeMo I 2026-07-01 11:21:29 wer:338] WER predicted:mình bảy tôi tuy đau đường
[NeMo I 2026-07-01 11:21:37 wer:336]

[NeMo I 2026-07-01 11:21:37 wer:337] WER reference:luôn ngẩng cao đầu sự khác biệt lớn nhất giữa người tự tin và người nhút nhát là gì
[NeMo I 2026-07-01 11:21:37 wer:338] WER predicted:luôn ngn cao đầu x khách người lớn nhỏ d người từ tiền biết và người nh nhấtạ là gì
[NeMo I 2026-07-01 11:21:46 wer:336]

[NeMo I 2026-07-01 11:21:46 wer:337] WER reference:với các bạn trẻ trên đây có vẻ tình yêu không phải là tất cả
[NeMo I 2026-07-01 11:21:46 wer:338] WER predicted:với các bạn trẻ chính đây có việc tình yêu kh và là tục cả
[NeMo I 2026-07-01 11:21:54 wer:336]

[NeMo I 2026-07-01 11:21:54 wer:337] WER reference:nếu trẻ bú không đủ có thể vắt sữa và cho trẻ uống bằng muỗng
[NeMo I 2026-07-01 11:21:54 wer:338] WER predicted:như trẻú không đủ có thể biết sự và tr trẻ  uống bằngôn
[NeMo I 2026-07-01 11:22:03 wer:336]

[NeMo I 2026-07-01 11:22:03 wer:337] WER reference:hãy để thời gian tìm hiểu thêm và thuyết phục gia đình
[NeMo I 2026-07-01 11:22:03 wer:338] WER predicted:hãy để thời gian để mỹ thế phải thu phục gia đình
[NeMo I 2026-07-01 11:22:11 wer:336]

[NeMo I 2026-07-01 11:22:11 wer:337] WER reference:vân vân và vân vân
[NeMo I 2026-07-01 11:22:11 wer:338] WER predicted:vẫn bốn và vẫn bốn
[NeMo I 2026-07-01 11:22:20 wer:336]

[NeMo I 2026-07-01 11:22:20 wer:337] WER reference:mà phụ nữ trong khu vực công đang gặp phải
[NeMo I 2026-07-01 11:22:20 wer:338] WER predicted:mà phụ nơi trong khu vực công đang g gặp phải
[NeMo I 2026-07-01 11:22:28 wer:336]

[NeMo I 2026-07-01 11:22:28 wer:337] WER reference:những năm trước phần lớn sếu ở kiên lương kiên giang
[NeMo I 2026-07-01 11:22:28 wer:338] WER predicted:những năm ch phần lên sẽ ở khi lớn ki gia
[NeMo I 2026-07-01 11:22:37 wer:336]

[NeMo I 2026-07-01 11:22:37 wer:337] WER reference:theo nguyên đào kinh tế đô thị
[NeMo I 2026-07-01 11:22:37 wer:338] WER predicted:theo nguyên đào ki tình đủ thời
[NeMo I 2026-07-01 11:22:45 wer:336]

[NeMo I 2026-07-01 11:22:45 wer:337] WER reference:nhưng ngủ quá nhiều sẽ khiến bạn trở nên bơ phờ
[NeMo I 2026-07-01 11:22:45 wer:338] WER predicted:nhưng người quá nhiều sẽ khiến bạn trên đến b ph
[NeMo I 2026-07-01 11:22:54 wer:336]

[NeMo I 2026-07-01 11:22:54 wer:337] WER reference:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 11:22:54 wer:338] WER predicted:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 11:23:03 wer:336]

[NeMo I 2026-07-01 11:23:03 wer:337] WER reference:thường xuyên đối mặt với nạn khan hiếm lương thực
[NeMo I 2026-07-01 11:23:03 wer:338] WER predicted:thường x đối m với ăn khá hếm luôn thực
[NeMo I 2026-07-01 11:23:11 wer:336]

[NeMo I 2026-07-01 11:23:11 wer:337] WER reference:tôi có cảm tình với cô ấy nhưng tôi không muốn xen vào giữa họ
[NeMo I 2026-07-01 11:23:11 wer:338] WER predicted:tôi có cảm tình với cơ ấyững tôi không muốn xe vào d họ
[NeMo I 2026-07-01 11:23:20 wer:336]

[NeMo I 2026-07-01 11:23:20 wer:337] WER reference:với tôi chết là một sự ích kỷ còn bản chất sự sống đã là một bao dung ít nhất với chính mình
[NeMo I 2026-07-01 11:23:20 wer:338] WER predicted:với tôi ch là một sự kỳ công bạn ch sĩ sống đã một bao g biết nhất với chính mới
[NeMo I 2026-07-01 11:23:28 wer:336]

[NeMo I 2026-07-01 11:23:28 wer:337] WER reference:cậu không biết làm gì thì suốt đời cậu đúng là một kẻ hèn nhát
[NeMo I 2026-07-01 11:23:28 wer:338] WER predicted:cầu không biết làm gì thì xuất đời cầu đường là một các hàng nhà
[NeMo I 2026-07-01 11:23:37 wer:336]

[NeMo I 2026-07-01 11:23:37 wer:337] WER reference:màu đen của những tấm cha
[NeMo I 2026-07-01 11:23:37 wer:338] WER predicted:màu đang của những tâm xe
[NeMo I 2026-07-01 11:23:45 wer:336]

[NeMo I 2026-07-01 11:23:45 wer:337] WER reference:tôi chỉ thấy người ta nhắc đến phượng vĩ tháng sáu hay cùng lắm là tháng năm
[NeMo I 2026-07-01 11:23:45 wer:338] WER predicted:tôi chỉ thấy ngườiáạ đến phương với th sau hai cũng tám là thành ra
[NeMo I 2026-07-01 11:23:53 wer:336]

[NeMo I 2026-07-01 11:23:53 wer:337] WER reference:với câu trả lời xuất sắc và gương mặt khả ái
[NeMo I 2026-07-01 11:23:53 wer:338] WER predicted:với cô cho lời sức s vàương một khá ai
[NeMo I 2026-07-01 11:24:02 wer:336]

[NeMo I 2026-07-01 11:24:02 wer:337] WER reference:nhưng em có biết rằng anh yêu em cũng bởi những lý do đó
[NeMo I 2026-07-01 11:24:02 wer:338] WER predicted:thì có biết tr anh như em cũng mới nh lý do
[NeMo I 2026-07-01 11:24:10 wer:336]

[NeMo I 2026-07-01 11:24:10 wer:337] WER reference:để nhìn thấy sự khôi hài
[NeMo I 2026-07-01 11:24:10 wer:338] WER predicted:để nhìn thấy sự khu hai
[NeMo I 2026-07-01 11:24:19 wer:336]

[NeMo I 2026-07-01 11:24:19 wer:337] WER reference:rèm cửa phòng khách của bạn giống như cung điện
[NeMo I 2026-07-01 11:24:19 wer:338] WER predicted:ra của phòng khách của bạn gi như cũng điện
[NeMo I 2026-07-01 11:24:27 wer:336]

[NeMo I 2026-07-01 11:24:27 wer:337] WER reference:và những khuyết điểm nhỏ của họ
[NeMo I 2026-07-01 11:24:27 wer:338] WER predicted:và những quyết điểm nhà của họ
[NeMo I 2026-07-01 11:24:36 wer:336]

[NeMo I 2026-07-01 11:24:36 wer:337] WER reference:tôi biết đây là quy tắc đòi hỏi
[NeMo I 2026-07-01 11:24:36 wer:338] WER predicted:tôi biết đây là quyết tác đòi hỏi
[NeMo I 2026-07-01 11:24:44 wer:336]

[NeMo I 2026-07-01 11:24:44 wer:337] WER reference:cũng trong ngày đó bài xã luận gằn giọng
[NeMo I 2026-07-01 11:24:44 wer:338] WER predicted:cũng trong ngày đó và sến g rằng gi
[NeMo I 2026-07-01 11:24:53 wer:336]

[NeMo I 2026-07-01 11:24:53 wer:337] WER reference:bạn có thể ghé thăm nó
[NeMo I 2026-07-01 11:24:53 wer:338] WER predicted:bạn có thể g nghĩa tha nó
[NeMo I 2026-07-01 11:25:01 wer:336]

[NeMo I 2026-07-01 11:25:01 wer:337] WER reference:các anh sẽ mãi là những người con ưu tú của tổ quốc của nhân dân việt nam
[NeMo I 2026-07-01 11:25:01 wer:338] WER predicted:các anh xem hay là những người con của thủ tổ quốc của nhân dân việc nam
[NeMo I 2026-07-01 11:25:09 wer:336]

[NeMo I 2026-07-01 11:25:09 wer:337] WER reference:để luôn có một bình hoa tươi mới
[NeMo I 2026-07-01 11:25:09 wer:338] WER predicted:để luôn có một bệnh hoa tôi mới
[NeMo I 2026-07-01 11:25:18 wer:336]

[NeMo I 2026-07-01 11:25:18 wer:337] WER reference:chúc bạn đọc có thật nhiều thời gian thư giãn thoải mái
[NeMo I 2026-07-01 11:25:18 wer:338] WER predicted:trước bạn đó có thật nhiều thời gian thứ d ở tôiiá
[NeMo I 2026-07-01 11:25:26 wer:336]

[NeMo I 2026-07-01 11:25:26 wer:337] WER reference:bất chấp sự ngăn cản của cơ quan chức năng
[NeMo I 2026-07-01 11:25:26 wer:338] WER predicted:bập sự năng đang của cơ quan nước năng
[NeMo I 2026-07-01 11:25:35 wer:336]

[NeMo I 2026-07-01 11:25:35 wer:337] WER reference:chỉ có điều cô ta mang giày chiếc váy len dài bằng lông cừu
[NeMo I 2026-07-01 11:25:35 wer:338] WER predicted:chỉ có điều cuộc ta mang giảiiếc với l lên dài bằng l luôn cứ
[NeMo I 2026-07-01 11:25:43 wer:336]

[NeMo I 2026-07-01 11:25:43 wer:337] WER reference:thánh nhân đãi khù khờ chính là chỗ này
[NeMo I 2026-07-01 11:25:43 wer:338] WER predicted:thành nhân ra khu thời chỉ thể trường này
[NeMo I 2026-07-01 11:25:52 wer:336]

[NeMo I 2026-07-01 11:25:52 wer:337] WER reference:cô bé rất lấy làm vui mừng và làm quen với những nốt nhạc đầu tiên bằng chính chiếc đàn đồ chơi ấy
[NeMo I 2026-07-01 11:25:52 wer:338] WER predicted:có bé làm vui và làm quan với những nàyạ đầu tiền trên bạn chính ch đang được cho ấy
[NeMo I 2026-07-01 11:26:00 wer:336]


Validation: |          | 0/? [00:00<?, ?it/s]

[NeMo I 2026-07-01 11:29:03 wer:336]

[NeMo I 2026-07-01 11:29:03 wer:337] WER reference:những con vật này đã bị giết và đốt
[NeMo I 2026-07-01 11:29:03 wer:338] WER predicted:nh con vật này đã bị gì và tốt
[NeMo I 2026-07-01 11:29:03 wer:336]

[NeMo I 2026-07-01 11:29:03 wer:337] WER reference:do vậy có máy cũng không thường dùng
[NeMo I 2026-07-01 11:29:03 wer:338] WER predicted:do vậy có mấy cũng không thường dụng
[NeMo I 2026-07-01 11:29:03 wer:336]

[NeMo I 2026-07-01 11:29:03 wer:337] WER reference:đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
[NeMo I 2026-07-01 11:29:03 wer:338] WER predicted:đây sẽ là của gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
[NeMo I 2026-07-01 11:29:03 wer:336]

[NeMo I 2026-07-01 11:29:03 wer:337] WER reference:sau đó một vật lạ bay xợt ngang nóc nhà ông
[NeMo I 2026-07-01 11:29:03 wer:338] WER predicted:sau đó một và là bảy sự năng nốc nhau
[NeMo I 2026-07-01 11:29:03 wer:336]

[NeMo I 2026-07-01 11:29:03 wer:337] WER reference:hiện ra tận phía xa
[NeMo I 2026-07-01 11:29:03 wer:338] WER predicted:hiện ra tình phía xa
[NeMo I 2026-07-01 11:29:03 wer:336]

[NeMo I 2026-07-01 11:29:03 wer:337] WER reference:nên với thông tin này
[NeMo I 2026-07-01 11:29:03 wer:338] WER predicted:nên với thông tiền này
[NeMo I 2026-07-01 11:29:04 wer:336]

[NeMo I 2026-07-01 11:29:04 wer:337] WER reference:và dân dã như chính cái tên của nó
[NeMo I 2026-07-01 11:29:04 wer:338] WER predicted:và dân gia như chính cái tình của nó
[NeMo I 2026-07-01 11:29:04 wer:336]

[NeMo I 2026-07-01 11:29:04 wer:337] WER reference:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 11:29:04 wer:338] WER predicted:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 11:29:04 wer:336]

[NeMo I 2026-07-01 11:29:04 wer:337] WER reference:sau nhiều pha hảm thành liên tục
[NeMo I 2026-07-01 11:29:04 wer:338] WER predicted:sau nhiều phá h thành liên tốt
[NeMo I 2026-07-01 11:29:04 wer:336]

[NeMo I 2026-07-01 11:29:04 wer:337] WER reference:anh vẫn nhớ kỷ niệm cầu đầu lâu
[NeMo I 2026-07-01 11:29:04 wer:338] WER predicted:anh vẫn như kỳ nhiệm cầu đầu lâu
[NeMo I 2026-07-01 11:29:04 wer:336]

[NeMo I 2026-07-01 11:29:04 wer:337] WER reference:gay go lắm nhưng hoàng anh gia lai sẽ làm được
[NeMo I 2026-07-01 11:29:04 wer:338] WER predicted:g g có làm nhưng hơn anh gia là sẽ làm được
[NeMo I 2026-07-01 11:29:04 wer:336]

[NeMo I 2026-07-01 11:29:04 wer:337] WER reference:do đó khi chơi chung với bạn bè cùng lứa chúng thường tỏ ra thiếu tự tin
[NeMo I 2026-07-01 11:29:04 wer:338] WER predicted:do đó khi tr chơi chúng với bạn bé cũng lư chúng ta thường tôi cả thiếu từ tình
[NeMo I 2026-07-01 11:29:04 wer:336]

[NeMo I 2026-07-01 11:29:04 wer:337] WER reference:mối đục luỗng cả tấm gỗ
[NeMo I 2026-07-01 11:29:04 wer:338] WER predicted:mọ được luôn các t tâm g
[NeMo I 2026-07-01 11:29:04 wer:336]

[NeMo I 2026-07-01 11:29:04 wer:337] WER reference:người ta cho rằng trung tâm này có khả năng ảnh hưởng đến quá trình lão hóa
[NeMo I 2026-07-01 11:29:04 wer:338] WER predicted:người ta cho rằng trong tâm này có khá năng anh hướng đến quá trên lâu hoa
[NeMo I 2026-07-01 11:29:04 wer:336]

[NeMo I 2026-07-01 11:29:04 wer:337] WER reference:các giò phong lan tháng ba cũng không chịu yên mình
[NeMo I 2026-07-01 11:29:04 wer:338] WER predicted:các cho phòng lên tha bà cũng công chịu ý mình
[NeMo I 2026-07-01 11:29:04 wer:336]

[NeMo I 2026-07-01 11:29:04 wer:337] WER reference:hãy cho tôi quyền năng vô tận để bảo vệ loài vật
[NeMo I 2026-07-01 11:29:04 wer:338] WER predicted:hay cho tôi viên năng v vụ tăng để bảo vềỗ vật
[NeMo I 2026-07-01 11:29:04 wer:336]

[NeMo I 2026-07-01 11:29:04 wer:337] WER reference:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 11:29:04 wer:338] WER predicted:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 11:29:04 wer:336]

[NeMo I 2026-07-01 11:29:04 wer:337] WER reference:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 11:29:04 wer:338] WER predicted:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 11:29:04 wer:336]

[NeMo I 2026-07-01 11:29:04 wer:337] WER reference:sáng chiều hội diễn tiếng hát bảo minh do công ty bảo hiểm bảo minh tổ chức
[NeMo I 2026-07-01 11:29:04 wer:338] WER predicted:sáng chịu họ diễn tiếng khác đầu mình do công ty b bảo em bảo mình tôi chức
[NeMo I 2026-07-01 11:29:04 wer:336]

[NeMo I 2026-07-01 11:29:04 wer:337] WER reference:cô nằm thiếp đi lúc nào không biết
[NeMo I 2026-07-01 11:29:04 wer:338] WER predicted:cô năm tiếp đi lúc nào không biết
[NeMo I 2026-07-01 11:29:04 wer:336]

[NeMo I 2026-07-01 11:29:04 wer:337] WER reference:mười bảy mười tám mười chín
[NeMo I 2026-07-01 11:29:04 wer:338] WER predicted:mươi bảy mươi tám mươi chín
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:tích cóp đủ thứ đồ lạc xon những ngọn đèn
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:tiếpốc đưa thứ đồ đã số nhữngọ đến
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:nhưng đất nước đã chọn một nhà lãnh đạo khác
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:nhưng được nước đã cho một nhà là đầu khác
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:ưu thế này có được là nhờ quá trình cơ giới hóa nhanh sử dụng phân bón cho dù hậu quả có là
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:uống thế này có được là nhớ quá trình cơ giới hoa nhân sự dụng phần bốn cho dụnghầu quá có là
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:thường xuyên xảy ra hiện tượng đạo văn quỵt nhuận bút
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:thường xuyên x ra hiện thường đầu văn quyết nh quốc
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:chỉ cho chúng tôi xem hàng đống gạch đá cát sỏi
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:chỉ cho chúng tôi xem hàng động g đã các số
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:đối với cảng hàng không quốc tế đà nẵng sử dụng nhà ga hành khách hiện hữu làm nhà ga nội địa
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:đối với càng hàng không quốc tế đã năng sự dụng nhà cả hành khách hiện hồ làm nhà cả nói để
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:người giàu thì vác nặng những xâu tiền kẽm trên vai
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:người dào thì phátắc những sau tiềnk trên phải
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:các nữ công nhân làm ca đêm
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:các nữa công nhân làm cả điểm
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:tui biết bà giỏi rồi
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:tôi biết ba d rồi
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:đưa một chú bồ câu bay đi bay về
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:đường một chú bộ cầu bảy đi bị về
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:tôi đến kiểm tra và phát hiện thấy ông và cô gái nằm kia thám tử ra hiệu cho ngài triệu phú nhìn vào phòng tắm cô ta đã chết
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:tôi đến kiể ra và phát hiện thấy ông và cô gái nămk tâm từ ra hiểu cho ngày chịu phương nh vào phòng tâm cô đã chết
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:để thực hiện thắng lợi kế hoạch năm năm
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:để thực hiện thân lại cái hết năm năm
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:trước khi hóa thân thành cộng hòa sét để đến bồ đào nha
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:trước khi hoa thân thành có hoa sức để đến bộ động nhà
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:tuy nhiên tôi không chắc những người chưa từng đọc cuốn nhật ký có thể hiểu hết được ý nghĩa bộ phim
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:tuy nhiên tôi không chắc những người chưa từ đọc cũng nhất kỳ có thể hiểu hết được ý nghĩ bộ phim
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:chi đầu tư từ khu vực nhà nước còn lớn và hiệu quả thấp
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:chỉ đầu tư từ khu vực nhà n nước còn lớn và hiệu quá hợp
[NeMo I 2026-07-01 11:29:05 wer:336]

[NeMo I 2026-07-01 11:29:05 wer:337] WER reference:cái nền xưa của nó bây giờ là một cái hố nông choèn
[NeMo I 2026-07-01 11:29:05 wer:338] WER predicted:cái nên s của nó bị giờ là một cái hồ năm tr
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:giải truyền thông điện ảnh trung quốc là giải thưởng điện ảnh duy nhất xét trao cho tất cả các bộ phim hoa ngữ
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:dài trên thường đến anh chúng quốc là dài thường đến anh gì sẽ cho cho tất cả các bộ hiện hoànư
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:dự đoán ba tháng nữa giá cà phê sẽ tăng gấp đôi hiện nay
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:điều rằng bà tháng nữa giá và về sự tăng gặp đổi hiện này
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:họ đến đây vì nhiều mục đích
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:họ đến đâyì nhiều mộtích
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:vậy trước đây nông dân đối phó với hiện tượng này như thế nào thưa ông
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:vậy trước này n năm nhân đối phố v với hiện từ này như đến nào thu  ông
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:làm sao để có tiền nhanh nhất
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:làm sao để có tiền nhân nh nhất
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:đùi dang ra ngoài
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:được gian ra ngoài
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:đã hai lần cô gác lại ước mơ vào đời và cũng đã ít nhiều trải qua những thăng trầm xô bồ của cuộc sống
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:đã hai l lần cô gái lạiút mới vào đời và cũng đã ít nhiều trái quá những thành tr số bộ của cuộc sống
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:trong bối cảnh như vậy một phản ứng chính sách đối với vấn đề thất nghiệp đang là đòi hỏi cấp bách hiện nay
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:trong bộ cảnh như vậy một phầnững chính sách đối với vẫn để nghiệp đang là để họ các cách hiện này
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:ở xứ sở chuột túi
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:ở s sự tr chủ tôi
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:do vậy dựa trên cơ sở nào mà ông khoa phát biểu như vậy
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:do vậy dự trên cơ s nào m ông khoa phát biểu như vậy
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:tá tàng
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:ta tăng
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:cách đây tám năm nhưng trước đó khoảng hai năm đã được mời đóng phim và có nhiều vai chính trong các phim điện ảnh truyền hình
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:cách đây tâm năm những trước đó hoàn hai năm đã được mới động phim và có nhiều và chính trong các phim điện anh truyền hình
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:đã thăm hỏi thì thế nào cũng phải có quà cáp
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:đã tâm họ thì thế nào cũng phải có quả các
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:có mặt tạià điện phòng
[NeMo I 2026-07-01 11:29:06 wer:336]

[NeMo I 2026-07-01 11:29:06 wer:337] WER reference:em lơ đễnh lật xem vài tờ báo
[NeMo I 2026-07-01 11:29:06 wer:338] WER predicted:em là điện l xem và từ báo
[NeMo I 2026-07-01 11:29:07 wer:336]

[NeMo I 2026-07-01 11:29:07 wer:337] WER reference:và không ít người cứ tì tì uống từ sáng đến tối suốt mấy ngày hội nghị
[NeMo I 2026-07-01 11:29:07 wer:338] WER predicted:và không ít người cứ ty từ  uống từ sáng đến tôi xuất máy ngày hội này
[NeMo I 2026-07-01 11:29:07 wer:336]

[NeMo I 2026-07-01 11:29:07 wer:337] WER reference:minh châu vào miền nam công tác tại nhà hát trần hữu trang
[NeMo I 2026-07-01 11:29:07 wer:338] WER predicted:mình cao vào m năm công tất tại nhà ho rằng h rằng
[NeMo I 2026-07-01 11:29:07 wer:336]

[NeMo I 2026-07-01 11:29:07 wer:337] WER reference:hết chiến tranh quê hương im tiếng súng anh lính cụ hồ lại trở về với đời thường tham gia sản xuất xây dựng và bảo vệ đất nước
[NeMo I 2026-07-01 11:29:07 wer:338] WER predicted:hết tiếng trên với hơn ý tiếng xuống anh lên của hồ lại cho về với đời thường tha giá sản xuất sẽ dững và b với đất nước
[NeMo I 2026-07-01 11:29:07 wer:336]

[NeMo I 2026-07-01 11:29:07 wer:337] WER reference:chuyến đi đó đến giờ vẫn là một ám ảnh trong ký ức tôi
[NeMo I 2026-07-01 11:29:07 wer:338] WER predicted:chỉ đi đó đến giờ vẫn là một ông anh trong chỉ
[NeMo I 2026-07-01 11:29:07 wer:336]

[NeMo I 2026-07-01 11:29:07 wer:337] WER reference:ây da ây da
[NeMo I 2026-07-01 11:29:07 wer:338] WER predicted:d gia
[NeMo I 2026-07-01 11:29:07 wer:336]

[NeMo I 2026-07-01 11:29:07 wer:337] WER reference:có rất nhiều vệ tinh bị rơi khỏi quỹ đạo
[NeMo I 2026-07-01 11:29:07 wer:338] WER predicted:rất nhiều về tính bị rồi khó qu nào
[NeMo I 2026-07-01 11:29:07 wer:336]

[NeMo I 2026-07-01 11:29:07 wer:337] WER reference:nhuốm đầy máu của thổ dân châu mỹ
[NeMo I 2026-07-01 11:29:07 wer:338] WER predicted:dụng đây máu của thu dân cho mỹ
[NeMo I 2026-07-01 11:29:07 wer:336]

[NeMo I 2026-07-01 11:29:07 wer:337] WER reference:cụ thể về đất đai xây dựng văn hóa thuộc về từng ngành riêng biệt
[NeMo I 2026-07-01 11:29:07 wer:338] WER predicted:cô thể về đất đây văn sẽ những văn hoa thuốc về từ ngành riêng biết
[NeMo I 2026-07-01 11:29:07 wer:336]

[NeMo I 2026-07-01 11:29:07 wer:337] WER reference:tôi muốn hỏi liệu có mùi hương sen nhân tạo là một loại hóa chất không
[NeMo I 2026-07-01 11:29:07 wer:338] WER predicted:tôi mua hỏi liệu có người hướng s nhân tạo là một loại họ chắc cao
[NeMo I 2026-07-01 11:29:07 wer:336]

[NeMo I 2026-07-01 11:29:07 wer:337] WER reference:cả nhà bà ngoại cười nắc nẻ vì câu nói ngây ngô của con
[NeMo I 2026-07-01 11:29:07 wer:338] WER predicted:các nhà bao ngoài người nước nghe v cô nói ngày ngồi của con
[NeMo I 2026-07-01 11:29:07 wer:336]

[NeMo I 2026-07-01 11:29:07 wer:337] WER reference:xin được chân khuân vác
[NeMo I 2026-07-01 11:29:07 wer:338] WER predicted:xin được trên khu phát
[NeMo I 2026-07-01 11:29:07 wer:336]

[NeMo I 2026-07-01 11:29:07 wer:337] WER reference:nằm khuất dưới tàn tre sát bờ sông châu
[NeMo I 2026-07-01 11:29:07 wer:338] WER predicted:ho giới đang trẻ sẽ bà sống ch
[NeMo I 2026-07-01 11:29:07 wer:336]

[NeMo I 2026-07-01 11:29:07 wer:337] WER reference:nếu kiên cố hóa thì vốn được đưa thẳng cho dân sẽ không thất thoát
[NeMo I 2026-07-01 11:29:07 wer:338] WER predicted:nếu ki cô hoa thì bốn đượcưa tăng cho dân sẽ không thật
[NeMo I 2026-07-01 11:29:07 wer:336]

[NeMo I 2026-07-01 11:29:07 wer:337] WER reference:nói chung cô hồng nào cũng có một số phận hoàn cảnh và cuộc đời riêng
[NeMo I 2026-07-01 11:29:07 wer:338] WER predicted:nói chúng cô học nào cũng có một số phần hoàn cảnh với cuộc đời riêng
[NeMo I 2026-07-01 11:29:07 wer:336]

[NeMo I 2026-07-01 11:29:07 wer:337] WER reference:nhưng tất cả những điều ấy chẳng mấy khi đi liền với nhau
[NeMo I 2026-07-01 11:29:07 wer:338] WER predicted:những tất cả những điều ấy ch mấy khi đi liên với nhau
[NeMo I 2026-07-01 11:29:08 wer:336]

[NeMo I 2026-07-01 11:29:08 wer:337] WER reference:như vậy là bạn có thể sử dụng được nhiều số điện thoại của nhiều nhà cung cấp dịch vụ chỉ trên một sim
[NeMo I 2026-07-01 11:29:08 wer:338] WER predicted:như vậy bạn có thể sự dụng được nhiều số đến th của như nhà cũng cấp dịch vụ chỉ trên một xem
[NeMo I 2026-07-01 11:29:08 wer:336]

[NeMo I 2026-07-01 11:29:08 wer:337] WER reference:trong trường hợp hai bên có thỏa thuận lại không yêu cầu trọng tài giải quyết nữa thì có quyền kiện ra tòa án
[NeMo I 2026-07-01 11:29:08 wer:338] WER predicted:trong trường hợp hai bên có thể thường lại không yêu cầu trong ta d quyết nữa thì có viên kiến ra toàn ăn
[NeMo I 2026-07-01 11:29:08 wer:336]

[NeMo I 2026-07-01 11:29:08 wer:337] WER reference:kiểu này chắc phải cắt giảm biên chế
[NeMo I 2026-07-01 11:29:08 wer:338] WER predicted:chưa này chắc phải các giá biến chế
[NeMo I 2026-07-01 11:29:08 wer:336]

[NeMo I 2026-07-01 11:29:08 wer:337] WER reference:nhưng tôi không yêu cô cô biết rõ điều đó mà
[NeMo I 2026-07-01 11:29:08 wer:338] WER predicted:nhưng tôi không yêu cô cô biết rồi điều đó mà
[NeMo I 2026-07-01 11:29:08 wer:336]

[NeMo I 2026-07-01 11:29:08 wer:337] WER reference:khó mà đoán trước chính xác kết quả khi quả bóng còn lăn
[NeMo I 2026-07-01 11:29:08 wer:338] WER predicted:không mà đó trước chính sẽích qua khi qua b con
[NeMo I 2026-07-01 11:29:08 wer:336]

[NeMo I 2026-07-01 11:29:08 wer:337] WER reference:vừa nhìn thấy sự xuất hiện của bố tất cả mấy thằng khác vùng bỏ chạy sạch
[NeMo I 2026-07-01 11:29:08 wer:338] WER predicted:với nh thấy sự sự hiện của bố tất cả máy th thành khác vùng bội trẻ sách
[NeMo I 2026-07-01 11:29:08 wer:336]

[NeMo I 2026-07-01 11:29:08 wer:337] WER reference:phải nâng cao khả năng cạnh tranh của nền kinh tế
[NeMo I 2026-07-01 11:29:08 wer:338] WER predicted:phải năng cao hình năng cảnh trên của nên kinh tình
[NeMo I 2026-07-01 11:29:08 wer:336]

[NeMo I 2026-07-01 11:29:08 wer:337] WER reference:bà thường lấy ý tưởng cho các tác phẩm từ đâu
[NeMo I 2026-07-01 11:29:08 wer:338] WER predicted:bà thườngấy ý từ cho các tác phẩm từ đồng
[NeMo I 2026-07-01 11:29:08 wer:336]

[NeMo I 2026-07-01 11:29:08 wer:337] WER reference:khi chứng kiến người vợ lăng loàn
[NeMo I 2026-07-01 11:29:08 wer:338] WER predicted:khi chứng kiến người vào l lần lòng
[NeMo I 2026-07-01 11:29:08 wer:336]

[NeMo I 2026-07-01 11:29:08 wer:337] WER reference:tác phẩm to lớn bằng đồng như tượng phật quỳnh lâm chuông quy điền tháp báo thiên vạc phổ minh an nam tứ đại khí
[NeMo I 2026-07-01 11:29:08 wer:338] WER predicted:ta phẩm ta lớn bạn đồng như tu phát qu làm chúng qu điện th bảo tìm và phố mình ăn năm tư đây khi
[NeMo I 2026-07-01 11:29:08 wer:336]

[NeMo I 2026-07-01 11:29:08 wer:337] WER reference:ngoài ra họ vẫn còn muốn giữ chân cầu thủ xuất sắc nhất của mình
[NeMo I 2026-07-01 11:29:08 wer:338] WER predicted:họ vẫn cầu muốnư chân cầu thủ xuất s
[NeMo I 2026-07-01 11:29:08 wer:336]

[NeMo I 2026-07-01 11:29:08 wer:337] WER reference:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 11:29:08 wer:338] WER predicted:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 11:29:08 wer:336]

[NeMo I 2026-07-01 11:29:08 wer:337] WER reference:và gã thệ bị điều về làm trưởng phòng xã hội huyện
[NeMo I 2026-07-01 11:29:08 wer:338] WER predicted:và cả thể biết điều về làm trường phần x hội h
[NeMo I 2026-07-01 11:29:08 wer:336]

[NeMo I 2026-07-01 11:29:08 wer:337] WER reference:là rút rỉa tiền của bạn càng nhiều càng tốt

[NeMo W 2026-07-01 11:29:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 11:29:24 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

[best val_wer] epoch=3 val_wer=0.471481 exported=/kaggle/working/phase3_continue_best.nemo

Sample predictions after epoch 3:
  [0] REF: những con vật này đã bị giết và đốt
      HYP: nh con vật này đã bị gì và tốt
  [1] REF: phòng chống tham nhũng không được chủ quan cần làm liên tục đồng bộ và có các giải pháp
      HYP: phòng trong tham dụng không được chủ quan cần làm liên tục động bộ và có các lại pháp
  [2] REF: do vậy có máy cũng không thường dùng
      HYP: do vậy có mấy cũng không thường dụng
  [3] REF: mới khệnh khạng đứng lên đi ra
      HYP: mới kh khá đến lên đi ra
  [4] REF: đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
      HYP: đây sẽ là của gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
  [5] REF: sau một năm eo sèo
      HYP: sáu một năm yêu x
  [6] REF: sau đó một vật lạ bay xợt ngang nóc nhà ông
      HYP: sau đó một và là bảy sự năng nốc nhau
  [7] REF: chín mươi hai chín mươi ba
      HYP: chín mươi hai chín mươi ba
  [8] REF: hiện ra tận phía xa
      HYP: hiện ra tình phía xa
  [9] REF: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã qua của thị trường
      HYP: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã quá của thì trường
[epoch] epoch=3/12 step=942 val_loss=2.283615827560425 val_wer=0.47148144245147705
[NeMo I 2026-07-01 11:29:51 wer:336]

[NeMo I 2026-07-01 11:29:51 wer:337] WER reference:rất nhiều trường hợp phụ huynh đau đầu vì con một đã tìm đến chuyên viên tư vấn tâm lý
[NeMo I 2026-07-01 11:29:51 wer:338] WER predicted:rất trường học phụ kh đầu đầuì anh một đã tìm đến trên viên tư anh tâm lý
[NeMo I 2026-07-01 11:30:00 wer:336]

[NeMo I 2026-07-01 11:30:00 wer:337] WER reference:trước tình thế đó tôi buộc phải tìm cho mình một bến đỗ mới và tôi đã quyết định ra đi
[NeMo I 2026-07-01 11:30:00 wer:338] WER predicted:nước tình thế đó tôi bộ phải tiền cho mình một b đầu mới và tôi đã quyết bệnh ra đi
[NeMo I 2026-07-01 11:30:08 wer:336]

[NeMo I 2026-07-01 11:30:08 wer:337] WER reference:tuy nhiên tình hình đó không diễn ra ở tất cả trường
[NeMo I 2026-07-01 11:30:08 wer:338] WER predicted:tuy nhiên tình hình đó không nhá ở tất các trường
[NeMo I 2026-07-01 11:30:17 wer:336]

[NeMo I 2026-07-01 11:30:17 wer:337] WER reference:nếu xét trên qui mô toàn tỉnh con số ấy vẫn còn khiêm tốn lắm
[NeMo I 2026-07-01 11:30:17 wer:338] WER predicted:nên x chỉ ph mua toàn tình cầu số ấy vẫn còn khiù làm
[NeMo I 2026-07-01 11:30:25 wer:336]

[NeMo I 2026-07-01 11:30:25 wer:337] WER reference:các vùng sâu vùng xa khó mà phát triển
[NeMo I 2026-07-01 11:30:25 wer:338] WER predicted:các vùng sau vùng sẽ khó mà phát chỉ
[NeMo I 2026-07-01 11:30:33 wer:336]

[NeMo I 2026-07-01 11:30:33 wer:337] WER reference:thì không hiểu sao ở phần thơ cổ đại
[NeMo I 2026-07-01 11:30:33 wer:338] WER predicted:thì không hiểu sao ở phần hết của đây
[NeMo I 2026-07-01 11:30:42 wer:336]

[NeMo I 2026-07-01 11:30:42 wer:337] WER reference:anh muốn thùy có thể tự do tìm cho mình một hạnh phúc khác tràn đầy
[NeMo I 2026-07-01 11:30:42 wer:338] WER predicted:anh muốn thời có thể từ do tìm cho mình một thành ph khác cho lại
[NeMo I 2026-07-01 11:30:50 wer:336]

[NeMo I 2026-07-01 11:30:50 wer:337] WER reference:áo thun trắng sát nách
[NeMo I 2026-07-01 11:30:50 wer:338] WER predicted:ở thu trang sát nhất
[NeMo I 2026-07-01 11:30:59 wer:336]

[NeMo I 2026-07-01 11:30:59 wer:337] WER reference:đây cũng là giai đoạn thị trường nhiều biến cố nhất
[NeMo I 2026-07-01 11:30:59 wer:338] WER predicted:đây cũng là chế đồng thì trường nhiều biến cô nhất
[NeMo I 2026-07-01 11:31:07 wer:336]

[NeMo I 2026-07-01 11:31:07 wer:337] WER reference:mới thành món ngon và độc đáo
[NeMo I 2026-07-01 11:31:07 wer:338] WER predicted:mới thành món ngon và được đâu
[NeMo I 2026-07-01 11:31:16 wer:336]

[NeMo I 2026-07-01 11:31:16 wer:337] WER reference:người đẹp không thiếu chỉ sợ ông anh không có tiền
[NeMo I 2026-07-01 11:31:16 wer:338] WER predicted:người để không thiếu chỉ s ông anh không có tình
[NeMo I 2026-07-01 11:31:25 wer:336]

[NeMo I 2026-07-01 11:31:25 wer:337] WER reference:ngày thường chù ụ thì được
[NeMo I 2026-07-01 11:31:25 wer:338] WER predicted:ngày thường chủ ông gì được
[NeMo I 2026-07-01 11:31:34 wer:336]

[NeMo I 2026-07-01 11:31:34 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 11:31:34 wer:338] WER predicted:có mặt tại sẽ điện phương
[NeMo I 2026-07-01 11:31:42 wer:336]

[NeMo I 2026-07-01 11:31:42 wer:337] WER reference:tôi cũng biết có những tiêu cực trong giáo dục và nhà trường cũng như những lĩnh vực khác của xã hội
[NeMo I 2026-07-01 11:31:42 wer:338] WER predicted:tôi cũng biết có những tiêu thực trong giá được và nhà trường của như những lên với h của xã hội
[NeMo I 2026-07-01 11:31:51 wer:336]

[NeMo I 2026-07-01 11:31:51 wer:337] WER reference:xắn quần vượt qua là bước vào thế giới
[NeMo I 2026-07-01 11:31:51 wer:338] WER predicted:sống qu v qua là bước vào thời giới
[NeMo I 2026-07-01 11:31:59 wer:336]

[NeMo I 2026-07-01 11:31:59 wer:337] WER reference:mới và cải tiến
[NeMo I 2026-07-01 11:31:59 wer:338] WER predicted:mới và cái tiền
[NeMo I 2026-07-01 11:32:08 wer:336]

[NeMo I 2026-07-01 11:32:08 wer:337] WER reference:hai vợ chồng thị tớn và văn đục
[NeMo I 2026-07-01 11:32:08 wer:338] WER predicted:hai vợ trong thì từ và văn được
[NeMo I 2026-07-01 11:32:16 wer:336]

[NeMo I 2026-07-01 11:32:16 wer:337] WER reference:chợ đêm ca ba dành cho những người đang vào mùa tăng ca cuối năm
[NeMo I 2026-07-01 11:32:16 wer:338] WER predicted:ở đến và ba gi cho nh người đang vào một ta cả cứ năm
[NeMo I 2026-07-01 11:32:25 wer:336]

[NeMo I 2026-07-01 11:32:25 wer:337] WER reference:hai mươi hai mươi mốt
[NeMo I 2026-07-01 11:32:25 wer:338] WER predicted:hai mươi hai mươi mốt
[NeMo I 2026-07-01 11:32:33 wer:336]

[NeMo I 2026-07-01 11:32:33 wer:337] WER reference:anh không thể quên được những giây phút ngọt ngào ấy
[NeMo I 2026-07-01 11:32:33 wer:338] WER predicted:anh không được qu được nh ph gian ngọ nào ấy
[NeMo I 2026-07-01 11:32:42 wer:336]

[NeMo I 2026-07-01 11:32:42 wer:337] WER reference:đưa tới tình trạng phá sản
[NeMo I 2026-07-01 11:32:42 wer:338] WER predicted:ưa tư tiền r phá sản
[NeMo I 2026-07-01 11:32:50 wer:336]

[NeMo I 2026-07-01 11:32:50 wer:337] WER reference:phụ huynh và học sinh đang phải è cổ vì sách giá cao
[NeMo I 2026-07-01 11:32:50 wer:338] WER predicted:vụ qu và học sinh đang phải em cô vì sách gia cao
[NeMo I 2026-07-01 11:32:59 wer:336]

[NeMo I 2026-07-01 11:32:59 wer:337] WER reference:thỉnh thoảng lại có người ghép thận trước đó trở qua xin xét nghiệm vì có trục trặc
[NeMo I 2026-07-01 11:32:59 wer:338] WER predicted:tình toàn lại có người g thân tư gặp tôi qua sinh sẽ nghe về cóục đọc
[NeMo I 2026-07-01 11:33:07 wer:336]

[NeMo I 2026-07-01 11:33:07 wer:337] WER reference:cuộc thi nhằm trau dồi niềm đam mê
[NeMo I 2026-07-01 11:33:07 wer:338] WER predicted:cuộc thế nhân cho d nhiệm đã mẹ
[NeMo I 2026-07-01 11:33:16 wer:336]

[NeMo I 2026-07-01 11:33:16 wer:337] WER reference:đề thi môn vẽ thông thường là về vẽ trang trí sản phẩm vật thể
[NeMo I 2026-07-01 11:33:16 wer:338] WER predicted:để thi muốn vẻ hô thường là về việc sáng chỉ sản phẩm một thể
[NeMo I 2026-07-01 11:33:25 wer:336]

[NeMo I 2026-07-01 11:33:25 wer:337] WER reference:bước vào một mối tình
[NeMo I 2026-07-01 11:33:25 wer:338] WER predicted:bước vào một mua tình
[NeMo I 2026-07-01 11:33:33 wer:336]

[NeMo I 2026-07-01 11:33:33 wer:337] WER reference:lão nạp chỉ có nhiêu đây thôi
[NeMo I 2026-07-01 11:33:33 wer:338] WER predicted:làạ chỉ có như lại tôi
[NeMo I 2026-07-01 11:33:42 wer:336]

[NeMo I 2026-07-01 11:33:42 wer:337] WER reference:hai tuần sau
[NeMo I 2026-07-01 11:33:42 wer:338] WER predicted:hai cũng sáu
[NeMo I 2026-07-01 11:33:50 wer:336]

[NeMo I 2026-07-01 11:33:50 wer:337] WER reference:những ngày cuối cùng trên dương thế
[NeMo I 2026-07-01 11:33:50 wer:338] WER predicted:những này cuối cùng trên dân thế
[NeMo I 2026-07-01 11:33:59 wer:336]

[NeMo I 2026-07-01 11:33:59 wer:337] WER reference:trên nhiều tuyến phố công nhân đang hối hả dọn dẹp
[NeMo I 2026-07-01 11:33:59 wer:338] WER predicted:trên nhiều tiếng ph công nh đang hội hay chọn nghiệpp
[NeMo I 2026-07-01 11:34:07 wer:336]

[NeMo I 2026-07-01 11:34:07 wer:337] WER reference:có trường hợp bất hợp pháp như trần thị thu h
[NeMo I 2026-07-01 11:34:07 wer:338] WER predicted:có chuyện học bất học pháp như trong thì thu
[NeMo I 2026-07-01 11:34:16 wer:336]

[NeMo I 2026-07-01 11:34:16 wer:337] WER reference:nhưng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được các khó khăn đó
[NeMo I 2026-07-01 11:34:16 wer:338] WER predicted:chúng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được cả kh không đó
[NeMo I 2026-07-01 11:34:24 wer:336]

[NeMo I 2026-07-01 11:34:24 wer:337] WER reference:lúc đó em không thể tiếp tục công việc đánh cá của cha một mình vì còn quá nhỏ
[NeMo I 2026-07-01 11:34:24 wer:338] WER predicted:lúc đó em không phải tiếp cơ không việc đến các của cho một mình việc còn qua nhỏ
[NeMo I 2026-07-01 11:34:33 wer:336]

[NeMo I 2026-07-01 11:34:33 wer:337] WER reference:cuốn sách nói về sự lầm lẫn giữa luật kinh tế ở châu âu và châu mỹ kim vẫn chưa đọc tới vì cô không quan tâm đến luật
[NeMo I 2026-07-01 11:34:33 wer:338] WER predicted:cũng sẽ nói về làm lần d được ki thế ở trong ông và trong muốn cho vẫn chưa đọc tôi việc của không quan tăng đến luật
[NeMo I 2026-07-01 11:34:41 wer:336]

[NeMo I 2026-07-01 11:34:41 wer:337] WER reference:khi tên lửa bay lên
[NeMo I 2026-07-01 11:34:41 wer:338] WER predicted:khi tên l lực vậyi lên
[NeMo I 2026-07-01 11:34:50 wer:336]

[NeMo I 2026-07-01 11:34:50 wer:337] WER reference:mà theo thời gian sẽ tiệm cận với trí khôn của con người
[NeMo I 2026-07-01 11:34:50 wer:338] WER predicted:mà theo thời dân sẽ tìm cần với trí cũng của quốc con người
[NeMo I 2026-07-01 11:34:58 wer:336]

[NeMo I 2026-07-01 11:34:58 wer:337] WER reference:bên kia láng giềng của tôi hôm nay không thấy thăm hoa
[NeMo I 2026-07-01 11:34:58 wer:338] WER predicted:đến chỉ là diễn của tôi hô này không thấy th hơn
[NeMo I 2026-07-01 11:35:07 wer:336]

[NeMo I 2026-07-01 11:35:07 wer:337] WER reference:anh yêu cầu các cầu thủ phải đeo bám ngay khi đối phương có bóng
[NeMo I 2026-07-01 11:35:07 wer:338] WER predicted:anh nhiều cầu các cầu số phảieo bạn này khi đối phương có
[NeMo I 2026-07-01 11:35:15 wer:336]

[NeMo I 2026-07-01 11:35:15 wer:337] WER reference:ngay cả công an đi lẻ loi cũng bị tấn công vì trong khu vực này có một thứ luật riêng cấm người lạ vào
[NeMo I 2026-07-01 11:35:15 wer:338] WER predicted:nghe và không đi lẽ cũng bị không con việc trong có việc mẹ một thứ lực viên công như l
[NeMo I 2026-07-01 11:35:24 wer:336]

[NeMo I 2026-07-01 11:35:24 wer:337] WER reference:thì chúng sẽ nằm trong tầm kiểm soát của bạn
[NeMo I 2026-07-01 11:35:24 wer:338] WER predicted:thì chúng sẽ n năm trong làmm kiể sau của bạn
[NeMo I 2026-07-01 11:35:32 wer:336]

[NeMo I 2026-07-01 11:35:32 wer:337] WER reference:đó là hai con sói hoàn toàn trái ngược nhau về hình thức
[NeMo I 2026-07-01 11:35:32 wer:338] WER predicted:đó là hay con s hộ còn chính được nhau về hình thức
[NeMo I 2026-07-01 11:35:41 wer:336]

[NeMo I 2026-07-01 11:35:41 wer:337] WER reference:trại đồng xã yên sở giữa một biển nước mênh mông ảnh nguyễn quân
[NeMo I 2026-07-01 11:35:41 wer:338] WER predicted:tr đồng x em s giờ một bị trước mình m anh nguyên quan
[NeMo I 2026-07-01 11:35:49 wer:336]

[NeMo I 2026-07-01 11:35:49 wer:337] WER reference:không sao rồi em mừng lắm
[NeMo I 2026-07-01 11:35:49 wer:338] WER predicted:không sao rồi em mình làm
[NeMo I 2026-07-01 11:35:57 wer:336]

[NeMo I 2026-07-01 11:35:57 wer:337] WER reference:việc tòa án của pháp truy tố công dân một nước độc lập trên lãnh thổ quê hương của người ấy là một điều vô giá trị
[NeMo I 2026-07-01 11:35:57 wer:338] WER predicted:việc tôi ăn cuộc phát tr tốt của không một được được lập trên l lên tôi cuối hơn ng ở ấy là một bị chú giá trị
[NeMo I 2026-07-01 11:36:06 wer:336]

[NeMo I 2026-07-01 11:36:06 wer:337] WER reference:bà mẹ nghèo đông con
[NeMo I 2026-07-01 11:36:06 wer:338] WER predicted:và mẹ nghe vẫn con
[NeMo I 2026-07-01 11:36:14 wer:336]

[NeMo I 2026-07-01 11:36:14 wer:337] WER reference:lấy tĩnh chế động
[NeMo I 2026-07-01 11:36:14 wer:338] WER predicted:l liệu tình cho động
[NeMo I 2026-07-01 11:36:23 wer:336]

[NeMo I 2026-07-01 11:36:23 wer:337] WER reference:mình mẩy tôi tuy đau đớn
[NeMo I 2026-07-01 11:36:23 wer:338] WER predicted:mình bảy tôi tuy đau đường
[NeMo I 2026-07-01 11:36:31 wer:336]

[NeMo I 2026-07-01 11:36:31 wer:337] WER reference:luôn ngẩng cao đầu sự khác biệt lớn nhất giữa người tự tin và người nhút nhát là gì
[NeMo I 2026-07-01 11:36:31 wer:338] WER predicted:luôn ngn cao đầu x khách người lớn nhỏ d người từ tiếng biết và người nh nhấtạ là gì
[NeMo I 2026-07-01 11:36:40 wer:336]

[NeMo I 2026-07-01 11:36:40 wer:337] WER reference:với các bạn trẻ trên đây có vẻ tình yêu không phải là tất cả
[NeMo I 2026-07-01 11:36:40 wer:338] WER predicted:với các bạn trẻ chính đây có về tình yêu kh và là tục cả
[NeMo I 2026-07-01 11:36:48 wer:336]

[NeMo I 2026-07-01 11:36:48 wer:337] WER reference:nếu trẻ bú không đủ có thể vắt sữa và cho trẻ uống bằng muỗng
[NeMo I 2026-07-01 11:36:48 wer:338] WER predicted:như trẻ vụ không đủ có thể biết s và tr trẻ  uống bằngu
[NeMo I 2026-07-01 11:36:57 wer:336]

[NeMo I 2026-07-01 11:36:57 wer:337] WER reference:hãy để thời gian tìm hiểu thêm và thuyết phục gia đình
[NeMo I 2026-07-01 11:36:57 wer:338] WER predicted:hãy để thời gian để mỹ thêm phải thu phục gia đình
[NeMo I 2026-07-01 11:37:05 wer:336]

[NeMo I 2026-07-01 11:37:05 wer:337] WER reference:vân vân và vân vân
[NeMo I 2026-07-01 11:37:05 wer:338] WER predicted:v vẫn bốn và vẫn bốn
[NeMo I 2026-07-01 11:37:14 wer:336]

[NeMo I 2026-07-01 11:37:14 wer:337] WER reference:mà phụ nữ trong khu vực công đang gặp phải
[NeMo I 2026-07-01 11:37:14 wer:338] WER predicted:mà phụ nơi trong khu vực công đang g gặp phải
[NeMo I 2026-07-01 11:37:22 wer:336]

[NeMo I 2026-07-01 11:37:22 wer:337] WER reference:những năm trước phần lớn sếu ở kiên lương kiên giang
[NeMo I 2026-07-01 11:37:22 wer:338] WER predicted:những năm ch phần lên sẽ ở khi lớn ki gia
[NeMo I 2026-07-01 11:37:31 wer:336]

[NeMo I 2026-07-01 11:37:31 wer:337] WER reference:theo nguyên đào kinh tế đô thị
[NeMo I 2026-07-01 11:37:31 wer:338] WER predicted:theo nguyên đào ki tênưa thời
[NeMo I 2026-07-01 11:37:39 wer:336]

[NeMo I 2026-07-01 11:37:39 wer:337] WER reference:nhưng ngủ quá nhiều sẽ khiến bạn trở nên bơ phờ
[NeMo I 2026-07-01 11:37:39 wer:338] WER predicted:nhưng người quá nhiều sẽ khiến bạn trên đến b ph
[NeMo I 2026-07-01 11:37:48 wer:336]

[NeMo I 2026-07-01 11:37:48 wer:337] WER reference:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 11:37:48 wer:338] WER predicted:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 11:37:56 wer:336]

[NeMo I 2026-07-01 11:37:56 wer:337] WER reference:thường xuyên đối mặt với nạn khan hiếm lương thực
[NeMo I 2026-07-01 11:37:56 wer:338] WER predicted:thường x đối mặt với ăn khá hếm luôn thực
[NeMo I 2026-07-01 11:38:05 wer:336]

[NeMo I 2026-07-01 11:38:05 wer:337] WER reference:tôi có cảm tình với cô ấy nhưng tôi không muốn xen vào giữa họ
[NeMo I 2026-07-01 11:38:05 wer:338] WER predicted:tôi có cảm tình với cơ ấyững tôi không muốn xe vào d họ
[NeMo I 2026-07-01 11:38:13 wer:336]

[NeMo I 2026-07-01 11:38:13 wer:337] WER reference:với tôi chết là một sự ích kỷ còn bản chất sự sống đã là một bao dung ít nhất với chính mình
[NeMo I 2026-07-01 11:38:13 wer:338] WER predicted:với tôi ch là một sự kỳ công bạn chất sĩ sống đã một bao người biết nhất với chính mới
[NeMo I 2026-07-01 11:38:22 wer:336]

[NeMo I 2026-07-01 11:38:22 wer:337] WER reference:cậu không biết làm gì thì suốt đời cậu đúng là một kẻ hèn nhát
[NeMo I 2026-07-01 11:38:22 wer:338] WER predicted:cầu không biết làm gì thì xuất đời cầu đường là một các hàng nam
[NeMo I 2026-07-01 11:38:30 wer:336]

[NeMo I 2026-07-01 11:38:30 wer:337] WER reference:màu đen của những tấm cha
[NeMo I 2026-07-01 11:38:30 wer:338] WER predicted:màu đang của những tâm gia
[NeMo I 2026-07-01 11:38:39 wer:336]

[NeMo I 2026-07-01 11:38:39 wer:337] WER reference:tôi chỉ thấy người ta nhắc đến phượng vĩ tháng sáu hay cùng lắm là tháng năm
[NeMo I 2026-07-01 11:38:39 wer:338] WER predicted:tôi chỉ thấy ngườiáạ đến phương với tình sau hai cũng tám là thành ra
[NeMo I 2026-07-01 11:38:47 wer:336]

[NeMo I 2026-07-01 11:38:47 wer:337] WER reference:với câu trả lời xuất sắc và gương mặt khả ái
[NeMo I 2026-07-01 11:38:47 wer:338] WER predicted:với cô cho lời sức rất vàương một khá ai
[NeMo I 2026-07-01 11:38:56 wer:336]

[NeMo I 2026-07-01 11:38:56 wer:337] WER reference:nhưng em có biết rằng anh yêu em cũng bởi những lý do đó
[NeMo I 2026-07-01 11:38:56 wer:338] WER predicted:thì có biết tr anh như em cũng người nh lý do
[NeMo I 2026-07-01 11:39:04 wer:336]

[NeMo I 2026-07-01 11:39:04 wer:337] WER reference:để nhìn thấy sự khôi hài
[NeMo I 2026-07-01 11:39:04 wer:338] WER predicted:để nhìn thấy sự khu hai
[NeMo I 2026-07-01 11:39:13 wer:336]

[NeMo I 2026-07-01 11:39:13 wer:337] WER reference:rèm cửa phòng khách của bạn giống như cung điện
[NeMo I 2026-07-01 11:39:13 wer:338] WER predicted:ra c của phòng khách của bạn gi như cũng điện
[NeMo I 2026-07-01 11:39:21 wer:336]

[NeMo I 2026-07-01 11:39:21 wer:337] WER reference:và những khuyết điểm nhỏ của họ
[NeMo I 2026-07-01 11:39:21 wer:338] WER predicted:và những quyết điểm nhà của họ
[NeMo I 2026-07-01 11:39:30 wer:336]

[NeMo I 2026-07-01 11:39:30 wer:337] WER reference:tôi biết đây là quy tắc đòi hỏi
[NeMo I 2026-07-01 11:39:30 wer:338] WER predicted:tôi biết đây là quyết tác đòi hỏi
[NeMo I 2026-07-01 11:39:38 wer:336]

[NeMo I 2026-07-01 11:39:38 wer:337] WER reference:cũng trong ngày đó bài xã luận gằn giọng
[NeMo I 2026-07-01 11:39:38 wer:338] WER predicted:cũng trong ngày đó và sến g gi
[NeMo I 2026-07-01 11:39:47 wer:336]

[NeMo I 2026-07-01 11:39:47 wer:337] WER reference:bạn có thể ghé thăm nó
[NeMo I 2026-07-01 11:39:47 wer:338] WER predicted:bạn có thể g nghĩa tha nó
[NeMo I 2026-07-01 11:39:55 wer:336]

[NeMo I 2026-07-01 11:39:55 wer:337] WER reference:các anh sẽ mãi là những người con ưu tú của tổ quốc của nhân dân việt nam
[NeMo I 2026-07-01 11:39:55 wer:338] WER predicted:các anh xem hay là những người conu thủ tổ quốc của nhân dân việt nam
[NeMo I 2026-07-01 11:40:04 wer:336]

[NeMo I 2026-07-01 11:40:04 wer:337] WER reference:để luôn có một bình hoa tươi mới
[NeMo I 2026-07-01 11:40:04 wer:338] WER predicted:để luôn có một bệnh hoa tôi mới
[NeMo I 2026-07-01 11:40:12 wer:336]

[NeMo I 2026-07-01 11:40:12 wer:337] WER reference:chúc bạn đọc có thật nhiều thời gian thư giãn thoải mái
[NeMo I 2026-07-01 11:40:12 wer:338] WER predicted:ch bạn đó có thật nhiều thời gian thứ d ở tôiiá
[NeMo I 2026-07-01 11:40:21 wer:336]

[NeMo I 2026-07-01 11:40:21 wer:337] WER reference:bất chấp sự ngăn cản của cơ quan chức năng
[NeMo I 2026-07-01 11:40:21 wer:338] WER predicted:bập sự năng đang của cơ quan nước năng
[NeMo I 2026-07-01 11:40:29 wer:336]

[NeMo I 2026-07-01 11:40:29 wer:337] WER reference:chỉ có điều cô ta mang giày chiếc váy len dài bằng lông cừu
[NeMo I 2026-07-01 11:40:29 wer:338] WER predicted:chỉ có điều cuộc ta mang giảiiếc với l lên dài bằng l luôn cứ
[NeMo I 2026-07-01 11:40:37 wer:336]

[NeMo I 2026-07-01 11:40:37 wer:337] WER reference:thánh nhân đãi khù khờ chính là chỗ này
[NeMo I 2026-07-01 11:40:37 wer:338] WER predicted:thành nhân ra khu thời chỉ là chủ này
[NeMo I 2026-07-01 11:40:46 wer:336]

[NeMo I 2026-07-01 11:40:46 wer:337] WER reference:cô bé rất lấy làm vui mừng và làm quen với những nốt nhạc đầu tiên bằng chính chiếc đàn đồ chơi ấy
[NeMo I 2026-07-01 11:40:46 wer:338] WER predicted:có bé rất làm vui và làm quan với nhữngạ đầu tiền trên bạn chính ch đang được chơi ấy
[NeMo I 2026-07-01 11:40:54 wer:336]


Validation: |          | 0/? [00:00<?, ?it/s]

[NeMo I 2026-07-01 11:43:57 wer:336]

[NeMo I 2026-07-01 11:43:57 wer:337] WER reference:những con vật này đã bị giết và đốt
[NeMo I 2026-07-01 11:43:57 wer:338] WER predicted:nh con vật này đã bị gì và tốt
[NeMo I 2026-07-01 11:43:57 wer:336]

[NeMo I 2026-07-01 11:43:57 wer:337] WER reference:do vậy có máy cũng không thường dùng
[NeMo I 2026-07-01 11:43:57 wer:338] WER predicted:do vậy có mấy cũng không thường dụng
[NeMo I 2026-07-01 11:43:57 wer:336]

[NeMo I 2026-07-01 11:43:57 wer:337] WER reference:đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
[NeMo I 2026-07-01 11:43:57 wer:338] WER predicted:đây sẽ là cuộc gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
[NeMo I 2026-07-01 11:43:57 wer:336]

[NeMo I 2026-07-01 11:43:57 wer:337] WER reference:sau đó một vật lạ bay xợt ngang nóc nhà ông
[NeMo I 2026-07-01 11:43:57 wer:338] WER predicted:sau đó một và là bảy sự năng nốc nhau
[NeMo I 2026-07-01 11:43:57 wer:336]

[NeMo I 2026-07-01 11:43:57 wer:337] WER reference:hiện ra tận phía xa
[NeMo I 2026-07-01 11:43:57 wer:338] WER predicted:hiện ra tình phía xa
[NeMo I 2026-07-01 11:43:57 wer:336]

[NeMo I 2026-07-01 11:43:57 wer:337] WER reference:nên với thông tin này
[NeMo I 2026-07-01 11:43:57 wer:338] WER predicted:nên với thông tiền này
[NeMo I 2026-07-01 11:43:57 wer:336]

[NeMo I 2026-07-01 11:43:57 wer:337] WER reference:và dân dã như chính cái tên của nó
[NeMo I 2026-07-01 11:43:57 wer:338] WER predicted:và dân gia như chính cái tình của nó
[NeMo I 2026-07-01 11:43:58 wer:336]

[NeMo I 2026-07-01 11:43:58 wer:337] WER reference:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 11:43:58 wer:338] WER predicted:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 11:43:58 wer:336]

[NeMo I 2026-07-01 11:43:58 wer:337] WER reference:sau nhiều pha hảm thành liên tục
[NeMo I 2026-07-01 11:43:58 wer:338] WER predicted:sau nhiều phá h thành liên tốt
[NeMo I 2026-07-01 11:43:58 wer:336]

[NeMo I 2026-07-01 11:43:58 wer:337] WER reference:anh vẫn nhớ kỷ niệm cầu đầu lâu
[NeMo I 2026-07-01 11:43:58 wer:338] WER predicted:anh vẫn như kỳiềm cầu đầu lâu
[NeMo I 2026-07-01 11:43:58 wer:336]

[NeMo I 2026-07-01 11:43:58 wer:337] WER reference:gay go lắm nhưng hoàng anh gia lai sẽ làm được
[NeMo I 2026-07-01 11:43:58 wer:338] WER predicted:g g có làm nhưng hơn anh gia là sẽ làm được
[NeMo I 2026-07-01 11:43:58 wer:336]

[NeMo I 2026-07-01 11:43:58 wer:337] WER reference:do đó khi chơi chung với bạn bè cùng lứa chúng thường tỏ ra thiếu tự tin
[NeMo I 2026-07-01 11:43:58 wer:338] WER predicted:do đó khi tr chơi chúng với bạn bé cũng lư chúng ta thường tôi cả thiếu từ tình
[NeMo I 2026-07-01 11:43:58 wer:336]

[NeMo I 2026-07-01 11:43:58 wer:337] WER reference:mối đục luỗng cả tấm gỗ
[NeMo I 2026-07-01 11:43:58 wer:338] WER predicted:mới được luôn các t tâm g
[NeMo I 2026-07-01 11:43:58 wer:336]

[NeMo I 2026-07-01 11:43:58 wer:337] WER reference:người ta cho rằng trung tâm này có khả năng ảnh hưởng đến quá trình lão hóa
[NeMo I 2026-07-01 11:43:58 wer:338] WER predicted:người ta cho rằng trong tâm này có khá năng anh hướng đến quá trên lâu hoa
[NeMo I 2026-07-01 11:43:58 wer:336]

[NeMo I 2026-07-01 11:43:58 wer:337] WER reference:các giò phong lan tháng ba cũng không chịu yên mình
[NeMo I 2026-07-01 11:43:58 wer:338] WER predicted:các cho phòng lên tha bà cũng công chịu ý mình
[NeMo I 2026-07-01 11:43:58 wer:336]

[NeMo I 2026-07-01 11:43:58 wer:337] WER reference:hãy cho tôi quyền năng vô tận để bảo vệ loài vật
[NeMo I 2026-07-01 11:43:58 wer:338] WER predicted:hay cho tôi viên năng v vụ tăng để báo vềỗi vật
[NeMo I 2026-07-01 11:43:58 wer:336]

[NeMo I 2026-07-01 11:43:58 wer:337] WER reference:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 11:43:58 wer:338] WER predicted:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 11:43:58 wer:336]

[NeMo I 2026-07-01 11:43:58 wer:337] WER reference:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 11:43:58 wer:338] WER predicted:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 11:43:58 wer:336]

[NeMo I 2026-07-01 11:43:58 wer:337] WER reference:sáng chiều hội diễn tiếng hát bảo minh do công ty bảo hiểm bảo minh tổ chức
[NeMo I 2026-07-01 11:43:58 wer:338] WER predicted:sáng chịu họ diễn tiếng khác đầu mình do công ty bảo em báo mình tôi chức
[NeMo I 2026-07-01 11:43:58 wer:336]

[NeMo I 2026-07-01 11:43:58 wer:337] WER reference:cô nằm thiếp đi lúc nào không biết
[NeMo I 2026-07-01 11:43:58 wer:338] WER predicted:cô năm tiếp đi lúc nào không biết
[NeMo I 2026-07-01 11:43:58 wer:336]

[NeMo I 2026-07-01 11:43:58 wer:337] WER reference:mười bảy mười tám mười chín
[NeMo I 2026-07-01 11:43:58 wer:338] WER predicted:mươi bảy mươi tám mươi chín
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:tích cóp đủ thứ đồ lạc xon những ngọn đèn
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:tiếp cấpưa thứ đồ đ đã số nhữngọ đến
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:nhưng đất nước đã chọn một nhà lãnh đạo khác
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:nhưng được nước đã chọn một nhà là đầu khác
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:ưu thế này có được là nhờ quá trình cơ giới hóa nhanh sử dụng phân bón cho dù hậu quả có là
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:uống thế này có được là nhớ quá trình cơ giới hoa nhanh sự dụng phần bốn cho dụnghầu quá có là
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:thường xuyên xảy ra hiện tượng đạo văn quỵt nhuận bút
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:thường xuyên x ra hiện thường đầu văn quyết nhút
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:chỉ cho chúng tôi xem hàng đống gạch đá cát sỏi
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:chỉ cho chúng tôi xem hàng đồng các đã các số
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:đối với cảng hàng không quốc tế đà nẵng sử dụng nhà ga hành khách hiện hữu làm nhà ga nội địa
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:đối với càng hàng không quốc tế đã năng sự dụng nhà cả hành khách hiện hồ làm nhà cả nói để
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:người giàu thì vác nặng những xâu tiền kẽm trên vai
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:ngườiào thì phátắc những sau tiềnk trên phải
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:các nữ công nhân làm ca đêm
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:các nữ công nhân làm cả điểm
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:tui biết bà giỏi rồi
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:tôi biết ba d rồi
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:đưa một chú bồ câu bay đi bay về
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:đường một chú bộ cầu bảy đi bị về
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:tôi đến kiểm tra và phát hiện thấy ông và cô gái nằm kia thám tử ra hiệu cho ngài triệu phú nhìn vào phòng tắm cô ta đã chết
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:tôi đến kiểm ra và phát hiện thấy ông và cô gái nămk tâm từ ra hiểu cho ngày chịu phương nhìn vào phòng tâm cô đã chết
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:để thực hiện thắng lợi kế hoạch năm năm
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:để thực hiện thân lại cái hết năm năm
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:trước khi hóa thân thành cộng hòa sét để đến bồ đào nha
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:trước khi hoa thân thành có hoa sức để đến bộ động nhà
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:tuy nhiên tôi không chắc những người chưa từng đọc cuốn nhật ký có thể hiểu hết được ý nghĩa bộ phim
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:tuy nhiên tôi không chắc những người chưa từ đọc cũng nhất kỳ có thể hiểu hết được ý nghĩ bộ phim
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:chi đầu tư từ khu vực nhà nước còn lớn và hiệu quả thấp
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:chỉ đầu tư từ khu vực nhà n nước còn lớn và hiệu quá hợp
[NeMo I 2026-07-01 11:43:59 wer:336]

[NeMo I 2026-07-01 11:43:59 wer:337] WER reference:cái nền xưa của nó bây giờ là một cái hố nông choèn
[NeMo I 2026-07-01 11:43:59 wer:338] WER predicted:cái nên s của nó bị giờ là một cái hồ năm tr
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:giải truyền thông điện ảnh trung quốc là giải thưởng điện ảnh duy nhất xét trao cho tất cả các bộ phim hoa ngữ
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:dài trên thường đến anh chúng quốc là dài thường đến anh gì sẽ cho cho tất cả các bộ hiện hoànư
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:dự đoán ba tháng nữa giá cà phê sẽ tăng gấp đôi hiện nay
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:điều rằng bà tháng nữa giá và về sự tăng gặp đôi hiện này
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:họ đến đây vì nhiều mục đích
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:họ đến đâyì nhiều mộtích
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:vậy trước đây nông dân đối phó với hiện tượng này như thế nào thưa ông
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:vậy trước này n năm nhân đối phố v với hiện từ này như đến nào thu  ông
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:làm sao để có tiền nhanh nhất
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:làm sao để có tiền nhân nh nhất
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:đùi dang ra ngoài
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:được gian ra ngoài
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:đã hai lần cô gác lại ước mơ vào đời và cũng đã ít nhiều trải qua những thăng trầm xô bồ của cuộc sống
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:đã hai l lần cô gái lạiút mới vào đời và cũng đã ít nhiều trái quá những thân tr số bộ của của sống
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:trong bối cảnh như vậy một phản ứng chính sách đối với vấn đề thất nghiệp đang là đòi hỏi cấp bách hiện nay
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:trong bộ cảnh như vậy một phầnững chính sách đối với vẫn để nghiệpp đang là để họ các cách hiện này
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:ở xứ sở chuột túi
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:ở s sự tr chủ tôi
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:do vậy dựa trên cơ sở nào mà ông khoa phát biểu như vậy
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:do vậy dự trên cơ s nào ông hoa phát biểu như vậy
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:tá tàng
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:ta tăng
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:cách đây tám năm nhưng trước đó khoảng hai năm đã được mời đóng phim và có nhiều vai chính trong các phim điện ảnh truyền hình
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:cách đây tâm năm những trước đó hoàn hai năm đã được mới động phim và có nhiều và chính trong các phim điện anh truyền hình
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:đã thăm hỏi thì thế nào cũng phải có quà cáp
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:đã tâmm họ thì thế nào cũng phải có quả các
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:có mặt tạià điện phòng
[NeMo I 2026-07-01 11:44:00 wer:336]

[NeMo I 2026-07-01 11:44:00 wer:337] WER reference:em lơ đễnh lật xem vài tờ báo
[NeMo I 2026-07-01 11:44:00 wer:338] WER predicted:em là điện l xem vàờ báo
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:và không ít người cứ tì tì uống từ sáng đến tối suốt mấy ngày hội nghị
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:và không ít người cứ ty từ  uống từ sáng đến tôi xuất máy ngày hội này
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:minh châu vào miền nam công tác tại nhà hát trần hữu trang
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:mình cao vào m nam công tất tại nhà ho rằng h rằng
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:hết chiến tranh quê hương im tiếng súng anh lính cụ hồ lại trở về với đời thường tham gia sản xuất xây dựng và bảo vệ đất nước
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:hết tiếng trên với hơn ý tiếng xuống anh lên của hội lại cho về với đời thường tha giá sẽ xuất sẽ dững và b và đất nước
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:chuyến đi đó đến giờ vẫn là một ám ảnh trong ký ức tôi
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:chỉ đi đó đến giờ vẫn là một ông anh trong chỉ
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:ây da ây da
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:giá gia
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:có rất nhiều vệ tinh bị rơi khỏi quỹ đạo
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:nhiều về tính bị rồi khó quy nào
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:nhuốm đầy máu của thổ dân châu mỹ
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:dụng đây máu của thu dân cho mỹ
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:cụ thể về đất đai xây dựng văn hóa thuộc về từng ngành riêng biệt
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:cô thể về đất đây văn sẽ những văn hoa thuốc về từ ngành riêng biết
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:tôi muốn hỏi liệu có mùi hương sen nhân tạo là một loại hóa chất không
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:tôi mua hỏi liệu có người hướng s nhân tạo là một loại họ chắc cao
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:cả nhà bà ngoại cười nắc nẻ vì câu nói ngây ngô của con
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:các nhà bao ngoài người nước ngheì cô nói ngày ngồi của con
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:xin được chân khuân vác
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:xin được trên khu phát
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:nằm khuất dưới tàn tre sát bờ sông châu
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:ho giới đang trẻ sẽ bà sống ch
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:nếu kiên cố hóa thì vốn được đưa thẳng cho dân sẽ không thất thoát
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:nếu ki cô hoa thì bốn đượcưa tăng cho dân sẽ không thật
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:nói chung cô hồng nào cũng có một số phận hoàn cảnh và cuộc đời riêng
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:nói chúng cô học nào cũng có một số phần hoàn cảnh với cuộc đời riêng
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:nhưng tất cả những điều ấy chẳng mấy khi đi liền với nhau
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:những tất cả những điều ấy ch mấy khi đi liên với nhau
[NeMo I 2026-07-01 11:44:01 wer:336]

[NeMo I 2026-07-01 11:44:01 wer:337] WER reference:như vậy là bạn có thể sử dụng được nhiều số điện thoại của nhiều nhà cung cấp dịch vụ chỉ trên một sim
[NeMo I 2026-07-01 11:44:01 wer:338] WER predicted:như vậy bạn có thể sự dụng được nhiều số đến th của như nhà cũng cấp dịch vụ chỉ trên một xem
[NeMo I 2026-07-01 11:44:02 wer:336]

[NeMo I 2026-07-01 11:44:02 wer:337] WER reference:trong trường hợp hai bên có thỏa thuận lại không yêu cầu trọng tài giải quyết nữa thì có quyền kiện ra tòa án
[NeMo I 2026-07-01 11:44:02 wer:338] WER predicted:trong trường hợp hai bên có thể thường lại không yêu cầu trong ta d quyết nữa thì có viên kiến ra toàn ăn
[NeMo I 2026-07-01 11:44:02 wer:336]

[NeMo I 2026-07-01 11:44:02 wer:337] WER reference:kiểu này chắc phải cắt giảm biên chế
[NeMo I 2026-07-01 11:44:02 wer:338] WER predicted:chưa này chắc phải các giá biến chế
[NeMo I 2026-07-01 11:44:02 wer:336]

[NeMo I 2026-07-01 11:44:02 wer:337] WER reference:nhưng tôi không yêu cô cô biết rõ điều đó mà
[NeMo I 2026-07-01 11:44:02 wer:338] WER predicted:nhưng tôi không yêu cô cô biết rồi điều đó mà
[NeMo I 2026-07-01 11:44:02 wer:336]

[NeMo I 2026-07-01 11:44:02 wer:337] WER reference:khó mà đoán trước chính xác kết quả khi quả bóng còn lăn
[NeMo I 2026-07-01 11:44:02 wer:338] WER predicted:không mà đó trước chính sẽ kết qua khi qua b con
[NeMo I 2026-07-01 11:44:02 wer:336]

[NeMo I 2026-07-01 11:44:02 wer:337] WER reference:vừa nhìn thấy sự xuất hiện của bố tất cả mấy thằng khác vùng bỏ chạy sạch
[NeMo I 2026-07-01 11:44:02 wer:338] WER predicted:ừa nh thấy sự sự hiện của bố tất cả máy th thành khác vùng bỏi trẻ sách
[NeMo I 2026-07-01 11:44:02 wer:336]

[NeMo I 2026-07-01 11:44:02 wer:337] WER reference:phải nâng cao khả năng cạnh tranh của nền kinh tế
[NeMo I 2026-07-01 11:44:02 wer:338] WER predicted:phải năng cao hình năng cảnh trên của nên kinh tên
[NeMo I 2026-07-01 11:44:02 wer:336]

[NeMo I 2026-07-01 11:44:02 wer:337] WER reference:bà thường lấy ý tưởng cho các tác phẩm từ đâu
[NeMo I 2026-07-01 11:44:02 wer:338] WER predicted:bà thườngấy ý từ cho các tác phẩm từ đồng
[NeMo I 2026-07-01 11:44:02 wer:336]

[NeMo I 2026-07-01 11:44:02 wer:337] WER reference:khi chứng kiến người vợ lăng loàn
[NeMo I 2026-07-01 11:44:02 wer:338] WER predicted:khi chứng kiến người vào l lần lòng
[NeMo I 2026-07-01 11:44:02 wer:336]

[NeMo I 2026-07-01 11:44:02 wer:337] WER reference:tác phẩm to lớn bằng đồng như tượng phật quỳnh lâm chuông quy điền tháp báo thiên vạc phổ minh an nam tứ đại khí
[NeMo I 2026-07-01 11:44:02 wer:338] WER predicted:ta phẩm ta lớn bạn đồng như thường phát qu làm chúng quy điện th bảo tìm và phố mình ăn năm tư đây khi
[NeMo I 2026-07-01 11:44:02 wer:336]

[NeMo I 2026-07-01 11:44:02 wer:337] WER reference:ngoài ra họ vẫn còn muốn giữ chân cầu thủ xuất sắc nhất của mình
[NeMo I 2026-07-01 11:44:02 wer:338] WER predicted:họ vẫn cầu muốnư chân cầu thủ xuất s
[NeMo I 2026-07-01 11:44:02 wer:336]

[NeMo I 2026-07-01 11:44:02 wer:337] WER reference:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 11:44:02 wer:338] WER predicted:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 11:44:02 wer:336]

[NeMo I 2026-07-01 11:44:02 wer:337] WER reference:và gã thệ bị điều về làm trưởng phòng xã hội huyện
[NeMo I 2026-07-01 11:44:02 wer:338] WER predicted:và cả thể biết điều về làm trường phần x hội h
[NeMo I 2026-07-01 11:44:02 wer:336]

[NeMo I 2026-07-01 11:44:02 wer:337] WER reference:là rút rỉa tiền của bạn càng nhiều càng tốt

[NeMo W 2026-07-01 11:44:17 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 11:44:17 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

[best val_wer] epoch=4 val_wer=0.466250 exported=/kaggle/working/phase3_continue_best.nemo

Sample predictions after epoch 4:
  [0] REF: những con vật này đã bị giết và đốt
      HYP: nh con vật này đã bị gì vàốc
  [1] REF: phòng chống tham nhũng không được chủ quan cần làm liên tục đồng bộ và có các giải pháp
      HYP: phòng trong tham dụng không được chủ quan cần làm liên tục động bộ và có các lại pháp
  [2] REF: do vậy có máy cũng không thường dùng
      HYP: do vậy có mấy cũng không thường dụng
  [3] REF: mới khệnh khạng đứng lên đi ra
      HYP: mới kh khá đứng lên đi ra
  [4] REF: đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
      HYP: đây sẽ là cuộc gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
  [5] REF: sau một năm eo sèo
      HYP: sáu một năm yêu sẽ
  [6] REF: sau đó một vật lạ bay xợt ngang nóc nhà ông
      HYP: sau đó một và là bảy sự năng nốc nhau
  [7] REF: chín mươi hai chín mươi ba
      HYP: chín mươi hai chín mươi ba
  [8] REF: hiện ra tận phía xa
      HYP: hiện ra tình phía xa
  [9] REF: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã qua của thị trường
      HYP: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã quá của thì trường
[epoch] epoch=4/12 step=1256 val_loss=2.2475168704986572 val_wer=0.46624985337257385
[NeMo I 2026-07-01 11:44:48 wer:336]

[NeMo I 2026-07-01 11:44:48 wer:337] WER reference:rất nhiều trường hợp phụ huynh đau đầu vì con một đã tìm đến chuyên viên tư vấn tâm lý
[NeMo I 2026-07-01 11:44:48 wer:338] WER predicted:rất người trường học phụ kh đầu đầuì anh một đã tìm đến trên viên tư anh tâm lý
[NeMo I 2026-07-01 11:44:57 wer:336]

[NeMo I 2026-07-01 11:44:57 wer:337] WER reference:trước tình thế đó tôi buộc phải tìm cho mình một bến đỗ mới và tôi đã quyết định ra đi
[NeMo I 2026-07-01 11:44:57 wer:338] WER predicted:lúc tình thế đó tôi bộ phải tiền cho mình một bên đ đầu mới và tôi đã quyết định ra đây
[NeMo I 2026-07-01 11:45:05 wer:336]

[NeMo I 2026-07-01 11:45:05 wer:337] WER reference:tuy nhiên tình hình đó không diễn ra ở tất cả trường
[NeMo I 2026-07-01 11:45:05 wer:338] WER predicted:tuy nhiên tình hình đó không diễná ở tất các trường
[NeMo I 2026-07-01 11:45:14 wer:336]

[NeMo I 2026-07-01 11:45:14 wer:337] WER reference:nếu xét trên qui mô toàn tỉnh con số ấy vẫn còn khiêm tốn lắm
[NeMo I 2026-07-01 11:45:14 wer:338] WER predicted:để x chỉ phí mua toàn tình cầu sự ấy vẫn còn khiù làm
[NeMo I 2026-07-01 11:45:22 wer:336]

[NeMo I 2026-07-01 11:45:22 wer:337] WER reference:các vùng sâu vùng xa khó mà phát triển
[NeMo I 2026-07-01 11:45:22 wer:338] WER predicted:các vùng sau vùng sẽ khó mà phát triển
[NeMo I 2026-07-01 11:45:30 wer:336]

[NeMo I 2026-07-01 11:45:30 wer:337] WER reference:thì không hiểu sao ở phần thơ cổ đại
[NeMo I 2026-07-01 11:45:30 wer:338] WER predicted:thì không hiểu sao ở phần hết của đầy
[NeMo I 2026-07-01 11:45:39 wer:336]

[NeMo I 2026-07-01 11:45:39 wer:337] WER reference:anh muốn thùy có thể tự do tìm cho mình một hạnh phúc khác tràn đầy
[NeMo I 2026-07-01 11:45:39 wer:338] WER predicted:anh muốn thời có thể từ do tìm cho mình một thành phục khác cho lại
[NeMo I 2026-07-01 11:45:47 wer:336]

[NeMo I 2026-07-01 11:45:47 wer:337] WER reference:áo thun trắng sát nách
[NeMo I 2026-07-01 11:45:47 wer:338] WER predicted:ở thu trang sát nhất
[NeMo I 2026-07-01 11:45:56 wer:336]

[NeMo I 2026-07-01 11:45:56 wer:337] WER reference:đây cũng là giai đoạn thị trường nhiều biến cố nhất
[NeMo I 2026-07-01 11:45:56 wer:338] WER predicted:đây cũng là chế đồng thì trường nhiều biến cô nhất
[NeMo I 2026-07-01 11:46:04 wer:336]

[NeMo I 2026-07-01 11:46:04 wer:337] WER reference:mới thành món ngon và độc đáo
[NeMo I 2026-07-01 11:46:04 wer:338] WER predicted:mới thành món ngon và được đâu
[NeMo I 2026-07-01 11:46:12 wer:336]

[NeMo I 2026-07-01 11:46:12 wer:337] WER reference:người đẹp không thiếu chỉ sợ ông anh không có tiền
[NeMo I 2026-07-01 11:46:12 wer:338] WER predicted:người để không thiếu chỉ s ông anh không có tình
[NeMo I 2026-07-01 11:46:21 wer:336]

[NeMo I 2026-07-01 11:46:21 wer:337] WER reference:ngày thường chù ụ thì được
[NeMo I 2026-07-01 11:46:21 wer:338] WER predicted:ngày thường chủ ông gì được
[NeMo I 2026-07-01 11:46:29 wer:336]

[NeMo I 2026-07-01 11:46:29 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 11:46:29 wer:338] WER predicted:có mặt tại sẽ điện phương
[NeMo I 2026-07-01 11:46:38 wer:336]

[NeMo I 2026-07-01 11:46:38 wer:337] WER reference:tôi cũng biết có những tiêu cực trong giáo dục và nhà trường cũng như những lĩnh vực khác của xã hội
[NeMo I 2026-07-01 11:46:38 wer:338] WER predicted:tôi cũng biết có những tiêu thực trong giá được và nhà trường cũng như những lên với h của xã hội
[NeMo I 2026-07-01 11:46:46 wer:336]

[NeMo I 2026-07-01 11:46:46 wer:337] WER reference:xắn quần vượt qua là bước vào thế giới
[NeMo I 2026-07-01 11:46:46 wer:338] WER predicted:sống qu v qua là bước vào thời giới
[NeMo I 2026-07-01 11:46:55 wer:336]

[NeMo I 2026-07-01 11:46:55 wer:337] WER reference:mới và cải tiến
[NeMo I 2026-07-01 11:46:55 wer:338] WER predicted:mới và cái tiền
[NeMo I 2026-07-01 11:47:03 wer:336]

[NeMo I 2026-07-01 11:47:03 wer:337] WER reference:hai vợ chồng thị tớn và văn đục
[NeMo I 2026-07-01 11:47:03 wer:338] WER predicted:hai vợ trong thì từ và văn được
[NeMo I 2026-07-01 11:47:12 wer:336]

[NeMo I 2026-07-01 11:47:12 wer:337] WER reference:chợ đêm ca ba dành cho những người đang vào mùa tăng ca cuối năm
[NeMo I 2026-07-01 11:47:12 wer:338] WER predicted:ở đến và ba danh cho nh người đang vào một ta cả cứ năm
[NeMo I 2026-07-01 11:47:20 wer:336]

[NeMo I 2026-07-01 11:47:20 wer:337] WER reference:hai mươi hai mươi mốt
[NeMo I 2026-07-01 11:47:20 wer:338] WER predicted:hai mươi hai mươi mốt
[NeMo I 2026-07-01 11:47:29 wer:336]

[NeMo I 2026-07-01 11:47:29 wer:337] WER reference:anh không thể quên được những giây phút ngọt ngào ấy
[NeMo I 2026-07-01 11:47:29 wer:338] WER predicted:anh không được qu được nh ph gì ngọ nào ấy
[NeMo I 2026-07-01 11:47:37 wer:336]

[NeMo I 2026-07-01 11:47:37 wer:337] WER reference:đưa tới tình trạng phá sản
[NeMo I 2026-07-01 11:47:37 wer:338] WER predicted:ưa tư tiền r phá sản
[NeMo I 2026-07-01 11:47:45 wer:336]

[NeMo I 2026-07-01 11:47:45 wer:337] WER reference:phụ huynh và học sinh đang phải è cổ vì sách giá cao
[NeMo I 2026-07-01 11:47:45 wer:338] WER predicted:vụ qu và học sinh đang phải em cô vì sách gia cao
[NeMo I 2026-07-01 11:47:54 wer:336]

[NeMo I 2026-07-01 11:47:54 wer:337] WER reference:thỉnh thoảng lại có người ghép thận trước đó trở qua xin xét nghiệm vì có trục trặc
[NeMo I 2026-07-01 11:47:54 wer:338] WER predicted:tình toàn lại có người gằ tư gặp tôi qua sinh sẽ nhiều về cóục đọc
[NeMo I 2026-07-01 11:48:02 wer:336]

[NeMo I 2026-07-01 11:48:02 wer:337] WER reference:cuộc thi nhằm trau dồi niềm đam mê
[NeMo I 2026-07-01 11:48:02 wer:338] WER predicted:cuộc thế nh tr d nhiệm đã mẹ
[NeMo I 2026-07-01 11:48:11 wer:336]

[NeMo I 2026-07-01 11:48:11 wer:337] WER reference:đề thi môn vẽ thông thường là về vẽ trang trí sản phẩm vật thể
[NeMo I 2026-07-01 11:48:11 wer:338] WER predicted:để thi muốn vẻ hô thường là về về sáng chỉ sáng phẩm một thể
[NeMo I 2026-07-01 11:48:19 wer:336]

[NeMo I 2026-07-01 11:48:19 wer:337] WER reference:bước vào một mối tình
[NeMo I 2026-07-01 11:48:19 wer:338] WER predicted:bước vào một mua tình
[NeMo I 2026-07-01 11:48:28 wer:336]

[NeMo I 2026-07-01 11:48:28 wer:337] WER reference:lão nạp chỉ có nhiêu đây thôi
[NeMo I 2026-07-01 11:48:28 wer:338] WER predicted:là ôngạ chỉ có như lại tôi
[NeMo I 2026-07-01 11:48:36 wer:336]

[NeMo I 2026-07-01 11:48:36 wer:337] WER reference:hai tuần sau
[NeMo I 2026-07-01 11:48:36 wer:338] WER predicted:hai cũng sáu
[NeMo I 2026-07-01 11:48:45 wer:336]

[NeMo I 2026-07-01 11:48:45 wer:337] WER reference:những ngày cuối cùng trên dương thế
[NeMo I 2026-07-01 11:48:45 wer:338] WER predicted:những này cuối cùng trên dân thế
[NeMo I 2026-07-01 11:48:53 wer:336]

[NeMo I 2026-07-01 11:48:53 wer:337] WER reference:trên nhiều tuyến phố công nhân đang hối hả dọn dẹp
[NeMo I 2026-07-01 11:48:53 wer:338] WER predicted:trên nhiều tiếng ph công nh đang hội hay động nghiệpp
[NeMo I 2026-07-01 11:49:02 wer:336]

[NeMo I 2026-07-01 11:49:02 wer:337] WER reference:có trường hợp bất hợp pháp như trần thị thu h
[NeMo I 2026-07-01 11:49:02 wer:338] WER predicted:có chuyện học bất học pháp như trong thì thu
[NeMo I 2026-07-01 11:49:10 wer:336]

[NeMo I 2026-07-01 11:49:10 wer:337] WER reference:nhưng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được các khó khăn đó
[NeMo I 2026-07-01 11:49:10 wer:338] WER predicted:chúng tôi nghĩ r nếu có quyết tâm cao thì sẽ giải quyết được cả khó không đó
[NeMo I 2026-07-01 11:49:19 wer:336]

[NeMo I 2026-07-01 11:49:19 wer:337] WER reference:lúc đó em không thể tiếp tục công việc đánh cá của cha một mình vì còn quá nhỏ
[NeMo I 2026-07-01 11:49:19 wer:338] WER predicted:lúc đó em không phải tiếp được không việc đến các của chà một mình việc còn qua nhỏ
[NeMo I 2026-07-01 11:49:27 wer:336]

[NeMo I 2026-07-01 11:49:27 wer:337] WER reference:cuốn sách nói về sự lầm lẫn giữa luật kinh tế ở châu âu và châu mỹ kim vẫn chưa đọc tới vì cô không quan tâm đến luật
[NeMo I 2026-07-01 11:49:27 wer:338] WER predicted:cũng sinh nói về làm lần nhiều được ki thế ở ch ông và trong muốn cho vẫn chưa đọc tôi việc của không quan tăng đến luật
[NeMo I 2026-07-01 11:49:35 wer:336]

[NeMo I 2026-07-01 11:49:35 wer:337] WER reference:khi tên lửa bay lên
[NeMo I 2026-07-01 11:49:35 wer:338] WER predicted:khi tên l lời vậyi lên
[NeMo I 2026-07-01 11:49:44 wer:336]

[NeMo I 2026-07-01 11:49:44 wer:337] WER reference:mà theo thời gian sẽ tiệm cận với trí khôn của con người
[NeMo I 2026-07-01 11:49:44 wer:338] WER predicted:mà theo thời dân sẽ tìm cần với trí cũng của quốc con người
[NeMo I 2026-07-01 11:49:52 wer:336]

[NeMo I 2026-07-01 11:49:52 wer:337] WER reference:bên kia láng giềng của tôi hôm nay không thấy thăm hoa
[NeMo I 2026-07-01 11:49:52 wer:338] WER predicted:đến chỉ là diễn của tôi hô này không thấy th h
[NeMo I 2026-07-01 11:50:01 wer:336]

[NeMo I 2026-07-01 11:50:01 wer:337] WER reference:anh yêu cầu các cầu thủ phải đeo bám ngay khi đối phương có bóng
[NeMo I 2026-07-01 11:50:01 wer:338] WER predicted:anh nhiều cầu các cầu số phảieo bạn ngày khi đối phương có
[NeMo I 2026-07-01 11:50:09 wer:336]

[NeMo I 2026-07-01 11:50:09 wer:337] WER reference:ngay cả công an đi lẻ loi cũng bị tấn công vì trong khu vực này có một thứ luật riêng cấm người lạ vào
[NeMo I 2026-07-01 11:50:09 wer:338] WER predicted:nghe và không mình đi lẽ cũng bị không con việc trong có việc mẹ một thứ lực viên công như l
[NeMo I 2026-07-01 11:50:18 wer:336]

[NeMo I 2026-07-01 11:50:18 wer:337] WER reference:thì chúng sẽ nằm trong tầm kiểm soát của bạn
[NeMo I 2026-07-01 11:50:18 wer:338] WER predicted:thì chúng sẽ năm trong làmm kiể sau của bạn
[NeMo I 2026-07-01 11:50:26 wer:336]

[NeMo I 2026-07-01 11:50:26 wer:337] WER reference:đó là hai con sói hoàn toàn trái ngược nhau về hình thức
[NeMo I 2026-07-01 11:50:26 wer:338] WER predicted:đó là hay con s hộ còn chính được nhau về hình thức
[NeMo I 2026-07-01 11:50:35 wer:336]

[NeMo I 2026-07-01 11:50:35 wer:337] WER reference:trại đồng xã yên sở giữa một biển nước mênh mông ảnh nguyễn quân
[NeMo I 2026-07-01 11:50:35 wer:338] WER predicted:tr đồng x em s giờ một bịương mình m  anh nguyên quan
[NeMo I 2026-07-01 11:50:43 wer:336]

[NeMo I 2026-07-01 11:50:43 wer:337] WER reference:không sao rồi em mừng lắm
[NeMo I 2026-07-01 11:50:43 wer:338] WER predicted:không sao rồi em mình lăm
[NeMo I 2026-07-01 11:50:52 wer:336]

[NeMo I 2026-07-01 11:50:52 wer:337] WER reference:việc tòa án của pháp truy tố công dân một nước độc lập trên lãnh thổ quê hương của người ấy là một điều vô giá trị
[NeMo I 2026-07-01 11:50:52 wer:338] WER predicted:việc tôi ăn cuộc phát tr tốt người không một được được l trên l lên tôi cuối hơn còn ở ấy là một bị chú giá trị
[NeMo I 2026-07-01 11:51:00 wer:336]

[NeMo I 2026-07-01 11:51:00 wer:337] WER reference:bà mẹ nghèo đông con
[NeMo I 2026-07-01 11:51:00 wer:338] WER predicted:và mẹ nghe vẫn con
[NeMo I 2026-07-01 11:51:09 wer:336]

[NeMo I 2026-07-01 11:51:09 wer:337] WER reference:lấy tĩnh chế động
[NeMo I 2026-07-01 11:51:09 wer:338] WER predicted:l lý tình cho đồng
[NeMo I 2026-07-01 11:51:17 wer:336]

[NeMo I 2026-07-01 11:51:17 wer:337] WER reference:mình mẩy tôi tuy đau đớn
[NeMo I 2026-07-01 11:51:17 wer:338] WER predicted:mình bảy tôi tuy đau đường
[NeMo I 2026-07-01 11:51:26 wer:336]

[NeMo I 2026-07-01 11:51:26 wer:337] WER reference:luôn ngẩng cao đầu sự khác biệt lớn nhất giữa người tự tin và người nhút nhát là gì
[NeMo I 2026-07-01 11:51:26 wer:338] WER predicted:luôn ngn cao đầu x khách người lớn nhỏ d người từ tiếng biết và người nh nhấtạ là gì
[NeMo I 2026-07-01 11:51:34 wer:336]

[NeMo I 2026-07-01 11:51:34 wer:337] WER reference:với các bạn trẻ trên đây có vẻ tình yêu không phải là tất cả
[NeMo I 2026-07-01 11:51:34 wer:338] WER predicted:với các bạn trẻ chính đây có về tình yêu kh và là t cả
[NeMo I 2026-07-01 11:51:43 wer:336]

[NeMo I 2026-07-01 11:51:43 wer:337] WER reference:nếu trẻ bú không đủ có thể vắt sữa và cho trẻ uống bằng muỗng
[NeMo I 2026-07-01 11:51:43 wer:338] WER predicted:như trẻ vụ không đủ có thể biết s và tr trẻ  uống bằngôn
[NeMo I 2026-07-01 11:51:51 wer:336]

[NeMo I 2026-07-01 11:51:51 wer:337] WER reference:hãy để thời gian tìm hiểu thêm và thuyết phục gia đình
[NeMo I 2026-07-01 11:51:51 wer:338] WER predicted:hãy để thời gian để mỹ thêm phải thu phục gia đình
[NeMo I 2026-07-01 11:52:00 wer:336]

[NeMo I 2026-07-01 11:52:00 wer:337] WER reference:vân vân và vân vân
[NeMo I 2026-07-01 11:52:00 wer:338] WER predicted:v vẫn bốn và vẫn bốn
[NeMo I 2026-07-01 11:52:08 wer:336]

[NeMo I 2026-07-01 11:52:08 wer:337] WER reference:mà phụ nữ trong khu vực công đang gặp phải
[NeMo I 2026-07-01 11:52:08 wer:338] WER predicted:mà phụ nơi trong khu vực công đang g gặp phải
[NeMo I 2026-07-01 11:52:17 wer:336]

[NeMo I 2026-07-01 11:52:17 wer:337] WER reference:những năm trước phần lớn sếu ở kiên lương kiên giang
[NeMo I 2026-07-01 11:52:17 wer:338] WER predicted:những năm ch phần lên sẽ ở khi lớn ki gia
[NeMo I 2026-07-01 11:52:25 wer:336]

[NeMo I 2026-07-01 11:52:25 wer:337] WER reference:theo nguyên đào kinh tế đô thị
[NeMo I 2026-07-01 11:52:25 wer:338] WER predicted:theo nguyên đào ki tênưa thời
[NeMo I 2026-07-01 11:52:33 wer:336]

[NeMo I 2026-07-01 11:52:33 wer:337] WER reference:nhưng ngủ quá nhiều sẽ khiến bạn trở nên bơ phờ
[NeMo I 2026-07-01 11:52:33 wer:338] WER predicted:nhưng người quá nhiều sẽ khiến bạn trên đến b ph
[NeMo I 2026-07-01 11:52:42 wer:336]

[NeMo I 2026-07-01 11:52:42 wer:337] WER reference:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 11:52:42 wer:338] WER predicted:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 11:52:50 wer:336]

[NeMo I 2026-07-01 11:52:50 wer:337] WER reference:thường xuyên đối mặt với nạn khan hiếm lương thực
[NeMo I 2026-07-01 11:52:50 wer:338] WER predicted:thường x đối m với ăn khá hếm luôn thực
[NeMo I 2026-07-01 11:52:59 wer:336]

[NeMo I 2026-07-01 11:52:59 wer:337] WER reference:tôi có cảm tình với cô ấy nhưng tôi không muốn xen vào giữa họ
[NeMo I 2026-07-01 11:52:59 wer:338] WER predicted:tôi có cảm tình với cơ ấyững tôi không muốn xe vào d họ
[NeMo I 2026-07-01 11:53:07 wer:336]

[NeMo I 2026-07-01 11:53:07 wer:337] WER reference:với tôi chết là một sự ích kỷ còn bản chất sự sống đã là một bao dung ít nhất với chính mình
[NeMo I 2026-07-01 11:53:07 wer:338] WER predicted:với tôi ch là một sự kỳ công bạn chất sĩ sống đã một bao g biết nhất với chính mình
[NeMo I 2026-07-01 11:53:16 wer:336]

[NeMo I 2026-07-01 11:53:16 wer:337] WER reference:cậu không biết làm gì thì suốt đời cậu đúng là một kẻ hèn nhát
[NeMo I 2026-07-01 11:53:16 wer:338] WER predicted:cầu không biết làm gì thì xuất đời cầu đường là một các hàng nam
[NeMo I 2026-07-01 11:53:24 wer:336]

[NeMo I 2026-07-01 11:53:24 wer:337] WER reference:màu đen của những tấm cha
[NeMo I 2026-07-01 11:53:24 wer:338] WER predicted:màu đang của những tâm xe
[NeMo I 2026-07-01 11:53:33 wer:336]

[NeMo I 2026-07-01 11:53:33 wer:337] WER reference:tôi chỉ thấy người ta nhắc đến phượng vĩ tháng sáu hay cùng lắm là tháng năm
[NeMo I 2026-07-01 11:53:33 wer:338] WER predicted:tôi chỉ thấy ngườiáạ để phương với tình sau hai cũng tám là thành ra
[NeMo I 2026-07-01 11:53:41 wer:336]

[NeMo I 2026-07-01 11:53:41 wer:337] WER reference:với câu trả lời xuất sắc và gương mặt khả ái
[NeMo I 2026-07-01 11:53:41 wer:338] WER predicted:với cô cho lời sức s vàương một khá ai
[NeMo I 2026-07-01 11:53:50 wer:336]

[NeMo I 2026-07-01 11:53:50 wer:337] WER reference:nhưng em có biết rằng anh yêu em cũng bởi những lý do đó
[NeMo I 2026-07-01 11:53:50 wer:338] WER predicted:thì em có biết rằng anh như em cũng người nh lý do
[NeMo I 2026-07-01 11:53:58 wer:336]

[NeMo I 2026-07-01 11:53:58 wer:337] WER reference:để nhìn thấy sự khôi hài
[NeMo I 2026-07-01 11:53:58 wer:338] WER predicted:để nhìn thấy sự khu hai
[NeMo I 2026-07-01 11:54:07 wer:336]

[NeMo I 2026-07-01 11:54:07 wer:337] WER reference:rèm cửa phòng khách của bạn giống như cung điện
[NeMo I 2026-07-01 11:54:07 wer:338] WER predicted:ra c của phòng khách của bạn gi như cũng điện
[NeMo I 2026-07-01 11:54:15 wer:336]

[NeMo I 2026-07-01 11:54:15 wer:337] WER reference:và những khuyết điểm nhỏ của họ
[NeMo I 2026-07-01 11:54:15 wer:338] WER predicted:và những quyết điểm nhà của họ
[NeMo I 2026-07-01 11:54:23 wer:336]

[NeMo I 2026-07-01 11:54:23 wer:337] WER reference:tôi biết đây là quy tắc đòi hỏi
[NeMo I 2026-07-01 11:54:23 wer:338] WER predicted:tôi biết đây là quyết tác đòi hỏi
[NeMo I 2026-07-01 11:54:32 wer:336]

[NeMo I 2026-07-01 11:54:32 wer:337] WER reference:cũng trong ngày đó bài xã luận gằn giọng
[NeMo I 2026-07-01 11:54:32 wer:338] WER predicted:cũng trong ngày đó và sến g gi
[NeMo I 2026-07-01 11:54:40 wer:336]

[NeMo I 2026-07-01 11:54:40 wer:337] WER reference:bạn có thể ghé thăm nó
[NeMo I 2026-07-01 11:54:40 wer:338] WER predicted:bạn có thể g nghĩa tha nó
[NeMo I 2026-07-01 11:54:49 wer:336]

[NeMo I 2026-07-01 11:54:49 wer:337] WER reference:các anh sẽ mãi là những người con ưu tú của tổ quốc của nhân dân việt nam
[NeMo I 2026-07-01 11:54:49 wer:338] WER predicted:các anh xem hay là những người con của thủ tổ quốc của nhân dân việt nam
[NeMo I 2026-07-01 11:54:57 wer:336]

[NeMo I 2026-07-01 11:54:57 wer:337] WER reference:để luôn có một bình hoa tươi mới
[NeMo I 2026-07-01 11:54:57 wer:338] WER predicted:để luôn có một bệnh hoa tôi mới
[NeMo I 2026-07-01 11:55:05 wer:336]

[NeMo I 2026-07-01 11:55:05 wer:337] WER reference:chúc bạn đọc có thật nhiều thời gian thư giãn thoải mái
[NeMo I 2026-07-01 11:55:05 wer:338] WER predicted:trước bạn đó có thật nhiều thời gian thứ d ở tôiiá
[NeMo I 2026-07-01 11:55:14 wer:336]

[NeMo I 2026-07-01 11:55:14 wer:337] WER reference:bất chấp sự ngăn cản của cơ quan chức năng
[NeMo I 2026-07-01 11:55:14 wer:338] WER predicted:bập sự năng đang của cơ quan nước năng
[NeMo I 2026-07-01 11:55:22 wer:336]

[NeMo I 2026-07-01 11:55:22 wer:337] WER reference:chỉ có điều cô ta mang giày chiếc váy len dài bằng lông cừu
[NeMo I 2026-07-01 11:55:22 wer:338] WER predicted:chỉ có điều cuộc ta mang giảiiếc với l lên dài bằng l luônm cứ
[NeMo I 2026-07-01 11:55:31 wer:336]

[NeMo I 2026-07-01 11:55:31 wer:337] WER reference:thánh nhân đãi khù khờ chính là chỗ này
[NeMo I 2026-07-01 11:55:31 wer:338] WER predicted:thành nhân ra khu thời chỉ là chủ này
[NeMo I 2026-07-01 11:55:39 wer:336]

[NeMo I 2026-07-01 11:55:39 wer:337] WER reference:cô bé rất lấy làm vui mừng và làm quen với những nốt nhạc đầu tiên bằng chính chiếc đàn đồ chơi ấy
[NeMo I 2026-07-01 11:55:39 wer:338] WER predicted:có bé rất làm vui và làm quan với những nàyạ đầu tiên trên bạn chính ch đang được chơi ấy
[NeMo I 2026-07-01 11:55:47 wer:336]


Validation: |          | 0/? [00:00<?, ?it/s]

[NeMo I 2026-07-01 11:58:49 wer:336]

[NeMo I 2026-07-01 11:58:49 wer:337] WER reference:những con vật này đã bị giết và đốt
[NeMo I 2026-07-01 11:58:49 wer:338] WER predicted:nh con vật này đã bị gì và tốt
[NeMo I 2026-07-01 11:58:49 wer:336]

[NeMo I 2026-07-01 11:58:49 wer:337] WER reference:do vậy có máy cũng không thường dùng
[NeMo I 2026-07-01 11:58:49 wer:338] WER predicted:do vậy có mấy cũng không thường dụng
[NeMo I 2026-07-01 11:58:49 wer:336]

[NeMo I 2026-07-01 11:58:49 wer:337] WER reference:đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
[NeMo I 2026-07-01 11:58:49 wer:338] WER predicted:đây sẽ là cuộc gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
[NeMo I 2026-07-01 11:58:49 wer:336]

[NeMo I 2026-07-01 11:58:49 wer:337] WER reference:sau đó một vật lạ bay xợt ngang nóc nhà ông
[NeMo I 2026-07-01 11:58:49 wer:338] WER predicted:sau đó một và là bảy sự năng nốc nhau
[NeMo I 2026-07-01 11:58:49 wer:336]

[NeMo I 2026-07-01 11:58:49 wer:337] WER reference:hiện ra tận phía xa
[NeMo I 2026-07-01 11:58:49 wer:338] WER predicted:hiện ra tình phía xa
[NeMo I 2026-07-01 11:58:49 wer:336]

[NeMo I 2026-07-01 11:58:49 wer:337] WER reference:nên với thông tin này
[NeMo I 2026-07-01 11:58:49 wer:338] WER predicted:nên với thông tiền này
[NeMo I 2026-07-01 11:58:49 wer:336]

[NeMo I 2026-07-01 11:58:49 wer:337] WER reference:và dân dã như chính cái tên của nó
[NeMo I 2026-07-01 11:58:49 wer:338] WER predicted:và dân gia như chính cái trên của nó
[NeMo I 2026-07-01 11:58:49 wer:336]

[NeMo I 2026-07-01 11:58:49 wer:337] WER reference:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 11:58:49 wer:338] WER predicted:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 11:58:49 wer:336]

[NeMo I 2026-07-01 11:58:49 wer:337] WER reference:sau nhiều pha hảm thành liên tục
[NeMo I 2026-07-01 11:58:49 wer:338] WER predicted:sau nhiều phá h thành liên tục
[NeMo I 2026-07-01 11:58:49 wer:336]

[NeMo I 2026-07-01 11:58:49 wer:337] WER reference:anh vẫn nhớ kỷ niệm cầu đầu lâu
[NeMo I 2026-07-01 11:58:49 wer:338] WER predicted:anh vẫn nhớ kỳiềm cầu đầu lâu
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:gay go lắm nhưng hoàng anh gia lai sẽ làm được
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:g g có làm nhưng hơn anh gia là sẽ làm được
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:do đó khi chơi chung với bạn bè cùng lứa chúng thường tỏ ra thiếu tự tin
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:do đó khi tr chơi chúng với bạn bé cũng lư chúng ta thường tôi cả thiếu từ tính
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:mối đục luỗng cả tấm gỗ
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:mới được luôn cả t tâm g
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:người ta cho rằng trung tâm này có khả năng ảnh hưởng đến quá trình lão hóa
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:người ta cho rằng trong tâm này có khá năng anh hướng đến quá trên lâu hoa
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:các giò phong lan tháng ba cũng không chịu yên mình
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:các cho phòng lên tha ba cũng công chịu ý mình
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:hãy cho tôi quyền năng vô tận để bảo vệ loài vật
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:hay cho tôi viên năng v vụ tăng để báo về lo vật
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:sáng chiều hội diễn tiếng hát bảo minh do công ty bảo hiểm bảo minh tổ chức
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:sáng chịu họ diễn tiếng khác đầu mình do công ty bảo em báo mình tôi chức
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:cô nằm thiếp đi lúc nào không biết
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:cô năm tiếp đi lúc nào không biết
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:mười bảy mười tám mười chín
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:mươi bảy mươi tám mươi chín
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:tích cóp đủ thứ đồ lạc xon những ngọn đèn
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:tiếpốc đưa thứ đồ đ đã số nhữngọ đến
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:nhưng đất nước đã chọn một nhà lãnh đạo khác
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:nhưng được nước đã chọn một nhà lên đầu khác
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:ưu thế này có được là nhờ quá trình cơ giới hóa nhanh sử dụng phân bón cho dù hậu quả có là
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:uống thế này có được là nhớ quá trình cơ giới hoa nhanh sự dụng phần bốn cho dụnghầu quá có là
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:thường xuyên xảy ra hiện tượng đạo văn quỵt nhuận bút
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:thường xuyên x ra hiện thường đầu văn quyết nhút
[NeMo I 2026-07-01 11:58:50 wer:336]

[NeMo I 2026-07-01 11:58:50 wer:337] WER reference:chỉ cho chúng tôi xem hàng đống gạch đá cát sỏi
[NeMo I 2026-07-01 11:58:50 wer:338] WER predicted:chỉ cho chúng tôi xem hàng đồng các đã các số
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:đối với cảng hàng không quốc tế đà nẵng sử dụng nhà ga hành khách hiện hữu làm nhà ga nội địa
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:đối với càng hàng không quốc tế đã năng sự dụng nhà cả hành khách hiện hồ làm nhà cả nói để
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:người giàu thì vác nặng những xâu tiền kẽm trên vai
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:ngườiào thì phátắc những sau tiềnk trên phải
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:các nữ công nhân làm ca đêm
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:các nữ công nhân làm cả điểm
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:tui biết bà giỏi rồi
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:tôi biết ba d rồi
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:đưa một chú bồ câu bay đi bay về
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:đường một chú bộ cầu bảy đi bị v về
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:tôi đến kiểm tra và phát hiện thấy ông và cô gái nằm kia thám tử ra hiệu cho ngài triệu phú nhìn vào phòng tắm cô ta đã chết
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:tôi đến kiểm ra và phát hiện thấy ông và cô gái nămk tâm từ ra hiểu cho ngày chịu phương nhìn vào phòng t cô đã chết
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:để thực hiện thắng lợi kế hoạch năm năm
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:để thực hiện thân lại cái hết năm năm
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:trước khi hóa thân thành cộng hòa sét để đến bồ đào nha
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:trước khi hoa thân thành có hoa sức để đến bộ động nhà
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:tuy nhiên tôi không chắc những người chưa từng đọc cuốn nhật ký có thể hiểu hết được ý nghĩa bộ phim
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:tuy nhiên tôi không chắc những người chưa từ đọc cũng nhất kỳ có thể hiểu hết được ý nghĩ bộ phim
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:chi đầu tư từ khu vực nhà nước còn lớn và hiệu quả thấp
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:chỉ đầu tư từ khu vực nhà n nước còn lớn và hiệu quá hợp
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:cái nền xưa của nó bây giờ là một cái hố nông choèn
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:cái nên s của nó bị giờ là một cái hồ năm tr
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:giải truyền thông điện ảnh trung quốc là giải thưởng điện ảnh duy nhất xét trao cho tất cả các bộ phim hoa ngữ
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:giải trên thường đến anh chúng quốc là dài thường đến anh gì sẽ cho cho tất cả các bộ hiện hoànư
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:dự đoán ba tháng nữa giá cà phê sẽ tăng gấp đôi hiện nay
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:điều rằng bà tháng nữa giá và về sự tăng gặp đôi hiện này
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:họ đến đây vì nhiều mục đích
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:họ đến đâyì nhiều mộtích
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 11:58:51 wer:336]

[NeMo I 2026-07-01 11:58:51 wer:337] WER reference:vậy trước đây nông dân đối phó với hiện tượng này như thế nào thưa ông
[NeMo I 2026-07-01 11:58:51 wer:338] WER predicted:vậy trước này n năm nhân đối phố v với hiện từ này như đến nào thu  ông
[NeMo I 2026-07-01 11:58:52 wer:336]

[NeMo I 2026-07-01 11:58:52 wer:337] WER reference:làm sao để có tiền nhanh nhất
[NeMo I 2026-07-01 11:58:52 wer:338] WER predicted:làm sao để có tiền nhân nhất
[NeMo I 2026-07-01 11:58:52 wer:336]

[NeMo I 2026-07-01 11:58:52 wer:337] WER reference:đùi dang ra ngoài
[NeMo I 2026-07-01 11:58:52 wer:338] WER predicted:được gian ra ngoài
[NeMo I 2026-07-01 11:58:52 wer:336]

[NeMo I 2026-07-01 11:58:52 wer:337] WER reference:đã hai lần cô gác lại ước mơ vào đời và cũng đã ít nhiều trải qua những thăng trầm xô bồ của cuộc sống
[NeMo I 2026-07-01 11:58:52 wer:338] WER predicted:đã hai l lần cô gái lạiút mới vào đời và cũng đã ít nhiều trái qua những thân tr số bộ của cuộc sống
[NeMo I 2026-07-01 11:58:52 wer:336]

[NeMo I 2026-07-01 11:58:52 wer:337] WER reference:trong bối cảnh như vậy một phản ứng chính sách đối với vấn đề thất nghiệp đang là đòi hỏi cấp bách hiện nay
[NeMo I 2026-07-01 11:58:52 wer:338] WER predicted:trong bộ cảnh như vậy một phầnững chính sách đối với vẫn để nghiệp đang là để họ cách cách hiện này
[NeMo I 2026-07-01 11:58:52 wer:336]

[NeMo I 2026-07-01 11:58:52 wer:337] WER reference:ở xứ sở chuột túi
[NeMo I 2026-07-01 11:58:52 wer:338] WER predicted:ở s sơ tr chủ tôi
[NeMo I 2026-07-01 11:58:52 wer:336]

[NeMo I 2026-07-01 11:58:52 wer:337] WER reference:do vậy dựa trên cơ sở nào mà ông khoa phát biểu như vậy
[NeMo I 2026-07-01 11:58:52 wer:338] WER predicted:do vậy dự trên cơ s nào ông hoa phát biểu như vậy
[NeMo I 2026-07-01 11:58:52 wer:336]

[NeMo I 2026-07-01 11:58:52 wer:337] WER reference:tá tàng
[NeMo I 2026-07-01 11:58:52 wer:338] WER predicted:ta tăng
[NeMo I 2026-07-01 11:58:52 wer:336]

[NeMo I 2026-07-01 11:58:52 wer:337] WER reference:cách đây tám năm nhưng trước đó khoảng hai năm đã được mời đóng phim và có nhiều vai chính trong các phim điện ảnh truyền hình
[NeMo I 2026-07-01 11:58:52 wer:338] WER predicted:cách đây tâm năm những trước đó hoàn hai năm đã được mới động phim và có nhiều và chính trong các phim điện anh truyền hình
[NeMo I 2026-07-01 11:58:52 wer:336]

[NeMo I 2026-07-01 11:58:52 wer:337] WER reference:đã thăm hỏi thì thế nào cũng phải có quà cáp
[NeMo I 2026-07-01 11:58:52 wer:338] WER predicted:đã tâmm họ thì thế nào cũng phải có quả các
[NeMo I 2026-07-01 11:58:52 wer:336]

[NeMo I 2026-07-01 11:58:52 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 11:58:52 wer:338] WER predicted:có mặt tạià điện phòng
[NeMo I 2026-07-01 11:58:52 wer:336]

[NeMo I 2026-07-01 11:58:52 wer:337] WER reference:em lơ đễnh lật xem vài tờ báo
[NeMo I 2026-07-01 11:58:52 wer:338] WER predicted:em là điện l xem vàờ báo
[NeMo I 2026-07-01 11:58:52 wer:336]

[NeMo I 2026-07-01 11:58:52 wer:337] WER reference:và không ít người cứ tì tì uống từ sáng đến tối suốt mấy ngày hội nghị
[NeMo I 2026-07-01 11:58:52 wer:338] WER predicted:và không ít người cứ ty từ  uống từ sáng đến tôi xuất máy ngày hội này
[NeMo I 2026-07-01 11:58:52 wer:336]

[NeMo I 2026-07-01 11:58:52 wer:337] WER reference:minh châu vào miền nam công tác tại nhà hát trần hữu trang
[NeMo I 2026-07-01 11:58:52 wer:338] WER predicted:mình cao vào m nam công tất tại nhà ho rằng h rằng
[NeMo I 2026-07-01 11:58:52 wer:336]

[NeMo I 2026-07-01 11:58:52 wer:337] WER reference:hết chiến tranh quê hương im tiếng súng anh lính cụ hồ lại trở về với đời thường tham gia sản xuất xây dựng và bảo vệ đất nước
[NeMo I 2026-07-01 11:58:52 wer:338] WER predicted:hết tiếng trên với hơn ý tiếng xuống anh lên của hồ lại cho về với đời thường tha giá sản xuất sẽ d và b và đất nước
[NeMo I 2026-07-01 11:58:52 wer:336]

[NeMo I 2026-07-01 11:58:52 wer:337] WER reference:chuyến đi đó đến giờ vẫn là một ám ảnh trong ký ức tôi
[NeMo I 2026-07-01 11:58:52 wer:338] WER predicted:chỉ đi đó đến giờ vẫn là một ông anh trong chỉ
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:ây da ây da
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:giá gia
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:có rất nhiều vệ tinh bị rơi khỏi quỹ đạo
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:nhiều về tính bị rồi khó qu nào
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:nhuốm đầy máu của thổ dân châu mỹ
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:dụng đây máu của thu dân cho mỹ
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:cụ thể về đất đai xây dựng văn hóa thuộc về từng ngành riêng biệt
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:cô thể về đất đây văn sẽ những văn hoa thuốc về từ ngành riêng biết
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:tôi muốn hỏi liệu có mùi hương sen nhân tạo là một loại hóa chất không
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:tôi mua hỏi liệu có người hướng s nhân tạo là một loại họ chắc cao
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:cả nhà bà ngoại cười nắc nẻ vì câu nói ngây ngô của con
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:các nhà bao ngoài người nước ngheì cô nói ngày ngủ của con
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:xin được chân khuân vác
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:xin được chân khu phát
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:nằm khuất dưới tàn tre sát bờ sông châu
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:ho giới thành trẻ sẽ bà sống ch
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:nếu kiên cố hóa thì vốn được đưa thẳng cho dân sẽ không thất thoát
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:nếu ki cô hoa thì bốn đượcưa tăng cho dân sẽ không thật
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:nói chung cô hồng nào cũng có một số phận hoàn cảnh và cuộc đời riêng
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:nói chúng cô học nào cũng có một số phần hoàn cảnhnh với cuộc đời riêng
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:nhưng tất cả những điều ấy chẳng mấy khi đi liền với nhau
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:những tất cả những điều ấy ch mấy khi đi liên với nhau
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:như vậy là bạn có thể sử dụng được nhiều số điện thoại của nhiều nhà cung cấp dịch vụ chỉ trên một sim
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:như vậy bạn có thể sự dụng được nhiều số đến th của như nhà cũng cấp dịch vụ chỉ trên một xem
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:trong trường hợp hai bên có thỏa thuận lại không yêu cầu trọng tài giải quyết nữa thì có quyền kiện ra tòa án
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:trong trường hợp hai bên có thể thường lại không yêu cầu trong ta d quyết nữa thì có viên kiến ra toàn ăn
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:kiểu này chắc phải cắt giảm biên chế
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:chưa này chắc phải các giá biến chế
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:nhưng tôi không yêu cô cô biết rõ điều đó mà
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:nhưng tôi không yêu cô cô biết rồi điều đó mà
[NeMo I 2026-07-01 11:58:53 wer:336]

[NeMo I 2026-07-01 11:58:53 wer:337] WER reference:khó mà đoán trước chính xác kết quả khi quả bóng còn lăn
[NeMo I 2026-07-01 11:58:53 wer:338] WER predicted:khó mà đó trước chính sẽ kết qua khi qua b bóng con
[NeMo I 2026-07-01 11:58:54 wer:336]

[NeMo I 2026-07-01 11:58:54 wer:337] WER reference:vừa nhìn thấy sự xuất hiện của bố tất cả mấy thằng khác vùng bỏ chạy sạch
[NeMo I 2026-07-01 11:58:54 wer:338] WER predicted:ừa nh thấy sự sự hiện của bố tất cả máy th thành khác vùng bỏi trẻ sách
[NeMo I 2026-07-01 11:58:54 wer:336]

[NeMo I 2026-07-01 11:58:54 wer:337] WER reference:phải nâng cao khả năng cạnh tranh của nền kinh tế
[NeMo I 2026-07-01 11:58:54 wer:338] WER predicted:phải năng cao khá năng cảnh trên của nên kinh tên
[NeMo I 2026-07-01 11:58:54 wer:336]

[NeMo I 2026-07-01 11:58:54 wer:337] WER reference:bà thường lấy ý tưởng cho các tác phẩm từ đâu
[NeMo I 2026-07-01 11:58:54 wer:338] WER predicted:bà thườngấy ý từ cho các tác phẩm từ đồng
[NeMo I 2026-07-01 11:58:54 wer:336]

[NeMo I 2026-07-01 11:58:54 wer:337] WER reference:khi chứng kiến người vợ lăng loàn
[NeMo I 2026-07-01 11:58:54 wer:338] WER predicted:khi chứng kiến người vào l lần lòng
[NeMo I 2026-07-01 11:58:54 wer:336]

[NeMo I 2026-07-01 11:58:54 wer:337] WER reference:tác phẩm to lớn bằng đồng như tượng phật quỳnh lâm chuông quy điền tháp báo thiên vạc phổ minh an nam tứ đại khí
[NeMo I 2026-07-01 11:58:54 wer:338] WER predicted:ta phẩm ta lớn bạn đồng như tượng phát qu làm chúng qu điện th bảo tìm và phố mình ăn nam tư đây khi
[NeMo I 2026-07-01 11:58:54 wer:336]

[NeMo I 2026-07-01 11:58:54 wer:337] WER reference:ngoài ra họ vẫn còn muốn giữ chân cầu thủ xuất sắc nhất của mình
[NeMo I 2026-07-01 11:58:54 wer:338] WER predicted:họ vẫn cầu muốnư chân cầu thủ xuất s
[NeMo I 2026-07-01 11:58:54 wer:336]

[NeMo I 2026-07-01 11:58:54 wer:337] WER reference:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 11:58:54 wer:338] WER predicted:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 11:58:54 wer:336]

[NeMo I 2026-07-01 11:58:54 wer:337] WER reference:và gã thệ bị điều về làm trưởng phòng xã hội huyện
[NeMo I 2026-07-01 11:58:54 wer:338] WER predicted:và cả thể biết điều về làm trường phần xã hội h
[NeMo I 2026-07-01 11:58:54 wer:336]

[NeMo I 2026-07-01 11:58:54 wer:337] WER reference:là rút rỉa tiền của bạn càng nhiều càng tốt

[NeMo W 2026-07-01 11:59:09 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 11:59:09 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

[best val_wer] epoch=5 val_wer=0.459997 exported=/kaggle/working/phase3_continue_best.nemo

Sample predictions after epoch 5:
  [0] REF: những con vật này đã bị giết và đốt
      HYP: nh con vật này đã bị gì và tốt
  [1] REF: phòng chống tham nhũng không được chủ quan cần làm liên tục đồng bộ và có các giải pháp
      HYP: phòng trong tham dụng không được chủ quan cần làm liên tục động bộ và có các lại pháp
  [2] REF: do vậy có máy cũng không thường dùng
      HYP: do vậy có mấy cũng không thường dụng
  [3] REF: mới khệnh khạng đứng lên đi ra
      HYP: mới kh khá đứng lên đi ra
  [4] REF: đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
      HYP: đây sẽ là cuộc gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
  [5] REF: sau một năm eo sèo
      HYP: sáu một năm yêu sẽ
  [6] REF: sau đó một vật lạ bay xợt ngang nóc nhà ông
      HYP: sau đó một và là bảy sự năng nốc nhau
  [7] REF: chín mươi hai chín mươi ba
      HYP: chín mươi hai chín mươi ba
  [8] REF: hiện ra tận phía xa
      HYP: hiện ra tình phía xa
  [9] REF: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã qua của thị trường
      HYP: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã quá của thì trường
[epoch] epoch=5/12 step=1570 val_loss=2.210176467895508 val_wer=0.4599974453449249
[NeMo I 2026-07-01 11:59:29 wer:336]

[NeMo I 2026-07-01 11:59:29 wer:337] WER reference:rất nhiều trường hợp phụ huynh đau đầu vì con một đã tìm đến chuyên viên tư vấn tâm lý
[NeMo I 2026-07-01 11:59:29 wer:338] WER predicted:rất trường học ph phụ kh đâu đầuì anh một đã tìm đến trên viên tư anh tâm lý
[NeMo I 2026-07-01 11:59:39 wer:336]

[NeMo I 2026-07-01 11:59:39 wer:337] WER reference:trước tình thế đó tôi buộc phải tìm cho mình một bến đỗ mới và tôi đã quyết định ra đi
[NeMo I 2026-07-01 11:59:39 wer:338] WER predicted:lúc tình thế đó tôi bộ phải tiền cho mình một bên đ đầu mới và tôi đã quyết bệnh ra đi
[NeMo I 2026-07-01 11:59:47 wer:336]

[NeMo I 2026-07-01 11:59:47 wer:337] WER reference:tuy nhiên tình hình đó không diễn ra ở tất cả trường
[NeMo I 2026-07-01 11:59:47 wer:338] WER predicted:tuy nhiên tình hình đó không diễná ở tất các tr trường
[NeMo I 2026-07-01 11:59:56 wer:336]

[NeMo I 2026-07-01 11:59:56 wer:337] WER reference:nếu xét trên qui mô toàn tỉnh con số ấy vẫn còn khiêm tốn lắm
[NeMo I 2026-07-01 11:59:56 wer:338] WER predicted:nên x chỉ phí mua toàn tình cầu số ấy vẫn còn khiù làm
[NeMo I 2026-07-01 12:00:04 wer:336]

[NeMo I 2026-07-01 12:00:04 wer:337] WER reference:các vùng sâu vùng xa khó mà phát triển
[NeMo I 2026-07-01 12:00:04 wer:338] WER predicted:các vùng sau vùng sẽ khó mà phát triển
[NeMo I 2026-07-01 12:00:13 wer:336]

[NeMo I 2026-07-01 12:00:13 wer:337] WER reference:thì không hiểu sao ở phần thơ cổ đại
[NeMo I 2026-07-01 12:00:13 wer:338] WER predicted:thì không hiểu sao ở phần hết của đầy
[NeMo I 2026-07-01 12:00:21 wer:336]

[NeMo I 2026-07-01 12:00:21 wer:337] WER reference:anh muốn thùy có thể tự do tìm cho mình một hạnh phúc khác tràn đầy
[NeMo I 2026-07-01 12:00:21 wer:338] WER predicted:anh muốn thời có thể từ do tìm cho mình một thành ph khác cho lại
[NeMo I 2026-07-01 12:00:30 wer:336]

[NeMo I 2026-07-01 12:00:30 wer:337] WER reference:áo thun trắng sát nách
[NeMo I 2026-07-01 12:00:30 wer:338] WER predicted:áo thu trang sát nhất
[NeMo I 2026-07-01 12:00:40 wer:336]

[NeMo I 2026-07-01 12:00:40 wer:337] WER reference:đây cũng là giai đoạn thị trường nhiều biến cố nhất
[NeMo I 2026-07-01 12:00:40 wer:338] WER predicted:đây cũng là chế đồng thì trường nhiều biến cô nhất
[NeMo I 2026-07-01 12:00:48 wer:336]

[NeMo I 2026-07-01 12:00:48 wer:337] WER reference:mới thành món ngon và độc đáo
[NeMo I 2026-07-01 12:00:48 wer:338] WER predicted:mới thành món ng ngon và được đâu
[NeMo I 2026-07-01 12:00:57 wer:336]

[NeMo I 2026-07-01 12:00:57 wer:337] WER reference:người đẹp không thiếu chỉ sợ ông anh không có tiền
[NeMo I 2026-07-01 12:00:57 wer:338] WER predicted:người để không hiểu chỉ s ông anh không có tình
[NeMo I 2026-07-01 12:01:06 wer:336]

[NeMo I 2026-07-01 12:01:06 wer:337] WER reference:ngày thường chù ụ thì được
[NeMo I 2026-07-01 12:01:06 wer:338] WER predicted:ngày thường chủ ông sĩ được
[NeMo I 2026-07-01 12:01:15 wer:336]

[NeMo I 2026-07-01 12:01:15 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 12:01:15 wer:338] WER predicted:có mặt tại sẽ điện phương
[NeMo I 2026-07-01 12:01:24 wer:336]

[NeMo I 2026-07-01 12:01:24 wer:337] WER reference:tôi cũng biết có những tiêu cực trong giáo dục và nhà trường cũng như những lĩnh vực khác của xã hội
[NeMo I 2026-07-01 12:01:24 wer:338] WER predicted:tôi cũng biết có những tiêu thực trong giá được và nhà trường của như những lên với h của xã hội
[NeMo I 2026-07-01 12:01:33 wer:336]

[NeMo I 2026-07-01 12:01:33 wer:337] WER reference:xắn quần vượt qua là bước vào thế giới
[NeMo I 2026-07-01 12:01:33 wer:338] WER predicted:sống qu v ba là bước vào thời giới
[NeMo I 2026-07-01 12:01:42 wer:336]

[NeMo I 2026-07-01 12:01:42 wer:337] WER reference:mới và cải tiến
[NeMo I 2026-07-01 12:01:42 wer:338] WER predicted:mới và cái tiền
[NeMo I 2026-07-01 12:01:51 wer:336]

[NeMo I 2026-07-01 12:01:51 wer:337] WER reference:hai vợ chồng thị tớn và văn đục
[NeMo I 2026-07-01 12:01:51 wer:338] WER predicted:hai vợ trong thì từ và văn được
[NeMo I 2026-07-01 12:02:00 wer:336]

[NeMo I 2026-07-01 12:02:00 wer:337] WER reference:chợ đêm ca ba dành cho những người đang vào mùa tăng ca cuối năm
[NeMo I 2026-07-01 12:02:00 wer:338] WER predicted:ở đến và ba danh choững người đang vào một ta cả cứ năm
[NeMo I 2026-07-01 12:02:09 wer:336]

[NeMo I 2026-07-01 12:02:09 wer:337] WER reference:hai mươi hai mươi mốt
[NeMo I 2026-07-01 12:02:09 wer:338] WER predicted:hai mươi hai mươi mốt
[NeMo I 2026-07-01 12:02:18 wer:336]

[NeMo I 2026-07-01 12:02:18 wer:337] WER reference:anh không thể quên được những giây phút ngọt ngào ấy
[NeMo I 2026-07-01 12:02:18 wer:338] WER predicted:anh không được qu được nh ph gian ngọ nào ấy
[NeMo I 2026-07-01 12:02:26 wer:336]

[NeMo I 2026-07-01 12:02:26 wer:337] WER reference:đưa tới tình trạng phá sản
[NeMo I 2026-07-01 12:02:26 wer:338] WER predicted:ưa tư tiền r phá sản
[NeMo I 2026-07-01 12:02:35 wer:336]

[NeMo I 2026-07-01 12:02:35 wer:337] WER reference:phụ huynh và học sinh đang phải è cổ vì sách giá cao
[NeMo I 2026-07-01 12:02:35 wer:338] WER predicted:vụ qu và học sinh đang phải em cô vì sách gia cao
[NeMo I 2026-07-01 12:02:44 wer:336]

[NeMo I 2026-07-01 12:02:44 wer:337] WER reference:thỉnh thoảng lại có người ghép thận trước đó trở qua xin xét nghiệm vì có trục trặc
[NeMo I 2026-07-01 12:02:44 wer:338] WER predicted:tình toàn lại có người g thằ tư gặp tôi qua sinh sẽ nhiều về cóục đọc
[NeMo I 2026-07-01 12:02:53 wer:336]

[NeMo I 2026-07-01 12:02:53 wer:337] WER reference:cuộc thi nhằm trau dồi niềm đam mê
[NeMo I 2026-07-01 12:02:53 wer:338] WER predicted:cuộc thế nhm tr d nhiệm đã mẹ
[NeMo I 2026-07-01 12:03:02 wer:336]

[NeMo I 2026-07-01 12:03:02 wer:337] WER reference:đề thi môn vẽ thông thường là về vẽ trang trí sản phẩm vật thể
[NeMo I 2026-07-01 12:03:02 wer:338] WER predicted:để thi muốn v vẻ hô thường là về về sáng chỉ sáng phẩm một thể
[NeMo I 2026-07-01 12:03:10 wer:336]

[NeMo I 2026-07-01 12:03:10 wer:337] WER reference:bước vào một mối tình
[NeMo I 2026-07-01 12:03:10 wer:338] WER predicted:bước vào một mua tình
[NeMo I 2026-07-01 12:03:19 wer:336]

[NeMo I 2026-07-01 12:03:19 wer:337] WER reference:lão nạp chỉ có nhiêu đây thôi
[NeMo I 2026-07-01 12:03:19 wer:338] WER predicted:làạ chỉ có như lại tôi
[NeMo I 2026-07-01 12:03:28 wer:336]

[NeMo I 2026-07-01 12:03:28 wer:337] WER reference:hai tuần sau
[NeMo I 2026-07-01 12:03:28 wer:338] WER predicted:hai cũng sáu
[NeMo I 2026-07-01 12:03:36 wer:336]

[NeMo I 2026-07-01 12:03:36 wer:337] WER reference:những ngày cuối cùng trên dương thế
[NeMo I 2026-07-01 12:03:36 wer:338] WER predicted:những này cuối cùng trên dân thế
[NeMo I 2026-07-01 12:03:45 wer:336]

[NeMo I 2026-07-01 12:03:45 wer:337] WER reference:trên nhiều tuyến phố công nhân đang hối hả dọn dẹp
[NeMo I 2026-07-01 12:03:45 wer:338] WER predicted:trên nhiều tiếng ph công nh đang hội hay chọn nghiệpp
[NeMo I 2026-07-01 12:03:53 wer:336]

[NeMo I 2026-07-01 12:03:53 wer:337] WER reference:có trường hợp bất hợp pháp như trần thị thu h
[NeMo I 2026-07-01 12:03:53 wer:338] WER predicted:có chuyện học bất học pháp như trong thì thu
[NeMo I 2026-07-01 12:04:02 wer:336]

[NeMo I 2026-07-01 12:04:02 wer:337] WER reference:nhưng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được các khó khăn đó
[NeMo I 2026-07-01 12:04:02 wer:338] WER predicted:chúng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được cả khó không đó
[NeMo I 2026-07-01 12:04:10 wer:336]

[NeMo I 2026-07-01 12:04:10 wer:337] WER reference:lúc đó em không thể tiếp tục công việc đánh cá của cha một mình vì còn quá nhỏ
[NeMo I 2026-07-01 12:04:10 wer:338] WER predicted:lúc đó em không phải tiếp được không việc đến các của tra một mình việc còn qua nhỏ
[NeMo I 2026-07-01 12:04:19 wer:336]

[NeMo I 2026-07-01 12:04:19 wer:337] WER reference:cuốn sách nói về sự lầm lẫn giữa luật kinh tế ở châu âu và châu mỹ kim vẫn chưa đọc tới vì cô không quan tâm đến luật
[NeMo I 2026-07-01 12:04:19 wer:338] WER predicted:cũng sinh nói về làm lần nhiều được ki thế ở ch ông và trong muốn cho vẫn chưa đọc tôi việc của không quan tăng đến luật
[NeMo I 2026-07-01 12:04:27 wer:336]

[NeMo I 2026-07-01 12:04:27 wer:337] WER reference:khi tên lửa bay lên
[NeMo I 2026-07-01 12:04:27 wer:338] WER predicted:khi tên l lời vậy lên
[NeMo I 2026-07-01 12:04:36 wer:336]

[NeMo I 2026-07-01 12:04:36 wer:337] WER reference:mà theo thời gian sẽ tiệm cận với trí khôn của con người
[NeMo I 2026-07-01 12:04:36 wer:338] WER predicted:mà theo thời dân sẽ tìm cần với trí cũng quốc con người
[NeMo I 2026-07-01 12:04:44 wer:336]

[NeMo I 2026-07-01 12:04:44 wer:337] WER reference:bên kia láng giềng của tôi hôm nay không thấy thăm hoa
[NeMo I 2026-07-01 12:04:44 wer:338] WER predicted:đến chỉ là diễn của tôi hô này không thấy th h
[NeMo I 2026-07-01 12:04:53 wer:336]

[NeMo I 2026-07-01 12:04:53 wer:337] WER reference:anh yêu cầu các cầu thủ phải đeo bám ngay khi đối phương có bóng
[NeMo I 2026-07-01 12:04:53 wer:338] WER predicted:anh nhiều cầu các cầu số phảieo bạn ngày khi đối phương có
[NeMo I 2026-07-01 12:05:02 wer:336]

[NeMo I 2026-07-01 12:05:02 wer:337] WER reference:ngay cả công an đi lẻ loi cũng bị tấn công vì trong khu vực này có một thứ luật riêng cấm người lạ vào
[NeMo I 2026-07-01 12:05:02 wer:338] WER predicted:nghe và không mình đi lẽ cũng bị không con việc trong có việc mẹ một thứ lực viên công như l
[NeMo I 2026-07-01 12:05:10 wer:336]

[NeMo I 2026-07-01 12:05:10 wer:337] WER reference:thì chúng sẽ nằm trong tầm kiểm soát của bạn
[NeMo I 2026-07-01 12:05:10 wer:338] WER predicted:thì chúng sẽ n năm trong làmm kiể sau của bạn
[NeMo I 2026-07-01 12:05:19 wer:336]

[NeMo I 2026-07-01 12:05:19 wer:337] WER reference:đó là hai con sói hoàn toàn trái ngược nhau về hình thức
[NeMo I 2026-07-01 12:05:19 wer:338] WER predicted:đó là hay con s hộ còn chính được nhau về hình thức
[NeMo I 2026-07-01 12:05:27 wer:336]

[NeMo I 2026-07-01 12:05:27 wer:337] WER reference:trại đồng xã yên sở giữa một biển nước mênh mông ảnh nguyễn quân
[NeMo I 2026-07-01 12:05:27 wer:338] WER predicted:tr đồng xã em s giờ một bịứ mình món anh quyền quan
[NeMo I 2026-07-01 12:05:36 wer:336]

[NeMo I 2026-07-01 12:05:36 wer:337] WER reference:không sao rồi em mừng lắm
[NeMo I 2026-07-01 12:05:36 wer:338] WER predicted:không sao rồi em mình lăm
[NeMo I 2026-07-01 12:05:44 wer:336]

[NeMo I 2026-07-01 12:05:44 wer:337] WER reference:việc tòa án của pháp truy tố công dân một nước độc lập trên lãnh thổ quê hương của người ấy là một điều vô giá trị
[NeMo I 2026-07-01 12:05:44 wer:338] WER predicted:việc tôi ăn cuộc phát tr tốt người không một được được lập trên l lên tôi cuối hơn ng ở ấy là một bị chú giá trị
[NeMo I 2026-07-01 12:05:53 wer:336]

[NeMo I 2026-07-01 12:05:53 wer:337] WER reference:bà mẹ nghèo đông con
[NeMo I 2026-07-01 12:05:53 wer:338] WER predicted:và mẹ nghe vẫn con
[NeMo I 2026-07-01 12:06:01 wer:336]

[NeMo I 2026-07-01 12:06:01 wer:337] WER reference:lấy tĩnh chế động
[NeMo I 2026-07-01 12:06:01 wer:338] WER predicted:l liệu tình cho đồng
[NeMo I 2026-07-01 12:06:10 wer:336]

[NeMo I 2026-07-01 12:06:10 wer:337] WER reference:mình mẩy tôi tuy đau đớn
[NeMo I 2026-07-01 12:06:10 wer:338] WER predicted:mình bảy tôi tuy đau đường
[NeMo I 2026-07-01 12:06:19 wer:336]

[NeMo I 2026-07-01 12:06:19 wer:337] WER reference:luôn ngẩng cao đầu sự khác biệt lớn nhất giữa người tự tin và người nhút nhát là gì
[NeMo I 2026-07-01 12:06:19 wer:338] WER predicted:luôn ngn cao đầu x khách người lớn nhỏ d người từ tiếng biết và người nh nhấtạ là gì
[NeMo I 2026-07-01 12:06:27 wer:336]

[NeMo I 2026-07-01 12:06:27 wer:337] WER reference:với các bạn trẻ trên đây có vẻ tình yêu không phải là tất cả
[NeMo I 2026-07-01 12:06:27 wer:338] WER predicted:với các bạn trẻ chính đây có về tình yêu kh và là tục cả
[NeMo I 2026-07-01 12:06:36 wer:336]

[NeMo I 2026-07-01 12:06:36 wer:337] WER reference:nếu trẻ bú không đủ có thể vắt sữa và cho trẻ uống bằng muỗng
[NeMo I 2026-07-01 12:06:36 wer:338] WER predicted:như trẻú không đủ có thể biết s và tr trẻ  uống bằngôn
[NeMo I 2026-07-01 12:06:44 wer:336]

[NeMo I 2026-07-01 12:06:44 wer:337] WER reference:hãy để thời gian tìm hiểu thêm và thuyết phục gia đình
[NeMo I 2026-07-01 12:06:44 wer:338] WER predicted:hãy để thời gian để mỹ thêm phải thu phục gia đình
[NeMo I 2026-07-01 12:06:53 wer:336]

[NeMo I 2026-07-01 12:06:53 wer:337] WER reference:vân vân và vân vân
[NeMo I 2026-07-01 12:06:53 wer:338] WER predicted:v vẫn bốn và vẫn bốn
[NeMo I 2026-07-01 12:07:01 wer:336]

[NeMo I 2026-07-01 12:07:01 wer:337] WER reference:mà phụ nữ trong khu vực công đang gặp phải
[NeMo I 2026-07-01 12:07:01 wer:338] WER predicted:mà phụ nơi trong khu vực công đang g gặp phải
[NeMo I 2026-07-01 12:07:10 wer:336]

[NeMo I 2026-07-01 12:07:10 wer:337] WER reference:những năm trước phần lớn sếu ở kiên lương kiên giang
[NeMo I 2026-07-01 12:07:10 wer:338] WER predicted:những năm ch phần lên sẽ ở khi lớn ki gia
[NeMo I 2026-07-01 12:07:18 wer:336]

[NeMo I 2026-07-01 12:07:18 wer:337] WER reference:theo nguyên đào kinh tế đô thị
[NeMo I 2026-07-01 12:07:18 wer:338] WER predicted:theo nguyên đào ki tênưa thời
[NeMo I 2026-07-01 12:08:18 wer:336]

[NeMo I 2026-07-01 12:08:18 wer:337] WER reference:màu đen của những tấm cha
[NeMo I 2026-07-01 12:08:18 wer:338] WER predicted:màu đang của những tâm gia
[NeMo I 2026-07-01 12:08:27 wer:336]

[NeMo I 2026-07-01 12:08:27 wer:337] WER reference:tôi chỉ thấy người ta nhắc đến phượng vĩ tháng sáu hay cùng lắm là tháng năm
[NeMo I 2026-07-01 12:08:27 wer:338] WER predicted:tôi chỉ thấy ngườiáạ để phương vị tình sau hai cũng tám là thành ra
[NeMo I 2026-07-01 12:08:35 wer:336]

[NeMo I 2026-07-01 12:08:35 wer:337] WER reference:với câu trả lời xuất sắc và gương mặt khả ái
[NeMo I 2026-07-01 12:08:35 wer:338] WER predicted:với cô cho lời sức s vàương một khá ai
[NeMo I 2026-07-01 12:08:44 wer:336]

[NeMo I 2026-07-01 12:08:44 wer:337] WER reference:nhưng em có biết rằng anh yêu em cũng bởi những lý do đó
[NeMo I 2026-07-01 12:08:44 wer:338] WER predicted:thì em có biết rằng anh như em cũng mọ nh lý do
[NeMo I 2026-07-01 12:10:35 wer:336]

[NeMo I 2026-07-01 12:10:35 wer:337] WER reference:cô bé rất lấy làm vui mừng và làm quen với những nốt nhạc đầu tiên bằng chính chiếc đàn đồ chơi ấy
[NeMo I 2026-07-01 12:10:35 wer:338] WER predicted:có bé rất làm vui và làm quan với nhữngạ đầu tiền trên bạn chính ch đang được chơi ấy
[NeMo I 2026-07-01 12:10:43 wer:336]

[NeMo I 2026-07-01 12:10:43 wer:337] WER reference:với mức khởi điểm tính thuế như trong dự thảo là cao
[NeMo I 2026-07-01 12:10:43 wer:338] WER predicted:với mất thời điểm xin thế như trong nhiều th tạo là
[NeMo I 2026-07-01 12:10:52 wer:336]

[NeMo I 2026-07-01 12:10:52 wer:337] WER reference:tuy nhiên cũng không ít máy bay gặp sự cố trên đường bay
[NeMo I 2026-07-01 12:10:52 wer:338] WER predicted:tuy nhiên cũng không ít máy ba làm sự của trên đồng ba
[NeMo I 2026-07-01 12:20:54 wer:336]

[NeMo I 2026-07-01 12:20:54 wer:337] WER reference:bà mẹ nghèo đông con
[NeMo I 2026-07-01 12:20:54 wer:338] WER predicted:bà mẹ nghe vẫn con
[NeMo I 2026-07-01 12:21:03 wer:336]

[NeMo I 2026-07-01 12:21:03 wer:337] WER reference:lấy tĩnh chế động
[NeMo I 2026-07-01 12:21:03 wer:338] WER predicted:l liệu tình cho đồng
[NeMo I 2026-07-01 12:21:12 wer:336]

[NeMo I 2026-07-01 12:21:12 wer:337] WER reference:mình mẩy tôi tuy đau đớn
[NeMo I 2026-07-01 12:21:12 wer:338] WER predicted:mình bảy tôi tuy đau đường
[NeMo I 2026-07-01 12:21:20 wer:336]

[NeMo I 2026-07-01 12:21:20 wer:337] WER reference:luôn ngẩng cao đầu sự khác biệt lớn nhất giữa người tự tin và người nhút nhát là gì
[NeMo I 2026-07-01 12:21:20 wer:338] WER predicted:luôn ngn cao đầu x khách người lớn nhỏ d người từ tiếng biết và người nh nhấtạ là gì
[NeMo I 2026-07-01 12:21:29 wer:336]

[NeMo I 2026-07-01 12:21:29 wer:337] WER reference:với các bạn trẻ trên đây có vẻ tình yêu không phải là tất cả
[NeMo I 2026-07-01 12:21:29 wer:338] WER predicted:với các bạn trẻ chính đây có về tình yêu kh và là t tục cả
[NeMo I 2026-07-01 12:21:38 wer:336]

[NeMo I 2026-07-01 12:21:38 wer:337] WER reference:nếu trẻ bú không đủ có thể vắt sữa và cho trẻ uống bằng muỗng
[NeMo I 2026-07-01 12:21:38 wer:338] WER predicted:như trẻú không đủ có thể biết s và tr trẻ  uống bằngôn
[NeMo I 2026-07-01 12:21:46 wer:336]

[NeMo I 2026-07-01 12:21:46 wer:337] WER reference:hãy để thời gian tìm hiểu thêm và thuyết phục gia đình
[NeMo I 2026-07-01 12:21:46 wer:338] WER predicted:hay để thời gian để mỹ thêm phải thu phục gia đình
[NeMo I 2026-07-01 12:21:55 wer:336]

[NeMo I 2026-07-01 12:21:55 wer:337] WER reference:vân vân và vân vân
[NeMo I 2026-07-01 12:21:55 wer:338] WER predicted:v vẫn bốn và vẫn bốn
[NeMo I 2026-07-01 12:22:04 wer:336]

[NeMo I 2026-07-01 12:22:04 wer:337] WER reference:mà phụ nữ trong khu vực công đang gặp phải
[NeMo I 2026-07-01 12:22:04 wer:338] WER predicted:mà phụ nơi trong khu vực công đang g gặp phải
[NeMo I 2026-07-01 12:22:12 wer:336]

[NeMo I 2026-07-01 12:22:12 wer:337] WER reference:những năm trước phần lớn sếu ở kiên lương kiên giang
[NeMo I 2026-07-01 12:22:12 wer:338] WER predicted:những năm ch phần lên sẽ ở khi lớn ki gia
[NeMo I 2026-07-01 12:22:21 wer:336]

[NeMo I 2026-07-01 12:22:21 wer:337] WER reference:theo nguyên đào kinh tế đô thị
[NeMo I 2026-07-01 12:22:21 wer:338] WER predicted:theo nguyên đào ki tênưa thời
[NeMo I 2026-07-01 12:22:30 wer:336]

[NeMo I 2026-07-01 12:22:30 wer:337] WER reference:nhưng ngủ quá nhiều sẽ khiến bạn trở nên bơ phờ
[NeMo I 2026-07-01 12:22:30 wer:338] WER predicted:nhưng ngủ quá nhiều sẽ khiến bạn trên đến b ph
[NeMo I 2026-07-01 12:22:38 wer:336]

[NeMo I 2026-07-01 12:22:38 wer:337] WER reference:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 12:22:38 wer:338] WER predicted:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 12:22:47 wer:336]

[NeMo I 2026-07-01 12:22:47 wer:337] WER reference:thường xuyên đối mặt với nạn khan hiếm lương thực
[NeMo I 2026-07-01 12:22:47 wer:338] WER predicted:thường x đối mặt với ngành khá hếm luôn thực
[NeMo I 2026-07-01 12:22:56 wer:336]

[NeMo I 2026-07-01 12:22:56 wer:337] WER reference:tôi có cảm tình với cô ấy nhưng tôi không muốn xen vào giữa họ
[NeMo I 2026-07-01 12:22:56 wer:338] WER predicted:tôi có cảm tình với cơ ấyững tôi không muốn xe vào d họ
[NeMo I 2026-07-01 12:23:04 wer:336]

[NeMo I 2026-07-01 12:23:04 wer:337] WER reference:với tôi chết là một sự ích kỷ còn bản chất sự sống đã là một bao dung ít nhất với chính mình
[NeMo I 2026-07-01 12:23:04 wer:338] WER predicted:với tôi ch là một sự kỳ công bạn chất sĩ sống đã một bao g biết nhất với chính mình
[NeMo I 2026-07-01 12:23:13 wer:336]


Validation: |          | 0/? [00:00<?, ?it/s]

[NeMo I 2026-07-01 12:43:58 wer:336]

[NeMo I 2026-07-01 12:43:58 wer:337] WER reference:những con vật này đã bị giết và đốt
[NeMo I 2026-07-01 12:43:58 wer:338] WER predicted:nh con vật này đã bị d vàốc
[NeMo I 2026-07-01 12:43:58 wer:336]

[NeMo I 2026-07-01 12:43:58 wer:337] WER reference:do vậy có máy cũng không thường dùng
[NeMo I 2026-07-01 12:43:58 wer:338] WER predicted:do vậy có mấy cũng không thường dụng
[NeMo I 2026-07-01 12:43:58 wer:336]

[NeMo I 2026-07-01 12:43:58 wer:337] WER reference:đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
[NeMo I 2026-07-01 12:43:58 wer:338] WER predicted:đây sẽ là cuộc gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
[NeMo I 2026-07-01 12:43:58 wer:336]

[NeMo I 2026-07-01 12:43:58 wer:337] WER reference:sau đó một vật lạ bay xợt ngang nóc nhà ông
[NeMo I 2026-07-01 12:43:58 wer:338] WER predicted:sau đó một và là b sự ng năngn nốc nhau
[NeMo I 2026-07-01 12:43:58 wer:336]

[NeMo I 2026-07-01 12:43:58 wer:337] WER reference:hiện ra tận phía xa
[NeMo I 2026-07-01 12:43:58 wer:338] WER predicted:hiện ra tình phía xa
[NeMo I 2026-07-01 12:43:59 wer:336]

[NeMo I 2026-07-01 12:43:59 wer:337] WER reference:nên với thông tin này
[NeMo I 2026-07-01 12:43:59 wer:338] WER predicted:nên với thông tiền này
[NeMo I 2026-07-01 12:43:59 wer:336]

[NeMo I 2026-07-01 12:43:59 wer:337] WER reference:và dân dã như chính cái tên của nó
[NeMo I 2026-07-01 12:43:59 wer:338] WER predicted:và dân gia như chính cái trên của nó
[NeMo I 2026-07-01 12:43:59 wer:336]

[NeMo I 2026-07-01 12:43:59 wer:337] WER reference:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 12:43:59 wer:338] WER predicted:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 12:43:59 wer:336]

[NeMo I 2026-07-01 12:43:59 wer:337] WER reference:sau nhiều pha hảm thành liên tục
[NeMo I 2026-07-01 12:43:59 wer:338] WER predicted:sau nhiều phá h thành liên tục
[NeMo I 2026-07-01 12:43:59 wer:336]

[NeMo I 2026-07-01 12:43:59 wer:337] WER reference:anh vẫn nhớ kỷ niệm cầu đầu lâu
[NeMo I 2026-07-01 12:43:59 wer:338] WER predicted:anh v vẫn nhớ kỳiềm cầu đầu lâu
[NeMo I 2026-07-01 12:43:59 wer:336]

[NeMo I 2026-07-01 12:43:59 wer:337] WER reference:gay go lắm nhưng hoàng anh gia lai sẽ làm được
[NeMo I 2026-07-01 12:43:59 wer:338] WER predicted:g g làm nhưng hơn anh gia là sẽ làm được
[NeMo I 2026-07-01 12:43:59 wer:336]

[NeMo I 2026-07-01 12:43:59 wer:337] WER reference:do đó khi chơi chung với bạn bè cùng lứa chúng thường tỏ ra thiếu tự tin
[NeMo I 2026-07-01 12:43:59 wer:338] WER predicted:do đó khi tr chơi chúng với bạn bé cũng lư chúng ta thường tôi cả thiếu từ tính
[NeMo I 2026-07-01 12:43:59 wer:336]

[NeMo I 2026-07-01 12:43:59 wer:337] WER reference:mối đục luỗng cả tấm gỗ
[NeMo I 2026-07-01 12:43:59 wer:338] WER predicted:mới được luôn cả t tâm g
[NeMo I 2026-07-01 12:43:59 wer:336]

[NeMo I 2026-07-01 12:43:59 wer:337] WER reference:người ta cho rằng trung tâm này có khả năng ảnh hưởng đến quá trình lão hóa
[NeMo I 2026-07-01 12:43:59 wer:338] WER predicted:người ta cho rằng trung tâm này có khá năng anh hướng đến quá trên lao hoa
[NeMo I 2026-07-01 12:43:59 wer:336]

[NeMo I 2026-07-01 12:43:59 wer:337] WER reference:các giò phong lan tháng ba cũng không chịu yên mình
[NeMo I 2026-07-01 12:43:59 wer:338] WER predicted:các cho phẩm lên tha ba cũng công chịu ý mình
[NeMo I 2026-07-01 12:43:59 wer:336]

[NeMo I 2026-07-01 12:43:59 wer:337] WER reference:hãy cho tôi quyền năng vô tận để bảo vệ loài vật
[NeMo I 2026-07-01 12:43:59 wer:338] WER predicted:hay cho tôi viên năng vô tăng để bảo về loi vật
[NeMo I 2026-07-01 12:43:59 wer:336]

[NeMo I 2026-07-01 12:43:59 wer:337] WER reference:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 12:43:59 wer:338] WER predicted:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 12:43:59 wer:336]

[NeMo I 2026-07-01 12:43:59 wer:337] WER reference:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 12:43:59 wer:338] WER predicted:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 12:43:59 wer:336]

[NeMo I 2026-07-01 12:43:59 wer:337] WER reference:sáng chiều hội diễn tiếng hát bảo minh do công ty bảo hiểm bảo minh tổ chức
[NeMo I 2026-07-01 12:43:59 wer:338] WER predicted:sáng chịu hỏi diễn tiếng khác đầu mình do công ty bảo em báo mình tôi chức
[NeMo I 2026-07-01 12:43:59 wer:336]

[NeMo I 2026-07-01 12:43:59 wer:337] WER reference:cô nằm thiếp đi lúc nào không biết
[NeMo I 2026-07-01 12:43:59 wer:338] WER predicted:cô năm tiếp đi lúc nào không biết
[NeMo I 2026-07-01 12:44:00 wer:336]

[NeMo I 2026-07-01 12:44:00 wer:337] WER reference:mười bảy mười tám mười chín
[NeMo I 2026-07-01 12:44:00 wer:338] WER predicted:mươi bảy mươi tám mươi chín
[NeMo I 2026-07-01 12:44:00 wer:336]

[NeMo I 2026-07-01 12:44:00 wer:337] WER reference:tích cóp đủ thứ đồ lạc xon những ngọn đèn
[NeMo I 2026-07-01 12:44:00 wer:338] WER predicted:tiếpốc đưa thứ đồ đ đã số những ngọ đang
[NeMo I 2026-07-01 12:44:00 wer:336]

[NeMo I 2026-07-01 12:44:00 wer:337] WER reference:nhưng đất nước đã chọn một nhà lãnh đạo khác
[NeMo I 2026-07-01 12:44:00 wer:338] WER predicted:nhưng nước nước đã chọn một nhà là đầu khác
[NeMo I 2026-07-01 12:44:00 wer:336]

[NeMo I 2026-07-01 12:44:00 wer:337] WER reference:ưu thế này có được là nhờ quá trình cơ giới hóa nhanh sử dụng phân bón cho dù hậu quả có là
[NeMo I 2026-07-01 12:44:00 wer:338] WER predicted:uống thế này có được là nhớ quá trình cơ giới hoa nhanh sự dụng phần bốn cho dụnghầu quả có là
[NeMo I 2026-07-01 12:44:00 wer:336]

[NeMo I 2026-07-01 12:44:00 wer:337] WER reference:thường xuyên xảy ra hiện tượng đạo văn quỵt nhuận bút
[NeMo I 2026-07-01 12:44:00 wer:338] WER predicted:thường xuyên x ra hiện thường đào văn quyết nhút
[NeMo I 2026-07-01 12:44:00 wer:336]

[NeMo I 2026-07-01 12:44:00 wer:337] WER reference:chỉ cho chúng tôi xem hàng đống gạch đá cát sỏi
[NeMo I 2026-07-01 12:44:00 wer:338] WER predicted:chỉ cho chúng tôi xem hàng đồng cả đã các số
[NeMo I 2026-07-01 12:44:00 wer:336]

[NeMo I 2026-07-01 12:44:00 wer:337] WER reference:đối với cảng hàng không quốc tế đà nẵng sử dụng nhà ga hành khách hiện hữu làm nhà ga nội địa
[NeMo I 2026-07-01 12:44:00 wer:338] WER predicted:đối với càng hàng không quốc tế đã năng sự dụng nhà gia hành khách hiện hồ làm nhà g nói để
[NeMo I 2026-07-01 12:44:00 wer:336]

[NeMo I 2026-07-01 12:44:00 wer:337] WER reference:người giàu thì vác nặng những xâu tiền kẽm trên vai
[NeMo I 2026-07-01 12:44:00 wer:338] WER predicted:ngườiào thì phát nạ những sau tiềnk trên phải
[NeMo I 2026-07-01 12:44:00 wer:336]

[NeMo I 2026-07-01 12:44:00 wer:337] WER reference:các nữ công nhân làm ca đêm
[NeMo I 2026-07-01 12:44:00 wer:338] WER predicted:các nữ công nhân làm cả điểm
[NeMo I 2026-07-01 12:44:00 wer:336]

[NeMo I 2026-07-01 12:44:00 wer:337] WER reference:tui biết bà giỏi rồi
[NeMo I 2026-07-01 12:44:00 wer:338] WER predicted:tôi biết ba di rồi
[NeMo I 2026-07-01 12:44:00 wer:336]

[NeMo I 2026-07-01 12:44:00 wer:337] WER reference:đưa một chú bồ câu bay đi bay về
[NeMo I 2026-07-01 12:44:00 wer:338] WER predicted:đường một chú bộ cầu bảy đi bị v về
[NeMo I 2026-07-01 12:44:00 wer:336]

[NeMo I 2026-07-01 12:44:00 wer:337] WER reference:tôi đến kiểm tra và phát hiện thấy ông và cô gái nằm kia thám tử ra hiệu cho ngài triệu phú nhìn vào phòng tắm cô ta đã chết
[NeMo I 2026-07-01 12:44:00 wer:338] WER predicted:tôi đến kiểm ra và phát hiện thấy ông và cô gái nămk tha từ ra hiểu cho ngày chịu phương nhìn vào phòng tâm cô đã chết
[NeMo I 2026-07-01 12:44:00 wer:336]

[NeMo I 2026-07-01 12:44:00 wer:337] WER reference:để thực hiện thắng lợi kế hoạch năm năm
[NeMo I 2026-07-01 12:44:00 wer:338] WER predicted:để thực hiện thân lại cái hết năm năm
[NeMo I 2026-07-01 12:44:00 wer:336]

[NeMo I 2026-07-01 12:44:00 wer:337] WER reference:trước khi hóa thân thành cộng hòa sét để đến bồ đào nha
[NeMo I 2026-07-01 12:44:00 wer:338] WER predicted:trước khi hoa thân thành có hoa sức để đến bộ đồng nhà
[NeMo I 2026-07-01 12:44:00 wer:336]

[NeMo I 2026-07-01 12:44:00 wer:337] WER reference:tuy nhiên tôi không chắc những người chưa từng đọc cuốn nhật ký có thể hiểu hết được ý nghĩa bộ phim
[NeMo I 2026-07-01 12:44:00 wer:338] WER predicted:tuy nhiên tôi không chắc những người chưa từ đọc cũng nhất kỳ có thể hiểu hết được ý nghĩ bộ phim
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:chi đầu tư từ khu vực nhà nước còn lớn và hiệu quả thấp
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:chỉ đầu tư từ khu vực nhà n nước còn lớn và hiệu quá th hợp
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:cái nền xưa của nó bây giờ là một cái hố nông choèn
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:cái nên s của nó bị giờ là một cái hồ n năm tr
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:giải truyền thông điện ảnh trung quốc là giải thưởng điện ảnh duy nhất xét trao cho tất cả các bộ phim hoa ngữ
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:giải trên thường đến anh chúng quốc là dài thường đến anh gì sẽ cho cho tất cả các bộ hiện hoànư
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:dự đoán ba tháng nữa giá cà phê sẽ tăng gấp đôi hiện nay
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:điều rằng ba tháng nữa giá và về sự tăng gặp đôi hiện này
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:họ đến đây vì nhiều mục đích
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:họ đến đâyì nhiều một đích
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:vậy trước đây nông dân đối phó với hiện tượng này như thế nào thưa ông
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:vậy trước đây n năm nhân đối phố v với hiện từ này như đến nào thu  ông
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:làm sao để có tiền nhanh nhất
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:làm sao để có tiền nhân nhất
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:đùi dang ra ngoài
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:được gian ra ngoài
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:đã hai lần cô gác lại ước mơ vào đời và cũng đã ít nhiều trải qua những thăng trầm xô bồ của cuộc sống
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:đã hai l lần cô gái lạiút mới vào đời và cũng đã ít nhiều trái qua những thân tr số bộ của cuộc sống
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:trong bối cảnh như vậy một phản ứng chính sách đối với vấn đề thất nghiệp đang là đòi hỏi cấp bách hiện nay
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:trong bộ cảnh như vậy một phầnững chính sách đối với vẫn để nghiệpp đang là đời họ cách cách hiện này
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:ở xứ sở chuột túi
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:ở sở tr chủ tôi
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:do vậy dựa trên cơ sở nào mà ông khoa phát biểu như vậy
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:do vậy dự trên cơ s nào ông khoa phát biểu như vậy
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:tá tàng
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:ta tăng
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:cách đây tám năm nhưng trước đó khoảng hai năm đã được mời đóng phim và có nhiều vai chính trong các phim điện ảnh truyền hình
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:cách đây tâm năm nh trước đó kho hai năm đã được mới động phim và có nhiều và chính trong các phim điện anh truyền hình
[NeMo I 2026-07-01 12:44:01 wer:336]

[NeMo I 2026-07-01 12:44:01 wer:337] WER reference:đã thăm hỏi thì thế nào cũng phải có quà cáp
[NeMo I 2026-07-01 12:44:01 wer:338] WER predicted:đã tâmm họ thì thế nào cũng phải có quả các
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:có m tạià điện phòng
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:em lơ đễnh lật xem vài tờ báo
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:em là điện l xem vàờ báo
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:và không ít người cứ tì tì uống từ sáng đến tối suốt mấy ngày hội nghị
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:và không ít người cứ ty từ  uống từ sáng đến tôi xuất máy ngày hội này
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:minh châu vào miền nam công tác tại nhà hát trần hữu trang
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:mình cao vào m nam công tất tại nhà ho rằng h rằng
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:hết chiến tranh quê hương im tiếng súng anh lính cụ hồ lại trở về với đời thường tham gia sản xuất xây dựng và bảo vệ đất nước
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:hết tiếng trên với hơn ý tiếng xuống anh lên của hồ lại cho về với đời thường tham giá sản xuất sẽ d vào b với đất nước
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:chuyến đi đó đến giờ vẫn là một ám ảnh trong ký ức tôi
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:chỉ đi đó đến giờ vẫn là một ông anh trong kỳ
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:ây da ây da
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:giá gia
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:có rất nhiều vệ tinh bị rơi khỏi quỹ đạo
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:rất nhiều về tính bị rồi khó qu nào
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:nhuốm đầy máu của thổ dân châu mỹ
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:dụng đây m máu của thủ dân cho mỹ
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:cụ thể về đất đai xây dựng văn hóa thuộc về từng ngành riêng biệt
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:cô thể về đất đây văn sẽ những văn hoa thuốc về từ ngành riêng biết
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:tôi muốn hỏi liệu có mùi hương sen nhân tạo là một loại hóa chất không
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:tôi muốn hỏi liệu có mười hướng s nhân tạo là một loạii họ chắc cao
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:cả nhà bà ngoại cười nắc nẻ vì câu nói ngây ngô của con
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:các nhà bao ngoài người nước ngheì cô nói ngày ngủ của con
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:xin được chân khuân vác
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:xin được trên khu phát
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:nằm khuất dưới tàn tre sát bờ sông châu
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:ho giới đàn trẻ sẽ bà sống ch
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:nếu kiên cố hóa thì vốn được đưa thẳng cho dân sẽ không thất thoát
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:nếu ki cô hoa thì bốn đượcưa tăng cho dân sẽ không thật
[NeMo I 2026-07-01 12:44:02 wer:336]

[NeMo I 2026-07-01 12:44:02 wer:337] WER reference:nói chung cô hồng nào cũng có một số phận hoàn cảnh và cuộc đời riêng
[NeMo I 2026-07-01 12:44:02 wer:338] WER predicted:nói chúng cô học nào cũng có một số phần hoàn cảnhnh với cuộc đời riêng
[NeMo I 2026-07-01 12:44:03 wer:336]

[NeMo I 2026-07-01 12:44:03 wer:337] WER reference:nhưng tất cả những điều ấy chẳng mấy khi đi liền với nhau
[NeMo I 2026-07-01 12:44:03 wer:338] WER predicted:những tất cả những điều ấy ch mấy khi đi liên với nhau
[NeMo I 2026-07-01 12:44:03 wer:336]

[NeMo I 2026-07-01 12:44:03 wer:337] WER reference:như vậy là bạn có thể sử dụng được nhiều số điện thoại của nhiều nhà cung cấp dịch vụ chỉ trên một sim
[NeMo I 2026-07-01 12:44:03 wer:338] WER predicted:như vậy bạn có thể sự dụng được nhiều số đến th của như nhà cũng cấp dịch vụ chỉ trên một xem
[NeMo I 2026-07-01 12:44:03 wer:336]

[NeMo I 2026-07-01 12:44:03 wer:337] WER reference:trong trường hợp hai bên có thỏa thuận lại không yêu cầu trọng tài giải quyết nữa thì có quyền kiện ra tòa án
[NeMo I 2026-07-01 12:44:03 wer:338] WER predicted:trong trường hợp hai bên có thể thường lại không yêu cầu trong ta d quyết nữa thì có quyền kiến ra toàn ăn
[NeMo I 2026-07-01 12:44:03 wer:336]

[NeMo I 2026-07-01 12:44:03 wer:337] WER reference:kiểu này chắc phải cắt giảm biên chế
[NeMo I 2026-07-01 12:44:03 wer:338] WER predicted:kiể này chắc phải các giảm biến chế
[NeMo I 2026-07-01 12:44:03 wer:336]

[NeMo I 2026-07-01 12:44:03 wer:337] WER reference:nhưng tôi không yêu cô cô biết rõ điều đó mà
[NeMo I 2026-07-01 12:44:03 wer:338] WER predicted:nhưng tôi không yêu cô cô biết rồi điều đó mà
[NeMo I 2026-07-01 12:44:03 wer:336]

[NeMo I 2026-07-01 12:44:03 wer:337] WER reference:khó mà đoán trước chính xác kết quả khi quả bóng còn lăn
[NeMo I 2026-07-01 12:44:03 wer:338] WER predicted:khó mà đó trước chính sẽích quả khi qua b bóng con
[NeMo I 2026-07-01 12:44:03 wer:336]

[NeMo I 2026-07-01 12:44:03 wer:337] WER reference:vừa nhìn thấy sự xuất hiện của bố tất cả mấy thằng khác vùng bỏ chạy sạch
[NeMo I 2026-07-01 12:44:03 wer:338] WER predicted:ừa nh thấy sự sự hiện của bố tất cả máy th thành khác vùng bỏi trẻ sách
[NeMo I 2026-07-01 12:44:03 wer:336]

[NeMo I 2026-07-01 12:44:03 wer:337] WER reference:phải nâng cao khả năng cạnh tranh của nền kinh tế
[NeMo I 2026-07-01 12:44:03 wer:338] WER predicted:phải năng cao khá năng cảnh trên của nên kinh tên
[NeMo I 2026-07-01 12:44:03 wer:336]

[NeMo I 2026-07-01 12:44:03 wer:337] WER reference:bà thường lấy ý tưởng cho các tác phẩm từ đâu
[NeMo I 2026-07-01 12:44:03 wer:338] WER predicted:bà thườngấy ý từ cho các tác phẩm từ đồng
[NeMo I 2026-07-01 12:44:03 wer:336]

[NeMo I 2026-07-01 12:44:03 wer:337] WER reference:khi chứng kiến người vợ lăng loàn
[NeMo I 2026-07-01 12:44:03 wer:338] WER predicted:khi chứng kiến người vào l lần lòng
[NeMo I 2026-07-01 12:44:03 wer:336]

[NeMo I 2026-07-01 12:44:03 wer:337] WER reference:tác phẩm to lớn bằng đồng như tượng phật quỳnh lâm chuông quy điền tháp báo thiên vạc phổ minh an nam tứ đại khí
[NeMo I 2026-07-01 12:44:03 wer:338] WER predicted:ta phẩm ta lớn bạn đồng như tượng phát qu làm chúng qu điện th bảo tìm và phố mình ăn năm tư đây khi
[NeMo I 2026-07-01 12:44:03 wer:336]

[NeMo I 2026-07-01 12:44:03 wer:337] WER reference:ngoài ra họ vẫn còn muốn giữ chân cầu thủ xuất sắc nhất của mình
[NeMo I 2026-07-01 12:44:03 wer:338] WER predicted:họ vẫn cầu muốnư chân cầu thủ xuất s
[NeMo I 2026-07-01 12:44:03 wer:336]

[NeMo I 2026-07-01 12:44:03 wer:337] WER reference:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 12:44:03 wer:338] WER predicted:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 12:44:03 wer:336]

[NeMo I 2026-07-01 12:44:03 wer:337] WER reference:và gã thệ bị điều về làm trưởng phòng xã hội huyện
[NeMo I 2026-07-01 12:44:03 wer:338] WER predicted:và cả thể biết điều về làm trường phần xã hội h
[NeMo I 2026-07-01 12:44:03 wer:336]

[NeMo I 2026-07-01 12:44:03 wer:337] WER reference:là rút rỉa tiền của bạn càng nhiều càng tốt

[NeMo W 2026-07-01 12:44:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 12:44:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

[best val_wer] epoch=8 val_wer=0.443792 exported=/kaggle/working/phase3_continue_best.nemo

Sample predictions after epoch 8:
  [0] REF: những con vật này đã bị giết và đốt
      HYP: nh con vật này đã bị d vàốc
  [1] REF: phòng chống tham nhũng không được chủ quan cần làm liên tục đồng bộ và có các giải pháp
      HYP: phòng trong tham dụng không được chủ quan cần làm liên tục động bộ và có các đại pháp
  [2] REF: do vậy có máy cũng không thường dùng
      HYP: do vậy có mấy cũng không thường dụng
  [3] REF: mới khệnh khạng đứng lên đi ra
      HYP: mới kh khá đứng lên đi ra
  [4] REF: đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
      HYP: đây sẽ là cuộc gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
  [5] REF: sau một năm eo sèo
      HYP: sáu một năm yêu xe
  [6] REF: sau đó một vật lạ bay xợt ngang nóc nhà ông
      HYP: sau đó một và là b sự ng năngn nốc nhau
  [7] REF: chín mươi hai chín mươi ba
      HYP: chín mươi hai chín mươi ba
  [8] REF: hiện ra tận phía xa
      HYP: hiện ra tình phía xa
  [9] REF: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã qua của thị trường
      HYP: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã quá của thì trường
[epoch] epoch=8/12 step=2512 val_loss=2.1281535625457764 val_wer=0.4437922537326813
[NeMo I 2026-07-01 12:44:47 wer:336]

[NeMo I 2026-07-01 12:44:47 wer:337] WER reference:rất nhiều trường hợp phụ huynh đau đầu vì con một đã tìm đến chuyên viên tư vấn tâm lý
[NeMo I 2026-07-01 12:44:47 wer:338] WER predicted:rất người trường học phụ kh đâu đầuì anh một đã tìm đến trên viên tư anh tâm lý
[NeMo I 2026-07-01 12:44:56 wer:336]

[NeMo I 2026-07-01 12:44:56 wer:337] WER reference:trước tình thế đó tôi buộc phải tìm cho mình một bến đỗ mới và tôi đã quyết định ra đi
[NeMo I 2026-07-01 12:44:56 wer:338] WER predicted:lúc tình thế đó tôi bộ phải tiền cho mình một bên đ đầu mới và tôi đã quyết bệnh ra đi
[NeMo I 2026-07-01 12:45:04 wer:336]

[NeMo I 2026-07-01 12:45:04 wer:337] WER reference:tuy nhiên tình hình đó không diễn ra ở tất cả trường
[NeMo I 2026-07-01 12:45:04 wer:338] WER predicted:tuy nhiên tình hình đó không diễná ở tất cả trường
[NeMo I 2026-07-01 12:45:13 wer:336]

[NeMo I 2026-07-01 12:45:13 wer:337] WER reference:nếu xét trên qui mô toàn tỉnh con số ấy vẫn còn khiêm tốn lắm
[NeMo I 2026-07-01 12:45:13 wer:338] WER predicted:nên x chỉ phí mua toàn tình cầu số ấy vẫn còn khiù làm
[NeMo I 2026-07-01 12:45:22 wer:336]

[NeMo I 2026-07-01 12:45:22 wer:337] WER reference:các vùng sâu vùng xa khó mà phát triển
[NeMo I 2026-07-01 12:45:22 wer:338] WER predicted:các vùng sau vùng sẽ khó mà phát triển
[NeMo I 2026-07-01 12:45:30 wer:336]

[NeMo I 2026-07-01 12:45:30 wer:337] WER reference:thì không hiểu sao ở phần thơ cổ đại
[NeMo I 2026-07-01 12:45:30 wer:338] WER predicted:thì không hiểu sao ở phần hết của đầy
[NeMo I 2026-07-01 12:45:39 wer:336]

[NeMo I 2026-07-01 12:45:39 wer:337] WER reference:anh muốn thùy có thể tự do tìm cho mình một hạnh phúc khác tràn đầy
[NeMo I 2026-07-01 12:45:39 wer:338] WER predicted:anh muốn thời có thể từ do tìm cho mình một thành ph khác cho lại
[NeMo I 2026-07-01 12:45:47 wer:336]

[NeMo I 2026-07-01 12:45:47 wer:337] WER reference:áo thun trắng sát nách
[NeMo I 2026-07-01 12:45:47 wer:338] WER predicted:áo thu trang sátắc
[NeMo I 2026-07-01 12:45:56 wer:336]

[NeMo I 2026-07-01 12:45:56 wer:337] WER reference:đây cũng là giai đoạn thị trường nhiều biến cố nhất
[NeMo I 2026-07-01 12:45:56 wer:338] WER predicted:đây cũng là chế đồng thì trường nhiều biến cô nhất
[NeMo I 2026-07-01 12:46:05 wer:336]

[NeMo I 2026-07-01 12:46:05 wer:337] WER reference:mới thành món ngon và độc đáo
[NeMo I 2026-07-01 12:46:05 wer:338] WER predicted:mới thành m món ng ngon và được đâu
[NeMo I 2026-07-01 12:46:13 wer:336]

[NeMo I 2026-07-01 12:46:13 wer:337] WER reference:người đẹp không thiếu chỉ sợ ông anh không có tiền
[NeMo I 2026-07-01 12:46:13 wer:338] WER predicted:người để không thiếu chỉ s ông anh không có tình
[NeMo I 2026-07-01 12:46:22 wer:336]

[NeMo I 2026-07-01 12:46:22 wer:337] WER reference:ngày thường chù ụ thì được
[NeMo I 2026-07-01 12:46:22 wer:338] WER predicted:ngày thường chủổ chỉ được
[NeMo I 2026-07-01 12:46:31 wer:336]

[NeMo I 2026-07-01 12:46:31 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 12:46:31 wer:338] WER predicted:có mặt tại sẽ điện phương
[NeMo I 2026-07-01 12:46:39 wer:336]

[NeMo I 2026-07-01 12:46:39 wer:337] WER reference:tôi cũng biết có những tiêu cực trong giáo dục và nhà trường cũng như những lĩnh vực khác của xã hội
[NeMo I 2026-07-01 12:46:39 wer:338] WER predicted:tôi cũng biết có những tiêu thực trong giá được và nhà trường của như những lên vợ h của xã hội
[NeMo I 2026-07-01 12:46:48 wer:336]

[NeMo I 2026-07-01 12:46:48 wer:337] WER reference:xắn quần vượt qua là bước vào thế giới
[NeMo I 2026-07-01 12:46:48 wer:338] WER predicted:sống qu v qua là bước vào thời giới
[NeMo I 2026-07-01 12:46:56 wer:336]

[NeMo I 2026-07-01 12:46:56 wer:337] WER reference:mới và cải tiến
[NeMo I 2026-07-01 12:46:56 wer:338] WER predicted:mới và cái tiền
[NeMo I 2026-07-01 12:47:05 wer:336]

[NeMo I 2026-07-01 12:47:05 wer:337] WER reference:hai vợ chồng thị tớn và văn đục
[NeMo I 2026-07-01 12:47:05 wer:338] WER predicted:hai vợ trong thì tưởng và văn được
[NeMo I 2026-07-01 12:47:13 wer:336]

[NeMo I 2026-07-01 12:47:13 wer:337] WER reference:chợ đêm ca ba dành cho những người đang vào mùa tăng ca cuối năm
[NeMo I 2026-07-01 12:47:13 wer:338] WER predicted:ở đến ba ba danh choững người đang vào một ta cả cứ năm
[NeMo I 2026-07-01 12:47:22 wer:336]

[NeMo I 2026-07-01 12:47:22 wer:337] WER reference:hai mươi hai mươi mốt
[NeMo I 2026-07-01 12:47:22 wer:338] WER predicted:hai mươi hai mươi mốt
[NeMo I 2026-07-01 12:47:30 wer:336]

[NeMo I 2026-07-01 12:47:30 wer:337] WER reference:anh không thể quên được những giây phút ngọt ngào ấy
[NeMo I 2026-07-01 12:47:30 wer:338] WER predicted:anh không được quan được nh ph gian ngọ nào ấy
[NeMo I 2026-07-01 12:47:39 wer:336]

[NeMo I 2026-07-01 12:47:39 wer:337] WER reference:đưa tới tình trạng phá sản
[NeMo I 2026-07-01 12:47:39 wer:338] WER predicted:ưa tư tiền rằng phá sản
[NeMo I 2026-07-01 12:47:47 wer:336]

[NeMo I 2026-07-01 12:47:47 wer:337] WER reference:phụ huynh và học sinh đang phải è cổ vì sách giá cao
[NeMo I 2026-07-01 12:47:47 wer:338] WER predicted:vụ qu và học sinh đang phải em cô vì sách gia cao
[NeMo I 2026-07-01 12:47:56 wer:336]

[NeMo I 2026-07-01 12:47:56 wer:337] WER reference:thỉnh thoảng lại có người ghép thận trước đó trở qua xin xét nghiệm vì có trục trặc
[NeMo I 2026-07-01 12:47:56 wer:338] WER predicted:tình toàn lại có người gằ tư tôi qua sinh sẽ nhiều về cóục đọc
[NeMo I 2026-07-01 12:48:04 wer:336]

[NeMo I 2026-07-01 12:48:04 wer:337] WER reference:cuộc thi nhằm trau dồi niềm đam mê
[NeMo I 2026-07-01 12:48:04 wer:338] WER predicted:cuộc thi nh tr d nhiệm đã mẹ
[NeMo I 2026-07-01 12:48:13 wer:336]

[NeMo I 2026-07-01 12:48:13 wer:337] WER reference:đề thi môn vẽ thông thường là về vẽ trang trí sản phẩm vật thể
[NeMo I 2026-07-01 12:48:13 wer:338] WER predicted:để thi muốn v vẻ hô thường là về về sáng chỉ sáng phẩm một thể
[NeMo I 2026-07-01 12:48:21 wer:336]

[NeMo I 2026-07-01 12:48:21 wer:337] WER reference:bước vào một mối tình
[NeMo I 2026-07-01 12:48:21 wer:338] WER predicted:bước vào một mua tình
[NeMo I 2026-07-01 12:48:30 wer:336]

[NeMo I 2026-07-01 12:48:30 wer:337] WER reference:lão nạp chỉ có nhiêu đây thôi
[NeMo I 2026-07-01 12:48:30 wer:338] WER predicted:làạ chỉ có như lại tôi
[NeMo I 2026-07-01 12:48:39 wer:336]

[NeMo I 2026-07-01 12:48:39 wer:337] WER reference:hai tuần sau
[NeMo I 2026-07-01 12:48:39 wer:338] WER predicted:hai tuần sáu
[NeMo I 2026-07-01 12:48:47 wer:336]

[NeMo I 2026-07-01 12:48:47 wer:337] WER reference:những ngày cuối cùng trên dương thế
[NeMo I 2026-07-01 12:48:47 wer:338] WER predicted:những này cuối cùng trên dân thế
[NeMo I 2026-07-01 12:48:55 wer:336]

[NeMo I 2026-07-01 12:48:55 wer:337] WER reference:trên nhiều tuyến phố công nhân đang hối hả dọn dẹp
[NeMo I 2026-07-01 12:48:55 wer:338] WER predicted:trên nhiều tiếng ph công nh đang hội hay động nghiệpp
[NeMo I 2026-07-01 12:49:04 wer:336]

[NeMo I 2026-07-01 12:49:04 wer:337] WER reference:có trường hợp bất hợp pháp như trần thị thu h
[NeMo I 2026-07-01 12:49:04 wer:338] WER predicted:có chuyện học bất hợp pháp như trong thì thu
[NeMo I 2026-07-01 12:49:12 wer:336]

[NeMo I 2026-07-01 12:49:12 wer:337] WER reference:nhưng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được các khó khăn đó
[NeMo I 2026-07-01 12:49:12 wer:338] WER predicted:chúng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được cả khó không đó
[NeMo I 2026-07-01 12:49:21 wer:336]

[NeMo I 2026-07-01 12:49:21 wer:337] WER reference:lúc đó em không thể tiếp tục công việc đánh cá của cha một mình vì còn quá nhỏ
[NeMo I 2026-07-01 12:49:21 wer:338] WER predicted:lúc đó em không phải tiếp được không việcánh các của tra một mình việc còn qua nhỏ
[NeMo I 2026-07-01 12:49:30 wer:336]

[NeMo I 2026-07-01 12:49:30 wer:337] WER reference:cuốn sách nói về sự lầm lẫn giữa luật kinh tế ở châu âu và châu mỹ kim vẫn chưa đọc tới vì cô không quan tâm đến luật
[NeMo I 2026-07-01 12:49:30 wer:338] WER predicted:cũng sinh nói về làm lần nhiều được ki tế ở ch ông và trong muốn cho vẫn chưa đọc tôi việc của không quan tăng đến luật
[NeMo I 2026-07-01 12:49:38 wer:336]

[NeMo I 2026-07-01 12:49:38 wer:337] WER reference:khi tên lửa bay lên
[NeMo I 2026-07-01 12:49:38 wer:338] WER predicted:khi tên l lời vậy lên
[NeMo I 2026-07-01 12:49:47 wer:336]

[NeMo I 2026-07-01 12:49:47 wer:337] WER reference:mà theo thời gian sẽ tiệm cận với trí khôn của con người
[NeMo I 2026-07-01 12:49:47 wer:338] WER predicted:mà theo thời dân sẽ tìm cần với trí không quốc con người
[NeMo I 2026-07-01 12:49:55 wer:336]

[NeMo I 2026-07-01 12:49:55 wer:337] WER reference:bên kia láng giềng của tôi hôm nay không thấy thăm hoa
[NeMo I 2026-07-01 12:49:55 wer:338] WER predicted:đến chỉ lan diễn của tôi hô này không thấy th h
[NeMo I 2026-07-01 12:50:04 wer:336]

[NeMo I 2026-07-01 12:50:04 wer:337] WER reference:anh yêu cầu các cầu thủ phải đeo bám ngay khi đối phương có bóng
[NeMo I 2026-07-01 12:50:04 wer:338] WER predicted:anh nhiều cầu các cầu số phảieo bạn ngày khi đối phương có
[NeMo I 2026-07-01 12:50:12 wer:336]

[NeMo I 2026-07-01 12:50:12 wer:337] WER reference:ngay cả công an đi lẻ loi cũng bị tấn công vì trong khu vực này có một thứ luật riêng cấm người lạ vào
[NeMo I 2026-07-01 12:50:12 wer:338] WER predicted:nghe và không mình đi lẽ cũng bị không con việc trong có việc mẹ một thứ lực viên công như l
[NeMo I 2026-07-01 12:50:21 wer:336]

[NeMo I 2026-07-01 12:50:21 wer:337] WER reference:thì chúng sẽ nằm trong tầm kiểm soát của bạn
[NeMo I 2026-07-01 12:50:21 wer:338] WER predicted:thì chúng sẽ năm trong đ làmm kiể sau của bạn
[NeMo I 2026-07-01 12:50:29 wer:336]

[NeMo I 2026-07-01 12:50:29 wer:337] WER reference:đó là hai con sói hoàn toàn trái ngược nhau về hình thức
[NeMo I 2026-07-01 12:50:29 wer:338] WER predicted:đó là hay con s hộ còn chính được nhau về hình thức
[NeMo I 2026-07-01 12:50:38 wer:336]

[NeMo I 2026-07-01 12:50:38 wer:337] WER reference:trại đồng xã yên sở giữa một biển nước mênh mông ảnh nguyễn quân
[NeMo I 2026-07-01 12:50:38 wer:338] WER predicted:tr đồng xã em s giờ một biểnứ mình món  anh nguyên quan
[NeMo I 2026-07-01 12:50:47 wer:336]

[NeMo I 2026-07-01 12:50:47 wer:337] WER reference:không sao rồi em mừng lắm
[NeMo I 2026-07-01 12:50:47 wer:338] WER predicted:không sao rồi em mình lắm
[NeMo I 2026-07-01 12:50:55 wer:336]

[NeMo I 2026-07-01 12:50:55 wer:337] WER reference:việc tòa án của pháp truy tố công dân một nước độc lập trên lãnh thổ quê hương của người ấy là một điều vô giá trị
[NeMo I 2026-07-01 12:50:55 wer:338] WER predicted:việc tôi ăn cuộc pháp tr tốt người không một được được lập trên l lên tôi cuối hơn còn ở ấy là một bị chú giá trị
[NeMo I 2026-07-01 12:51:04 wer:336]

[NeMo I 2026-07-01 12:51:04 wer:337] WER reference:bà mẹ nghèo đông con
[NeMo I 2026-07-01 12:51:04 wer:338] WER predicted:bà mẹ nghe vấn con
[NeMo I 2026-07-01 12:51:12 wer:336]

[NeMo I 2026-07-01 12:51:12 wer:337] WER reference:lấy tĩnh chế động
[NeMo I 2026-07-01 12:51:12 wer:338] WER predicted:l liệu tình cho đồng
[NeMo I 2026-07-01 12:51:21 wer:336]

[NeMo I 2026-07-01 12:51:21 wer:337] WER reference:mình mẩy tôi tuy đau đớn
[NeMo I 2026-07-01 12:51:21 wer:338] WER predicted:mình bảy tôi tuy đau đường
[NeMo I 2026-07-01 12:51:29 wer:336]

[NeMo I 2026-07-01 12:51:29 wer:337] WER reference:luôn ngẩng cao đầu sự khác biệt lớn nhất giữa người tự tin và người nhút nhát là gì
[NeMo I 2026-07-01 12:51:29 wer:338] WER predicted:luôn ngn cao đầu x khách người lớn nhỏ d người từ tiếng và người nh nhấtạ là gì
[NeMo I 2026-07-01 12:51:38 wer:336]

[NeMo I 2026-07-01 12:51:38 wer:337] WER reference:với các bạn trẻ trên đây có vẻ tình yêu không phải là tất cả
[NeMo I 2026-07-01 12:51:38 wer:338] WER predicted:với các bạn trẻ chính đây có về tình yêu kh và là tục cả
[NeMo I 2026-07-01 12:51:47 wer:336]

[NeMo I 2026-07-01 12:51:47 wer:337] WER reference:nếu trẻ bú không đủ có thể vắt sữa và cho trẻ uống bằng muỗng
[NeMo I 2026-07-01 12:51:47 wer:338] WER predicted:như trẻú không đủ có thể biết s và tr trẻ  uống bằngôn
[NeMo I 2026-07-01 12:51:55 wer:336]

[NeMo I 2026-07-01 12:51:55 wer:337] WER reference:hãy để thời gian tìm hiểu thêm và thuyết phục gia đình
[NeMo I 2026-07-01 12:51:55 wer:338] WER predicted:hãy để thời gian để mỹ thêm phải thu phục gia đình
[NeMo I 2026-07-01 12:52:04 wer:336]

[NeMo I 2026-07-01 12:52:04 wer:337] WER reference:vân vân và vân vân
[NeMo I 2026-07-01 12:52:04 wer:338] WER predicted:v vẫn bốn và vẫn bốn
[NeMo I 2026-07-01 12:52:12 wer:336]

[NeMo I 2026-07-01 12:52:12 wer:337] WER reference:mà phụ nữ trong khu vực công đang gặp phải
[NeMo I 2026-07-01 12:52:12 wer:338] WER predicted:mà phụ nơi trong khu vực công đang g gặp phải
[NeMo I 2026-07-01 12:52:21 wer:336]

[NeMo I 2026-07-01 12:52:21 wer:337] WER reference:những năm trước phần lớn sếu ở kiên lương kiên giang
[NeMo I 2026-07-01 12:52:21 wer:338] WER predicted:những năm ch phần lên sẽ ở khi lớn ki gia
[NeMo I 2026-07-01 12:52:29 wer:336]

[NeMo I 2026-07-01 12:52:29 wer:337] WER reference:theo nguyên đào kinh tế đô thị
[NeMo I 2026-07-01 12:52:29 wer:338] WER predicted:theo nguyên đào ki tênưa thời
[NeMo I 2026-07-01 12:52:38 wer:336]

[NeMo I 2026-07-01 12:52:38 wer:337] WER reference:nhưng ngủ quá nhiều sẽ khiến bạn trở nên bơ phờ
[NeMo I 2026-07-01 12:52:38 wer:338] WER predicted:nhưng ngủ quá nhiều sẽ khiến nạn trên đến b ph
[NeMo I 2026-07-01 12:52:47 wer:336]

[NeMo I 2026-07-01 12:52:47 wer:337] WER reference:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 12:52:47 wer:338] WER predicted:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 12:52:55 wer:336]

[NeMo I 2026-07-01 12:52:55 wer:337] WER reference:thường xuyên đối mặt với nạn khan hiếm lương thực
[NeMo I 2026-07-01 12:52:55 wer:338] WER predicted:thường x đối mặt với ngành khá hếm luôn thực
[NeMo I 2026-07-01 12:53:04 wer:336]

[NeMo I 2026-07-01 12:53:04 wer:337] WER reference:tôi có cảm tình với cô ấy nhưng tôi không muốn xen vào giữa họ
[NeMo I 2026-07-01 12:53:04 wer:338] WER predicted:tôi có cảm tình với cơ ấyững tôi không muốn xe vào d họ
[NeMo I 2026-07-01 12:53:12 wer:336]

[NeMo I 2026-07-01 12:53:12 wer:337] WER reference:với tôi chết là một sự ích kỷ còn bản chất sự sống đã là một bao dung ít nhất với chính mình
[NeMo I 2026-07-01 12:53:12 wer:338] WER predicted:với tôi chết là một sự kỳ công bạn chất sĩ sống đã một bao g biết nhất với chính mình
[NeMo I 2026-07-01 12:53:21 wer:336]

[NeMo I 2026-07-01 12:53:21 wer:337] WER reference:cậu không biết làm gì thì suốt đời cậu đúng là một kẻ hèn nhát
[NeMo I 2026-07-01 12:53:21 wer:338] WER predicted:cầu không biết làm gì thì xuất đời cầu đúng là một các hàng nhạc
[NeMo I 2026-07-01 12:53:29 wer:336]

[NeMo I 2026-07-01 12:53:29 wer:337] WER reference:màu đen của những tấm cha
[NeMo I 2026-07-01 12:53:29 wer:338] WER predicted:màu đang của những t tâm gia
[NeMo I 2026-07-01 12:53:38 wer:336]

[NeMo I 2026-07-01 12:53:38 wer:337] WER reference:tôi chỉ thấy người ta nhắc đến phượng vĩ tháng sáu hay cùng lắm là tháng năm
[NeMo I 2026-07-01 12:53:38 wer:338] WER predicted:tôi chỉ thấy ngườiáá đến phương vị tình sau hai cũng tám là thành ra
[NeMo I 2026-07-01 12:53:46 wer:336]

[NeMo I 2026-07-01 12:53:46 wer:337] WER reference:với câu trả lời xuất sắc và gương mặt khả ái
[NeMo I 2026-07-01 12:53:46 wer:338] WER predicted:với cô trả lời sức s vàương một khả ai
[NeMo I 2026-07-01 12:53:55 wer:336]

[NeMo I 2026-07-01 12:53:55 wer:337] WER reference:nhưng em có biết rằng anh yêu em cũng bởi những lý do đó
[NeMo I 2026-07-01 12:53:55 wer:338] WER predicted:thì em có biết rằng anh như em cũng ở những lý do
[NeMo I 2026-07-01 12:54:03 wer:336]

[NeMo I 2026-07-01 12:54:03 wer:337] WER reference:để nhìn thấy sự khôi hài
[NeMo I 2026-07-01 12:54:03 wer:338] WER predicted:để nhìn thấy sự khu hai
[NeMo I 2026-07-01 12:54:12 wer:336]

[NeMo I 2026-07-01 12:54:12 wer:337] WER reference:rèm cửa phòng khách của bạn giống như cung điện
[NeMo I 2026-07-01 12:54:12 wer:338] WER predicted:ra của phòng khách của bạn gi như cũng điện
[NeMo I 2026-07-01 12:54:20 wer:336]

[NeMo I 2026-07-01 12:54:20 wer:337] WER reference:và những khuyết điểm nhỏ của họ
[NeMo I 2026-07-01 12:54:20 wer:338] WER predicted:và những quyết điểm nhà của họ
[NeMo I 2026-07-01 12:54:29 wer:336]

[NeMo I 2026-07-01 12:54:29 wer:337] WER reference:tôi biết đây là quy tắc đòi hỏi
[NeMo I 2026-07-01 12:54:29 wer:338] WER predicted:tôi biết đây là quy tác đòi hỏi
[NeMo I 2026-07-01 12:54:37 wer:336]

[NeMo I 2026-07-01 12:54:37 wer:337] WER reference:cũng trong ngày đó bài xã luận gằn giọng
[NeMo I 2026-07-01 12:54:37 wer:338] WER predicted:cũng trong ngày đó và sến g rằng gi
[NeMo I 2026-07-01 12:54:46 wer:336]

[NeMo I 2026-07-01 12:54:46 wer:337] WER reference:bạn có thể ghé thăm nó
[NeMo I 2026-07-01 12:54:46 wer:338] WER predicted:bạn có thể g nghĩa tha nó
[NeMo I 2026-07-01 12:54:54 wer:336]

[NeMo I 2026-07-01 12:54:54 wer:337] WER reference:các anh sẽ mãi là những người con ưu tú của tổ quốc của nhân dân việt nam
[NeMo I 2026-07-01 12:54:54 wer:338] WER predicted:các anh xem hay là những người conuú tổ quốc của nhân dân việt nam
[NeMo I 2026-07-01 12:55:03 wer:336]

[NeMo I 2026-07-01 12:55:03 wer:337] WER reference:để luôn có một bình hoa tươi mới
[NeMo I 2026-07-01 12:55:03 wer:338] WER predicted:để luôn có một bệnh hoa tôi mới
[NeMo I 2026-07-01 12:55:11 wer:336]

[NeMo I 2026-07-01 12:55:11 wer:337] WER reference:chúc bạn đọc có thật nhiều thời gian thư giãn thoải mái
[NeMo I 2026-07-01 12:55:11 wer:338] WER predicted:ch bạn đọc có thật nhiều thời gian thứ d ở tôiiá
[NeMo I 2026-07-01 12:55:20 wer:336]

[NeMo I 2026-07-01 12:55:20 wer:337] WER reference:bất chấp sự ngăn cản của cơ quan chức năng
[NeMo I 2026-07-01 12:55:20 wer:338] WER predicted:bập sự năngạ của cơ quan nước năng
[NeMo I 2026-07-01 12:55:28 wer:336]

[NeMo I 2026-07-01 12:55:28 wer:337] WER reference:chỉ có điều cô ta mang giày chiếc váy len dài bằng lông cừu
[NeMo I 2026-07-01 12:55:28 wer:338] WER predicted:chỉ có điều cuộc ta mang giảiiếc với l lên dài bằng l luônm cứ
[NeMo I 2026-07-01 12:55:37 wer:336]

[NeMo I 2026-07-01 12:55:37 wer:337] WER reference:thánh nhân đãi khù khờ chính là chỗ này
[NeMo I 2026-07-01 12:55:37 wer:338] WER predicted:thành nhân ra khu thời chỉ là chủ này
[NeMo I 2026-07-01 12:55:45 wer:336]

[NeMo I 2026-07-01 12:55:45 wer:337] WER reference:cô bé rất lấy làm vui mừng và làm quen với những nốt nhạc đầu tiên bằng chính chiếc đàn đồ chơi ấy
[NeMo I 2026-07-01 12:55:45 wer:338] WER predicted:có bé rất làm vui và làm quan với nhữngạ đầu tiên trên bạn chính ch đang được chơi ấy
[NeMo I 2026-07-01 12:55:54 wer:336]


Validation: |          | 0/? [00:00<?, ?it/s]

[NeMo I 2026-07-01 12:58:58 wer:336]

[NeMo I 2026-07-01 12:58:58 wer:337] WER reference:những con vật này đã bị giết và đốt
[NeMo I 2026-07-01 12:58:58 wer:338] WER predicted:nh con vật này đã bị d vàốc
[NeMo I 2026-07-01 12:58:58 wer:336]

[NeMo I 2026-07-01 12:58:58 wer:337] WER reference:do vậy có máy cũng không thường dùng
[NeMo I 2026-07-01 12:58:58 wer:338] WER predicted:do vậy có mấy cũng không thường dụng
[NeMo I 2026-07-01 12:58:58 wer:336]

[NeMo I 2026-07-01 12:58:58 wer:337] WER reference:đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
[NeMo I 2026-07-01 12:58:58 wer:338] WER predicted:đây sẽ là cuộc g gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
[NeMo I 2026-07-01 12:58:58 wer:336]

[NeMo I 2026-07-01 12:58:58 wer:337] WER reference:sau đó một vật lạ bay xợt ngang nóc nhà ông
[NeMo I 2026-07-01 12:58:58 wer:338] WER predicted:sau đó một và là b sự ng năngn nốc nhau
[NeMo I 2026-07-01 12:58:58 wer:336]

[NeMo I 2026-07-01 12:58:58 wer:337] WER reference:hiện ra tận phía xa
[NeMo I 2026-07-01 12:58:58 wer:338] WER predicted:hiện ra tình phía xa
[NeMo I 2026-07-01 12:58:58 wer:336]

[NeMo I 2026-07-01 12:58:58 wer:337] WER reference:nên với thông tin này
[NeMo I 2026-07-01 12:58:58 wer:338] WER predicted:nên với thông tiền này
[NeMo I 2026-07-01 12:58:58 wer:336]

[NeMo I 2026-07-01 12:58:58 wer:337] WER reference:và dân dã như chính cái tên của nó
[NeMo I 2026-07-01 12:58:58 wer:338] WER predicted:và dân gia như chính cái trên của nó
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:sau nhiều pha hảm thành liên tục
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:sau nhiều phá h thành liên tục
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:anh vẫn nhớ kỷ niệm cầu đầu lâu
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:anh v vẫn nhớ kỳiềm cầu đầu lâu
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:gay go lắm nhưng hoàng anh gia lai sẽ làm được
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:g g lắm nhưng hơn anh gia là sẽ làm được
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:do đó khi chơi chung với bạn bè cùng lứa chúng thường tỏ ra thiếu tự tin
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:do đó khi tr chơi chúng với bạn bé cũng lư chúng ta thường tôi cả thiếu từ tính
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:mối đục luỗng cả tấm gỗ
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:mới được luôn cả t tâm g
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:người ta cho rằng trung tâm này có khả năng ảnh hưởng đến quá trình lão hóa
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:người ta cho rằng trung tâm này có khá năng anh hướng đến quá trên lao hoa
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:các giò phong lan tháng ba cũng không chịu yên mình
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:các cho phẩm lên tha ba cũng công chịu ý mình
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:hãy cho tôi quyền năng vô tận để bảo vệ loài vật
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:hay cho tôi viên năng vô tăng để bảo về loi vật
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:sáng chiều hội diễn tiếng hát bảo minh do công ty bảo hiểm bảo minh tổ chức
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:sáng chịu hỏi diễn tiếng khác đầu mình do công ty bảo em báo mình tôi chức
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:cô nằm thiếp đi lúc nào không biết
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:cô năm tiếp đi lúc nào không biết
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:mười bảy mười tám mười chín
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:mươi bảy mươi tám mươi chín
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:tích cóp đủ thứ đồ lạc xon những ngọn đèn
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:tiếpốc đưa thứ đồ đ đã số những ngọ đang
[NeMo I 2026-07-01 12:58:59 wer:336]

[NeMo I 2026-07-01 12:58:59 wer:337] WER reference:nhưng đất nước đã chọn một nhà lãnh đạo khác
[NeMo I 2026-07-01 12:58:59 wer:338] WER predicted:nhưng nước nước đã chọn một nhà lên đầu khác
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:ưu thế này có được là nhờ quá trình cơ giới hóa nhanh sử dụng phân bón cho dù hậu quả có là
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:uống thế này có được là nhớ quá trình cơ giới hoa nhanh sự dụng phần bốn cho dụnghầu quả có làm
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:thường xuyên xảy ra hiện tượng đạo văn quỵt nhuận bút
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:thường xuyên x ra hiện thường đào văn quyết nhút
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:chỉ cho chúng tôi xem hàng đống gạch đá cát sỏi
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:chỉ cho chúng tôi xem hàng đồng cả đã các số
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:đối với cảng hàng không quốc tế đà nẵng sử dụng nhà ga hành khách hiện hữu làm nhà ga nội địa
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:đối với càng hàng không quốc tế đã năng sự dụng nhà gia hành khách hiện hồ làm nhà g nói để
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:người giàu thì vác nặng những xâu tiền kẽm trên vai
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:ngườiào thì vật nạ những sau tiềnk trên phải
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:các nữ công nhân làm ca đêm
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:các nữ công nhân làm cả điểm
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:tui biết bà giỏi rồi
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:tôi biết ba di rồi
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:đưa một chú bồ câu bay đi bay về
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:đường một chú bộ cầu bảy đi bị v về
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:tôi đến kiểm tra và phát hiện thấy ông và cô gái nằm kia thám tử ra hiệu cho ngài triệu phú nhìn vào phòng tắm cô ta đã chết
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:tôi đến kiểm ra và phát hiện thấy ông và cô gái nămk tha từ ra hiểu cho ngày chịu phương nhìn vào phòng tâm cô đã chết
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:để thực hiện thắng lợi kế hoạch năm năm
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:để thực hiện thân lại cái hết năm năm
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:trước khi hóa thân thành cộng hòa sét để đến bồ đào nha
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:trước khi hoa thân thành còn hoa sức để đến bộ đồng nhà
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:tuy nhiên tôi không chắc những người chưa từng đọc cuốn nhật ký có thể hiểu hết được ý nghĩa bộ phim
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:tuy nhiên tôi không chắc những người chưa từ đọc cũng nhất kỳ có thể hiểu hết được ý nghĩ bộ phim
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:chi đầu tư từ khu vực nhà nước còn lớn và hiệu quả thấp
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:chỉ đầu tư từ khu vực nhà n nước còn lớn và hiệu quá th hợp
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:cái nền xưa của nó bây giờ là một cái hố nông choèn
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:cái nên s của nó bị giờ là một cái hồ n năm tr
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:giải truyền thông điện ảnh trung quốc là giải thưởng điện ảnh duy nhất xét trao cho tất cả các bộ phim hoa ngữ
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:giải trên thường đến anh chúng quốc là dài thường đến anh gì sẽ cho cho tất cả các bộ hiện hoànư
[NeMo I 2026-07-01 12:59:00 wer:336]

[NeMo I 2026-07-01 12:59:00 wer:337] WER reference:dự đoán ba tháng nữa giá cà phê sẽ tăng gấp đôi hiện nay
[NeMo I 2026-07-01 12:59:00 wer:338] WER predicted:điều rằng ba tháng nữa giá và về s tăng gặp đôi hiện này
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:họ đến đây vì nhiều mục đích
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:họ đến đâyì nhiều một đích
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:vậy trước đây nông dân đối phó với hiện tượng này như thế nào thưa ông
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:vậy trước đây n năm nhân đối phố v với hiện từ này như đến nào thu  ông
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:làm sao để có tiền nhanh nhất
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:làm sao để có tiền nhân nhất
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:đùi dang ra ngoài
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:được gian ra ngoài
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:đã hai lần cô gác lại ước mơ vào đời và cũng đã ít nhiều trải qua những thăng trầm xô bồ của cuộc sống
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:đã hai l lần cô gái lạiút mới vào đời và cũng đã  ít nhiều trái qua những tha tr số bộ của cuộc sống
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:trong bối cảnh như vậy một phản ứng chính sách đối với vấn đề thất nghiệp đang là đòi hỏi cấp bách hiện nay
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:trong bộ cảnh như vậy một phầnững chính sách đối với vẫn để nghiệpp đang là đời họ cách cách hiện này
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:ở xứ sở chuột túi
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:ở s sơ tr chủ tôi
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:do vậy dựa trên cơ sở nào mà ông khoa phát biểu như vậy
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:do vậy dự trên cơ s nào ông khoa phát biểu như vậy
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:tá tàng
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:ta tăng
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:cách đây tám năm nhưng trước đó khoảng hai năm đã được mời đóng phim và có nhiều vai chính trong các phim điện ảnh truyền hình
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:cách đây tâm năm nh trước đó hoàn hai năm đã được mới động phim và có nhiều và chính trong các phim điện anh truyền hình
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:đã thăm hỏi thì thế nào cũng phải có quà cáp
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:đã tâmm họ thì thế nào cũng phải có quả các
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:có mặt tạià điện phòng
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:em lơ đễnh lật xem vài tờ báo
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:em là điện l xem vàờ báo
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:và không ít người cứ tì tì uống từ sáng đến tối suốt mấy ngày hội nghị
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:và không ít người cứ ty từ  uống từ sáng đến tôi xuất máy ngày hội này
[NeMo I 2026-07-01 12:59:01 wer:336]

[NeMo I 2026-07-01 12:59:01 wer:337] WER reference:minh châu vào miền nam công tác tại nhà hát trần hữu trang
[NeMo I 2026-07-01 12:59:01 wer:338] WER predicted:mình cao vào m nam công tất tại nhà ho rằng h rằng
[NeMo I 2026-07-01 12:59:02 wer:336]

[NeMo I 2026-07-01 12:59:02 wer:337] WER reference:hết chiến tranh quê hương im tiếng súng anh lính cụ hồ lại trở về với đời thường tham gia sản xuất xây dựng và bảo vệ đất nước
[NeMo I 2026-07-01 12:59:02 wer:338] WER predicted:hết tiếng trên với hơn ý tiếng xuống anh lên của hồ lại cho về với đời thường tham giá sản xuất sẽ d vào b với đất nước
[NeMo I 2026-07-01 12:59:02 wer:336]

[NeMo I 2026-07-01 12:59:02 wer:337] WER reference:chuyến đi đó đến giờ vẫn là một ám ảnh trong ký ức tôi
[NeMo I 2026-07-01 12:59:02 wer:338] WER predicted:chỉ đi đó đến giờ vẫn là một ông anh trong chỉ
[NeMo I 2026-07-01 12:59:02 wer:336]

[NeMo I 2026-07-01 12:59:02 wer:337] WER reference:ây da ây da
[NeMo I 2026-07-01 12:59:02 wer:338] WER predicted:giá gia
[NeMo I 2026-07-01 12:59:02 wer:336]

[NeMo I 2026-07-01 12:59:02 wer:337] WER reference:có rất nhiều vệ tinh bị rơi khỏi quỹ đạo
[NeMo I 2026-07-01 12:59:02 wer:338] WER predicted:rất nhiều về tính bị rồi khó quy nào
[NeMo I 2026-07-01 12:59:02 wer:336]

[NeMo I 2026-07-01 12:59:02 wer:337] WER reference:nhuốm đầy máu của thổ dân châu mỹ
[NeMo I 2026-07-01 12:59:02 wer:338] WER predicted:nhóm đây m máu của thủ dân cho mỹ
[NeMo I 2026-07-01 12:59:02 wer:336]

[NeMo I 2026-07-01 12:59:02 wer:337] WER reference:cụ thể về đất đai xây dựng văn hóa thuộc về từng ngành riêng biệt
[NeMo I 2026-07-01 12:59:02 wer:338] WER predicted:cô thể về đất đây văn sẽ những văn hoa thuốc về từ ngành riêng biết
[NeMo I 2026-07-01 12:59:02 wer:336]

[NeMo I 2026-07-01 12:59:02 wer:337] WER reference:tôi muốn hỏi liệu có mùi hương sen nhân tạo là một loại hóa chất không
[NeMo I 2026-07-01 12:59:02 wer:338] WER predicted:tôi muốn hỏi liệu có mười hướng s nhân tạo là một loại họ chắc cao
[NeMo I 2026-07-01 12:59:02 wer:336]

[NeMo I 2026-07-01 12:59:02 wer:337] WER reference:cả nhà bà ngoại cười nắc nẻ vì câu nói ngây ngô của con
[NeMo I 2026-07-01 12:59:02 wer:338] WER predicted:các nhà bao ngoài người nước ngheì cô nói ngày ngủ của con
[NeMo I 2026-07-01 12:59:02 wer:336]

[NeMo I 2026-07-01 12:59:02 wer:337] WER reference:xin được chân khuân vác
[NeMo I 2026-07-01 12:59:02 wer:338] WER predicted:xin được trên khu phát
[NeMo I 2026-07-01 12:59:02 wer:336]

[NeMo I 2026-07-01 12:59:02 wer:337] WER reference:nằm khuất dưới tàn tre sát bờ sông châu
[NeMo I 2026-07-01 12:59:02 wer:338] WER predicted:ho giới đàn trẻ sẽ bà sống ch
[NeMo I 2026-07-01 12:59:02 wer:336]

[NeMo I 2026-07-01 12:59:02 wer:337] WER reference:nếu kiên cố hóa thì vốn được đưa thẳng cho dân sẽ không thất thoát
[NeMo I 2026-07-01 12:59:02 wer:338] WER predicted:nếu ki cô hoa thì bốn được đưa tăng cho dân sẽ không thật
[NeMo I 2026-07-01 12:59:02 wer:336]

[NeMo I 2026-07-01 12:59:02 wer:337] WER reference:nói chung cô hồng nào cũng có một số phận hoàn cảnh và cuộc đời riêng
[NeMo I 2026-07-01 12:59:02 wer:338] WER predicted:nói chúng cô học nào cũng có một số phần hoàn cảnhnh với cuộc đời riêng
[NeMo I 2026-07-01 12:59:02 wer:336]

[NeMo I 2026-07-01 12:59:02 wer:337] WER reference:nhưng tất cả những điều ấy chẳng mấy khi đi liền với nhau
[NeMo I 2026-07-01 12:59:02 wer:338] WER predicted:những tất cả những điều ấy ch mấy khi đi liên với nhau
[NeMo I 2026-07-01 12:59:02 wer:336]

[NeMo I 2026-07-01 12:59:02 wer:337] WER reference:như vậy là bạn có thể sử dụng được nhiều số điện thoại của nhiều nhà cung cấp dịch vụ chỉ trên một sim
[NeMo I 2026-07-01 12:59:02 wer:338] WER predicted:như vậy bạn có thể sự dụng được nhiều số đến th của như nhà cũng cấp dịch vụ chỉ trên một xem
[NeMo I 2026-07-01 12:59:02 wer:336]

[NeMo I 2026-07-01 12:59:02 wer:337] WER reference:trong trường hợp hai bên có thỏa thuận lại không yêu cầu trọng tài giải quyết nữa thì có quyền kiện ra tòa án
[NeMo I 2026-07-01 12:59:02 wer:338] WER predicted:trong trường hợp hai bên có thể thường lại không yêu cầu trong ta d quyết nữa thì có quyền kiến ra toàn ăn
[NeMo I 2026-07-01 12:59:03 wer:336]

[NeMo I 2026-07-01 12:59:03 wer:337] WER reference:kiểu này chắc phải cắt giảm biên chế
[NeMo I 2026-07-01 12:59:03 wer:338] WER predicted:kiể này chắc phải các giảm biến chế
[NeMo I 2026-07-01 12:59:03 wer:336]

[NeMo I 2026-07-01 12:59:03 wer:337] WER reference:nhưng tôi không yêu cô cô biết rõ điều đó mà
[NeMo I 2026-07-01 12:59:03 wer:338] WER predicted:nhưng tôi không yêu cô cô biết rồi điều đó mà
[NeMo I 2026-07-01 12:59:03 wer:336]

[NeMo I 2026-07-01 12:59:03 wer:337] WER reference:khó mà đoán trước chính xác kết quả khi quả bóng còn lăn
[NeMo I 2026-07-01 12:59:03 wer:338] WER predicted:khó mà đó trước chính sẽích quả khi qua b bóng con
[NeMo I 2026-07-01 12:59:03 wer:336]

[NeMo I 2026-07-01 12:59:03 wer:337] WER reference:vừa nhìn thấy sự xuất hiện của bố tất cả mấy thằng khác vùng bỏ chạy sạch
[NeMo I 2026-07-01 12:59:03 wer:338] WER predicted:ừa nh thấy sự sự hiện của bố tất cả máy th thành khác vùng bỏi trẻ sách
[NeMo I 2026-07-01 12:59:03 wer:336]

[NeMo I 2026-07-01 12:59:03 wer:337] WER reference:phải nâng cao khả năng cạnh tranh của nền kinh tế
[NeMo I 2026-07-01 12:59:03 wer:338] WER predicted:phải năng cao kh năng cảnh trên của nên kinh tên
[NeMo I 2026-07-01 12:59:03 wer:336]

[NeMo I 2026-07-01 12:59:03 wer:337] WER reference:bà thường lấy ý tưởng cho các tác phẩm từ đâu
[NeMo I 2026-07-01 12:59:03 wer:338] WER predicted:bà thườngấy ý từ cho các tác phẩm từ đồng
[NeMo I 2026-07-01 12:59:03 wer:336]

[NeMo I 2026-07-01 12:59:03 wer:337] WER reference:khi chứng kiến người vợ lăng loàn
[NeMo I 2026-07-01 12:59:03 wer:338] WER predicted:khi chứng kiến người vào l lần lòng
[NeMo I 2026-07-01 12:59:03 wer:336]

[NeMo I 2026-07-01 12:59:03 wer:337] WER reference:tác phẩm to lớn bằng đồng như tượng phật quỳnh lâm chuông quy điền tháp báo thiên vạc phổ minh an nam tứ đại khí
[NeMo I 2026-07-01 12:59:03 wer:338] WER predicted:ta phẩm ta lớn bạn đồng như tượng phát qu lắm chúng qu điện th bảo tìm và phố mình ăn nam tư đây khi
[NeMo I 2026-07-01 12:59:03 wer:336]

[NeMo I 2026-07-01 12:59:03 wer:337] WER reference:ngoài ra họ vẫn còn muốn giữ chân cầu thủ xuất sắc nhất của mình
[NeMo I 2026-07-01 12:59:03 wer:338] WER predicted:họ vẫn cầu muốnư chân cầu thủ xuất s
[NeMo I 2026-07-01 12:59:03 wer:336]

[NeMo I 2026-07-01 12:59:03 wer:337] WER reference:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 12:59:03 wer:338] WER predicted:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 12:59:03 wer:336]

[NeMo I 2026-07-01 12:59:03 wer:337] WER reference:và gã thệ bị điều về làm trưởng phòng xã hội huyện
[NeMo I 2026-07-01 12:59:03 wer:338] WER predicted:và cả thể biết điều về làm trường phần xã hộii h
[NeMo I 2026-07-01 12:59:03 wer:336]

[NeMo I 2026-07-01 12:59:03 wer:337] WER reference:là rút rỉa tiền của bạn càng nhiều càng tốt

[NeMo W 2026-07-01 12:59:18 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 12:59:18 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

[best val_wer] epoch=9 val_wer=0.443027 exported=/kaggle/working/phase3_continue_best.nemo

Sample predictions after epoch 9:
  [0] REF: những con vật này đã bị giết và đốt
      HYP: nh con vật này đã bị d vàốc
  [1] REF: phòng chống tham nhũng không được chủ quan cần làm liên tục đồng bộ và có các giải pháp
      HYP: phòng trong tham nh dụng không được chủ quan cần làm liên tục động bộ và có các đại pháp
  [2] REF: do vậy có máy cũng không thường dùng
      HYP: do vậy có mấy cũng không thường dụng
  [3] REF: mới khệnh khạng đứng lên đi ra
      HYP: mới kh khá đứng lên đi ra
  [4] REF: đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
      HYP: đây sẽ là cuộc gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
  [5] REF: sau một năm eo sèo
      HYP: sáu một năm yêu xe
  [6] REF: sau đó một vật lạ bay xợt ngang nóc nhà ông
      HYP: sau đó một và là b sự ng năngn nốc nhau
  [7] REF: chín mươi hai chín mươi ba
      HYP: chín mươi hai chín mươi ba
  [8] REF: hiện ra tận phía xa
      HYP: hiện ra tình phía xa
  [9] REF: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã qua của thị trường
      HYP: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã quá của thì trường
[epoch] epoch=9/12 step=2826 val_loss=2.1137197017669678 val_wer=0.44302666187286377
[NeMo I 2026-07-01 12:59:48 wer:336]

[NeMo I 2026-07-01 12:59:48 wer:337] WER reference:rất nhiều trường hợp phụ huynh đau đầu vì con một đã tìm đến chuyên viên tư vấn tâm lý
[NeMo I 2026-07-01 12:59:48 wer:338] WER predicted:rất người trường học phụ kh đâu đầuì anh một đã tìm đến trên viên tư anh tâm lý
[NeMo I 2026-07-01 12:59:57 wer:336]

[NeMo I 2026-07-01 12:59:57 wer:337] WER reference:trước tình thế đó tôi buộc phải tìm cho mình một bến đỗ mới và tôi đã quyết định ra đi
[NeMo I 2026-07-01 12:59:57 wer:338] WER predicted:lúc tình thế đó tôi bộ phải tiền cho mình một bên đ đầu mới và tôi đã quyết bệnh ra đi
[NeMo I 2026-07-01 13:00:05 wer:336]

[NeMo I 2026-07-01 13:00:05 wer:337] WER reference:tuy nhiên tình hình đó không diễn ra ở tất cả trường
[NeMo I 2026-07-01 13:00:05 wer:338] WER predicted:tuy nhiên tình hình đó không diễná ở tất cả tr trường
[NeMo I 2026-07-01 13:00:14 wer:336]

[NeMo I 2026-07-01 13:00:14 wer:337] WER reference:nếu xét trên qui mô toàn tỉnh con số ấy vẫn còn khiêm tốn lắm
[NeMo I 2026-07-01 13:00:14 wer:338] WER predicted:nên x chỉ phí mua toàn tình cầu số ấy vẫn còn khiù làm
[NeMo I 2026-07-01 13:00:22 wer:336]

[NeMo I 2026-07-01 13:00:22 wer:337] WER reference:các vùng sâu vùng xa khó mà phát triển
[NeMo I 2026-07-01 13:00:22 wer:338] WER predicted:các vùng sau vùng sẽ khó mà phát triển
[NeMo I 2026-07-01 13:00:31 wer:336]

[NeMo I 2026-07-01 13:00:31 wer:337] WER reference:thì không hiểu sao ở phần thơ cổ đại
[NeMo I 2026-07-01 13:00:31 wer:338] WER predicted:thì không hiểu sao ở phần hết của đầy
[NeMo I 2026-07-01 13:00:40 wer:336]

[NeMo I 2026-07-01 13:00:40 wer:337] WER reference:anh muốn thùy có thể tự do tìm cho mình một hạnh phúc khác tràn đầy
[NeMo I 2026-07-01 13:00:40 wer:338] WER predicted:anh muốn thì có thể từ do tìm cho mình một thành ph khác ngày lại
[NeMo I 2026-07-01 13:00:48 wer:336]

[NeMo I 2026-07-01 13:00:48 wer:337] WER reference:áo thun trắng sát nách
[NeMo I 2026-07-01 13:00:48 wer:338] WER predicted:áo thu trang sát nắc
[NeMo I 2026-07-01 13:00:56 wer:336]

[NeMo I 2026-07-01 13:00:56 wer:337] WER reference:đây cũng là giai đoạn thị trường nhiều biến cố nhất
[NeMo I 2026-07-01 13:00:56 wer:338] WER predicted:đây cũng là chế đồng thì trường nhiều biến cô nhất
[NeMo I 2026-07-01 13:01:05 wer:336]

[NeMo I 2026-07-01 13:01:05 wer:337] WER reference:mới thành món ngon và độc đáo
[NeMo I 2026-07-01 13:01:05 wer:338] WER predicted:mới thành m món ngon và được đâu
[NeMo I 2026-07-01 13:01:14 wer:336]

[NeMo I 2026-07-01 13:01:14 wer:337] WER reference:người đẹp không thiếu chỉ sợ ông anh không có tiền
[NeMo I 2026-07-01 13:01:14 wer:338] WER predicted:người để không thiếu chỉ s ông anh không có tình
[NeMo I 2026-07-01 13:01:22 wer:336]

[NeMo I 2026-07-01 13:01:22 wer:337] WER reference:ngày thường chù ụ thì được
[NeMo I 2026-07-01 13:01:22 wer:338] WER predicted:ngày thường chủổ chỉ được
[NeMo I 2026-07-01 13:01:31 wer:336]

[NeMo I 2026-07-01 13:01:31 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 13:01:31 wer:338] WER predicted:có mặt tại sẽ điện phương
[NeMo I 2026-07-01 13:01:40 wer:336]

[NeMo I 2026-07-01 13:01:40 wer:337] WER reference:tôi cũng biết có những tiêu cực trong giáo dục và nhà trường cũng như những lĩnh vực khác của xã hội
[NeMo I 2026-07-01 13:01:40 wer:338] WER predicted:tôi cũng biết có những tiêu thực trong giá được và nhà trường của như những lên vợ h của xã hội
[NeMo I 2026-07-01 13:01:48 wer:336]

[NeMo I 2026-07-01 13:01:48 wer:337] WER reference:xắn quần vượt qua là bước vào thế giới
[NeMo I 2026-07-01 13:01:48 wer:338] WER predicted:sốngn qu v qua là bước vào thế giới
[NeMo I 2026-07-01 13:01:57 wer:336]

[NeMo I 2026-07-01 13:01:57 wer:337] WER reference:mới và cải tiến
[NeMo I 2026-07-01 13:01:57 wer:338] WER predicted:mới và cái tiền
[NeMo I 2026-07-01 13:02:05 wer:336]

[NeMo I 2026-07-01 13:02:05 wer:337] WER reference:hai vợ chồng thị tớn và văn đục
[NeMo I 2026-07-01 13:02:05 wer:338] WER predicted:hai vợ trong thì tưởng và văn được
[NeMo I 2026-07-01 13:02:14 wer:336]

[NeMo I 2026-07-01 13:02:14 wer:337] WER reference:chợ đêm ca ba dành cho những người đang vào mùa tăng ca cuối năm
[NeMo I 2026-07-01 13:02:14 wer:338] WER predicted:ở đến có ba danh cho những người đang vào một ta cả cứ năm
[NeMo I 2026-07-01 13:02:23 wer:336]

[NeMo I 2026-07-01 13:02:23 wer:337] WER reference:hai mươi hai mươi mốt
[NeMo I 2026-07-01 13:02:23 wer:338] WER predicted:hai mươi hai mươi mốt
[NeMo I 2026-07-01 13:02:31 wer:336]

[NeMo I 2026-07-01 13:02:31 wer:337] WER reference:anh không thể quên được những giây phút ngọt ngào ấy
[NeMo I 2026-07-01 13:02:31 wer:338] WER predicted:anh không được quan được nh ph gian ngọ nào ấy
[NeMo I 2026-07-01 13:02:40 wer:336]

[NeMo I 2026-07-01 13:02:40 wer:337] WER reference:đưa tới tình trạng phá sản
[NeMo I 2026-07-01 13:02:40 wer:338] WER predicted:ưa tư tiền rằng phá sản
[NeMo I 2026-07-01 13:02:48 wer:336]

[NeMo I 2026-07-01 13:02:48 wer:337] WER reference:phụ huynh và học sinh đang phải è cổ vì sách giá cao
[NeMo I 2026-07-01 13:02:48 wer:338] WER predicted:vụ qu và học sinh đang phải em cô vì sách gia cao
[NeMo I 2026-07-01 13:02:57 wer:336]

[NeMo I 2026-07-01 13:02:57 wer:337] WER reference:thỉnh thoảng lại có người ghép thận trước đó trở qua xin xét nghiệm vì có trục trặc
[NeMo I 2026-07-01 13:02:57 wer:338] WER predicted:tình toàn lại có người g thằ tư và tôi qua sinh sẽ nhiều về cóục đọc
[NeMo I 2026-07-01 13:03:06 wer:336]

[NeMo I 2026-07-01 13:03:06 wer:337] WER reference:cuộc thi nhằm trau dồi niềm đam mê
[NeMo I 2026-07-01 13:03:06 wer:338] WER predicted:cuộc thi nhm tr d nhiệm đã mẹ
[NeMo I 2026-07-01 13:03:14 wer:336]

[NeMo I 2026-07-01 13:03:14 wer:337] WER reference:đề thi môn vẽ thông thường là về vẽ trang trí sản phẩm vật thể
[NeMo I 2026-07-01 13:03:14 wer:338] WER predicted:để thi muốn v vẻ hô thường là về về sáng chỉ sản phẩm một thể
[NeMo I 2026-07-01 13:03:23 wer:336]

[NeMo I 2026-07-01 13:03:23 wer:337] WER reference:bước vào một mối tình
[NeMo I 2026-07-01 13:03:23 wer:338] WER predicted:bước vào một mua tình
[NeMo I 2026-07-01 13:03:31 wer:336]

[NeMo I 2026-07-01 13:03:31 wer:337] WER reference:lão nạp chỉ có nhiêu đây thôi
[NeMo I 2026-07-01 13:03:31 wer:338] WER predicted:làạ chỉ có như lại tôi
[NeMo I 2026-07-01 13:03:40 wer:336]

[NeMo I 2026-07-01 13:03:40 wer:337] WER reference:hai tuần sau
[NeMo I 2026-07-01 13:03:40 wer:338] WER predicted:hai tuần sáu
[NeMo I 2026-07-01 13:03:48 wer:336]

[NeMo I 2026-07-01 13:03:48 wer:337] WER reference:những ngày cuối cùng trên dương thế
[NeMo I 2026-07-01 13:03:48 wer:338] WER predicted:những này cuối cùng trên dân thế
[NeMo I 2026-07-01 13:03:57 wer:336]

[NeMo I 2026-07-01 13:03:57 wer:337] WER reference:trên nhiều tuyến phố công nhân đang hối hả dọn dẹp
[NeMo I 2026-07-01 13:03:57 wer:338] WER predicted:trên nhiều tiếng ph công nh đang hội hệ động nghiệpp
[NeMo I 2026-07-01 13:04:05 wer:336]

[NeMo I 2026-07-01 13:04:05 wer:337] WER reference:có trường hợp bất hợp pháp như trần thị thu h
[NeMo I 2026-07-01 13:04:05 wer:338] WER predicted:có chuyện học bất hợp pháp như trong thì thu
[NeMo I 2026-07-01 13:04:14 wer:336]

[NeMo I 2026-07-01 13:04:14 wer:337] WER reference:nhưng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được các khó khăn đó
[NeMo I 2026-07-01 13:04:14 wer:338] WER predicted:chúng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được cả khó không đó
[NeMo I 2026-07-01 13:04:22 wer:336]

[NeMo I 2026-07-01 13:04:22 wer:337] WER reference:lúc đó em không thể tiếp tục công việc đánh cá của cha một mình vì còn quá nhỏ
[NeMo I 2026-07-01 13:04:22 wer:338] WER predicted:lúc đó em không phải tiếp được không việcánh các của tra một mình việc còn qua nhỏ
[NeMo I 2026-07-01 13:04:31 wer:336]

[NeMo I 2026-07-01 13:04:31 wer:337] WER reference:cuốn sách nói về sự lầm lẫn giữa luật kinh tế ở châu âu và châu mỹ kim vẫn chưa đọc tới vì cô không quan tâm đến luật
[NeMo I 2026-07-01 13:04:31 wer:338] WER predicted:cũng sinh nói về làm lần nhiều được ki tế ở ch ông và trong muốn cho vẫn chưa đọc tôi việc của không quan tăng đến luật
[NeMo I 2026-07-01 13:04:40 wer:336]

[NeMo I 2026-07-01 13:04:40 wer:337] WER reference:khi tên lửa bay lên
[NeMo I 2026-07-01 13:04:40 wer:338] WER predicted:khi tên l lời vậy lên
[NeMo I 2026-07-01 13:04:48 wer:336]

[NeMo I 2026-07-01 13:04:48 wer:337] WER reference:mà theo thời gian sẽ tiệm cận với trí khôn của con người
[NeMo I 2026-07-01 13:04:48 wer:338] WER predicted:mà theo thời dân sẽ tìm cần với trí không quốc con người
[NeMo I 2026-07-01 13:04:57 wer:336]

[NeMo I 2026-07-01 13:04:57 wer:337] WER reference:bên kia láng giềng của tôi hôm nay không thấy thăm hoa
[NeMo I 2026-07-01 13:04:57 wer:338] WER predicted:đến kia lan diễn của tôi hô này không thấy th h
[NeMo I 2026-07-01 13:05:05 wer:336]

[NeMo I 2026-07-01 13:05:05 wer:337] WER reference:anh yêu cầu các cầu thủ phải đeo bám ngay khi đối phương có bóng
[NeMo I 2026-07-01 13:05:05 wer:338] WER predicted:anh nhiều cầu các cầu số phảieo bạn ngày khi đối phương có
[NeMo I 2026-07-01 13:05:14 wer:336]

[NeMo I 2026-07-01 13:05:14 wer:337] WER reference:ngay cả công an đi lẻ loi cũng bị tấn công vì trong khu vực này có một thứ luật riêng cấm người lạ vào
[NeMo I 2026-07-01 13:05:14 wer:338] WER predicted:nghe và không mình đi lẽ cũng bị không con việc trong có việc mẹ một thứ lực viên công như l
[NeMo I 2026-07-01 13:05:22 wer:336]

[NeMo I 2026-07-01 13:05:22 wer:337] WER reference:thì chúng sẽ nằm trong tầm kiểm soát của bạn
[NeMo I 2026-07-01 13:05:22 wer:338] WER predicted:thì chúng sẽ năm trong đầm kiể sau của bạn
[NeMo I 2026-07-01 13:05:31 wer:336]

[NeMo I 2026-07-01 13:05:31 wer:337] WER reference:đó là hai con sói hoàn toàn trái ngược nhau về hình thức
[NeMo I 2026-07-01 13:05:31 wer:338] WER predicted:đó là hay con s hộ còn chính được nhau về hình thức
[NeMo I 2026-07-01 13:05:40 wer:336]

[NeMo I 2026-07-01 13:05:40 wer:337] WER reference:trại đồng xã yên sở giữa một biển nước mênh mông ảnh nguyễn quân
[NeMo I 2026-07-01 13:05:40 wer:338] WER predicted:tr đồng xã em s giờ một biểnứ mình món  anh nguyên quan
[NeMo I 2026-07-01 13:05:48 wer:336]

[NeMo I 2026-07-01 13:05:48 wer:337] WER reference:không sao rồi em mừng lắm
[NeMo I 2026-07-01 13:05:48 wer:338] WER predicted:không sao rồi em mình lắm
[NeMo I 2026-07-01 13:05:57 wer:336]

[NeMo I 2026-07-01 13:05:57 wer:337] WER reference:việc tòa án của pháp truy tố công dân một nước độc lập trên lãnh thổ quê hương của người ấy là một điều vô giá trị
[NeMo I 2026-07-01 13:05:57 wer:338] WER predicted:việc tôi ăn cuộc pháp tr tốt người không một được được lập trên l lên tôi cuối hơn còn ở ấy là một bị chú giá trị
[NeMo I 2026-07-01 13:06:05 wer:336]

[NeMo I 2026-07-01 13:06:05 wer:337] WER reference:bà mẹ nghèo đông con
[NeMo I 2026-07-01 13:06:05 wer:338] WER predicted:bà mẹ nghe vấn con
[NeMo I 2026-07-01 13:06:14 wer:336]

[NeMo I 2026-07-01 13:06:14 wer:337] WER reference:lấy tĩnh chế động
[NeMo I 2026-07-01 13:06:14 wer:338] WER predicted:l liệu tình cho đồng
[NeMo I 2026-07-01 13:06:22 wer:336]

[NeMo I 2026-07-01 13:06:23 wer:337] WER reference:mình mẩy tôi tuy đau đớn
[NeMo I 2026-07-01 13:06:23 wer:338] WER predicted:mình bảy tôi tuy đau đường
[NeMo I 2026-07-01 13:06:31 wer:336]

[NeMo I 2026-07-01 13:06:31 wer:337] WER reference:luôn ngẩng cao đầu sự khác biệt lớn nhất giữa người tự tin và người nhút nhát là gì
[NeMo I 2026-07-01 13:06:31 wer:338] WER predicted:luôn ngn cao đầu x khách người lớn nhỏ d người từ tiếng v người nh nhấtạ là gì
[NeMo I 2026-07-01 13:06:40 wer:336]

[NeMo I 2026-07-01 13:06:40 wer:337] WER reference:với các bạn trẻ trên đây có vẻ tình yêu không phải là tất cả
[NeMo I 2026-07-01 13:06:40 wer:338] WER predicted:với các bạn trẻ chính đây có về tình yêu kh và là tục cả
[NeMo I 2026-07-01 13:06:48 wer:336]

[NeMo I 2026-07-01 13:06:48 wer:337] WER reference:nếu trẻ bú không đủ có thể vắt sữa và cho trẻ uống bằng muỗng
[NeMo I 2026-07-01 13:06:48 wer:338] WER predicted:như trẻú không đủ có thể biết s và tr trẻ  uống bằngôn
[NeMo I 2026-07-01 13:06:57 wer:336]

[NeMo I 2026-07-01 13:06:57 wer:337] WER reference:hãy để thời gian tìm hiểu thêm và thuyết phục gia đình
[NeMo I 2026-07-01 13:06:57 wer:338] WER predicted:hãy để thời gian để mỹ thêm phải thu phục gia đình
[NeMo I 2026-07-01 13:07:05 wer:336]

[NeMo I 2026-07-01 13:07:05 wer:337] WER reference:vân vân và vân vân
[NeMo I 2026-07-01 13:07:05 wer:338] WER predicted:v vẫn bốn và vẫn bốn
[NeMo I 2026-07-01 13:07:14 wer:336]

[NeMo I 2026-07-01 13:07:14 wer:337] WER reference:mà phụ nữ trong khu vực công đang gặp phải
[NeMo I 2026-07-01 13:07:14 wer:338] WER predicted:mà phụ nơi trong khu vực công đang g gặp phải
[NeMo I 2026-07-01 13:07:23 wer:336]

[NeMo I 2026-07-01 13:07:23 wer:337] WER reference:những năm trước phần lớn sếu ở kiên lương kiên giang
[NeMo I 2026-07-01 13:07:23 wer:338] WER predicted:những năm ch phần lên sẽ ở khi lớn ki gia
[NeMo I 2026-07-01 13:07:31 wer:336]

[NeMo I 2026-07-01 13:07:31 wer:337] WER reference:theo nguyên đào kinh tế đô thị
[NeMo I 2026-07-01 13:07:31 wer:338] WER predicted:theo nguyên đào ki tênưa thời
[NeMo I 2026-07-01 13:07:40 wer:336]

[NeMo I 2026-07-01 13:07:40 wer:337] WER reference:nhưng ngủ quá nhiều sẽ khiến bạn trở nên bơ phờ
[NeMo I 2026-07-01 13:07:40 wer:338] WER predicted:nhưng ngủ quá nhiều sẽ khiến bạn trên đến b ph
[NeMo I 2026-07-01 13:07:48 wer:336]

[NeMo I 2026-07-01 13:07:48 wer:337] WER reference:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 13:07:48 wer:338] WER predicted:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 13:07:57 wer:336]

[NeMo I 2026-07-01 13:07:57 wer:337] WER reference:thường xuyên đối mặt với nạn khan hiếm lương thực
[NeMo I 2026-07-01 13:07:57 wer:338] WER predicted:thường x đối mặt với ngành khá hếm luôn thực
[NeMo I 2026-07-01 13:08:05 wer:336]

[NeMo I 2026-07-01 13:08:05 wer:337] WER reference:tôi có cảm tình với cô ấy nhưng tôi không muốn xen vào giữa họ
[NeMo I 2026-07-01 13:08:05 wer:338] WER predicted:tôi có cảm tình với cơ ấyững tôi không muốn xe vào d họ
[NeMo I 2026-07-01 13:08:14 wer:336]

[NeMo I 2026-07-01 13:08:14 wer:337] WER reference:với tôi chết là một sự ích kỷ còn bản chất sự sống đã là một bao dung ít nhất với chính mình
[NeMo I 2026-07-01 13:08:14 wer:338] WER predicted:với tôi chết là một sự kỳ công bạn chất sĩ sống đã một bao g biết nhất với chính mình
[NeMo I 2026-07-01 13:08:22 wer:336]

[NeMo I 2026-07-01 13:08:22 wer:337] WER reference:cậu không biết làm gì thì suốt đời cậu đúng là một kẻ hèn nhát
[NeMo I 2026-07-01 13:08:22 wer:338] WER predicted:cầu không biết làm gì thì xuất đời cầu đúng là một các hàng nhạc
[NeMo I 2026-07-01 13:08:31 wer:336]

[NeMo I 2026-07-01 13:08:31 wer:337] WER reference:màu đen của những tấm cha
[NeMo I 2026-07-01 13:08:31 wer:338] WER predicted:màu đang của những t tâm gia
[NeMo I 2026-07-01 13:08:39 wer:336]

[NeMo I 2026-07-01 13:08:39 wer:337] WER reference:tôi chỉ thấy người ta nhắc đến phượng vĩ tháng sáu hay cùng lắm là tháng năm
[NeMo I 2026-07-01 13:08:39 wer:338] WER predicted:tôi chỉ thấy ngườiáá đến phương vị tình sau hai cũng tám là thành ra
[NeMo I 2026-07-01 13:08:48 wer:336]

[NeMo I 2026-07-01 13:08:48 wer:337] WER reference:với câu trả lời xuất sắc và gương mặt khả ái
[NeMo I 2026-07-01 13:08:48 wer:338] WER predicted:với cô trả lời sức s vàương một khả ai
[NeMo I 2026-07-01 13:08:56 wer:336]

[NeMo I 2026-07-01 13:08:56 wer:337] WER reference:nhưng em có biết rằng anh yêu em cũng bởi những lý do đó
[NeMo I 2026-07-01 13:08:56 wer:338] WER predicted:theo em có biết rằng anh như em cũng mọ những lý do
[NeMo I 2026-07-01 13:09:05 wer:336]

[NeMo I 2026-07-01 13:09:05 wer:337] WER reference:để nhìn thấy sự khôi hài
[NeMo I 2026-07-01 13:09:05 wer:338] WER predicted:để nhìn thấy sự khu hai
[NeMo I 2026-07-01 13:09:13 wer:336]

[NeMo I 2026-07-01 13:09:13 wer:337] WER reference:rèm cửa phòng khách của bạn giống như cung điện
[NeMo I 2026-07-01 13:09:13 wer:338] WER predicted:ra của phòng khách của bạn gi như cũng điện
[NeMo I 2026-07-01 13:09:22 wer:336]

[NeMo I 2026-07-01 13:09:22 wer:337] WER reference:và những khuyết điểm nhỏ của họ
[NeMo I 2026-07-01 13:09:22 wer:338] WER predicted:và những quyết điểm nhà của họ
[NeMo I 2026-07-01 13:09:30 wer:336]

[NeMo I 2026-07-01 13:09:30 wer:337] WER reference:tôi biết đây là quy tắc đòi hỏi
[NeMo I 2026-07-01 13:09:30 wer:338] WER predicted:tôi biết đây là quy tác đòi hỏi
[NeMo I 2026-07-01 13:09:39 wer:336]

[NeMo I 2026-07-01 13:09:39 wer:337] WER reference:cũng trong ngày đó bài xã luận gằn giọng
[NeMo I 2026-07-01 13:09:39 wer:338] WER predicted:cũng trong ngày đó và sến g rằng gi
[NeMo I 2026-07-01 13:09:47 wer:336]

[NeMo I 2026-07-01 13:09:47 wer:337] WER reference:bạn có thể ghé thăm nó
[NeMo I 2026-07-01 13:09:47 wer:338] WER predicted:bạn có thể g nghĩa tha nó
[NeMo I 2026-07-01 13:09:56 wer:336]

[NeMo I 2026-07-01 13:09:56 wer:337] WER reference:các anh sẽ mãi là những người con ưu tú của tổ quốc của nhân dân việt nam
[NeMo I 2026-07-01 13:09:56 wer:338] WER predicted:các anh xem hay là những người conuú tổ quốc của nhân dân việt nam
[NeMo I 2026-07-01 13:10:04 wer:336]

[NeMo I 2026-07-01 13:10:04 wer:337] WER reference:để luôn có một bình hoa tươi mới
[NeMo I 2026-07-01 13:10:04 wer:338] WER predicted:để luôn có một bệnh hoa tôi mới
[NeMo I 2026-07-01 13:10:13 wer:336]

[NeMo I 2026-07-01 13:10:13 wer:337] WER reference:chúc bạn đọc có thật nhiều thời gian thư giãn thoải mái
[NeMo I 2026-07-01 13:10:13 wer:338] WER predicted:ch bạn đọc có thật nhiều thời gian thứ d ở tôiiá
[NeMo I 2026-07-01 13:10:21 wer:336]

[NeMo I 2026-07-01 13:10:21 wer:337] WER reference:bất chấp sự ngăn cản của cơ quan chức năng
[NeMo I 2026-07-01 13:10:21 wer:338] WER predicted:bập sự năngạ của cơ quan nước năng
[NeMo I 2026-07-01 13:10:30 wer:336]

[NeMo I 2026-07-01 13:10:30 wer:337] WER reference:chỉ có điều cô ta mang giày chiếc váy len dài bằng lông cừu
[NeMo I 2026-07-01 13:10:30 wer:338] WER predicted:chỉ có điều cuộc ta mang giảiiếc với l lên dài bằng l luônm cứ
[NeMo I 2026-07-01 13:10:39 wer:336]

[NeMo I 2026-07-01 13:10:39 wer:337] WER reference:thánh nhân đãi khù khờ chính là chỗ này
[NeMo I 2026-07-01 13:10:39 wer:338] WER predicted:thành nhân ra khu thời chỉ là chủ này
[NeMo I 2026-07-01 13:10:47 wer:336]

[NeMo I 2026-07-01 13:10:47 wer:337] WER reference:cô bé rất lấy làm vui mừng và làm quen với những nốt nhạc đầu tiên bằng chính chiếc đàn đồ chơi ấy
[NeMo I 2026-07-01 13:10:47 wer:338] WER predicted:có bé rất làm vui và làm quan với nhữngạ đầu tiên trên bạn chính ch đang được chơi ấy
[NeMo I 2026-07-01 13:10:56 wer:336]


Validation: |          | 0/? [00:00<?, ?it/s]

[NeMo I 2026-07-01 13:14:03 wer:336]

[NeMo I 2026-07-01 13:14:03 wer:337] WER reference:những con vật này đã bị giết và đốt
[NeMo I 2026-07-01 13:14:03 wer:338] WER predicted:nh con vật này đã bị d vàốc
[NeMo I 2026-07-01 13:14:03 wer:336]

[NeMo I 2026-07-01 13:14:03 wer:337] WER reference:do vậy có máy cũng không thường dùng
[NeMo I 2026-07-01 13:14:03 wer:338] WER predicted:do vậy có mấy cũng không thường dụng
[NeMo I 2026-07-01 13:14:03 wer:336]

[NeMo I 2026-07-01 13:14:03 wer:337] WER reference:đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
[NeMo I 2026-07-01 13:14:03 wer:338] WER predicted:đây sẽ là cuộc g gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
[NeMo I 2026-07-01 13:14:03 wer:336]

[NeMo I 2026-07-01 13:14:03 wer:337] WER reference:sau đó một vật lạ bay xợt ngang nóc nhà ông
[NeMo I 2026-07-01 13:14:03 wer:338] WER predicted:sau đó một và là b sự ng năngn nốc nhau
[NeMo I 2026-07-01 13:14:03 wer:336]

[NeMo I 2026-07-01 13:14:03 wer:337] WER reference:hiện ra tận phía xa
[NeMo I 2026-07-01 13:14:03 wer:338] WER predicted:hiện ra tình phía xa
[NeMo I 2026-07-01 13:14:03 wer:336]

[NeMo I 2026-07-01 13:14:03 wer:337] WER reference:nên với thông tin này
[NeMo I 2026-07-01 13:14:03 wer:338] WER predicted:nên với thông tiền này
[NeMo I 2026-07-01 13:14:03 wer:336]

[NeMo I 2026-07-01 13:14:03 wer:337] WER reference:và dân dã như chính cái tên của nó
[NeMo I 2026-07-01 13:14:03 wer:338] WER predicted:và dân gia như chính cái trên của nó
[NeMo I 2026-07-01 13:14:03 wer:336]

[NeMo I 2026-07-01 13:14:03 wer:337] WER reference:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 13:14:03 wer:338] WER predicted:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 13:14:03 wer:336]

[NeMo I 2026-07-01 13:14:03 wer:337] WER reference:sau nhiều pha hảm thành liên tục
[NeMo I 2026-07-01 13:14:03 wer:338] WER predicted:sau nhiều phá h thành liên tục
[NeMo I 2026-07-01 13:14:03 wer:336]

[NeMo I 2026-07-01 13:14:03 wer:337] WER reference:anh vẫn nhớ kỷ niệm cầu đầu lâu
[NeMo I 2026-07-01 13:14:03 wer:338] WER predicted:anh v vẫn nhớ kỳiềm cầu đầu lâu
[NeMo I 2026-07-01 13:14:03 wer:336]

[NeMo I 2026-07-01 13:14:03 wer:337] WER reference:gay go lắm nhưng hoàng anh gia lai sẽ làm được
[NeMo I 2026-07-01 13:14:03 wer:338] WER predicted:g g l lắm nhưng hơn anh gia là sẽ làm đ được
[NeMo I 2026-07-01 13:14:03 wer:336]

[NeMo I 2026-07-01 13:14:03 wer:337] WER reference:do đó khi chơi chung với bạn bè cùng lứa chúng thường tỏ ra thiếu tự tin
[NeMo I 2026-07-01 13:14:03 wer:338] WER predicted:do đó khi tr chơi chúng với bạn bé cũng lư chúng ta thường tôi cả thiếu từ tính
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:mối đục luỗng cả tấm gỗ
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:mới được luôn cả t tâm g
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:người ta cho rằng trung tâm này có khả năng ảnh hưởng đến quá trình lão hóa
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:người ta cho rằng trung tâm này có khá năng anh hướng đến quá trên lao hoa
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:các giò phong lan tháng ba cũng không chịu yên mình
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:các cho phẩm lên tha ba cũng công chịu ý mình
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:hãy cho tôi quyền năng vô tận để bảo vệ loài vật
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:hay cho tôi viên năng v vô tăng để bảo về loi vật
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:sáng chiều hội diễn tiếng hát bảo minh do công ty bảo hiểm bảo minh tổ chức
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:sáng chịu hỏi diễn tiếng khác đầu mình do công ty bảo hiểm báo mình tổ chức
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:cô nằm thiếp đi lúc nào không biết
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:cô năm tiếp đi lúc nào không biết
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:mười bảy mười tám mười chín
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:mươi bảy mươi tám mươi chín
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:tích cóp đủ thứ đồ lạc xon những ngọn đèn
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:tiếpốc đưa thứ đồ đ đã so những ngọ đang
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:nhưng đất nước đã chọn một nhà lãnh đạo khác
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:nhưng nước nước đã chọn một nhà lên đầu khác
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:ưu thế này có được là nhờ quá trình cơ giới hóa nhanh sử dụng phân bón cho dù hậu quả có là
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:uống thế này có được là nhớ quá trình cơ giới hoa nhanh sự dụng phần bốn cho dụnghầu quả có làm
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:thường xuyên xảy ra hiện tượng đạo văn quỵt nhuận bút
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:thường xuyên x ra hiện thường đào văn quyết nhút
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:chỉ cho chúng tôi xem hàng đống gạch đá cát sỏi
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:chỉ cho chúng tôi xem hàng đồng cả đã các số
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:đối với cảng hàng không quốc tế đà nẵng sử dụng nhà ga hành khách hiện hữu làm nhà ga nội địa
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:đối với càng hàng không quốc tế đã năng sự dụng nhà gia hành khách hiện hồ làm nhà g nói để
[NeMo I 2026-07-01 13:14:04 wer:336]

[NeMo I 2026-07-01 13:14:04 wer:337] WER reference:người giàu thì vác nặng những xâu tiền kẽm trên vai
[NeMo I 2026-07-01 13:14:04 wer:338] WER predicted:ngườiào thì vật nạ những sau tiềnk trên phải
[NeMo I 2026-07-01 13:14:05 wer:336]

[NeMo I 2026-07-01 13:14:05 wer:337] WER reference:các nữ công nhân làm ca đêm
[NeMo I 2026-07-01 13:14:05 wer:338] WER predicted:các nữ công nhân làm cả điểm
[NeMo I 2026-07-01 13:14:05 wer:336]

[NeMo I 2026-07-01 13:14:05 wer:337] WER reference:tui biết bà giỏi rồi
[NeMo I 2026-07-01 13:14:05 wer:338] WER predicted:tôi biết bà di rồi
[NeMo I 2026-07-01 13:14:05 wer:336]

[NeMo I 2026-07-01 13:14:05 wer:337] WER reference:đưa một chú bồ câu bay đi bay về
[NeMo I 2026-07-01 13:14:05 wer:338] WER predicted:đường một chú bộ cầu bảy đi bị v về
[NeMo I 2026-07-01 13:14:05 wer:336]

[NeMo I 2026-07-01 13:14:05 wer:337] WER reference:tôi đến kiểm tra và phát hiện thấy ông và cô gái nằm kia thám tử ra hiệu cho ngài triệu phú nhìn vào phòng tắm cô ta đã chết
[NeMo I 2026-07-01 13:14:05 wer:338] WER predicted:tôi đến kiểm ra và phát hiện thấy ông và cô gái nămk tha từ ra hiểu cho ngày chịu phương nhìn vào phòng tâm cô đã chết
[NeMo I 2026-07-01 13:14:05 wer:336]

[NeMo I 2026-07-01 13:14:05 wer:337] WER reference:để thực hiện thắng lợi kế hoạch năm năm
[NeMo I 2026-07-01 13:14:05 wer:338] WER predicted:để thực hiện thân lại cái hết năm năm
[NeMo I 2026-07-01 13:14:05 wer:336]

[NeMo I 2026-07-01 13:14:05 wer:337] WER reference:trước khi hóa thân thành cộng hòa sét để đến bồ đào nha
[NeMo I 2026-07-01 13:14:05 wer:338] WER predicted:trước khi hoa thân thành còn hoa sức để đến bộ đồng nhà
[NeMo I 2026-07-01 13:14:05 wer:336]

[NeMo I 2026-07-01 13:14:05 wer:337] WER reference:tuy nhiên tôi không chắc những người chưa từng đọc cuốn nhật ký có thể hiểu hết được ý nghĩa bộ phim
[NeMo I 2026-07-01 13:14:05 wer:338] WER predicted:tuy nhiên tôi không chắc những người chưa từ đọc cũng nhất kỳ có thể hiểu hết được ý nghĩ bộ phim
[NeMo I 2026-07-01 13:14:05 wer:336]

[NeMo I 2026-07-01 13:14:05 wer:337] WER reference:chi đầu tư từ khu vực nhà nước còn lớn và hiệu quả thấp
[NeMo I 2026-07-01 13:14:05 wer:338] WER predicted:chỉ đầu tư từ khu vực nhà n nước còn lớn và hiệu quả th hợp
[NeMo I 2026-07-01 13:14:05 wer:336]

[NeMo I 2026-07-01 13:14:05 wer:337] WER reference:cái nền xưa của nó bây giờ là một cái hố nông choèn
[NeMo I 2026-07-01 13:14:05 wer:338] WER predicted:cái nên s của nó bị giờ là một cái hồ n năm tr
[NeMo I 2026-07-01 13:14:05 wer:336]

[NeMo I 2026-07-01 13:14:05 wer:337] WER reference:giải truyền thông điện ảnh trung quốc là giải thưởng điện ảnh duy nhất xét trao cho tất cả các bộ phim hoa ngữ
[NeMo I 2026-07-01 13:14:05 wer:338] WER predicted:giải trên thường đến anh chúng quốc là dài thường đến anh gì sẽ cho cho tất cả các bộ hiện hoànư
[NeMo I 2026-07-01 13:14:05 wer:336]

[NeMo I 2026-07-01 13:14:05 wer:337] WER reference:dự đoán ba tháng nữa giá cà phê sẽ tăng gấp đôi hiện nay
[NeMo I 2026-07-01 13:14:05 wer:338] WER predicted:điều rằng ba tháng nữa giá và về sự tăng gặp đôi hiện này
[NeMo I 2026-07-01 13:14:05 wer:336]

[NeMo I 2026-07-01 13:14:05 wer:337] WER reference:họ đến đây vì nhiều mục đích
[NeMo I 2026-07-01 13:14:05 wer:338] WER predicted:họ đến đâyì nhiều một đích
[NeMo I 2026-07-01 13:14:05 wer:336]

[NeMo I 2026-07-01 13:14:05 wer:337] WER reference:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 13:14:05 wer:338] WER predicted:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 13:14:05 wer:336]

[NeMo I 2026-07-01 13:14:05 wer:337] WER reference:vậy trước đây nông dân đối phó với hiện tượng này như thế nào thưa ông
[NeMo I 2026-07-01 13:14:05 wer:338] WER predicted:vậy trước đây n năm nhân đối phố v với hiện từ này như đến nào thu  ông
[NeMo I 2026-07-01 13:14:05 wer:336]

[NeMo I 2026-07-01 13:14:05 wer:337] WER reference:làm sao để có tiền nhanh nhất
[NeMo I 2026-07-01 13:14:05 wer:338] WER predicted:làm sao để có tiền nhân nhất
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:đùi dang ra ngoài
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:được gian ra ngoài
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:đã hai lần cô gác lại ước mơ vào đời và cũng đã ít nhiều trải qua những thăng trầm xô bồ của cuộc sống
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:đã hai l lần cô gái lạiút mới vào đời và cũng đã ít nhiều trái qua những tha tr số bộ của cuộc sống
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:trong bối cảnh như vậy một phản ứng chính sách đối với vấn đề thất nghiệp đang là đòi hỏi cấp bách hiện nay
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:trong bộ cảnh như vậy một phầnững chính sách đối với vẫn để nghiệpp đang là đời họ cách cách hiện này
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:ở xứ sở chuột túi
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:ở s sơ tr chủ tôi
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:do vậy dựa trên cơ sở nào mà ông khoa phát biểu như vậy
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:do vậy dự trên cơ s nào ông khoa phát biểu như vậy
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:tá tàng
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:ta tăng
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:cách đây tám năm nhưng trước đó khoảng hai năm đã được mời đóng phim và có nhiều vai chính trong các phim điện ảnh truyền hình
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:cách đây tâm năm nh trước đó kho hai năm đã được mới động phim và có nhiều và chính trong các phim điện anh truyền hình
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:đã thăm hỏi thì thế nào cũng phải có quà cáp
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:đã tâmm họ thì thế nào cũng phải có quả các
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:có mặt tạià điện phòng
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:em lơ đễnh lật xem vài tờ báo
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:em là điện l xem vàờ báo
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:và không ít người cứ tì tì uống từ sáng đến tối suốt mấy ngày hội nghị
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:và không ít người cứ ty từ  uống từ sáng đến tôi xuất máy ngày hội này
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:minh châu vào miền nam công tác tại nhà hát trần hữu trang
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:mình cao vào m nam công tất tại nhà ho rằng h rằng
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:hết chiến tranh quê hương im tiếng súng anh lính cụ hồ lại trở về với đời thường tham gia sản xuất xây dựng và bảo vệ đất nước
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:hết tiếng trên với hơn ý tiếng xuống anh lên của hồ lại cho về với đời thường tham giá sản xuất sẽ d vào b với đất nước
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:chuyến đi đó đến giờ vẫn là một ám ảnh trong ký ức tôi
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:chỉ đi đó đến giờ vẫn là một ông anh trong kỳ
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:ây da ây da
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:giá gia
[NeMo I 2026-07-01 13:14:06 wer:336]

[NeMo I 2026-07-01 13:14:06 wer:337] WER reference:có rất nhiều vệ tinh bị rơi khỏi quỹ đạo
[NeMo I 2026-07-01 13:14:06 wer:338] WER predicted:rất nhiều về tính bị rồi khó qu nào
[NeMo I 2026-07-01 13:14:07 wer:336]

[NeMo I 2026-07-01 13:14:07 wer:337] WER reference:nhuốm đầy máu của thổ dân châu mỹ
[NeMo I 2026-07-01 13:14:07 wer:338] WER predicted:nhóm đây m máu của thủ dân cho mỹ
[NeMo I 2026-07-01 13:14:07 wer:336]

[NeMo I 2026-07-01 13:14:07 wer:337] WER reference:cụ thể về đất đai xây dựng văn hóa thuộc về từng ngành riêng biệt
[NeMo I 2026-07-01 13:14:07 wer:338] WER predicted:cô thể về đ đất đây văn sẽ những văn hoa thuốc về từ ngành riêng biết
[NeMo I 2026-07-01 13:14:07 wer:336]

[NeMo I 2026-07-01 13:14:07 wer:337] WER reference:tôi muốn hỏi liệu có mùi hương sen nhân tạo là một loại hóa chất không
[NeMo I 2026-07-01 13:14:07 wer:338] WER predicted:tôi muốn hỏi liệu có mười hướng s nhân tạo là một loại họ chắc cao
[NeMo I 2026-07-01 13:14:07 wer:336]

[NeMo I 2026-07-01 13:14:07 wer:337] WER reference:cả nhà bà ngoại cười nắc nẻ vì câu nói ngây ngô của con
[NeMo I 2026-07-01 13:14:07 wer:338] WER predicted:các nhà bao ngoài người nước ngheì cô nói ngày ngủ của con
[NeMo I 2026-07-01 13:14:07 wer:336]

[NeMo I 2026-07-01 13:14:07 wer:337] WER reference:xin được chân khuân vác
[NeMo I 2026-07-01 13:14:07 wer:338] WER predicted:xin được trên khu phát
[NeMo I 2026-07-01 13:14:07 wer:336]

[NeMo I 2026-07-01 13:14:07 wer:337] WER reference:nằm khuất dưới tàn tre sát bờ sông châu
[NeMo I 2026-07-01 13:14:07 wer:338] WER predicted:ho giới thành trẻ sẽ bà s sống ch
[NeMo I 2026-07-01 13:14:07 wer:336]

[NeMo I 2026-07-01 13:14:07 wer:337] WER reference:nếu kiên cố hóa thì vốn được đưa thẳng cho dân sẽ không thất thoát
[NeMo I 2026-07-01 13:14:07 wer:338] WER predicted:nếu ki cô hoa thì bốn được đưa tăng cho dân sẽ không thật
[NeMo I 2026-07-01 13:14:07 wer:336]

[NeMo I 2026-07-01 13:14:07 wer:337] WER reference:nói chung cô hồng nào cũng có một số phận hoàn cảnh và cuộc đời riêng
[NeMo I 2026-07-01 13:14:07 wer:338] WER predicted:nói chúng cô học nào cũng có một số phần hoàn cảnhnh với cuộc đời riêng
[NeMo I 2026-07-01 13:14:07 wer:336]

[NeMo I 2026-07-01 13:14:07 wer:337] WER reference:nhưng tất cả những điều ấy chẳng mấy khi đi liền với nhau
[NeMo I 2026-07-01 13:14:07 wer:338] WER predicted:những tất cả những điều ấy ch mấy khi đi liên với nhau
[NeMo I 2026-07-01 13:14:07 wer:336]

[NeMo I 2026-07-01 13:14:07 wer:337] WER reference:như vậy là bạn có thể sử dụng được nhiều số điện thoại của nhiều nhà cung cấp dịch vụ chỉ trên một sim
[NeMo I 2026-07-01 13:14:07 wer:338] WER predicted:như vậy bạn có thể sự dụng được nhiều số đến th của như nhà cũng cấp dịch vụ chỉ trên một xem
[NeMo I 2026-07-01 13:14:07 wer:336]

[NeMo I 2026-07-01 13:14:07 wer:337] WER reference:trong trường hợp hai bên có thỏa thuận lại không yêu cầu trọng tài giải quyết nữa thì có quyền kiện ra tòa án
[NeMo I 2026-07-01 13:14:07 wer:338] WER predicted:trong trường hợp hai bên có thể thường lại không yêu cầu trong ta d quyết nữa thì có quyền kiến ra toàn ăn
[NeMo I 2026-07-01 13:14:07 wer:336]

[NeMo I 2026-07-01 13:14:07 wer:337] WER reference:kiểu này chắc phải cắt giảm biên chế
[NeMo I 2026-07-01 13:14:07 wer:338] WER predicted:kiể này chắc phải các giảm biến chế
[NeMo I 2026-07-01 13:14:07 wer:336]

[NeMo I 2026-07-01 13:14:07 wer:337] WER reference:nhưng tôi không yêu cô cô biết rõ điều đó mà
[NeMo I 2026-07-01 13:14:07 wer:338] WER predicted:nhưng tôi không yêu cô cô biết rồi điều đó mà
[NeMo I 2026-07-01 13:14:07 wer:336]

[NeMo I 2026-07-01 13:14:07 wer:337] WER reference:khó mà đoán trước chính xác kết quả khi quả bóng còn lăn
[NeMo I 2026-07-01 13:14:07 wer:338] WER predicted:khó mà đó trước chính sẽích quả khi qua b bóng con
[NeMo I 2026-07-01 13:14:07 wer:336]

[NeMo I 2026-07-01 13:14:07 wer:337] WER reference:vừa nhìn thấy sự xuất hiện của bố tất cả mấy thằng khác vùng bỏ chạy sạch
[NeMo I 2026-07-01 13:14:07 wer:338] WER predicted:ừa nh thấy sự sự hiện của bố tất cả máy th thành khác vùng bỏi trẻ sách
[NeMo I 2026-07-01 13:14:08 wer:336]

[NeMo I 2026-07-01 13:14:08 wer:337] WER reference:phải nâng cao khả năng cạnh tranh của nền kinh tế
[NeMo I 2026-07-01 13:14:08 wer:338] WER predicted:phải năng cao kh năng cảnh trên của nên kinh tên
[NeMo I 2026-07-01 13:14:08 wer:336]

[NeMo I 2026-07-01 13:14:08 wer:337] WER reference:bà thường lấy ý tưởng cho các tác phẩm từ đâu
[NeMo I 2026-07-01 13:14:08 wer:338] WER predicted:bà thườngấy ý từ cho các tác phẩm từ đồng
[NeMo I 2026-07-01 13:14:08 wer:336]

[NeMo I 2026-07-01 13:14:08 wer:337] WER reference:khi chứng kiến người vợ lăng loàn
[NeMo I 2026-07-01 13:14:08 wer:338] WER predicted:khi chứng kiến người vào l lần lòng
[NeMo I 2026-07-01 13:14:08 wer:336]

[NeMo I 2026-07-01 13:14:08 wer:337] WER reference:tác phẩm to lớn bằng đồng như tượng phật quỳnh lâm chuông quy điền tháp báo thiên vạc phổ minh an nam tứ đại khí
[NeMo I 2026-07-01 13:14:08 wer:338] WER predicted:ta phẩm ta lớn bạn đồng như tượng phát quyền lắm chúng qu điện th bảo tìm và phố mình ăn nam tư đây khi
[NeMo I 2026-07-01 13:14:08 wer:336]

[NeMo I 2026-07-01 13:14:08 wer:337] WER reference:ngoài ra họ vẫn còn muốn giữ chân cầu thủ xuất sắc nhất của mình
[NeMo I 2026-07-01 13:14:08 wer:338] WER predicted:họ vẫn cầu muốnư chân cầu thủ xuất s
[NeMo I 2026-07-01 13:14:08 wer:336]

[NeMo I 2026-07-01 13:14:08 wer:337] WER reference:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 13:14:08 wer:338] WER predicted:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 13:14:08 wer:336]

[NeMo I 2026-07-01 13:14:08 wer:337] WER reference:và gã thệ bị điều về làm trưởng phòng xã hội huyện
[NeMo I 2026-07-01 13:14:08 wer:338] WER predicted:và cả thể biết điều về làm trường phần xã hộii h
[NeMo I 2026-07-01 13:14:08 wer:336]

[NeMo I 2026-07-01 13:14:08 wer:337] WER reference:là rút rỉa tiền của bạn càng nhiều càng tốt

[NeMo W 2026-07-01 13:14:23 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:14:23 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

[best val_wer] epoch=10 val_wer=0.441368 exported=/kaggle/working/phase3_continue_best.nemo

Sample predictions after epoch 10:
  [0] REF: những con vật này đã bị giết và đốt
      HYP: nh con vật này đã bị d vàốc
  [1] REF: phòng chống tham nhũng không được chủ quan cần làm liên tục đồng bộ và có các giải pháp
      HYP: phòng trong tham nh dụng không được chủ quan cần làm liên tục động bộ và có các đại pháp
  [2] REF: do vậy có máy cũng không thường dùng
      HYP: do vậy có mấy cũng không thường dụng
  [3] REF: mới khệnh khạng đứng lên đi ra
      HYP: mới kh khá đứng lên đi ra
  [4] REF: đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
      HYP: đây sẽ là cuộc g gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
  [5] REF: sau một năm eo sèo
      HYP: sáu một năm yêu xe
  [6] REF: sau đó một vật lạ bay xợt ngang nóc nhà ông
      HYP: sau đó một và là b sự ng năngn nốc nhau
  [7] REF: chín mươi hai chín mươi ba
      HYP: chín mươi hai chín mươi ba
  [8] REF: hiện ra tận phía xa
      HYP: hiện ra tình phía xa
  [9] REF: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã qua của thị trường
      HYP: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã quá của thì trường
[epoch] epoch=10/12 step=3140 val_loss=2.10198974609375 val_wer=0.44136786460876465
[NeMo I 2026-07-01 13:14:44 wer:336]

[NeMo I 2026-07-01 13:14:44 wer:337] WER reference:rất nhiều trường hợp phụ huynh đau đầu vì con một đã tìm đến chuyên viên tư vấn tâm lý
[NeMo I 2026-07-01 13:14:44 wer:338] WER predicted:rất người trường học phụ kh đâu đầuì anh một đã tìm đến trên viên tư anh tâm lý
[NeMo I 2026-07-01 13:14:53 wer:336]

[NeMo I 2026-07-01 13:14:53 wer:337] WER reference:trước tình thế đó tôi buộc phải tìm cho mình một bến đỗ mới và tôi đã quyết định ra đi
[NeMo I 2026-07-01 13:14:53 wer:338] WER predicted:lúc tình thế đó tôi bộ phải tiền cho mình một bên đ đầu mới và tôi đã quyết bệnh ra đi
[NeMo I 2026-07-01 13:15:02 wer:336]

[NeMo I 2026-07-01 13:15:02 wer:337] WER reference:tuy nhiên tình hình đó không diễn ra ở tất cả trường
[NeMo I 2026-07-01 13:15:02 wer:338] WER predicted:tuy nhiên tình hình đó không diễná ở tất cả tr trường
[NeMo I 2026-07-01 13:15:11 wer:336]

[NeMo I 2026-07-01 13:15:11 wer:337] WER reference:nếu xét trên qui mô toàn tỉnh con số ấy vẫn còn khiêm tốn lắm
[NeMo I 2026-07-01 13:15:11 wer:338] WER predicted:nên x chỉ phí mua toàn tình cầu số ấy vẫn còn khiù làm
[NeMo I 2026-07-01 13:15:19 wer:336]

[NeMo I 2026-07-01 13:15:19 wer:337] WER reference:các vùng sâu vùng xa khó mà phát triển
[NeMo I 2026-07-01 13:15:19 wer:338] WER predicted:các vùng sau vùng sẽ khó mà phát triển
[NeMo I 2026-07-01 13:15:28 wer:336]

[NeMo I 2026-07-01 13:15:28 wer:337] WER reference:thì không hiểu sao ở phần thơ cổ đại
[NeMo I 2026-07-01 13:15:28 wer:338] WER predicted:thì không hiểu sao ở phần hết của đầy
[NeMo I 2026-07-01 13:15:37 wer:336]

[NeMo I 2026-07-01 13:15:37 wer:337] WER reference:anh muốn thùy có thể tự do tìm cho mình một hạnh phúc khác tràn đầy
[NeMo I 2026-07-01 13:15:37 wer:338] WER predicted:anh muốn thời có thể từ do tìm cho mình một thành ph khác cho lại
[NeMo I 2026-07-01 13:15:45 wer:336]

[NeMo I 2026-07-01 13:15:45 wer:337] WER reference:áo thun trắng sát nách
[NeMo I 2026-07-01 13:15:45 wer:338] WER predicted:áo thu trang sát nắc
[NeMo I 2026-07-01 13:15:54 wer:336]

[NeMo I 2026-07-01 13:15:54 wer:337] WER reference:đây cũng là giai đoạn thị trường nhiều biến cố nhất
[NeMo I 2026-07-01 13:15:54 wer:338] WER predicted:đây cũng là chế đồng thì trường nhiều biến cô nhất
[NeMo I 2026-07-01 13:16:03 wer:336]

[NeMo I 2026-07-01 13:16:03 wer:337] WER reference:mới thành món ngon và độc đáo
[NeMo I 2026-07-01 13:16:03 wer:338] WER predicted:mới thành m món ngon và được đâu
[NeMo I 2026-07-01 13:16:11 wer:336]

[NeMo I 2026-07-01 13:16:11 wer:337] WER reference:người đẹp không thiếu chỉ sợ ông anh không có tiền
[NeMo I 2026-07-01 13:16:11 wer:338] WER predicted:người để không thiếu chỉ s ông anh không có tình
[NeMo I 2026-07-01 13:16:20 wer:336]

[NeMo I 2026-07-01 13:16:20 wer:337] WER reference:ngày thường chù ụ thì được
[NeMo I 2026-07-01 13:16:20 wer:338] WER predicted:ngày thường chủổ chỉ được
[NeMo I 2026-07-01 13:16:29 wer:336]

[NeMo I 2026-07-01 13:16:29 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 13:16:29 wer:338] WER predicted:có mặt tại sẽ điện phương
[NeMo I 2026-07-01 13:16:37 wer:336]

[NeMo I 2026-07-01 13:16:37 wer:337] WER reference:tôi cũng biết có những tiêu cực trong giáo dục và nhà trường cũng như những lĩnh vực khác của xã hội
[NeMo I 2026-07-01 13:16:37 wer:338] WER predicted:tôi cũng biết có những tiêu thực trong giá được và nhà trường của như những lên vợ h của xã hội
[NeMo I 2026-07-01 13:16:46 wer:336]

[NeMo I 2026-07-01 13:16:46 wer:337] WER reference:xắn quần vượt qua là bước vào thế giới
[NeMo I 2026-07-01 13:16:46 wer:338] WER predicted:sốngn qu v qua là bước vào thế giới
[NeMo I 2026-07-01 13:16:55 wer:336]

[NeMo I 2026-07-01 13:16:55 wer:337] WER reference:mới và cải tiến
[NeMo I 2026-07-01 13:16:55 wer:338] WER predicted:mới và cả tiền
[NeMo I 2026-07-01 13:17:03 wer:336]

[NeMo I 2026-07-01 13:17:03 wer:337] WER reference:hai vợ chồng thị tớn và văn đục
[NeMo I 2026-07-01 13:17:03 wer:338] WER predicted:hai vợ trong thì tưởng và văn được
[NeMo I 2026-07-01 13:17:12 wer:336]

[NeMo I 2026-07-01 13:17:12 wer:337] WER reference:chợ đêm ca ba dành cho những người đang vào mùa tăng ca cuối năm
[NeMo I 2026-07-01 13:17:12 wer:338] WER predicted:ở đến có ba danh choững người đang vào một ta cả cứ năm
[NeMo I 2026-07-01 13:17:21 wer:336]

[NeMo I 2026-07-01 13:17:21 wer:337] WER reference:hai mươi hai mươi mốt
[NeMo I 2026-07-01 13:17:21 wer:338] WER predicted:hai mươi hai mươi mốt
[NeMo I 2026-07-01 13:17:30 wer:336]

[NeMo I 2026-07-01 13:17:30 wer:337] WER reference:anh không thể quên được những giây phút ngọt ngào ấy
[NeMo I 2026-07-01 13:17:30 wer:338] WER predicted:anh không được quanh được nh ph diễn ngọ nào ấy
[NeMo I 2026-07-01 13:17:38 wer:336]

[NeMo I 2026-07-01 13:17:38 wer:337] WER reference:đưa tới tình trạng phá sản
[NeMo I 2026-07-01 13:17:38 wer:338] WER predicted:ưa tư tiền rằng phá sản
[NeMo I 2026-07-01 13:17:47 wer:336]

[NeMo I 2026-07-01 13:17:47 wer:337] WER reference:phụ huynh và học sinh đang phải è cổ vì sách giá cao
[NeMo I 2026-07-01 13:17:47 wer:338] WER predicted:vụ qu và học sinh đang phải em cô vì sách gia cao
[NeMo I 2026-07-01 13:17:56 wer:336]

[NeMo I 2026-07-01 13:17:56 wer:337] WER reference:thỉnh thoảng lại có người ghép thận trước đó trở qua xin xét nghiệm vì có trục trặc
[NeMo I 2026-07-01 13:17:56 wer:338] WER predicted:tình toàn lại có người g thằ tư và tôi qua sinh sẽ nhiều về cóục đọc
[NeMo I 2026-07-01 13:18:04 wer:336]

[NeMo I 2026-07-01 13:18:04 wer:337] WER reference:cuộc thi nhằm trau dồi niềm đam mê
[NeMo I 2026-07-01 13:18:04 wer:338] WER predicted:cuộc thi nh tr d nhiệm đã mẹ
[NeMo I 2026-07-01 13:18:13 wer:336]

[NeMo I 2026-07-01 13:18:13 wer:337] WER reference:đề thi môn vẽ thông thường là về vẽ trang trí sản phẩm vật thể
[NeMo I 2026-07-01 13:18:13 wer:338] WER predicted:để thi muốn v vẻ hô thường là về về sáng chỉ sản phẩm một thể
[NeMo I 2026-07-01 13:18:22 wer:336]

[NeMo I 2026-07-01 13:18:22 wer:337] WER reference:bước vào một mối tình
[NeMo I 2026-07-01 13:18:22 wer:338] WER predicted:bước vào một mua tình
[NeMo I 2026-07-01 13:18:30 wer:336]

[NeMo I 2026-07-01 13:18:30 wer:337] WER reference:lão nạp chỉ có nhiêu đây thôi
[NeMo I 2026-07-01 13:18:30 wer:338] WER predicted:làạ chỉ có như lại tôi
[NeMo I 2026-07-01 13:18:39 wer:336]

[NeMo I 2026-07-01 13:18:39 wer:337] WER reference:hai tuần sau
[NeMo I 2026-07-01 13:18:39 wer:338] WER predicted:hai tuần sáu
[NeMo I 2026-07-01 13:18:48 wer:336]

[NeMo I 2026-07-01 13:18:48 wer:337] WER reference:những ngày cuối cùng trên dương thế
[NeMo I 2026-07-01 13:18:48 wer:338] WER predicted:những này cuối cùng trên dân thế
[NeMo I 2026-07-01 13:18:56 wer:336]

[NeMo I 2026-07-01 13:18:56 wer:337] WER reference:trên nhiều tuyến phố công nhân đang hối hả dọn dẹp
[NeMo I 2026-07-01 13:18:56 wer:338] WER predicted:trên nhiều tiếng ph công nh đang hội hệ động nghiệpp
[NeMo I 2026-07-01 13:19:05 wer:336]

[NeMo I 2026-07-01 13:19:05 wer:337] WER reference:có trường hợp bất hợp pháp như trần thị thu h
[NeMo I 2026-07-01 13:19:05 wer:338] WER predicted:có chuyện học bất hợp pháp như trong thì thu
[NeMo I 2026-07-01 13:19:14 wer:336]

[NeMo I 2026-07-01 13:19:14 wer:337] WER reference:nhưng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được các khó khăn đó
[NeMo I 2026-07-01 13:19:14 wer:338] WER predicted:chúng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được cả khó không đó
[NeMo I 2026-07-01 13:19:23 wer:336]

[NeMo I 2026-07-01 13:19:23 wer:337] WER reference:lúc đó em không thể tiếp tục công việc đánh cá của cha một mình vì còn quá nhỏ
[NeMo I 2026-07-01 13:19:23 wer:338] WER predicted:lúc đó em không phải tiếp được không việcánh các của tra một mình việc còn qua nhỏ
[NeMo I 2026-07-01 13:19:31 wer:336]

[NeMo I 2026-07-01 13:19:31 wer:337] WER reference:cuốn sách nói về sự lầm lẫn giữa luật kinh tế ở châu âu và châu mỹ kim vẫn chưa đọc tới vì cô không quan tâm đến luật
[NeMo I 2026-07-01 13:19:31 wer:338] WER predicted:cũng sinh nói về làm lần nhiều được ki tế ở ch ông và trong muốn cho vẫn chưa đọc tôi việc của không quan tăng đến luật
[NeMo I 2026-07-01 13:19:40 wer:336]

[NeMo I 2026-07-01 13:19:40 wer:337] WER reference:khi tên lửa bay lên
[NeMo I 2026-07-01 13:19:40 wer:338] WER predicted:khi tên l lời vậy lên
[NeMo I 2026-07-01 13:19:48 wer:336]

[NeMo I 2026-07-01 13:19:48 wer:337] WER reference:mà theo thời gian sẽ tiệm cận với trí khôn của con người
[NeMo I 2026-07-01 13:19:48 wer:338] WER predicted:mà theo thời dân sẽ tìm cần với trí không quốc con người
[NeMo I 2026-07-01 13:19:57 wer:336]

[NeMo I 2026-07-01 13:19:57 wer:337] WER reference:bên kia láng giềng của tôi hôm nay không thấy thăm hoa
[NeMo I 2026-07-01 13:19:57 wer:338] WER predicted:đến kia lan diễn của tôi hô này không thấy th h
[NeMo I 2026-07-01 13:20:06 wer:336]

[NeMo I 2026-07-01 13:20:06 wer:337] WER reference:anh yêu cầu các cầu thủ phải đeo bám ngay khi đối phương có bóng
[NeMo I 2026-07-01 13:20:06 wer:338] WER predicted:anh nhiều cầu các cầu số phảieo bạn ngày khi đối phương có
[NeMo I 2026-07-01 13:20:14 wer:336]

[NeMo I 2026-07-01 13:20:14 wer:337] WER reference:ngay cả công an đi lẻ loi cũng bị tấn công vì trong khu vực này có một thứ luật riêng cấm người lạ vào
[NeMo I 2026-07-01 13:20:14 wer:338] WER predicted:nghe và không mình đi lẽ cũng bị không con việc trong có việc mẹ một thứ lực viên công như l
[NeMo I 2026-07-01 13:20:23 wer:336]

[NeMo I 2026-07-01 13:20:23 wer:337] WER reference:thì chúng sẽ nằm trong tầm kiểm soát của bạn
[NeMo I 2026-07-01 13:20:23 wer:338] WER predicted:thì chúng sẽ năm trong đầm kiể sau của bạn
[NeMo I 2026-07-01 13:20:32 wer:336]

[NeMo I 2026-07-01 13:20:32 wer:337] WER reference:đó là hai con sói hoàn toàn trái ngược nhau về hình thức
[NeMo I 2026-07-01 13:20:32 wer:338] WER predicted:đó là hay con s hộ còn chính được nhau về hình thức
[NeMo I 2026-07-01 13:20:40 wer:336]

[NeMo I 2026-07-01 13:20:40 wer:337] WER reference:trại đồng xã yên sở giữa một biển nước mênh mông ảnh nguyễn quân
[NeMo I 2026-07-01 13:20:40 wer:338] WER predicted:tr đồng xã em s giờ một biểnứ mình món  anh nguyên quan
[NeMo I 2026-07-01 13:20:49 wer:336]

[NeMo I 2026-07-01 13:20:49 wer:337] WER reference:không sao rồi em mừng lắm
[NeMo I 2026-07-01 13:20:49 wer:338] WER predicted:không sao rồi em mình lắm
[NeMo I 2026-07-01 13:20:57 wer:336]

[NeMo I 2026-07-01 13:20:57 wer:337] WER reference:việc tòa án của pháp truy tố công dân một nước độc lập trên lãnh thổ quê hương của người ấy là một điều vô giá trị
[NeMo I 2026-07-01 13:20:57 wer:338] WER predicted:việc tôi ăn cuộc pháp tr tốt của không một được được lập trên l lên tôi cuối hơn còn ở ấy là một bị chú giá trị
[NeMo I 2026-07-01 13:21:06 wer:336]

[NeMo I 2026-07-01 13:21:06 wer:337] WER reference:bà mẹ nghèo đông con
[NeMo I 2026-07-01 13:21:06 wer:338] WER predicted:bà mẹ nghe vấn con
[NeMo I 2026-07-01 13:21:15 wer:336]

[NeMo I 2026-07-01 13:21:15 wer:337] WER reference:lấy tĩnh chế động
[NeMo I 2026-07-01 13:21:15 wer:338] WER predicted:l liệu tình cho đồng
[NeMo I 2026-07-01 13:21:23 wer:336]

[NeMo I 2026-07-01 13:21:23 wer:337] WER reference:mình mẩy tôi tuy đau đớn
[NeMo I 2026-07-01 13:21:23 wer:338] WER predicted:mình bảy tôi tuy đau đường
[NeMo I 2026-07-01 13:21:32 wer:336]

[NeMo I 2026-07-01 13:21:32 wer:337] WER reference:luôn ngẩng cao đầu sự khác biệt lớn nhất giữa người tự tin và người nhút nhát là gì
[NeMo I 2026-07-01 13:21:32 wer:338] WER predicted:luôn ngn cao đầu x khách người lớn nhỏ d người từ tiếng và người nh nhấtạ là gì
[NeMo I 2026-07-01 13:21:41 wer:336]

[NeMo I 2026-07-01 13:21:41 wer:337] WER reference:với các bạn trẻ trên đây có vẻ tình yêu không phải là tất cả
[NeMo I 2026-07-01 13:21:41 wer:338] WER predicted:với các bạn trẻ chính đây có về tình yêu kh và là tục cả
[NeMo I 2026-07-01 13:21:49 wer:336]

[NeMo I 2026-07-01 13:21:49 wer:337] WER reference:nếu trẻ bú không đủ có thể vắt sữa và cho trẻ uống bằng muỗng
[NeMo I 2026-07-01 13:21:49 wer:338] WER predicted:như trẻú không đủ có thể biết s và tr trẻ  uống bằngôn
[NeMo I 2026-07-01 13:21:58 wer:336]

[NeMo I 2026-07-01 13:21:58 wer:337] WER reference:hãy để thời gian tìm hiểu thêm và thuyết phục gia đình
[NeMo I 2026-07-01 13:21:58 wer:338] WER predicted:hãy để thời gian để mỹ thêm phải thu phục gia đình
[NeMo I 2026-07-01 13:22:07 wer:336]

[NeMo I 2026-07-01 13:22:07 wer:337] WER reference:vân vân và vân vân
[NeMo I 2026-07-01 13:22:07 wer:338] WER predicted:v vẫn bốn và vẫn bốn
[NeMo I 2026-07-01 13:22:15 wer:336]

[NeMo I 2026-07-01 13:22:15 wer:337] WER reference:mà phụ nữ trong khu vực công đang gặp phải
[NeMo I 2026-07-01 13:22:15 wer:338] WER predicted:mà phụ nơi trong khu vực công đang g gặp phải
[NeMo I 2026-07-01 13:22:24 wer:336]

[NeMo I 2026-07-01 13:22:24 wer:337] WER reference:những năm trước phần lớn sếu ở kiên lương kiên giang
[NeMo I 2026-07-01 13:22:24 wer:338] WER predicted:những năm ch phần lên sẽ ở khi lớn ki gia
[NeMo I 2026-07-01 13:22:33 wer:336]

[NeMo I 2026-07-01 13:22:33 wer:337] WER reference:theo nguyên đào kinh tế đô thị
[NeMo I 2026-07-01 13:22:33 wer:338] WER predicted:theo nguyên đào ki tênưa thời
[NeMo I 2026-07-01 13:22:42 wer:336]

[NeMo I 2026-07-01 13:22:42 wer:337] WER reference:nhưng ngủ quá nhiều sẽ khiến bạn trở nên bơ phờ
[NeMo I 2026-07-01 13:22:42 wer:338] WER predicted:nhưng ngủ quá nhiều sẽ khiến nạn trên đến b ph
[NeMo I 2026-07-01 13:22:50 wer:336]

[NeMo I 2026-07-01 13:22:50 wer:337] WER reference:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 13:22:50 wer:338] WER predicted:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 13:22:59 wer:336]

[NeMo I 2026-07-01 13:22:59 wer:337] WER reference:thường xuyên đối mặt với nạn khan hiếm lương thực
[NeMo I 2026-07-01 13:22:59 wer:338] WER predicted:thường x đối mặt với ngành khá hếm luôn thực
[NeMo I 2026-07-01 13:23:08 wer:336]

[NeMo I 2026-07-01 13:23:08 wer:337] WER reference:tôi có cảm tình với cô ấy nhưng tôi không muốn xen vào giữa họ
[NeMo I 2026-07-01 13:23:08 wer:338] WER predicted:tôi có cảm tình với cơ ấyững tôi không muốn xe vào d họ
[NeMo I 2026-07-01 13:23:16 wer:336]

[NeMo I 2026-07-01 13:23:16 wer:337] WER reference:với tôi chết là một sự ích kỷ còn bản chất sự sống đã là một bao dung ít nhất với chính mình
[NeMo I 2026-07-01 13:23:16 wer:338] WER predicted:với tôi chết là một sự kỳ công bạn chất sĩ sống đã một bao g biết nhất với chính mình
[NeMo I 2026-07-01 13:23:25 wer:336]

[NeMo I 2026-07-01 13:23:25 wer:337] WER reference:cậu không biết làm gì thì suốt đời cậu đúng là một kẻ hèn nhát
[NeMo I 2026-07-01 13:23:25 wer:338] WER predicted:cầu không biết làm gì thì xuất đời cầu đúng là một các hàng nhạc
[NeMo I 2026-07-01 13:23:34 wer:336]

[NeMo I 2026-07-01 13:23:34 wer:337] WER reference:màu đen của những tấm cha
[NeMo I 2026-07-01 13:23:34 wer:338] WER predicted:màu đang của những t tâm gia
[NeMo I 2026-07-01 13:23:42 wer:336]

[NeMo I 2026-07-01 13:23:42 wer:337] WER reference:tôi chỉ thấy người ta nhắc đến phượng vĩ tháng sáu hay cùng lắm là tháng năm
[NeMo I 2026-07-01 13:23:42 wer:338] WER predicted:tôi chỉ thấy ngườiáá đến phương vị tình sau hai cũng tám là thành ra
[NeMo I 2026-07-01 13:23:51 wer:336]

[NeMo I 2026-07-01 13:23:51 wer:337] WER reference:với câu trả lời xuất sắc và gương mặt khả ái
[NeMo I 2026-07-01 13:23:51 wer:338] WER predicted:với cô trả lời sức s vàương một khả ai
[NeMo I 2026-07-01 13:24:00 wer:336]

[NeMo I 2026-07-01 13:24:00 wer:337] WER reference:nhưng em có biết rằng anh yêu em cũng bởi những lý do đó
[NeMo I 2026-07-01 13:24:00 wer:338] WER predicted:n em có biết rằng anh như em cũng ở những lý do
[NeMo I 2026-07-01 13:24:09 wer:336]

[NeMo I 2026-07-01 13:24:09 wer:337] WER reference:để nhìn thấy sự khôi hài
[NeMo I 2026-07-01 13:24:09 wer:338] WER predicted:để nhìn thấy sự khu hai
[NeMo I 2026-07-01 13:24:17 wer:336]

[NeMo I 2026-07-01 13:24:17 wer:337] WER reference:rèm cửa phòng khách của bạn giống như cung điện
[NeMo I 2026-07-01 13:24:17 wer:338] WER predicted:ra của phòng khách của bạn gi như cũng điện
[NeMo I 2026-07-01 13:24:26 wer:336]

[NeMo I 2026-07-01 13:24:26 wer:337] WER reference:và những khuyết điểm nhỏ của họ
[NeMo I 2026-07-01 13:24:26 wer:338] WER predicted:và những quyết điểm nhà của họ
[NeMo I 2026-07-01 13:24:35 wer:336]

[NeMo I 2026-07-01 13:24:35 wer:337] WER reference:tôi biết đây là quy tắc đòi hỏi
[NeMo I 2026-07-01 13:24:35 wer:338] WER predicted:tôi biết đây là quy tác đòi hỏi
[NeMo I 2026-07-01 13:24:43 wer:336]

[NeMo I 2026-07-01 13:24:43 wer:337] WER reference:cũng trong ngày đó bài xã luận gằn giọng
[NeMo I 2026-07-01 13:24:43 wer:338] WER predicted:cũng trong ngày đó và sến g rằng gi
[NeMo I 2026-07-01 13:24:52 wer:336]

[NeMo I 2026-07-01 13:24:52 wer:337] WER reference:bạn có thể ghé thăm nó
[NeMo I 2026-07-01 13:24:52 wer:338] WER predicted:bạn có thể g nghĩa tha nó
[NeMo I 2026-07-01 13:25:01 wer:336]

[NeMo I 2026-07-01 13:25:01 wer:337] WER reference:các anh sẽ mãi là những người con ưu tú của tổ quốc của nhân dân việt nam
[NeMo I 2026-07-01 13:25:01 wer:338] WER predicted:các anh xem hay là những người con ngủ thủ tổ quốc của nhân dân việt nam
[NeMo I 2026-07-01 13:25:09 wer:336]

[NeMo I 2026-07-01 13:25:09 wer:337] WER reference:để luôn có một bình hoa tươi mới
[NeMo I 2026-07-01 13:25:09 wer:338] WER predicted:để luôn có một bệnh hoa tôi mới
[NeMo I 2026-07-01 13:25:18 wer:336]

[NeMo I 2026-07-01 13:25:18 wer:337] WER reference:chúc bạn đọc có thật nhiều thời gian thư giãn thoải mái
[NeMo I 2026-07-01 13:25:18 wer:338] WER predicted:ch bạn đọc có thật nhiều thời gian thứ d ở th tôiiá
[NeMo I 2026-07-01 13:25:27 wer:336]

[NeMo I 2026-07-01 13:25:27 wer:337] WER reference:bất chấp sự ngăn cản của cơ quan chức năng
[NeMo I 2026-07-01 13:25:27 wer:338] WER predicted:b chấp sự năngạ của cơ quan nước năng
[NeMo I 2026-07-01 13:25:35 wer:336]

[NeMo I 2026-07-01 13:25:35 wer:337] WER reference:chỉ có điều cô ta mang giày chiếc váy len dài bằng lông cừu
[NeMo I 2026-07-01 13:25:35 wer:338] WER predicted:chỉ có điều cuộc ta mang giảiiếc với l lên dài bằng l luônm cứ
[NeMo I 2026-07-01 13:25:44 wer:336]

[NeMo I 2026-07-01 13:25:44 wer:337] WER reference:thánh nhân đãi khù khờ chính là chỗ này
[NeMo I 2026-07-01 13:25:44 wer:338] WER predicted:thành nhân ra kh khu thời chỉ là chủ này
[NeMo I 2026-07-01 13:25:53 wer:336]

[NeMo I 2026-07-01 13:25:53 wer:337] WER reference:cô bé rất lấy làm vui mừng và làm quen với những nốt nhạc đầu tiên bằng chính chiếc đàn đồ chơi ấy
[NeMo I 2026-07-01 13:25:53 wer:338] WER predicted:có bé rất làm vui và làm quan với nhữngạ đầu tiên trên bạn chính ch đang được chơi ấy
[NeMo I 2026-07-01 13:26:02 wer:336]


Validation: |          | 0/? [00:00<?, ?it/s]

[NeMo I 2026-07-01 13:29:10 wer:336]

[NeMo I 2026-07-01 13:29:10 wer:337] WER reference:những con vật này đã bị giết và đốt
[NeMo I 2026-07-01 13:29:10 wer:338] WER predicted:nh con vật này đã bị d vàốc
[NeMo I 2026-07-01 13:29:10 wer:336]

[NeMo I 2026-07-01 13:29:10 wer:337] WER reference:do vậy có máy cũng không thường dùng
[NeMo I 2026-07-01 13:29:10 wer:338] WER predicted:do vậy có mấy cũng không thường dụng
[NeMo I 2026-07-01 13:29:10 wer:336]

[NeMo I 2026-07-01 13:29:10 wer:337] WER reference:đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
[NeMo I 2026-07-01 13:29:10 wer:338] WER predicted:đây sẽ là cuộc gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
[NeMo I 2026-07-01 13:29:10 wer:336]

[NeMo I 2026-07-01 13:29:10 wer:337] WER reference:sau đó một vật lạ bay xợt ngang nóc nhà ông
[NeMo I 2026-07-01 13:29:10 wer:338] WER predicted:sau đó một và là b sự ng năngn nốc nhau
[NeMo I 2026-07-01 13:29:10 wer:336]

[NeMo I 2026-07-01 13:29:10 wer:337] WER reference:hiện ra tận phía xa
[NeMo I 2026-07-01 13:29:10 wer:338] WER predicted:hiện ra tình phía xa
[NeMo I 2026-07-01 13:29:10 wer:336]

[NeMo I 2026-07-01 13:29:10 wer:337] WER reference:nên với thông tin này
[NeMo I 2026-07-01 13:29:10 wer:338] WER predicted:nên với thông tiền này
[NeMo I 2026-07-01 13:29:10 wer:336]

[NeMo I 2026-07-01 13:29:10 wer:337] WER reference:và dân dã như chính cái tên của nó
[NeMo I 2026-07-01 13:29:10 wer:338] WER predicted:và dân gia như chính cái trên của nó
[NeMo I 2026-07-01 13:29:10 wer:336]

[NeMo I 2026-07-01 13:29:10 wer:337] WER reference:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 13:29:10 wer:338] WER predicted:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 13:29:10 wer:336]

[NeMo I 2026-07-01 13:29:10 wer:337] WER reference:sau nhiều pha hảm thành liên tục
[NeMo I 2026-07-01 13:29:10 wer:338] WER predicted:sau nhiều phá h thành liên tục
[NeMo I 2026-07-01 13:29:10 wer:336]

[NeMo I 2026-07-01 13:29:10 wer:337] WER reference:anh vẫn nhớ kỷ niệm cầu đầu lâu
[NeMo I 2026-07-01 13:29:10 wer:338] WER predicted:anh v vẫn nhớ kỳiềm cầu đầu lâu
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:gay go lắm nhưng hoàng anh gia lai sẽ làm được
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:g g l lắm nhưng hơn anh gia là sẽ làm đ được
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:do đó khi chơi chung với bạn bè cùng lứa chúng thường tỏ ra thiếu tự tin
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:do đó khi tr chơi chúng với bạn bé cũng lư chúng ta thường tôi cả thiếu từ tính
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:mối đục luỗng cả tấm gỗ
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:mới được luôn cả t tâm g
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:người ta cho rằng trung tâm này có khả năng ảnh hưởng đến quá trình lão hóa
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:người ta cho rằng trung tâm này có khá năng anh hướng đến quá trên lao hoa
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:các giò phong lan tháng ba cũng không chịu yên mình
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:các cho phẩm lên tha ba cũng công chịu ý mình
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:hãy cho tôi quyền năng vô tận để bảo vệ loài vật
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:hay cho tôi viên năng v vô tăng để bảo về loi vật
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:sáng chiều hội diễn tiếng hát bảo minh do công ty bảo hiểm bảo minh tổ chức
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:sáng chịu họ diễn tiếng khác đầu mình do công ty bảo hiểm báo mình tôi chức
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:cô nằm thiếp đi lúc nào không biết
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:cô năm tiếp đi lúc nào không biết
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:mười bảy mười tám mười chín
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:mươi bảy mươi tám mươi chín
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:tích cóp đủ thứ đồ lạc xon những ngọn đèn
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:tiếpốc đưa thứ đồ đ đã so những ngọ đang
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:nhưng đất nước đã chọn một nhà lãnh đạo khác
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:nhưng nước nước đã chọn một nhà lên đầu khác
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:ưu thế này có được là nhờ quá trình cơ giới hóa nhanh sử dụng phân bón cho dù hậu quả có là
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:uống thế này có được là nhớ quá trình cơ giới hoa nhanh sự dụng phần bốn cho dụnghầu quả có làm
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:thường xuyên xảy ra hiện tượng đạo văn quỵt nhuận bút
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:thường xuyên x ra hiện thường đào văn quyết nhút
[NeMo I 2026-07-01 13:29:11 wer:336]

[NeMo I 2026-07-01 13:29:11 wer:337] WER reference:chỉ cho chúng tôi xem hàng đống gạch đá cát sỏi
[NeMo I 2026-07-01 13:29:11 wer:338] WER predicted:chỉ cho chúng tôi xem hàng đồng cả đã các số
[NeMo I 2026-07-01 13:29:12 wer:336]

[NeMo I 2026-07-01 13:29:12 wer:337] WER reference:đối với cảng hàng không quốc tế đà nẵng sử dụng nhà ga hành khách hiện hữu làm nhà ga nội địa
[NeMo I 2026-07-01 13:29:12 wer:338] WER predicted:đối với càng hàng không quốc tế đã năng sự dụng nhà gia hành khách hiện hồ làm nhà g nói để
[NeMo I 2026-07-01 13:29:12 wer:336]

[NeMo I 2026-07-01 13:29:12 wer:337] WER reference:người giàu thì vác nặng những xâu tiền kẽm trên vai
[NeMo I 2026-07-01 13:29:12 wer:338] WER predicted:ngườiào thì vật nạ những sau tiềnk trên phải
[NeMo I 2026-07-01 13:29:12 wer:336]

[NeMo I 2026-07-01 13:29:12 wer:337] WER reference:các nữ công nhân làm ca đêm
[NeMo I 2026-07-01 13:29:12 wer:338] WER predicted:các nữ công nhân làm cả điểm
[NeMo I 2026-07-01 13:29:12 wer:336]

[NeMo I 2026-07-01 13:29:12 wer:337] WER reference:tui biết bà giỏi rồi
[NeMo I 2026-07-01 13:29:12 wer:338] WER predicted:tôi biết bà di rồi
[NeMo I 2026-07-01 13:29:12 wer:336]

[NeMo I 2026-07-01 13:29:12 wer:337] WER reference:đưa một chú bồ câu bay đi bay về
[NeMo I 2026-07-01 13:29:12 wer:338] WER predicted:đường một chú bộ cầu bảy đi bị v về
[NeMo I 2026-07-01 13:29:12 wer:336]

[NeMo I 2026-07-01 13:29:12 wer:337] WER reference:tôi đến kiểm tra và phát hiện thấy ông và cô gái nằm kia thám tử ra hiệu cho ngài triệu phú nhìn vào phòng tắm cô ta đã chết
[NeMo I 2026-07-01 13:29:12 wer:338] WER predicted:tôi đến kiểm ra và phát hiện thấy ông và cô gái nămk tha từ ra hiểu cho ngày chịu phương nhìn vào phòng tâm cô đã chết
[NeMo I 2026-07-01 13:29:12 wer:336]

[NeMo I 2026-07-01 13:29:12 wer:337] WER reference:để thực hiện thắng lợi kế hoạch năm năm
[NeMo I 2026-07-01 13:29:12 wer:338] WER predicted:để thực hiện thân lại cái hết năm năm
[NeMo I 2026-07-01 13:29:12 wer:336]

[NeMo I 2026-07-01 13:29:12 wer:337] WER reference:trước khi hóa thân thành cộng hòa sét để đến bồ đào nha
[NeMo I 2026-07-01 13:29:12 wer:338] WER predicted:trước khi hoa thân thành còn hoa sức để đến bộ đồng nhà
[NeMo I 2026-07-01 13:29:12 wer:336]

[NeMo I 2026-07-01 13:29:12 wer:337] WER reference:tuy nhiên tôi không chắc những người chưa từng đọc cuốn nhật ký có thể hiểu hết được ý nghĩa bộ phim
[NeMo I 2026-07-01 13:29:12 wer:338] WER predicted:tuy nhiên tôi không chắc những người chưa từ đọc cũng nhất kỳ có thể hiểu hết được ý nghĩ bộ phim
[NeMo I 2026-07-01 13:29:12 wer:336]

[NeMo I 2026-07-01 13:29:12 wer:337] WER reference:chi đầu tư từ khu vực nhà nước còn lớn và hiệu quả thấp
[NeMo I 2026-07-01 13:29:12 wer:338] WER predicted:chỉ đầu tư từ khu vực nhà n nước còn lớn và hiệu quả th hợp
[NeMo I 2026-07-01 13:29:12 wer:336]

[NeMo I 2026-07-01 13:29:12 wer:337] WER reference:cái nền xưa của nó bây giờ là một cái hố nông choèn
[NeMo I 2026-07-01 13:29:12 wer:338] WER predicted:cái nên s của nó bị giờ là một cái hồ n năm tr
[NeMo I 2026-07-01 13:29:12 wer:336]

[NeMo I 2026-07-01 13:29:12 wer:337] WER reference:giải truyền thông điện ảnh trung quốc là giải thưởng điện ảnh duy nhất xét trao cho tất cả các bộ phim hoa ngữ
[NeMo I 2026-07-01 13:29:12 wer:338] WER predicted:giải trên thường đến anh chúng quốc là dài thường đến anh gì sẽ cho cho tất cả các bộ hiện hoànư
[NeMo I 2026-07-01 13:29:12 wer:336]

[NeMo I 2026-07-01 13:29:12 wer:337] WER reference:dự đoán ba tháng nữa giá cà phê sẽ tăng gấp đôi hiện nay
[NeMo I 2026-07-01 13:29:12 wer:338] WER predicted:điều rằng ba tháng nữa giá và về s tăng gặp đôi hiện này
[NeMo I 2026-07-01 13:29:12 wer:336]

[NeMo I 2026-07-01 13:29:12 wer:337] WER reference:họ đến đây vì nhiều mục đích
[NeMo I 2026-07-01 13:29:12 wer:338] WER predicted:họ đến đâyì nhiều một đích
[NeMo I 2026-07-01 13:29:12 wer:336]

[NeMo I 2026-07-01 13:29:12 wer:337] WER reference:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 13:29:12 wer:338] WER predicted:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:vậy trước đây nông dân đối phó với hiện tượng này như thế nào thưa ông
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:vậy trước đây n năm nhân đối phố v với hiện từ này như đến nào thu  ông
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:làm sao để có tiền nhanh nhất
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:làm sao để có tiền nhân nhất
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:đùi dang ra ngoài
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:được gian ra ngoài
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:đã hai lần cô gác lại ước mơ vào đời và cũng đã ít nhiều trải qua những thăng trầm xô bồ của cuộc sống
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:đã hai l lần cô gái lạiút mới vào đời và cũng đã ít nhiều trái qua những tha tr số bộ của cuộc sống
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:trong bối cảnh như vậy một phản ứng chính sách đối với vấn đề thất nghiệp đang là đòi hỏi cấp bách hiện nay
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:trong bộ cảnh như vậy một phầnững chính sách đối với vẫn để nghiệpp đang là đời họ cách cách hiện này
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:ở xứ sở chuột túi
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:ở s sơ tr chủ tôi
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:do vậy dựa trên cơ sở nào mà ông khoa phát biểu như vậy
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:do vậy dự trên cơ s nào ông khoa phát biểu như vậy
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:tá tàng
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:ta tăng
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:cách đây tám năm nhưng trước đó khoảng hai năm đã được mời đóng phim và có nhiều vai chính trong các phim điện ảnh truyền hình
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:cách đây tâm năm nh trước đó hoàn hai năm đã được mới động phim và có nhiều và chính trong các phim điện anh truyền hình
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:đã thăm hỏi thì thế nào cũng phải có quà cáp
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:đã tâmm họ thì thế nào cũng phải có quả các
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:có mặt tạià điện phòng
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:em lơ đễnh lật xem vài tờ báo
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:em là điện l xem vàờ báo
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:và không ít người cứ tì tì uống từ sáng đến tối suốt mấy ngày hội nghị
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:và không ít người cứ ty từ  uống từ sáng đến tôi xuất máy ngày hội này
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:minh châu vào miền nam công tác tại nhà hát trần hữu trang
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:mình cao vào m nam công tất tại nhà ho rằng h rằng
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:hết chiến tranh quê hương im tiếng súng anh lính cụ hồ lại trở về với đời thường tham gia sản xuất xây dựng và bảo vệ đất nước
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:hết tiếng trên với hơn ý tiếng xuống anh lên của hồ lại cho về với đời thường tham giá sản xuất sẽ d vào b với đất nước
[NeMo I 2026-07-01 13:29:13 wer:336]

[NeMo I 2026-07-01 13:29:13 wer:337] WER reference:chuyến đi đó đến giờ vẫn là một ám ảnh trong ký ức tôi
[NeMo I 2026-07-01 13:29:13 wer:338] WER predicted:chỉ đi đó đến giờ vẫn là một ông anh trong kỳ
[NeMo I 2026-07-01 13:29:14 wer:336]

[NeMo I 2026-07-01 13:29:14 wer:337] WER reference:ây da ây da
[NeMo I 2026-07-01 13:29:14 wer:338] WER predicted:giá gia
[NeMo I 2026-07-01 13:29:14 wer:336]

[NeMo I 2026-07-01 13:29:14 wer:337] WER reference:có rất nhiều vệ tinh bị rơi khỏi quỹ đạo
[NeMo I 2026-07-01 13:29:14 wer:338] WER predicted:rất nhiều về tính bị rồi khó qu nào
[NeMo I 2026-07-01 13:29:14 wer:336]

[NeMo I 2026-07-01 13:29:14 wer:337] WER reference:nhuốm đầy máu của thổ dân châu mỹ
[NeMo I 2026-07-01 13:29:14 wer:338] WER predicted:nhóm đây m máu của thủ dân cho mỹ
[NeMo I 2026-07-01 13:29:14 wer:336]

[NeMo I 2026-07-01 13:29:14 wer:337] WER reference:cụ thể về đất đai xây dựng văn hóa thuộc về từng ngành riêng biệt
[NeMo I 2026-07-01 13:29:14 wer:338] WER predicted:cô thể về đ đất đây văn sẽ những văn hoa thuốc về từ ngành riêng biết
[NeMo I 2026-07-01 13:29:14 wer:336]

[NeMo I 2026-07-01 13:29:14 wer:337] WER reference:tôi muốn hỏi liệu có mùi hương sen nhân tạo là một loại hóa chất không
[NeMo I 2026-07-01 13:29:14 wer:338] WER predicted:tôi muốn hỏi liệu có mười hướng s nhân tạo là một loại họ chắc cao
[NeMo I 2026-07-01 13:29:14 wer:336]

[NeMo I 2026-07-01 13:29:14 wer:337] WER reference:cả nhà bà ngoại cười nắc nẻ vì câu nói ngây ngô của con
[NeMo I 2026-07-01 13:29:14 wer:338] WER predicted:các nhà bao ngoài người nước ngheì cô nói ngày ngủ của con
[NeMo I 2026-07-01 13:29:14 wer:336]

[NeMo I 2026-07-01 13:29:14 wer:337] WER reference:xin được chân khuân vác
[NeMo I 2026-07-01 13:29:14 wer:338] WER predicted:xin được trên khu phát
[NeMo I 2026-07-01 13:29:14 wer:336]

[NeMo I 2026-07-01 13:29:14 wer:337] WER reference:nằm khuất dưới tàn tre sát bờ sông châu
[NeMo I 2026-07-01 13:29:14 wer:338] WER predicted:ho giới đàn trẻ sẽờ s sống ch
[NeMo I 2026-07-01 13:29:14 wer:336]

[NeMo I 2026-07-01 13:29:14 wer:337] WER reference:nếu kiên cố hóa thì vốn được đưa thẳng cho dân sẽ không thất thoát
[NeMo I 2026-07-01 13:29:14 wer:338] WER predicted:nếu ki cô hoa thì bốn được đưa tăng cho dân sẽ không thật
[NeMo I 2026-07-01 13:29:14 wer:336]

[NeMo I 2026-07-01 13:29:14 wer:337] WER reference:nói chung cô hồng nào cũng có một số phận hoàn cảnh và cuộc đời riêng
[NeMo I 2026-07-01 13:29:14 wer:338] WER predicted:nói chúng cô học nào cũng có một số phần hoàn cảnhnh với cuộc đời riêng
[NeMo I 2026-07-01 13:29:14 wer:336]

[NeMo I 2026-07-01 13:29:14 wer:337] WER reference:nhưng tất cả những điều ấy chẳng mấy khi đi liền với nhau
[NeMo I 2026-07-01 13:29:14 wer:338] WER predicted:những tất cả những điều ấy ch mấy khi đi liên với nhau
[NeMo I 2026-07-01 13:29:14 wer:336]

[NeMo I 2026-07-01 13:29:14 wer:337] WER reference:như vậy là bạn có thể sử dụng được nhiều số điện thoại của nhiều nhà cung cấp dịch vụ chỉ trên một sim
[NeMo I 2026-07-01 13:29:14 wer:338] WER predicted:như vậy bạn có thể sự dụng được nhiều số đến th của như nhà cũng cấp dịch vụ chỉ trên một xem
[NeMo I 2026-07-01 13:29:14 wer:336]

[NeMo I 2026-07-01 13:29:14 wer:337] WER reference:trong trường hợp hai bên có thỏa thuận lại không yêu cầu trọng tài giải quyết nữa thì có quyền kiện ra tòa án
[NeMo I 2026-07-01 13:29:14 wer:338] WER predicted:trong trường hợp hai bên có th thường lại không yêu cầu trong ta d quyết nữa thì có quyền kiến ra toàn ăn
[NeMo I 2026-07-01 13:29:14 wer:336]

[NeMo I 2026-07-01 13:29:14 wer:337] WER reference:kiểu này chắc phải cắt giảm biên chế
[NeMo I 2026-07-01 13:29:14 wer:338] WER predicted:kiể này chắc phải các giảm biến chế
[NeMo I 2026-07-01 13:29:14 wer:336]

[NeMo I 2026-07-01 13:29:14 wer:337] WER reference:nhưng tôi không yêu cô cô biết rõ điều đó mà
[NeMo I 2026-07-01 13:29:14 wer:338] WER predicted:nhưng tôi không yêu cô cô biết rồi điều đó mà
[NeMo I 2026-07-01 13:29:15 wer:336]

[NeMo I 2026-07-01 13:29:15 wer:337] WER reference:khó mà đoán trước chính xác kết quả khi quả bóng còn lăn
[NeMo I 2026-07-01 13:29:15 wer:338] WER predicted:khó mà đó trước chính sẽích quả khi qua b bóng con
[NeMo I 2026-07-01 13:29:15 wer:336]

[NeMo I 2026-07-01 13:29:15 wer:337] WER reference:vừa nhìn thấy sự xuất hiện của bố tất cả mấy thằng khác vùng bỏ chạy sạch
[NeMo I 2026-07-01 13:29:15 wer:338] WER predicted:ừa nh thấy sự sự hiện của bố tất cả máy th thành khác vùng bỏi trẻ sách
[NeMo I 2026-07-01 13:29:15 wer:336]

[NeMo I 2026-07-01 13:29:15 wer:337] WER reference:phải nâng cao khả năng cạnh tranh của nền kinh tế
[NeMo I 2026-07-01 13:29:15 wer:338] WER predicted:phải năng cao kh năng cảnh trên của nên kinh tên
[NeMo I 2026-07-01 13:29:15 wer:336]

[NeMo I 2026-07-01 13:29:15 wer:337] WER reference:bà thường lấy ý tưởng cho các tác phẩm từ đâu
[NeMo I 2026-07-01 13:29:15 wer:338] WER predicted:bà thườngấy ý từ cho các tác phẩm từ đồng
[NeMo I 2026-07-01 13:29:15 wer:336]

[NeMo I 2026-07-01 13:29:15 wer:337] WER reference:khi chứng kiến người vợ lăng loàn
[NeMo I 2026-07-01 13:29:15 wer:338] WER predicted:khi chứng kiến người vào l lần lòng
[NeMo I 2026-07-01 13:29:15 wer:336]

[NeMo I 2026-07-01 13:29:15 wer:337] WER reference:tác phẩm to lớn bằng đồng như tượng phật quỳnh lâm chuông quy điền tháp báo thiên vạc phổ minh an nam tứ đại khí
[NeMo I 2026-07-01 13:29:15 wer:338] WER predicted:ta phẩm ta lớn bạn đồng như tượng phát quyền lắm chúng qu điện th bảo tìm và phố mình ăn nam tư đây khi
[NeMo I 2026-07-01 13:29:15 wer:336]

[NeMo I 2026-07-01 13:29:15 wer:337] WER reference:ngoài ra họ vẫn còn muốn giữ chân cầu thủ xuất sắc nhất của mình
[NeMo I 2026-07-01 13:29:15 wer:338] WER predicted:họ vẫn cầu muốnư chân cầu thủ xuất s
[NeMo I 2026-07-01 13:29:15 wer:336]

[NeMo I 2026-07-01 13:29:15 wer:337] WER reference:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 13:29:15 wer:338] WER predicted:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 13:29:15 wer:336]

[NeMo I 2026-07-01 13:29:15 wer:337] WER reference:và gã thệ bị điều về làm trưởng phòng xã hội huyện
[NeMo I 2026-07-01 13:29:15 wer:338] WER predicted:và cả thể biết điều về làm trường phần xã hộii h
[NeMo I 2026-07-01 13:29:15 wer:336]

[NeMo I 2026-07-01 13:29:15 wer:337] WER reference:là rút rỉa tiền của bạn càng nhiều càng tốt

[NeMo W 2026-07-01 13:29:30 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:29:30 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

[best val_wer] epoch=11 val_wer=0.440730 exported=/kaggle/working/phase3_continue_best.nemo

Sample predictions after epoch 11:
  [0] REF: những con vật này đã bị giết và đốt
      HYP: nh con vật này đã bị d vàốc
  [1] REF: phòng chống tham nhũng không được chủ quan cần làm liên tục đồng bộ và có các giải pháp
      HYP: phòng trong tham nh dụng không được chủ quan cần làm liên động bộ và có các đại pháp
  [2] REF: do vậy có máy cũng không thường dùng
      HYP: do vậy có mấy cũng không thường dụng
  [3] REF: mới khệnh khạng đứng lên đi ra
      HYP: mới kh khá đứng lên đi ra
  [4] REF: đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
      HYP: đây sẽ là cuộc gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
  [5] REF: sau một năm eo sèo
      HYP: sáu một năm yêu xe
  [6] REF: sau đó một vật lạ bay xợt ngang nóc nhà ông
      HYP: sau đó một và là b sự ng năngn nốc nhau
  [7] REF: chín mươi hai chín mươi ba
      HYP: chín mươi hai chín mươi ba
  [8] REF: hiện ra tận phía xa
      HYP: hiện ra tình phía xa
  [9] REF: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã qua của thị trường
      HYP: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã quá của thì trường
[epoch] epoch=11/12 step=3454 val_loss=2.0922296047210693 val_wer=0.44072985649108887
[NeMo I 2026-07-01 13:29:51 wer:336]

[NeMo I 2026-07-01 13:29:51 wer:337] WER reference:rất nhiều trường hợp phụ huynh đau đầu vì con một đã tìm đến chuyên viên tư vấn tâm lý
[NeMo I 2026-07-01 13:29:51 wer:338] WER predicted:rất người trường học phụ kh đâu đầuì anh một đã tìm đến trên viên tư anh tâm lý
[NeMo I 2026-07-01 13:30:00 wer:336]

[NeMo I 2026-07-01 13:30:00 wer:337] WER reference:trước tình thế đó tôi buộc phải tìm cho mình một bến đỗ mới và tôi đã quyết định ra đi
[NeMo I 2026-07-01 13:30:00 wer:338] WER predicted:lúc tình thế đó tôi bộ phải tiền cho mình một bên đ đầu mới và tôi đã quyết bệnh ra đi
[NeMo I 2026-07-01 13:30:09 wer:336]

[NeMo I 2026-07-01 13:30:09 wer:337] WER reference:tuy nhiên tình hình đó không diễn ra ở tất cả trường
[NeMo I 2026-07-01 13:30:09 wer:338] WER predicted:tuy nhiên tình hình đó không diễná ở tất cả tr trường
[NeMo I 2026-07-01 13:30:17 wer:336]

[NeMo I 2026-07-01 13:30:17 wer:337] WER reference:nếu xét trên qui mô toàn tỉnh con số ấy vẫn còn khiêm tốn lắm
[NeMo I 2026-07-01 13:30:17 wer:338] WER predicted:nên x chỉ phí mua toàn tình cầu số ấy vẫn còn khiù làm
[NeMo I 2026-07-01 13:30:26 wer:336]

[NeMo I 2026-07-01 13:30:26 wer:337] WER reference:các vùng sâu vùng xa khó mà phát triển
[NeMo I 2026-07-01 13:30:26 wer:338] WER predicted:các vùng sau vùng xe khó mà phát triển
[NeMo I 2026-07-01 13:30:35 wer:336]

[NeMo I 2026-07-01 13:30:35 wer:337] WER reference:thì không hiểu sao ở phần thơ cổ đại
[NeMo I 2026-07-01 13:30:35 wer:338] WER predicted:thì không hiểu sao ở phần hết của đầy
[NeMo I 2026-07-01 13:30:43 wer:336]

[NeMo I 2026-07-01 13:30:43 wer:337] WER reference:anh muốn thùy có thể tự do tìm cho mình một hạnh phúc khác tràn đầy
[NeMo I 2026-07-01 13:30:43 wer:338] WER predicted:anh muốn thì có thể từ do tìm cho mình một thành ph khác ngày lại
[NeMo I 2026-07-01 13:30:52 wer:336]

[NeMo I 2026-07-01 13:30:52 wer:337] WER reference:áo thun trắng sát nách
[NeMo I 2026-07-01 13:30:52 wer:338] WER predicted:áo thu trang sát nắc
[NeMo I 2026-07-01 13:31:00 wer:336]

[NeMo I 2026-07-01 13:31:00 wer:337] WER reference:đây cũng là giai đoạn thị trường nhiều biến cố nhất
[NeMo I 2026-07-01 13:31:00 wer:338] WER predicted:đây cũng là chế đồng thì trường nhiều biến cô nhất
[NeMo I 2026-07-01 13:31:09 wer:336]

[NeMo I 2026-07-01 13:31:09 wer:337] WER reference:mới thành món ngon và độc đáo
[NeMo I 2026-07-01 13:31:09 wer:338] WER predicted:mới thành m món ngon và được đâu
[NeMo I 2026-07-01 13:31:18 wer:336]

[NeMo I 2026-07-01 13:31:18 wer:337] WER reference:người đẹp không thiếu chỉ sợ ông anh không có tiền
[NeMo I 2026-07-01 13:31:18 wer:338] WER predicted:người để không thiếu chỉ s ông anh không có tình
[NeMo I 2026-07-01 13:31:26 wer:336]

[NeMo I 2026-07-01 13:31:26 wer:337] WER reference:ngày thường chù ụ thì được
[NeMo I 2026-07-01 13:31:26 wer:338] WER predicted:ngày thường chủổ chỉ được
[NeMo I 2026-07-01 13:31:35 wer:336]

[NeMo I 2026-07-01 13:31:35 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 13:31:35 wer:338] WER predicted:có mặt tại sẽ điện phương
[NeMo I 2026-07-01 13:31:43 wer:336]

[NeMo I 2026-07-01 13:31:43 wer:337] WER reference:tôi cũng biết có những tiêu cực trong giáo dục và nhà trường cũng như những lĩnh vực khác của xã hội
[NeMo I 2026-07-01 13:31:43 wer:338] WER predicted:tôi cũng biết có những tiêu thực trong giá được và nhà trường của như những lên vợ h của xã hội
[NeMo I 2026-07-01 13:31:52 wer:336]

[NeMo I 2026-07-01 13:31:52 wer:337] WER reference:xắn quần vượt qua là bước vào thế giới
[NeMo I 2026-07-01 13:31:52 wer:338] WER predicted:sốngn qu v qua là bước vào thế giới
[NeMo I 2026-07-01 13:32:01 wer:336]

[NeMo I 2026-07-01 13:32:01 wer:337] WER reference:mới và cải tiến
[NeMo I 2026-07-01 13:32:01 wer:338] WER predicted:mới và cả tiền
[NeMo I 2026-07-01 13:32:09 wer:336]

[NeMo I 2026-07-01 13:32:09 wer:337] WER reference:hai vợ chồng thị tớn và văn đục
[NeMo I 2026-07-01 13:32:09 wer:338] WER predicted:hai vợ trong thì tưởng và văn được
[NeMo I 2026-07-01 13:32:18 wer:336]

[NeMo I 2026-07-01 13:32:18 wer:337] WER reference:chợ đêm ca ba dành cho những người đang vào mùa tăng ca cuối năm
[NeMo I 2026-07-01 13:32:18 wer:338] WER predicted:ở đến có ba danh choững người đang vào một tăng cả cứ năm
[NeMo I 2026-07-01 13:32:26 wer:336]

[NeMo I 2026-07-01 13:32:26 wer:337] WER reference:hai mươi hai mươi mốt
[NeMo I 2026-07-01 13:32:26 wer:338] WER predicted:hai mươi hai mươi mốt
[NeMo I 2026-07-01 13:32:35 wer:336]

[NeMo I 2026-07-01 13:32:35 wer:337] WER reference:anh không thể quên được những giây phút ngọt ngào ấy
[NeMo I 2026-07-01 13:32:35 wer:338] WER predicted:anh không được quanh được nh ph gian ngọ nào ấy
[NeMo I 2026-07-01 13:32:43 wer:336]

[NeMo I 2026-07-01 13:32:43 wer:337] WER reference:đưa tới tình trạng phá sản
[NeMo I 2026-07-01 13:32:43 wer:338] WER predicted:ưa tư tiền rằng phá sản
[NeMo I 2026-07-01 13:32:52 wer:336]

[NeMo I 2026-07-01 13:32:52 wer:337] WER reference:phụ huynh và học sinh đang phải è cổ vì sách giá cao
[NeMo I 2026-07-01 13:32:52 wer:338] WER predicted:vụ qu và học sinh đang phải em cô vì sách gia cao
[NeMo I 2026-07-01 13:33:01 wer:336]

[NeMo I 2026-07-01 13:33:01 wer:337] WER reference:thỉnh thoảng lại có người ghép thận trước đó trở qua xin xét nghiệm vì có trục trặc
[NeMo I 2026-07-01 13:33:01 wer:338] WER predicted:tình toàn lại có người g thằ tư và tôi qua sinh sẽ nhiều về cóục đọc
[NeMo I 2026-07-01 13:33:09 wer:336]

[NeMo I 2026-07-01 13:33:09 wer:337] WER reference:cuộc thi nhằm trau dồi niềm đam mê
[NeMo I 2026-07-01 13:33:09 wer:338] WER predicted:cuộc thi nh tr d nhiệm đã mẹ
[NeMo I 2026-07-01 13:33:18 wer:336]

[NeMo I 2026-07-01 13:33:18 wer:337] WER reference:đề thi môn vẽ thông thường là về vẽ trang trí sản phẩm vật thể
[NeMo I 2026-07-01 13:33:18 wer:338] WER predicted:để thi muốn v vẻ hô thường là về về sáng chỉ sản phẩm một thể
[NeMo I 2026-07-01 13:33:26 wer:336]

[NeMo I 2026-07-01 13:33:26 wer:337] WER reference:bước vào một mối tình
[NeMo I 2026-07-01 13:33:26 wer:338] WER predicted:bước vào một mua tình
[NeMo I 2026-07-01 13:33:35 wer:336]

[NeMo I 2026-07-01 13:33:35 wer:337] WER reference:lão nạp chỉ có nhiêu đây thôi
[NeMo I 2026-07-01 13:33:35 wer:338] WER predicted:làoạ chỉ có như lại tôi
[NeMo I 2026-07-01 13:33:43 wer:336]

[NeMo I 2026-07-01 13:33:43 wer:337] WER reference:hai tuần sau
[NeMo I 2026-07-01 13:33:43 wer:338] WER predicted:hai tuần sáu
[NeMo I 2026-07-01 13:33:52 wer:336]

[NeMo I 2026-07-01 13:33:52 wer:337] WER reference:những ngày cuối cùng trên dương thế
[NeMo I 2026-07-01 13:33:52 wer:338] WER predicted:những này cuối cùng trên dân thế
[NeMo I 2026-07-01 13:34:00 wer:336]

[NeMo I 2026-07-01 13:34:00 wer:337] WER reference:trên nhiều tuyến phố công nhân đang hối hả dọn dẹp
[NeMo I 2026-07-01 13:34:00 wer:338] WER predicted:trên nhiều tiếng ph công nhưng đang hội hệ động nghiệpp
[NeMo I 2026-07-01 13:34:09 wer:336]

[NeMo I 2026-07-01 13:34:09 wer:337] WER reference:có trường hợp bất hợp pháp như trần thị thu h
[NeMo I 2026-07-01 13:34:09 wer:338] WER predicted:có chuyện học bất hợp pháp như trong thì thu
[NeMo I 2026-07-01 13:34:17 wer:336]

[NeMo I 2026-07-01 13:34:17 wer:337] WER reference:nhưng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được các khó khăn đó
[NeMo I 2026-07-01 13:34:17 wer:338] WER predicted:chúng tôi nghĩ rằng nếu có quyết tâm cao thì sẽ giải quyết được cả khó không đó
[NeMo I 2026-07-01 13:34:26 wer:336]

[NeMo I 2026-07-01 13:34:26 wer:337] WER reference:lúc đó em không thể tiếp tục công việc đánh cá của cha một mình vì còn quá nhỏ
[NeMo I 2026-07-01 13:34:26 wer:338] WER predicted:lúc đó em không phải tiếp được không việcánh các của tra một mình việc còn quá nhỏ
[NeMo I 2026-07-01 13:34:35 wer:336]

[NeMo I 2026-07-01 13:34:35 wer:337] WER reference:cuốn sách nói về sự lầm lẫn giữa luật kinh tế ở châu âu và châu mỹ kim vẫn chưa đọc tới vì cô không quan tâm đến luật
[NeMo I 2026-07-01 13:34:35 wer:338] WER predicted:cũng sinh nói về làm lần nhiều được ki tế ở ch ông và trong muốn cho vẫn chưa đọc tôi việc của không quan tăng đến luật
[NeMo I 2026-07-01 13:34:43 wer:336]

[NeMo I 2026-07-01 13:34:43 wer:337] WER reference:khi tên lửa bay lên
[NeMo I 2026-07-01 13:34:43 wer:338] WER predicted:khi tên l lời vậy lên
[NeMo I 2026-07-01 13:34:52 wer:336]

[NeMo I 2026-07-01 13:34:52 wer:337] WER reference:mà theo thời gian sẽ tiệm cận với trí khôn của con người
[NeMo I 2026-07-01 13:34:52 wer:338] WER predicted:mà theo thời dân sẽ tìm cần với trí không quốc con người
[NeMo I 2026-07-01 13:35:00 wer:336]

[NeMo I 2026-07-01 13:35:00 wer:337] WER reference:bên kia láng giềng của tôi hôm nay không thấy thăm hoa
[NeMo I 2026-07-01 13:35:00 wer:338] WER predicted:đến kia lan diễn của tôi hô này không thấy th h
[NeMo I 2026-07-01 13:35:09 wer:336]

[NeMo I 2026-07-01 13:35:09 wer:337] WER reference:anh yêu cầu các cầu thủ phải đeo bám ngay khi đối phương có bóng
[NeMo I 2026-07-01 13:35:09 wer:338] WER predicted:anh nhiều cầu các cầu số phảieo bạn ngày khi đối phương có
[NeMo I 2026-07-01 13:35:18 wer:336]

[NeMo I 2026-07-01 13:35:18 wer:337] WER reference:ngay cả công an đi lẻ loi cũng bị tấn công vì trong khu vực này có một thứ luật riêng cấm người lạ vào
[NeMo I 2026-07-01 13:35:18 wer:338] WER predicted:nghe và không mình đi lẽ cũng bị không con việc trong có việc mẹ một thứ lực viên công như l
[NeMo I 2026-07-01 13:35:26 wer:336]

[NeMo I 2026-07-01 13:35:26 wer:337] WER reference:thì chúng sẽ nằm trong tầm kiểm soát của bạn
[NeMo I 2026-07-01 13:35:26 wer:338] WER predicted:thì chúng sẽ năm trong đầm kiể sau của bạn
[NeMo I 2026-07-01 13:35:35 wer:336]

[NeMo I 2026-07-01 13:35:35 wer:337] WER reference:đó là hai con sói hoàn toàn trái ngược nhau về hình thức
[NeMo I 2026-07-01 13:35:35 wer:338] WER predicted:đó là hay con s hộ còn chính được nhau về hình thức
[NeMo I 2026-07-01 13:35:43 wer:336]

[NeMo I 2026-07-01 13:35:43 wer:337] WER reference:trại đồng xã yên sở giữa một biển nước mênh mông ảnh nguyễn quân
[NeMo I 2026-07-01 13:35:43 wer:338] WER predicted:tr đồng xã em s giờ một biểnứ mình món  anh quyền quan
[NeMo I 2026-07-01 13:35:52 wer:336]

[NeMo I 2026-07-01 13:35:52 wer:337] WER reference:không sao rồi em mừng lắm
[NeMo I 2026-07-01 13:35:52 wer:338] WER predicted:không sao rồi em mình lắm
[NeMo I 2026-07-01 13:36:00 wer:336]

[NeMo I 2026-07-01 13:36:00 wer:337] WER reference:việc tòa án của pháp truy tố công dân một nước độc lập trên lãnh thổ quê hương của người ấy là một điều vô giá trị
[NeMo I 2026-07-01 13:36:00 wer:338] WER predicted:việc tôi ăn cuộc pháp tr tốt của không một được được lập trên l lên tôi cuối hơn còn ở ấy là một bị chú giá trị
[NeMo I 2026-07-01 13:36:09 wer:336]

[NeMo I 2026-07-01 13:36:09 wer:337] WER reference:bà mẹ nghèo đông con
[NeMo I 2026-07-01 13:36:09 wer:338] WER predicted:bà mẹ nghe vấn con
[NeMo I 2026-07-01 13:36:18 wer:336]

[NeMo I 2026-07-01 13:36:18 wer:337] WER reference:lấy tĩnh chế động
[NeMo I 2026-07-01 13:36:18 wer:338] WER predicted:l liệu tình cho động
[NeMo I 2026-07-01 13:36:26 wer:336]

[NeMo I 2026-07-01 13:36:26 wer:337] WER reference:mình mẩy tôi tuy đau đớn
[NeMo I 2026-07-01 13:36:26 wer:338] WER predicted:mình bảy tôi tuy đau đường
[NeMo I 2026-07-01 13:36:35 wer:336]

[NeMo I 2026-07-01 13:36:35 wer:337] WER reference:luôn ngẩng cao đầu sự khác biệt lớn nhất giữa người tự tin và người nhút nhát là gì
[NeMo I 2026-07-01 13:36:35 wer:338] WER predicted:luôn ngn cao đầu x khách người lớn nhỏ d người từ tiếng và người nh nhấtạ là gì
[NeMo I 2026-07-01 13:36:44 wer:336]

[NeMo I 2026-07-01 13:36:44 wer:337] WER reference:với các bạn trẻ trên đây có vẻ tình yêu không phải là tất cả
[NeMo I 2026-07-01 13:36:44 wer:338] WER predicted:với các bạn trẻ chính đây có về tình yêu kh và là tục cả
[NeMo I 2026-07-01 13:36:52 wer:336]

[NeMo I 2026-07-01 13:36:52 wer:337] WER reference:nếu trẻ bú không đủ có thể vắt sữa và cho trẻ uống bằng muỗng
[NeMo I 2026-07-01 13:36:52 wer:338] WER predicted:như trẻú không đủ có thể biết s và tr trẻ  uống bằngôn
[NeMo I 2026-07-01 13:37:01 wer:336]

[NeMo I 2026-07-01 13:37:01 wer:337] WER reference:hãy để thời gian tìm hiểu thêm và thuyết phục gia đình
[NeMo I 2026-07-01 13:37:01 wer:338] WER predicted:hãy để thời gian để mỹ thêm phải thu phục gia đình
[NeMo I 2026-07-01 13:37:10 wer:336]

[NeMo I 2026-07-01 13:37:10 wer:337] WER reference:vân vân và vân vân
[NeMo I 2026-07-01 13:37:10 wer:338] WER predicted:v vẫn bốn và vẫn bốn
[NeMo I 2026-07-01 13:37:19 wer:336]

[NeMo I 2026-07-01 13:37:19 wer:337] WER reference:mà phụ nữ trong khu vực công đang gặp phải
[NeMo I 2026-07-01 13:37:19 wer:338] WER predicted:mà phụ nơi trong khu vực công đang g gặp phải
[NeMo I 2026-07-01 13:37:27 wer:336]

[NeMo I 2026-07-01 13:37:27 wer:337] WER reference:những năm trước phần lớn sếu ở kiên lương kiên giang
[NeMo I 2026-07-01 13:37:27 wer:338] WER predicted:những năm ch phần lên sẽ ở khi lớn ki gia
[NeMo I 2026-07-01 13:37:36 wer:336]

[NeMo I 2026-07-01 13:37:36 wer:337] WER reference:theo nguyên đào kinh tế đô thị
[NeMo I 2026-07-01 13:37:36 wer:338] WER predicted:theo nguyên đào ki tên đưa thời
[NeMo I 2026-07-01 13:37:45 wer:336]

[NeMo I 2026-07-01 13:37:45 wer:337] WER reference:nhưng ngủ quá nhiều sẽ khiến bạn trở nên bơ phờ
[NeMo I 2026-07-01 13:37:45 wer:338] WER predicted:nhưng ngủ quá nhiều sẽ khiến bạn trên đến b ph
[NeMo I 2026-07-01 13:37:54 wer:336]

[NeMo I 2026-07-01 13:37:54 wer:337] WER reference:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 13:37:54 wer:338] WER predicted:tám mươi sáu tám mươi bảy
[NeMo I 2026-07-01 13:38:03 wer:336]

[NeMo I 2026-07-01 13:38:03 wer:337] WER reference:thường xuyên đối mặt với nạn khan hiếm lương thực
[NeMo I 2026-07-01 13:38:03 wer:338] WER predicted:thường x đối mặt với ngành khá hếm luôn thực
[NeMo I 2026-07-01 13:38:11 wer:336]

[NeMo I 2026-07-01 13:38:11 wer:337] WER reference:tôi có cảm tình với cô ấy nhưng tôi không muốn xen vào giữa họ
[NeMo I 2026-07-01 13:38:11 wer:338] WER predicted:tôi có cảm tình với cơ ấyững tôi không muốn xe vào d họ
[NeMo I 2026-07-01 13:38:20 wer:336]

[NeMo I 2026-07-01 13:38:20 wer:337] WER reference:với tôi chết là một sự ích kỷ còn bản chất sự sống đã là một bao dung ít nhất với chính mình
[NeMo I 2026-07-01 13:38:20 wer:338] WER predicted:với tôi chết là một sự kỳ công bạn chất sĩ sống đã một bao g biết nhất với chính mình
[NeMo I 2026-07-01 13:38:29 wer:336]

[NeMo I 2026-07-01 13:38:29 wer:337] WER reference:cậu không biết làm gì thì suốt đời cậu đúng là một kẻ hèn nhát
[NeMo I 2026-07-01 13:38:29 wer:338] WER predicted:cầu không biết làm gì thì xuất đời cầu đúng là một các hàng nhạc
[NeMo I 2026-07-01 13:38:37 wer:336]

[NeMo I 2026-07-01 13:38:37 wer:337] WER reference:màu đen của những tấm cha
[NeMo I 2026-07-01 13:38:37 wer:338] WER predicted:màu đang của những t tâm gia
[NeMo I 2026-07-01 13:38:46 wer:336]

[NeMo I 2026-07-01 13:38:46 wer:337] WER reference:tôi chỉ thấy người ta nhắc đến phượng vĩ tháng sáu hay cùng lắm là tháng năm
[NeMo I 2026-07-01 13:38:46 wer:338] WER predicted:tôi chỉ thấy ngườiáá đến phương vị tình sau hai cũng tám là thành ra
[NeMo I 2026-07-01 13:38:55 wer:336]

[NeMo I 2026-07-01 13:38:55 wer:337] WER reference:với câu trả lời xuất sắc và gương mặt khả ái
[NeMo I 2026-07-01 13:38:55 wer:338] WER predicted:với cô trả lời sức s vàương một khả ai
[NeMo I 2026-07-01 13:39:03 wer:336]

[NeMo I 2026-07-01 13:39:03 wer:337] WER reference:nhưng em có biết rằng anh yêu em cũng bởi những lý do đó
[NeMo I 2026-07-01 13:39:03 wer:338] WER predicted:n em có biết rằng anh như em cũng mọ những lý do
[NeMo I 2026-07-01 13:39:12 wer:336]

[NeMo I 2026-07-01 13:39:12 wer:337] WER reference:để nhìn thấy sự khôi hài
[NeMo I 2026-07-01 13:39:12 wer:338] WER predicted:để nhìn thấy sự khu hai
[NeMo I 2026-07-01 13:39:21 wer:336]

[NeMo I 2026-07-01 13:39:21 wer:337] WER reference:rèm cửa phòng khách của bạn giống như cung điện
[NeMo I 2026-07-01 13:39:21 wer:338] WER predicted:ra của phòng khách của bạn gi như cũng điện
[NeMo I 2026-07-01 13:39:29 wer:336]

[NeMo I 2026-07-01 13:39:29 wer:337] WER reference:và những khuyết điểm nhỏ của họ
[NeMo I 2026-07-01 13:39:29 wer:338] WER predicted:và những quyết điểm nhà của họ
[NeMo I 2026-07-01 13:39:38 wer:336]

[NeMo I 2026-07-01 13:39:38 wer:337] WER reference:tôi biết đây là quy tắc đòi hỏi
[NeMo I 2026-07-01 13:39:38 wer:338] WER predicted:tôi biết đây là quy tác đòi hỏi
[NeMo I 2026-07-01 13:39:47 wer:336]

[NeMo I 2026-07-01 13:39:47 wer:337] WER reference:cũng trong ngày đó bài xã luận gằn giọng
[NeMo I 2026-07-01 13:39:47 wer:338] WER predicted:cũng trong ngày đó và sến g rằng gi
[NeMo I 2026-07-01 13:39:56 wer:336]

[NeMo I 2026-07-01 13:39:56 wer:337] WER reference:bạn có thể ghé thăm nó
[NeMo I 2026-07-01 13:39:56 wer:338] WER predicted:bạn có thể g nghĩa tha nó
[NeMo I 2026-07-01 13:40:04 wer:336]

[NeMo I 2026-07-01 13:40:04 wer:337] WER reference:các anh sẽ mãi là những người con ưu tú của tổ quốc của nhân dân việt nam
[NeMo I 2026-07-01 13:40:04 wer:338] WER predicted:các anh xem hay là những người con ngủú tổ quốc của nhân dân việt nam
[NeMo I 2026-07-01 13:40:13 wer:336]

[NeMo I 2026-07-01 13:40:13 wer:337] WER reference:để luôn có một bình hoa tươi mới
[NeMo I 2026-07-01 13:40:13 wer:338] WER predicted:để luôn có một bệnh hoa tôi mới
[NeMo I 2026-07-01 13:40:22 wer:336]

[NeMo I 2026-07-01 13:40:22 wer:337] WER reference:chúc bạn đọc có thật nhiều thời gian thư giãn thoải mái
[NeMo I 2026-07-01 13:40:22 wer:338] WER predicted:ch bạn đọc có thật nhiều thời gian thứ d ở th tôiiá
[NeMo I 2026-07-01 13:40:30 wer:336]

[NeMo I 2026-07-01 13:40:30 wer:337] WER reference:bất chấp sự ngăn cản của cơ quan chức năng
[NeMo I 2026-07-01 13:40:30 wer:338] WER predicted:b chấp sự năngạ của cơ quan nước năng
[NeMo I 2026-07-01 13:40:39 wer:336]

[NeMo I 2026-07-01 13:40:39 wer:337] WER reference:chỉ có điều cô ta mang giày chiếc váy len dài bằng lông cừu
[NeMo I 2026-07-01 13:40:39 wer:338] WER predicted:chỉ có điều cuộc ta mang giảiiếc với l lên dài bằng l luônm cứ
[NeMo I 2026-07-01 13:40:48 wer:336]

[NeMo I 2026-07-01 13:40:48 wer:337] WER reference:thánh nhân đãi khù khờ chính là chỗ này
[NeMo I 2026-07-01 13:40:48 wer:338] WER predicted:thành nhân ra kh khu thời chỉ là chủ này
[NeMo I 2026-07-01 13:40:57 wer:336]

[NeMo I 2026-07-01 13:40:57 wer:337] WER reference:cô bé rất lấy làm vui mừng và làm quen với những nốt nhạc đầu tiên bằng chính chiếc đàn đồ chơi ấy
[NeMo I 2026-07-01 13:40:57 wer:338] WER predicted:có bé rất làm vui và làm quan với nhữngạ đầu tiên trên bạn chính ch đang được chơi ấy
[NeMo I 2026-07-01 13:41:06 wer:336]


Validation: |          | 0/? [00:00<?, ?it/s]

[NeMo I 2026-07-01 13:44:14 wer:336]

[NeMo I 2026-07-01 13:44:14 wer:337] WER reference:những con vật này đã bị giết và đốt
[NeMo I 2026-07-01 13:44:14 wer:338] WER predicted:nh con vật này đã bị d vàốc
[NeMo I 2026-07-01 13:44:14 wer:336]

[NeMo I 2026-07-01 13:44:14 wer:337] WER reference:do vậy có máy cũng không thường dùng
[NeMo I 2026-07-01 13:44:14 wer:338] WER predicted:do vậy có mấy cũng không thường dụng
[NeMo I 2026-07-01 13:44:14 wer:336]

[NeMo I 2026-07-01 13:44:14 wer:337] WER reference:đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
[NeMo I 2026-07-01 13:44:14 wer:338] WER predicted:đây sẽ là cuộc gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
[NeMo I 2026-07-01 13:44:14 wer:336]

[NeMo I 2026-07-01 13:44:14 wer:337] WER reference:sau đó một vật lạ bay xợt ngang nóc nhà ông
[NeMo I 2026-07-01 13:44:14 wer:338] WER predicted:sau đó một và là b sự ng năngn nốc nhau
[NeMo I 2026-07-01 13:44:14 wer:336]

[NeMo I 2026-07-01 13:44:14 wer:337] WER reference:hiện ra tận phía xa
[NeMo I 2026-07-01 13:44:14 wer:338] WER predicted:hiện ra tình phía xa
[NeMo I 2026-07-01 13:44:14 wer:336]

[NeMo I 2026-07-01 13:44:14 wer:337] WER reference:nên với thông tin này
[NeMo I 2026-07-01 13:44:14 wer:338] WER predicted:nên với thông tiền này
[NeMo I 2026-07-01 13:44:14 wer:336]

[NeMo I 2026-07-01 13:44:14 wer:337] WER reference:và dân dã như chính cái tên của nó
[NeMo I 2026-07-01 13:44:14 wer:338] WER predicted:và dân gia như chính cái trên của nó
[NeMo I 2026-07-01 13:44:14 wer:336]

[NeMo I 2026-07-01 13:44:14 wer:337] WER reference:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 13:44:14 wer:338] WER predicted:bốn mươi hai bốn mươi ba
[NeMo I 2026-07-01 13:44:14 wer:336]

[NeMo I 2026-07-01 13:44:14 wer:337] WER reference:sau nhiều pha hảm thành liên tục
[NeMo I 2026-07-01 13:44:14 wer:338] WER predicted:sau nhiều phá h thành liên tục
[NeMo I 2026-07-01 13:44:14 wer:336]

[NeMo I 2026-07-01 13:44:14 wer:337] WER reference:anh vẫn nhớ kỷ niệm cầu đầu lâu
[NeMo I 2026-07-01 13:44:14 wer:338] WER predicted:anh v vẫn nhớ kỳiềm cầu đầu lâu
[NeMo I 2026-07-01 13:44:15 wer:336]

[NeMo I 2026-07-01 13:44:15 wer:337] WER reference:gay go lắm nhưng hoàng anh gia lai sẽ làm được
[NeMo I 2026-07-01 13:44:15 wer:338] WER predicted:g g l lắm nhưng hơn anh gia là sẽ làm đ được
[NeMo I 2026-07-01 13:44:15 wer:336]

[NeMo I 2026-07-01 13:44:15 wer:337] WER reference:do đó khi chơi chung với bạn bè cùng lứa chúng thường tỏ ra thiếu tự tin
[NeMo I 2026-07-01 13:44:15 wer:338] WER predicted:do đó khi tr chơi chúng với bạn bé cũng lư chúng ta thường tôi cả thiếu từ tính
[NeMo I 2026-07-01 13:44:15 wer:336]

[NeMo I 2026-07-01 13:44:15 wer:337] WER reference:mối đục luỗng cả tấm gỗ
[NeMo I 2026-07-01 13:44:15 wer:338] WER predicted:mới được luôn cả t tâm g
[NeMo I 2026-07-01 13:44:15 wer:336]

[NeMo I 2026-07-01 13:44:15 wer:337] WER reference:người ta cho rằng trung tâm này có khả năng ảnh hưởng đến quá trình lão hóa
[NeMo I 2026-07-01 13:44:15 wer:338] WER predicted:người ta cho rằng trung tâm này có khá năng anh hướng đến quá trên lao hoa
[NeMo I 2026-07-01 13:44:15 wer:336]

[NeMo I 2026-07-01 13:44:15 wer:337] WER reference:các giò phong lan tháng ba cũng không chịu yên mình
[NeMo I 2026-07-01 13:44:15 wer:338] WER predicted:các cho phẩm lên tha ba cũng công chịu ý mình
[NeMo I 2026-07-01 13:44:15 wer:336]

[NeMo I 2026-07-01 13:44:15 wer:337] WER reference:hãy cho tôi quyền năng vô tận để bảo vệ loài vật
[NeMo I 2026-07-01 13:44:15 wer:338] WER predicted:hay cho tôi viên năng v vô tăng để báo về loi vật
[NeMo I 2026-07-01 13:44:15 wer:336]

[NeMo I 2026-07-01 13:44:15 wer:337] WER reference:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 13:44:15 wer:338] WER predicted:ba mươi tám ba mươi chín
[NeMo I 2026-07-01 13:44:15 wer:336]

[NeMo I 2026-07-01 13:44:15 wer:337] WER reference:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 13:44:15 wer:338] WER predicted:sáu mươi bốn sáu mươi lăm
[NeMo I 2026-07-01 13:44:15 wer:336]

[NeMo I 2026-07-01 13:44:15 wer:337] WER reference:sáng chiều hội diễn tiếng hát bảo minh do công ty bảo hiểm bảo minh tổ chức
[NeMo I 2026-07-01 13:44:15 wer:338] WER predicted:sáng chịu hỏi diễn tiếng khác đầu mình do công ty bảo hiểm báo mình tổ chức
[NeMo I 2026-07-01 13:44:15 wer:336]

[NeMo I 2026-07-01 13:44:15 wer:337] WER reference:cô nằm thiếp đi lúc nào không biết
[NeMo I 2026-07-01 13:44:15 wer:338] WER predicted:cô năm tiếp đi lúc nào không biết
[NeMo I 2026-07-01 13:44:15 wer:336]

[NeMo I 2026-07-01 13:44:15 wer:337] WER reference:mười bảy mười tám mười chín
[NeMo I 2026-07-01 13:44:15 wer:338] WER predicted:mươi bảy mươi tám mươi chín
[NeMo I 2026-07-01 13:44:15 wer:336]

[NeMo I 2026-07-01 13:44:15 wer:337] WER reference:tích cóp đủ thứ đồ lạc xon những ngọn đèn
[NeMo I 2026-07-01 13:44:15 wer:338] WER predicted:tiếpốc đưa thứ đồ đ đã số những ngọ đang
[NeMo I 2026-07-01 13:44:15 wer:336]

[NeMo I 2026-07-01 13:44:15 wer:337] WER reference:nhưng đất nước đã chọn một nhà lãnh đạo khác
[NeMo I 2026-07-01 13:44:15 wer:338] WER predicted:nhưng nước nước đã chọn một nhà lên đầu khác
[NeMo I 2026-07-01 13:44:15 wer:336]

[NeMo I 2026-07-01 13:44:15 wer:337] WER reference:ưu thế này có được là nhờ quá trình cơ giới hóa nhanh sử dụng phân bón cho dù hậu quả có là
[NeMo I 2026-07-01 13:44:15 wer:338] WER predicted:uống thế này có được là nhớ quá trình cơ giới hoa nhanh sự dụng phần bốn cho dụnghầu quả có làm
[NeMo I 2026-07-01 13:44:15 wer:336]

[NeMo I 2026-07-01 13:44:15 wer:337] WER reference:thường xuyên xảy ra hiện tượng đạo văn quỵt nhuận bút
[NeMo I 2026-07-01 13:44:15 wer:338] WER predicted:thường xuyên x ra hiện thường đào văn quyết nhút
[NeMo I 2026-07-01 13:44:16 wer:336]

[NeMo I 2026-07-01 13:44:16 wer:337] WER reference:chỉ cho chúng tôi xem hàng đống gạch đá cát sỏi
[NeMo I 2026-07-01 13:44:16 wer:338] WER predicted:chỉ cho chúng tôi xem hàng đồng cả đã các số
[NeMo I 2026-07-01 13:44:16 wer:336]

[NeMo I 2026-07-01 13:44:16 wer:337] WER reference:đối với cảng hàng không quốc tế đà nẵng sử dụng nhà ga hành khách hiện hữu làm nhà ga nội địa
[NeMo I 2026-07-01 13:44:16 wer:338] WER predicted:đối với càng hàng không quốc tế đã năng sự dụng nhà gia hành khách hiện hồ làm nhà g nói để
[NeMo I 2026-07-01 13:44:16 wer:336]

[NeMo I 2026-07-01 13:44:16 wer:337] WER reference:người giàu thì vác nặng những xâu tiền kẽm trên vai
[NeMo I 2026-07-01 13:44:16 wer:338] WER predicted:ngườiào thì vật nạ những sau tiềnk trên phải
[NeMo I 2026-07-01 13:44:16 wer:336]

[NeMo I 2026-07-01 13:44:16 wer:337] WER reference:các nữ công nhân làm ca đêm
[NeMo I 2026-07-01 13:44:16 wer:338] WER predicted:các nữ công nhân làm cá điểm
[NeMo I 2026-07-01 13:44:16 wer:336]

[NeMo I 2026-07-01 13:44:16 wer:337] WER reference:tui biết bà giỏi rồi
[NeMo I 2026-07-01 13:44:16 wer:338] WER predicted:tôi biết bà di rồi
[NeMo I 2026-07-01 13:44:16 wer:336]

[NeMo I 2026-07-01 13:44:16 wer:337] WER reference:đưa một chú bồ câu bay đi bay về
[NeMo I 2026-07-01 13:44:16 wer:338] WER predicted:đường một chú bộ cầu bảy đi bị v về
[NeMo I 2026-07-01 13:44:16 wer:336]

[NeMo I 2026-07-01 13:44:16 wer:337] WER reference:tôi đến kiểm tra và phát hiện thấy ông và cô gái nằm kia thám tử ra hiệu cho ngài triệu phú nhìn vào phòng tắm cô ta đã chết
[NeMo I 2026-07-01 13:44:16 wer:338] WER predicted:tôi đến kiểm ra và phát hiện thấy ông và cô gái nămk tha từ ra hiểu cho ngày chịu phương nhìn vào phòng tâm cô đã chết
[NeMo I 2026-07-01 13:44:16 wer:336]

[NeMo I 2026-07-01 13:44:16 wer:337] WER reference:để thực hiện thắng lợi kế hoạch năm năm
[NeMo I 2026-07-01 13:44:16 wer:338] WER predicted:để thực hiện thân lại cái hết năm năm
[NeMo I 2026-07-01 13:44:16 wer:336]

[NeMo I 2026-07-01 13:44:16 wer:337] WER reference:trước khi hóa thân thành cộng hòa sét để đến bồ đào nha
[NeMo I 2026-07-01 13:44:16 wer:338] WER predicted:trước khi hoa thân thành còn hoa sức để đến bộ đồng nhà
[NeMo I 2026-07-01 13:44:16 wer:336]

[NeMo I 2026-07-01 13:44:16 wer:337] WER reference:tuy nhiên tôi không chắc những người chưa từng đọc cuốn nhật ký có thể hiểu hết được ý nghĩa bộ phim
[NeMo I 2026-07-01 13:44:16 wer:338] WER predicted:tuy nhiên tôi không chắc những người chưa từ đọc cũng nhất kỳ có thể hiểu hết được ý nghĩ bộ phim
[NeMo I 2026-07-01 13:44:16 wer:336]

[NeMo I 2026-07-01 13:44:16 wer:337] WER reference:chi đầu tư từ khu vực nhà nước còn lớn và hiệu quả thấp
[NeMo I 2026-07-01 13:44:16 wer:338] WER predicted:chỉ đầu tư từ khu vực nhà n nước còn lớn và hiệu quả th hợp
[NeMo I 2026-07-01 13:44:16 wer:336]

[NeMo I 2026-07-01 13:44:16 wer:337] WER reference:cái nền xưa của nó bây giờ là một cái hố nông choèn
[NeMo I 2026-07-01 13:44:16 wer:338] WER predicted:cái nên s của nó bị giờ là một cái hồ n năm tr
[NeMo I 2026-07-01 13:44:16 wer:336]

[NeMo I 2026-07-01 13:44:16 wer:337] WER reference:giải truyền thông điện ảnh trung quốc là giải thưởng điện ảnh duy nhất xét trao cho tất cả các bộ phim hoa ngữ
[NeMo I 2026-07-01 13:44:16 wer:338] WER predicted:giải trên thường đến anh chúng quốc là dài thường đến anh gì sẽ cho cho tất cả các bộ hiện hoànư
[NeMo I 2026-07-01 13:44:16 wer:336]

[NeMo I 2026-07-01 13:44:16 wer:337] WER reference:dự đoán ba tháng nữa giá cà phê sẽ tăng gấp đôi hiện nay
[NeMo I 2026-07-01 13:44:16 wer:338] WER predicted:điều rằng ba tháng nữa giá và về sự tăng gặp đôi hiện này
[NeMo I 2026-07-01 13:44:16 wer:336]

[NeMo I 2026-07-01 13:44:16 wer:337] WER reference:họ đến đây vì nhiều mục đích
[NeMo I 2026-07-01 13:44:16 wer:338] WER predicted:họ đến đâyì nhiều một đích
[NeMo I 2026-07-01 13:44:17 wer:336]

[NeMo I 2026-07-01 13:44:17 wer:337] WER reference:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 13:44:17 wer:338] WER predicted:tám mươi bốn tám mươi lăm
[NeMo I 2026-07-01 13:44:17 wer:336]

[NeMo I 2026-07-01 13:44:17 wer:337] WER reference:vậy trước đây nông dân đối phó với hiện tượng này như thế nào thưa ông
[NeMo I 2026-07-01 13:44:17 wer:338] WER predicted:vậy trước đây n năm nhân đối phố v với hiện từ này như đến nào thu  ông
[NeMo I 2026-07-01 13:44:17 wer:336]

[NeMo I 2026-07-01 13:44:17 wer:337] WER reference:làm sao để có tiền nhanh nhất
[NeMo I 2026-07-01 13:44:17 wer:338] WER predicted:làm sao để có tiền nhân nhất
[NeMo I 2026-07-01 13:44:17 wer:336]

[NeMo I 2026-07-01 13:44:17 wer:337] WER reference:đùi dang ra ngoài
[NeMo I 2026-07-01 13:44:17 wer:338] WER predicted:được gian ra ngoài
[NeMo I 2026-07-01 13:44:17 wer:336]

[NeMo I 2026-07-01 13:44:17 wer:337] WER reference:đã hai lần cô gác lại ước mơ vào đời và cũng đã ít nhiều trải qua những thăng trầm xô bồ của cuộc sống
[NeMo I 2026-07-01 13:44:17 wer:338] WER predicted:đã hai l lần cô gái lạiút mới vào đời và cũng đã ít nhiều trái qua những tha tr số bộ của cuộc sống
[NeMo I 2026-07-01 13:44:17 wer:336]

[NeMo I 2026-07-01 13:44:17 wer:337] WER reference:trong bối cảnh như vậy một phản ứng chính sách đối với vấn đề thất nghiệp đang là đòi hỏi cấp bách hiện nay
[NeMo I 2026-07-01 13:44:17 wer:338] WER predicted:trong bộ cảnh như vậy một phầnững chính sách đối với vấn để nghiệpp đang là đời họ cách cách hiện này
[NeMo I 2026-07-01 13:44:17 wer:336]

[NeMo I 2026-07-01 13:44:17 wer:337] WER reference:ở xứ sở chuột túi
[NeMo I 2026-07-01 13:44:17 wer:338] WER predicted:ở s sơ tr chủ tôi
[NeMo I 2026-07-01 13:44:17 wer:336]

[NeMo I 2026-07-01 13:44:17 wer:337] WER reference:do vậy dựa trên cơ sở nào mà ông khoa phát biểu như vậy
[NeMo I 2026-07-01 13:44:17 wer:338] WER predicted:do vậy dự trên cơ s nào ông khoa phát biểu như vậy
[NeMo I 2026-07-01 13:44:17 wer:336]

[NeMo I 2026-07-01 13:44:17 wer:337] WER reference:tá tàng
[NeMo I 2026-07-01 13:44:17 wer:338] WER predicted:ta tăng
[NeMo I 2026-07-01 13:44:17 wer:336]

[NeMo I 2026-07-01 13:44:17 wer:337] WER reference:cách đây tám năm nhưng trước đó khoảng hai năm đã được mời đóng phim và có nhiều vai chính trong các phim điện ảnh truyền hình
[NeMo I 2026-07-01 13:44:17 wer:338] WER predicted:cách đây tâm năm nh trước đó kho hai năm đã được mới động phim và có nhiều và chính trong các phim điện anh truyền hình
[NeMo I 2026-07-01 13:44:17 wer:336]

[NeMo I 2026-07-01 13:44:17 wer:337] WER reference:đã thăm hỏi thì thế nào cũng phải có quà cáp
[NeMo I 2026-07-01 13:44:17 wer:338] WER predicted:đã tâmm họ thì thế nào cũng phải có quả các
[NeMo I 2026-07-01 13:44:17 wer:336]

[NeMo I 2026-07-01 13:44:17 wer:337] WER reference:có mặt tại xã điện phong
[NeMo I 2026-07-01 13:44:17 wer:338] WER predicted:có mặt tạià điện phòng
[NeMo I 2026-07-01 13:44:17 wer:336]

[NeMo I 2026-07-01 13:44:17 wer:337] WER reference:em lơ đễnh lật xem vài tờ báo
[NeMo I 2026-07-01 13:44:17 wer:338] WER predicted:em là điện l xem vàờ báo
[NeMo I 2026-07-01 13:44:17 wer:336]

[NeMo I 2026-07-01 13:44:17 wer:337] WER reference:và không ít người cứ tì tì uống từ sáng đến tối suốt mấy ngày hội nghị
[NeMo I 2026-07-01 13:44:17 wer:338] WER predicted:và không ít người cứ ty từ  uống từ sáng đến tôi xuất máy ngày hội này
[NeMo I 2026-07-01 13:44:17 wer:336]

[NeMo I 2026-07-01 13:44:17 wer:337] WER reference:minh châu vào miền nam công tác tại nhà hát trần hữu trang
[NeMo I 2026-07-01 13:44:17 wer:338] WER predicted:mình cao vào m nam công tất tại nhà ho rằng h rằng
[NeMo I 2026-07-01 13:44:18 wer:336]

[NeMo I 2026-07-01 13:44:18 wer:337] WER reference:hết chiến tranh quê hương im tiếng súng anh lính cụ hồ lại trở về với đời thường tham gia sản xuất xây dựng và bảo vệ đất nước
[NeMo I 2026-07-01 13:44:18 wer:338] WER predicted:hết tiếng trên với hơn ý tiếng xuống anh lên của hồ lại cho về với đời thường tham giá sản xuất sẽ d vào b với đất nước
[NeMo I 2026-07-01 13:44:18 wer:336]

[NeMo I 2026-07-01 13:44:18 wer:337] WER reference:chuyến đi đó đến giờ vẫn là một ám ảnh trong ký ức tôi
[NeMo I 2026-07-01 13:44:18 wer:338] WER predicted:chỉ đi đó đến giờ vẫn là một ông anh trong kỳ
[NeMo I 2026-07-01 13:44:18 wer:336]

[NeMo I 2026-07-01 13:44:18 wer:337] WER reference:ây da ây da
[NeMo I 2026-07-01 13:44:18 wer:338] WER predicted:giá gia
[NeMo I 2026-07-01 13:44:18 wer:336]

[NeMo I 2026-07-01 13:44:18 wer:337] WER reference:có rất nhiều vệ tinh bị rơi khỏi quỹ đạo
[NeMo I 2026-07-01 13:44:18 wer:338] WER predicted:rất nhiều về tính bị rồi khó qu nào
[NeMo I 2026-07-01 13:44:18 wer:336]

[NeMo I 2026-07-01 13:44:18 wer:337] WER reference:nhuốm đầy máu của thổ dân châu mỹ
[NeMo I 2026-07-01 13:44:18 wer:338] WER predicted:nhóm đây m máu của thủ dân cho mỹ
[NeMo I 2026-07-01 13:44:18 wer:336]

[NeMo I 2026-07-01 13:44:18 wer:337] WER reference:cụ thể về đất đai xây dựng văn hóa thuộc về từng ngành riêng biệt
[NeMo I 2026-07-01 13:44:18 wer:338] WER predicted:cô thể về đ đất đây văn sẽ những văn hoa thuốc về từ ngành riêng biết
[NeMo I 2026-07-01 13:44:18 wer:336]

[NeMo I 2026-07-01 13:44:18 wer:337] WER reference:tôi muốn hỏi liệu có mùi hương sen nhân tạo là một loại hóa chất không
[NeMo I 2026-07-01 13:44:18 wer:338] WER predicted:tôi muốn hỏi liệu có mười hướng s nhân tạo là một loại họ chắc cao
[NeMo I 2026-07-01 13:44:18 wer:336]

[NeMo I 2026-07-01 13:44:18 wer:337] WER reference:cả nhà bà ngoại cười nắc nẻ vì câu nói ngây ngô của con
[NeMo I 2026-07-01 13:44:18 wer:338] WER predicted:các nhà bao ngoài người nhất ngheì cô nói ngày ngủ của con
[NeMo I 2026-07-01 13:44:18 wer:336]

[NeMo I 2026-07-01 13:44:18 wer:337] WER reference:xin được chân khuân vác
[NeMo I 2026-07-01 13:44:18 wer:338] WER predicted:xin được trên khu phát
[NeMo I 2026-07-01 13:44:18 wer:336]

[NeMo I 2026-07-01 13:44:18 wer:337] WER reference:nằm khuất dưới tàn tre sát bờ sông châu
[NeMo I 2026-07-01 13:44:18 wer:338] WER predicted:ho giới đàn trẻ sẽờ s sống ch
[NeMo I 2026-07-01 13:44:18 wer:336]

[NeMo I 2026-07-01 13:44:18 wer:337] WER reference:nếu kiên cố hóa thì vốn được đưa thẳng cho dân sẽ không thất thoát
[NeMo I 2026-07-01 13:44:18 wer:338] WER predicted:nếu ki cô hoa thì bốn được đưa tăng cho dân sẽ không thật
[NeMo I 2026-07-01 13:44:18 wer:336]

[NeMo I 2026-07-01 13:44:18 wer:337] WER reference:nói chung cô hồng nào cũng có một số phận hoàn cảnh và cuộc đời riêng
[NeMo I 2026-07-01 13:44:18 wer:338] WER predicted:nói chúng cô học nào cũng có một số phần hoàn cảnhnh với cuộc đời riêng
[NeMo I 2026-07-01 13:44:18 wer:336]

[NeMo I 2026-07-01 13:44:18 wer:337] WER reference:nhưng tất cả những điều ấy chẳng mấy khi đi liền với nhau
[NeMo I 2026-07-01 13:44:18 wer:338] WER predicted:những tất cả những điều ấy ch mấy khi đi liên với nhau
[NeMo I 2026-07-01 13:44:18 wer:336]

[NeMo I 2026-07-01 13:44:18 wer:337] WER reference:như vậy là bạn có thể sử dụng được nhiều số điện thoại của nhiều nhà cung cấp dịch vụ chỉ trên một sim
[NeMo I 2026-07-01 13:44:18 wer:338] WER predicted:như vậy bạn có thể sự dụng được nhiều số đến th của như nhà cũng cấp dịch vụ chỉ trên một xem
[NeMo I 2026-07-01 13:44:19 wer:336]

[NeMo I 2026-07-01 13:44:19 wer:337] WER reference:trong trường hợp hai bên có thỏa thuận lại không yêu cầu trọng tài giải quyết nữa thì có quyền kiện ra tòa án
[NeMo I 2026-07-01 13:44:19 wer:338] WER predicted:trong trường hợp hai bên có th thường lại không yêu cầu trong ta d quyết nữa thì có quyền kiến ra toàn ăn
[NeMo I 2026-07-01 13:44:19 wer:336]

[NeMo I 2026-07-01 13:44:19 wer:337] WER reference:kiểu này chắc phải cắt giảm biên chế
[NeMo I 2026-07-01 13:44:19 wer:338] WER predicted:kiể này chắc phải các giảm biến chế
[NeMo I 2026-07-01 13:44:19 wer:336]

[NeMo I 2026-07-01 13:44:19 wer:337] WER reference:nhưng tôi không yêu cô cô biết rõ điều đó mà
[NeMo I 2026-07-01 13:44:19 wer:338] WER predicted:nhưng tôi không yêu cô cô biết rồi điều đó mà
[NeMo I 2026-07-01 13:44:19 wer:336]

[NeMo I 2026-07-01 13:44:19 wer:337] WER reference:khó mà đoán trước chính xác kết quả khi quả bóng còn lăn
[NeMo I 2026-07-01 13:44:19 wer:338] WER predicted:khó mà đó trước chính sẽích quả khi qua b bóng con
[NeMo I 2026-07-01 13:44:19 wer:336]

[NeMo I 2026-07-01 13:44:19 wer:337] WER reference:vừa nhìn thấy sự xuất hiện của bố tất cả mấy thằng khác vùng bỏ chạy sạch
[NeMo I 2026-07-01 13:44:19 wer:338] WER predicted:ừa nh thấy sự sự hiện của bố tất cả máy th thành khác vùng bỏi trẻ sách
[NeMo I 2026-07-01 13:44:19 wer:336]

[NeMo I 2026-07-01 13:44:19 wer:337] WER reference:phải nâng cao khả năng cạnh tranh của nền kinh tế
[NeMo I 2026-07-01 13:44:19 wer:338] WER predicted:phải năng cao kh năng cảnh trên của nên kinh tên
[NeMo I 2026-07-01 13:44:19 wer:336]

[NeMo I 2026-07-01 13:44:19 wer:337] WER reference:bà thường lấy ý tưởng cho các tác phẩm từ đâu
[NeMo I 2026-07-01 13:44:19 wer:338] WER predicted:bà thườngấy ý từ cho các tác phẩm từ đồng
[NeMo I 2026-07-01 13:44:19 wer:336]

[NeMo I 2026-07-01 13:44:19 wer:337] WER reference:khi chứng kiến người vợ lăng loàn
[NeMo I 2026-07-01 13:44:19 wer:338] WER predicted:khi chứng kiến người vào l lần lòng
[NeMo I 2026-07-01 13:44:19 wer:336]

[NeMo I 2026-07-01 13:44:19 wer:337] WER reference:tác phẩm to lớn bằng đồng như tượng phật quỳnh lâm chuông quy điền tháp báo thiên vạc phổ minh an nam tứ đại khí
[NeMo I 2026-07-01 13:44:19 wer:338] WER predicted:ta phẩm ta lớn bạn đồng như tượng phát quyền lắm chúng qu điện th bảo tìm và phố mình ăn nam tư đây khi
[NeMo I 2026-07-01 13:44:19 wer:336]

[NeMo I 2026-07-01 13:44:19 wer:337] WER reference:ngoài ra họ vẫn còn muốn giữ chân cầu thủ xuất sắc nhất của mình
[NeMo I 2026-07-01 13:44:19 wer:338] WER predicted:họ vẫn cầu muốnư chân cầu thủ xuất s
[NeMo I 2026-07-01 13:44:19 wer:336]

[NeMo I 2026-07-01 13:44:19 wer:337] WER reference:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 13:44:19 wer:338] WER predicted:hai mươi hai hai mươi ba
[NeMo I 2026-07-01 13:44:19 wer:336]

[NeMo I 2026-07-01 13:44:19 wer:337] WER reference:và gã thệ bị điều về làm trưởng phòng xã hội huyện
[NeMo I 2026-07-01 13:44:19 wer:338] WER predicted:và cả thể biết điều về làm trường phần xã hộii h
[NeMo I 2026-07-01 13:44:19 wer:336]

[NeMo I 2026-07-01 13:44:19 wer:337] WER reference:là rút rỉa tiền của bạn càng nhiều càng tốt

[NeMo W 2026-07-01 13:44:35 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:44:35 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

[best val_wer] epoch=12 val_wer=0.438433 exported=/kaggle/working/phase3_continue_best.nemo

Sample predictions after epoch 12:
  [0] REF: những con vật này đã bị giết và đốt
      HYP: nh con vật này đã bị d vàốc
  [1] REF: phòng chống tham nhũng không được chủ quan cần làm liên tục đồng bộ và có các giải pháp
      HYP: phòng trong tham nh dụng không được chủ quan cần làm liên tục động bộ và có các đại pháp
  [2] REF: do vậy có máy cũng không thường dùng
      HYP: do vậy có mấy cũng không thường dụng
  [3] REF: mới khệnh khạng đứng lên đi ra
      HYP: mới kh khá đứng lên đi ra
  [4] REF: đây sẽ là cuộc gặp gỡ cấp cao nhất giữa hai phía trong vòng bốn năm nay
      HYP: đây sẽ là cuộc g gặp g c cấp cao nhất dự hai phía trong vẫn bộ n năm này
  [5] REF: sau một năm eo sèo
      HYP: sáu một năm yêu xe
  [6] REF: sau đó một vật lạ bay xợt ngang nóc nhà ông
      HYP: sau đó một và là b sự ng năngn nốc nhau
  [7] REF: chín mươi hai chín mươi ba
      HYP: chín mươi hai chín mươi ba
  [8] REF: hiện ra tận phía xa
      HYP: hiện ra tình phía xa
  [9] REF: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã qua của thị trường
      HYP: những gì chúng ta đã làm chỉ thích hợp với những thời điểm đã quá của thì trường
[epoch] epoch=12/12 step=3768 val_loss=2.088430404663086 val_wer=0.43843308091163635

`Trainer.fit` stopped: `max_epochs=12` reached.

Evaluating phase3_continue_from_epoch11 on val: /kaggle/working/phase3_continue_best.nemo
[NeMo I 2026-07-01 13:44:57 mixins:184] Tokenizer SentencePieceTokenizer initialized with 1024 tokens

[NeMo W 2026-07-01 13:44:57 modelPT:188] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config :
    manifest_filepath: /kaggle/working/vivos_manifest_phase_best/train_manifest.json
    sample_rate: 16000
    batch_size: 2
    shuffle: true
    num_workers: 2
    pin_memory: true
    min_duration: 0.1
    is_tarred: false
    tarred_audio_filepaths: null
    max_duration: 8.0

[NeMo W 2026-07-01 13:44:57 modelPT:195] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
    Validation config :
    manifest_filepath: /kaggle/working/vivos_manifest_phase_best/val_manifest.json
    sample_rate: 16000
    batch_size: 2
    shuffle: false
    num_workers: 2
    pin_memory: true
    min_duration: 0.1
    is_tarred: false
    tarred_audio_filepaths: null

[NeMo W 2026-07-01 13:44:57 modelPT:202] Please call the ModelPT.setup_test_data() or ModelPT.setup_multiple_test_data() method and provide a valid configuration file to setup the test data loader(s).
    Test config :
    manifest_filepath: null
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    num_workers: 8
    pin_memory: true
    use_start_end_token: false

[NeMo I 2026-07-01 13:44:59 save_restore_connector:285] Model EncDecCTCModelBPE was successfully restored from /kaggle/working/phase3_continue_best.nemo.

[NeMo W 2026-07-01 13:44:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:44:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:44:59 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:44:59 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:00 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:00 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:01 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:01 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:02 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:02 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:03 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:03 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:04 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:04 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

{'phase': 'phase3_continue_from_epoch11', 'split': 'val', 'model_path': '/kaggle/working/phase3_continue_best.nemo', 'samples': 583, 'wer': 0.4375398749521501, 'cer': 0.20160976631459263, 'empty_pred_rate': 0.0, 'ref_word_count': 7837, 'pred_word_count': 7749, 'inference_seconds': 10.591688839998824, 'pred_ref_word_ratio': 0.9887712134745438}
Evaluating phase3_continue_from_epoch11 on test: /kaggle/working/phase3_continue_best.nemo
[NeMo I 2026-07-01 13:45:11 mixins:184] Tokenizer SentencePieceTokenizer initialized with 1024 tokens

[NeMo W 2026-07-01 13:45:11 modelPT:188] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config :
    manifest_filepath: /kaggle/working/vivos_manifest_phase_best/train_manifest.json
    sample_rate: 16000
    batch_size: 2
    shuffle: true
    num_workers: 2
    pin_memory: true
    min_duration: 0.1
    is_tarred: false
    tarred_audio_filepaths: null
    max_duration: 8.0

[NeMo W 2026-07-01 13:45:11 modelPT:195] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
    Validation config :
    manifest_filepath: /kaggle/working/vivos_manifest_phase_best/val_manifest.json
    sample_rate: 16000
    batch_size: 2
    shuffle: false
    num_workers: 2
    pin_memory: true
    min_duration: 0.1
    is_tarred: false
    tarred_audio_filepaths: null

[NeMo W 2026-07-01 13:45:11 modelPT:202] Please call the ModelPT.setup_test_data() or ModelPT.setup_multiple_test_data() method and provide a valid configuration file to setup the test data loader(s).
    Test config :
    manifest_filepath: null
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    num_workers: 8
    pin_memory: true
    use_start_end_token: false

[NeMo I 2026-07-01 13:45:13 save_restore_connector:285] Model EncDecCTCModelBPE was successfully restored from /kaggle/working/phase3_continue_best.nemo.

[NeMo W 2026-07-01 13:45:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:13 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:13 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:14 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:14 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:15 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:15 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:45:16 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)
[NeMo W 2026-07-01 13:45:16 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token

{'phase': 'phase3_continue_from_epoch11', 'split': 'test', 'model_path': '/kaggle/working/phase3_continue_best.nemo', 'samples': 760, 'wer': 0.4783734783734784, 'cer': 0.22471087241768636, 'empty_pred_rate': 0.0, 'ref_word_count': 7722, 'pred_word_count': 7723, 'inference_seconds': 9.637337202999333, 'pred_ref_word_ratio': 1.0001295001295}

{'name': 'phase3_continue_from_epoch11',
 'output_nemo': PosixPath('/kaggle/working/phase3_continue_best.nemo'),
 'init_nemo': PosixPath('/kaggle/input/models/trnmnhtn/finetune-fastconformer/other/default/1/phase3_best_full_finetune.nemo'),
 'trainable_mode': 'full_encoder_decoder',
 'max_epochs': 12,
 'lr': 2e-05,
 'batch_size': 2,
 'accumulate_grad_batches': 16,
 'unfrozen_encoder_blocks': 'all',
 'max_duration': 8.0,
 'encoder_block_path': 'encoder',
 'encoder_trainable_params': 115074560,
 'decoder_trainable_params': 525825,
 'total_trainable_params': 115600385,
 'total_params': 115600385,
 'trainable_fraction': 1.0,
 'best_val_wer': 0.43843308091163635,
 'best_epoch': 11,
 'best_nemo_path': '/kaggle/working/phase3_continue_best.nemo',
 'best_checkpoint_path': '/kaggle/working/nemo_experiments/fastconformer_vi/phase3_continue_from_epoch11/checkpoints/best-11-0.4381.ckpt',
 'last_checkpoint_path': '/kaggle/working/nemo_experiments/fastconformer_vi/phase3_continue_from_epoch11/checkpoints/last.ckpt',
 'elapsed_minutes': 181.64332000925,
 'steps_per_epoch': 314,
 'estimated_total_steps': 3768,
 'precision': '16-mixed',
 'warmup_steps': 500,
 'weight_decay': 0.001}

In [33]:
import pandas as pd
from jiwer import wer, cer

rows = []

model_path = "/kaggle/working/phase3_continue_best.nemo"
model = nemo_asr.models.ASRModel.restore_from(model_path)
model.eval()

audio_paths, refs = read_manifest_for_eval(TEST_MANIFEST)
hyps = model.transcribe(audio_paths, batch_size=8, verbose=False)

for audio, ref, hyp in zip(audio_paths, refs, hyps):
    ref_n = normalize_for_metric(ref)
    hyp_n = normalize_for_metric(hyp)
    rows.append({
        "audio": audio,
        "ref": ref_n,
        "hyp": hyp_n,
        "wer": wer(ref_n, hyp_n),
        "cer": cer(ref_n, hyp_n),
        "ref_len_words": len(ref_n.split()),
        "hyp_len_words": len(hyp_n.split()),
        "ref_len_chars": len(ref_n),
        "hyp_len_chars": len(hyp_n),
    })

df = pd.DataFrame(rows)
df.to_csv("/kaggle/working/error_analysis_test.csv", index=False, encoding="utf-8-sig")
df.head()

[NeMo I 2026-07-01 13:51:06 mixins:184] Tokenizer SentencePieceTokenizer initialized with 1024 tokens

[NeMo W 2026-07-01 13:51:06 modelPT:188] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config :
    manifest_filepath: /kaggle/working/vivos_manifest_phase_best/train_manifest.json
    sample_rate: 16000
    batch_size: 2
    shuffle: true
    num_workers: 2
    pin_memory: true
    min_duration: 0.1
    is_tarred: false
    tarred_audio_filepaths: null
    max_duration: 8.0

[NeMo W 2026-07-01 13:51:06 modelPT:195] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s).
    Validation config :
    manifest_filepath: /kaggle/working/vivos_manifest_phase_best/val_manifest.json
    sample_rate: 16000
    batch_size: 2
    shuffle: false
    num_workers: 2
    pin_memory: true
    min_duration: 0.1
    is_tarred: false
    tarred_audio_filepaths: null

[NeMo W 2026-07-01 13:51:06 modelPT:202] Please call the ModelPT.setup_test_data() or ModelPT.setup_multiple_test_data() method and provide a valid configuration file to setup the test data loader(s).
    Test config :
    manifest_filepath: null
    sample_rate: 16000
    batch_size: 16
    shuffle: false
    num_workers: 8
    pin_memory: true
    use_start_end_token: false

[NeMo I 2026-07-01 13:51:08 save_restore_connector:285] Model EncDecCTCModelBPE was successfully restored from /kaggle/working/phase3_continue_best.nemo.

[NeMo W 2026-07-01 13:51:08 dataloader:826] The following configuration keys are ignored by Lhotse dataloader: use_start_end_token
[NeMo W 2026-07-01 13:51:08 dataloader:523] You are using a non-tarred dataset and requested tokenization during data sampling (pretokenize=True). This will cause the tokenization to happen in the main (GPU) process,possibly impacting the training speed if your tokenizer is very large.If the impact is noticable, set pretokenize=False in dataloader config.(note: that will disable token-per-second filtering and 2D bucketing features)

,audio,ref,hyp,wer,cer,ref_len_words,hyp_len_words,ref_len_chars,hyp_len_chars
0,/kaggle/working/vivos/data/extracted/vivos/tes...,trở nên thụ động,hypothesis score tensor 3 5975 y sequence tens...,23.500000,31.187500,4,95,16,512
1,/kaggle/working/vivos/data/extracted/vivos/tes...,cũng khiến cho họ dè dặt,hypothesis score tensor 6 0061 y sequence tens...,15.500000,20.333333,6,96,24,506
2,/kaggle/working/vivos/data/extracted/vivos/tes...,chị gặn hỏi anh thề sống thề chết là không có,hypothesis score tensor 7 0633 y sequence tens...,10.545455,13.222222,11,123,45,634
3,/kaggle/working/vivos/data/extracted/vivos/tes...,điện thoại reng nhưng ta cũng phải nhấc máy đú...,hypothesis score tensor 9 8388 y sequence tens...,10.181818,10.592593,11,118,54,614
4,/kaggle/working/vivos/data/extracted/vivos/tes...,cũng thuộc loại dày đặc nhất trong hệ mặt trời,hypothesis score tensor 10 2570 y sequence ten...,11.000000,12.217391,10,115,46,595

In [35]:
df.sort_values("wer", ascending=False).head(30)[
    ["wer", "cer", "ref_len_words", "hyp_len_words", "ref", "hyp", "audio"]
]

,wer,cer,ref_len_words,hyp_len_words,ref,hyp,audio
167,43.500000,58.500000,2,87,trán giô,hypothesis score tensor 5 5906 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
222,40.000000,48.444444,2,81,làm khung,hypothesis score tensor 1 0211 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
58,39.000000,70.833333,2,78,ôi dào,hypothesis score tensor 1 8092 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
120,38.500000,70.666667,2,78,bà nói,hypothesis score tensor 1 2710 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
445,32.666667,51.900000,3,98,tại chợ cá,hypothesis score tensor 2 5723 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
141,30.333333,39.916667,3,91,rạch bàu mớp,hypothesis score tensor 5 8160 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
315,29.333333,43.909091,3,91,quá tốt rồi,hypothesis score tensor 1 8762 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
139,28.666667,51.222222,3,87,vì tối đó,hypothesis score tensor 1 9623 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
428,28.666667,39.250000,3,89,năm đầu tiên,hypothesis score tensor 1 8397 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
100,27.666667,38.000000,3,86,người ta nói,hypothesis score tensor 0 9303 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
55,26.333333,36.166667,3,81,sau cải cách,hypothesis score tensor 2 4705 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
252,26.000000,27.050000,4,105,trận chiến xích bích,hypothesis score tensor 7 6161 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
378,26.000000,28.200000,3,79,cao ngồng ngồng,hypothesis score tensor 4 2841 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
376,25.666667,42.300000,3,78,cái khó là,hypothesis score tensor 2 9727 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
44,25.666667,30.071429,3,79,không hiểu sao,hypothesis score tensor 1 7992 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
423,23.750000,30.750000,4,95,ngụ ấp hòn ngang,hypothesis score tensor 8 0874 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
0,23.500000,31.187500,4,95,trở nên thụ động,hypothesis score tensor 3 5975 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
475,23.200000,32.473684,5,121,một ba năm bảy chín,hypothesis score tensor 0 8248 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
104,22.750000,33.066667,4,95,và rất sáng tạo,hypothesis score tensor 4 2286 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
463,22.500000,28.000000,4,91,áo rách lươm bươm,hypothesis score tensor 5 1924 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
197,22.250000,29.312500,4,91,chưa rục rịch gì,hypothesis score tensor 8 5821 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
260,21.750000,26.882353,4,88,rô bót thông minh,hypothesis score tensor 3 9487 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
461,21.500000,28.875000,4,88,trả lời tôi biết,hypothesis score tensor 4 1862 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
407,21.500000,28.875000,4,88,nếu vì chúng tôi,hypothesis score tensor 2 1989 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
162,21.500000,30.400000,4,88,ông nhặt nó lên,hypothesis score tensor 3 1083 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
416,21.000000,23.526316,4,85,không phải nắp khum,hypothesis score tensor 2 7717 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
332,21.000000,25.166667,4,86,nước chảy quá mạnh,hypothesis score tensor 3 3068 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
115,20.750000,25.277778,4,87,cũng chưa biết nữa,hypothesis score tensor 1 8103 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
267,20.750000,22.400000,4,86,nhiều người cho biết,hypothesis score tensor 1 0095 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...
54,20.750000,25.764706,4,83,nhưng oái ăm thay,hypothesis score tensor 3 5440 y sequence tens...,/kaggle/working/vivos/data/extracted/vivos/tes...

In [36]:
df["len_bucket"] = pd.cut(
    df["ref_len_words"],
    bins=[0, 3, 6, 10, 15, 25, 100],
    labels=["1-3", "4-6", "7-10", "11-15", "16-25", "25+"]
)

df.groupby("len_bucket")[["wer", "cer"]].mean()

                  wer        cer
len_bucket
1-3         31.571429  46.384323
4-6         17.225969  22.152369
7-10        12.112919  14.929639
11-15        9.195368  10.919638
16-25        7.900463   9.670945
25+               NaN        NaN

In [37]:
df["word_len_ratio"] = df["hyp_len_words"] / df["ref_len_words"].clip(lower=1)

df[["word_len_ratio", "wer", "cer"]].describe()

       word_len_ratio         wer         cer
count      760.000000  760.000000  760.000000
mean        12.273153   11.733312   14.529878
std          4.319054    4.321519    6.618598
min          7.714286    7.142857    7.469697
25%          9.615385    9.076923   10.613636
50%         10.727273   10.230769   12.364525
75%         13.647321   13.129464   16.359524
max         43.500000   43.500000   70.833333

In [38]:
df[df["word_len_ratio"] < 0.7].sort_values("wer", ascending=False).head(20)[
    ["word_len_ratio", "wer", "ref", "hyp"]
]

Empty DataFrame
Columns: [word_len_ratio, wer, ref, hyp]
Index: []

In [39]:
df[df["word_len_ratio"] > 1.3].sort_values("wer", ascending=False).head(20)[
    ["word_len_ratio", "wer", "ref", "hyp"]
]

,word_len_ratio,wer,ref,hyp
167,43.500000,43.500000,trán giô,hypothesis score tensor 5 5906 y sequence tens...
222,40.500000,40.000000,làm khung,hypothesis score tensor 1 0211 y sequence tens...
58,39.000000,39.000000,ôi dào,hypothesis score tensor 1 8092 y sequence tens...
120,39.000000,38.500000,bà nói,hypothesis score tensor 1 2710 y sequence tens...
445,32.666667,32.666667,tại chợ cá,hypothesis score tensor 2 5723 y sequence tens...
141,30.333333,30.333333,rạch bàu mớp,hypothesis score tensor 5 8160 y sequence tens...
315,30.333333,29.333333,quá tốt rồi,hypothesis score tensor 1 8762 y sequence tens...
139,29.000000,28.666667,vì tối đó,hypothesis score tensor 1 9623 y sequence tens...
428,29.666667,28.666667,năm đầu tiên,hypothesis score tensor 1 8397 y sequence tens...
100,28.666667,27.666667,người ta nói,hypothesis score tensor 0 9303 y sequence tens...
55,27.000000,26.333333,sau cải cách,hypothesis score tensor 2 4705 y sequence tens...
252,26.250000,26.000000,trận chiến xích bích,hypothesis score tensor 7 6161 y sequence tens...
378,26.333333,26.000000,cao ngồng ngồng,hypothesis score tensor 4 2841 y sequence tens...
376,26.000000,25.666667,cái khó là,hypothesis score tensor 2 9727 y sequence tens...
44,26.333333,25.666667,không hiểu sao,hypothesis score tensor 1 7992 y sequence tens...
423,23.750000,23.750000,ngụ ấp hòn ngang,hypothesis score tensor 8 0874 y sequence tens...
0,23.750000,23.500000,trở nên thụ động,hypothesis score tensor 3 5975 y sequence tens...
475,24.200000,23.200000,một ba năm bảy chín,hypothesis score tensor 0 8248 y sequence tens...
104,23.750000,22.750000,và rất sáng tạo,hypothesis score tensor 4 2286 y sequence tens...
463,22.750000,22.500000,áo rách lươm bươm,hypothesis score tensor 5 1924 y sequence tens...

In [41]:
import unicodedata

def remove_accents(text):
    text = unicodedata.normalize("NFD", text)
    text = "".join(ch for ch in text if unicodedata.category(ch) != "Mn")
    return unicodedata.normalize("NFC", text).replace("đ", "d")

df["wer_no_accent"] = [
    wer(remove_accents(r), remove_accents(h))
    for r, h in zip(df["ref"], df["hyp"])
]

df["accent_penalty"] = df["wer"] - df["wer_no_accent"]

df.sort_values("accent_penalty", ascending=False).head(30)[
    ["wer", "wer_no_accent", "accent_penalty", "ref", "hyp"]
]

,wer,wer_no_accent,accent_penalty,ref,hyp
435,19.400000,18.600000,0.800000,trọng tài phạt thẻ đỏ,hypothesis score tensor 2 8885 y sequence tens...
423,23.750000,23.000000,0.750000,ngụ ấp hòn ngang,hypothesis score tensor 8 0874 y sequence tens...
194,12.000000,11.250000,0.750000,bọn buôn lậu ma túy và vũ khí,hypothesis score tensor 8 8167 y sequence tens...
457,14.428571,13.857143,0.571429,dưới ánh đèn mờ mờ ảo ảo,hypothesis score tensor 8 7676 y sequence tens...
349,16.500000,16.000000,0.500000,mười một mười hai mười ba,hypothesis score tensor 0 8638 y sequence tens...
0,23.500000,23.000000,0.500000,trở nên thụ động,hypothesis score tensor 3 5975 y sequence tens...
167,43.500000,43.000000,0.500000,trán giô,hypothesis score tensor 5 5906 y sequence tens...
120,38.500000,38.000000,0.500000,bà nói,hypothesis score tensor 1 2710 y sequence tens...
49,16.600000,16.200000,0.400000,mà cũng đầy thanh khiết,hypothesis score tensor 4 4251 y sequence tens...
168,17.600000,17.200000,0.400000,thu chạm ngõ rất hiền,hypothesis score tensor 6 6459 y sequence tens...
209,11.100000,10.700000,0.400000,dù là đậu sức mạnh hoặc cải bông khủng long,hypothesis score tensor 9 3465 y sequence tens...
142,20.400000,20.000000,0.400000,gí hòn than vào rơm,hypothesis score tensor 11 9240 y sequence ten...
352,13.000000,12.625000,0.375000,căn nhà đằng kia nghe nói có ma,hypothesis score tensor 9 4202 y sequence tens...
733,10.000000,9.636364,0.363636,chương trình học bổng thanh niên châu á của nh...,hypothesis score tensor 12 5320 y sequence ten...
139,28.666667,28.333333,0.333333,vì tối đó,hypothesis score tensor 1 9623 y sequence tens...
305,14.833333,14.500000,0.333333,là tương đối có hiệu quả,hypothesis score tensor 5 4181 y sequence tens...
94,12.888889,12.555556,0.333333,bàn chổi sơn bằng bông mềm rất phổ biến,hypothesis score tensor 14 5985 y sequence ten...
155,14.833333,14.500000,0.333333,cam sành lột vỏ còn chua,hypothesis score tensor 9 4620 y sequence tens...
53,15.000000,14.666667,0.333333,dọc hai bên sông ngàn sâu,hypothesis score tensor 8 2037 y sequence tens...
66,10.777778,10.444444,0.333333,sương mù đã đọng thành những hạt giá băng,hypothesis score tensor 9 4561 y sequence tens...
189,15.833333,15.500000,0.333333,bốn chiếc trống đại phèng la,hypothesis score tensor 5 7223 y sequence tens...
39,11.888889,11.555556,0.333333,anh bị đẩy từ hà nội vào sài gòn,hypothesis score tensor 9 6609 y sequence tens...
320,11.888889,11.555556,0.333333,làm rờm rợp biển mây lau lách phất phơ,hypothesis score tensor 11 0340 y sequence ten...
40,13.833333,13.500000,0.333333,phù hợp cho mọi cân nặng,hypothesis score tensor 8 5954 y sequence tens...
218,12.666667,12.333333,0.333333,thậm chí càng giống áo quí nàng càng mốt,hypothesis score tensor 14 6839 y sequence ten...
234,17.333333,17.000000,0.333333,sao kết quả ra tệ vậy,hypothesis score tensor 4 1687 y sequence tens...
318,16.333333,16.000000,0.333333,giàu đổi bạn sang đổi vợ,hypothesis score tensor 7 7094 y sequence tens...
324,12.666667,12.333333,0.333333,phòng trà khiêu vũ cánh quạt cối xay đỏ,hypothesis score tensor 11 0437 y sequence ten...
451,10.666667,10.333333,0.333333,nhóm thanh long trẻ diễn tiểu phẩm hài hắc bạc...,hypothesis score tensor 12 7962 y sequence ten...
55,26.333333,26.000000,0.333333,sau cải cách,hypothesis score tensor 2 4705 y sequence tens...

In [43]:
from collections import Counter
from difflib import SequenceMatcher

substitutions = Counter()
deletions = Counter()
insertions = Counter()

for ref, hyp in zip(df["ref"], df["hyp"]):
    r = ref.split()
    h = hyp.split()
    sm = SequenceMatcher(a=r, b=h)
    for tag, i1, i2, j1, j2 in sm.get_opcodes():
        if tag == "replace":
            for a, b in zip(r[i1:i2], h[j1:j2]):
                substitutions[(a, b)] += 1
        elif tag == "delete":
            for a in r[i1:i2]:
                deletions[a] += 1
        elif tag == "insert":
            for b in h[j1:j2]:
                insertions[b] += 1

print("Substitution:")
print(substitutions.most_common(30))

print("Deletion:")
print(deletions.most_common(30))

print("Insertion:")
print(insertions.most_common(30))

Substitution:
[(('nay', 'này'), 9), (('vì', 'hypothesis'), 7), (('mạnh', 'mình'), 7), (('những', 'hypothesis'), 7), (('cùng', 'cũng'), 7), (('câu', 'cầu'), 7), (('nhưng', 'hypothesis'), 6), (('an', 'ăn'), 6), (('minh', 'mình'), 6), (('ảnh', 'anh'), 6), (('đáng', 'đang'), 6), (('sâu', 'sau'), 5), (('thanh', 'thành'), 5), (('gọi', 'gọ'), 5), (('đấy', 'đây'), 5), (('tự', 'từ'), 5), (('từng', 'từ'), 5), (('chị', 'chỉ'), 5), (('việt', 'việc'), 5), (('chị', 'hypothesis'), 4), (('lạ', 'là'), 4), (('tôi', 'hypothesis'), 4), (('hẳn', 'hàng'), 4), (('đề', 'để'), 4), (('trị', 'chỉ'), 4), (('băng', 'bằng'), 4), (('ngoại', 'ngoài'), 4), (('trọng', 'trong'), 4), (('bản', 'bạn'), 4), (('tội', 'tôi'), 4)]
Deletion:
[('thấy', 1), ('quá', 1), ('giảm', 1), ('ác', 1), ('với', 1), ('mình', 1), ('cực', 1), ('gan', 1), ('sò', 1), ('thịt', 1), ('đỏ', 1), ('chè', 1), ('nặng', 1), ('trĩu', 1), ('chợ', 1)]
Insertion:
[('1024', 15567), ('none', 6176), ('state', 1158), ('confidence', 1158), ('token', 1158), ('lm', 1158), ('tensor', 929), ('y', 850), ('dec', 772), ('frame', 772), ('scores', 772), ('last', 772), ('hypothesis', 465), ('score', 465), ('sequence', 464), ('text', 464), ('0', 421), ('out', 386), ('timestamp', 386), ('alignments', 386), ('word', 386), ('length', 386), ('ngram', 386), ('tokens', 386), ('duration', 386), ('biasing', 386), ('cfg', 386), ('xatt', 386), ('9', 119), ('8', 117)]

## 14. Finalize Best Model and Show Artifacts

Chọn overall best theo validation WER và in các file cần download.

In [ ]:
select_overall_best(eval_rows)

print("\nArtifacts:")
for path in [
    PHASE1_BEST_NEMO,
    PHASE2_BEST_NEMO,
    PHASE3_BEST_NEMO,
    OVERALL_BEST_NEMO,
    TRAINING_CSV,
    EVAL_CSV,
    SAMPLE_PREDICTIONS_CSV,
]:
    if path.exists():
        print(path, f"{path.stat().st_size / (1024 ** 2):.2f} MB")
    else:
        print("Missing:", path)

print("\nCheckpoint folders:")
for phase in PHASES:
    print(phase.name, PHASE_ROOT / phase.name / "checkpoints")

if eval_rows:
    display(pd.DataFrame(eval_rows))
if training_rows:
    display(pd.DataFrame(training_rows))